### ISSUE TITLE
Media Queries not working for me

### ISSUE THREAD

**Issue by benoneal** [FormidableLabs/radium#100]
I'm not sure why, but my media queries aren't working at all. In the top level component of the app, I've got: 
```
var { MatchMediaBase } = require('radium');
MatchMediaBase.init({
  tiny: '(min-width: 200px)',
  small: '(min-width: 350px)',
  mobile: '(min-width: 450px)',
  medium: '(min-width: 500px)',
  large: '(min-width: 650px)',
  tablet: '(min-width: 700px)',
  huge: '(min-width: 800px)',
  laptop: '(min-width: 950px)',
  desktop: '(min-width: 1200px)',
  wide: '(min-width: 1450px)',
  tinyMax: '(max-width: 199px)',
  smallMax: '(max-width: 249px)',
  mobileMax: '(max-width: 349px)',
  mediumMax: '(max-width: 499px)',
  largeMax: '(max-width: 549px)',
  tabletMax: '(max-width: 699px)',
  hugeMax: '(max-width: 799px)',
  laptopMax: '(max-width: 849px)',
  desktopMax: '(max-width: 1199px)',
  wideMax: '(max-width: 1349px)'
});
...
mixins: [MatchMediaBase]
```
And in my component I have: 
```
var { StyleResolverMixin, MatchMediaItem } = require('radium');
mixins: [StyleResolverMixin, MatchMediaItem]
```
with styles: 
```
var Logo = {
  display: 'inline-block',
  height: 32,
  maxWidth: '100%',
  padding: '0 30px',
  lineHeight: '13px',
  marginBottom: -8,

  mediaQueries: [
    { laptopMax: {
      position: 'absolute',
      top: '40%',
      left: '50%',
      transform: 'translateX(-50%) translateY(-50%)',
      padding: 0,
      margin: 0
    }},
    { mediumMax: {
      top: 0,
      transform: 'translateX(-50%)'
    }}
  ]
};
```
But these styles never seem to be applied at any browser width. In testing in the console, I get this:  
```
window.matchMedia('laptopMax')
MediaQueryList {onchange: null, matches: false, media: "laptopmax", addListener: function, removeListener: function…}matches: falsemedia: "laptopmax"onchange: null__proto__: MediaQueryList
window.matchMedia('mobile')
MediaQueryList {onchange: null, matches: false, media: "mobile", addListener: function, removeListener: function…}matches: falsemedia: "mobile"onchange: null__proto__: MediaQueryList
window.matchMedia('tiny')
MediaQueryList {onchange: null, matches: false, media: "tiny", addListener: function, removeListener: function…}matches: falsemedia: "tiny"onchange: null__proto__: MediaQueryList
window.matchMedia('wide');
MediaQueryList {onchange: null, matches: false, media: "wide", addListener: function, removeListener: function…}matches: falsemedia: "wide"onchange: null__proto__: MediaQueryList
window.matchMedia('wideMax');
MediaQueryList {onchange: null, matches: false, media: "widemax", addListener: function, removeListener: function…}
```
So on the surface, it looks like MatchMediaBase.init() isn't working for some reason, and matchMedia lowercases my key names (which would break them, but also isn't the problem). 

I'm assuming this is working for someone out there, so any ideas what I've missed?

**Comment by alexlande** [comment]
Missed this one. Are you still having trouble with this @benoneal? I'm assuming based on your other PR that you got it working.

**Comment by benoneal** [comment]
Yeah it turns out that the react PureRenderMixin breaks media queries because it blocks updating on that node and all child nodes unless its props or state change, so it ignores context changes :| In my case I had it on one of the ancestor nodes.

Might be worth making a note in your documentation not to use PureRenderMixin anywhere in your app if you want media queries to work.

**Comment by alexlande** [comment]
Ah, yeah. With the upcoming API we don't use context anymore, which solves that problem. There's an issue tracking this in React if anyone wants to read more about the general `context` + `shouldComponentUpdate` thing: https://github.com/facebook/react/issues/2517

**Comment by buunguyen** [comment]
I stumbled upon this issue. Is there a full example of using MatchMediaBase like this in ES6 apps instead of having to hardcode the dimensions? I've searched the doc but can't find it.

**Comment by alexlande** [comment]
Hey @buunguyen-- `MatchMediaBase` was removed from Radium shortly after this PR was closed. You can find a guide to media query usage here: https://github.com/FormidableLabs/radium/tree/master/docs/guides#media-queries
