### ISSUE TITLE
npm-install incompatible with current version of typescript (3.x)

### ISSUE THREAD

**Issue by ronriley** [FormidableLabs/radium#1008]
I'm trying to use Radium with React and TypeScript 3, however there are dependencies on typescript 2.x which seem to be a blocker:

npm install --save radium
npm WARN fork-ts-checker-webpack-plugin@0.2.10 requires a peer of typescript@^2.1.0 but none is installed.

**Comment by kylecesmat** [comment]
@ronriley Radium does not take any kind of dependency on `fork-ts-checker-webpack-plugin` or any typescript tooling. 

I have been able to install `radium` into the latest `create-react-app` with modern TS tooling without any errors happening. My guess is your warning is coming from a different package that depends on `fork-ts-checker-webpack-plugin`

Here is the only package that I see taking a dep on `fork-ts-checker-webpack-plugin` after I installed radium into create-react-app.
<img width="528" alt="screen shot 2018-11-04 at 2 44 19 pm" src="https://user-images.githubusercontent.com/1633837/47970289-a1177d00-e040-11e8-8201-040b784cbcb5.png">
