### ISSUE TITLE
Add support for React Hooks

### ISSUE THREAD

**Issue by dudiharush** [FormidableLabs/radium#1016]
Currently I get an error message when wrapping my functional component in Radium function.

[https://codesandbox.io/s/m7ojlxokxy](https://codesandbox.io/s/m7ojlxokxy)
error message: Hooks can only be called inside the body of a function component. (https://fb.me/react-invalid-hook-call)

**Comment by nathanmarks** [comment]
I almost have a PR ready!

**Comment by kylecesmat** [comment]
This has been released in `0.26.0` ✨
