### ISSUE TITLE
import errror 

### ISSUE THREAD

**Issue by ucanme** [FormidableLabs/radium#1017]
./src/node_modules/_radium@0.25.1@radium/es/enhancer.js
  Line 15:  Import in body of module; reorder to top  import/first
  Line 16:  Import in body of module; reorder to top  import/first
  Line 18:  Import in body of module; reorder to top  import/first
  Line 19:  Import in body of module; reorder to top  import/first
  Line 20:  Import in body of module; reorder to top  import/first

Search for the keywords to learn more about each error.

**Comment by ryan-roemer** [comment]
@ucanme -- I'm curious as to the execution environment that caused this error? Are you doing a direct `<script type="module">` include in a browser or something?

https://unpkg.com/radium@0.25.2/es/enhancer.js
