### ISSUE TITLE
Media query proposal with new syntax

### ISSUE THREAD

**Issue by ianobermiller** [FormidableLabs/radium#102]
So, with the new syntax, the media query stuff probably has to change significantly as well. Here is one proposal:

In the style object, you can add media queries and their respective styles:

```js
var styles = {
  root: {
    width: '50%',
    '(max-width: 600px)': {
       width: '100%'
    }
  }
};
```

Behind the scenes, we add handlers to `matchMedia` in the same way as now, and we know to update the state of the component when the callback fires.

If you use computed property names, you can share your media queries:

```js
var styles = {
  root: {
    width: '50%',
    [MediaQueries.small]: {
       width: '100%'
    }
  }
};
```

What I am unsure about is how these would interact with `':hover'` and other special style props; do you allow `':hover'` inside a media query, or v.v., or both?

**Comment by alexlande** [comment]
This seems solid to me. Re: order of operations (so to speak), I think the current Radium pattern makes sense. Any group of styles (including a media query) can include browser states, but browser states can't include modifiers or media queries of their own.

**Comment by alexlande** [comment]
Done!
