### ISSUE TITLE
background and background-repeat - I have to choose between warning or correct operations

### ISSUE THREAD

**Issue by ronenmagid** [FormidableLabs/radium#1028]
I have this code.

If I use it as is, it works but issues a warning this warning:

`check-props-plugin.js:40 Radium: property "background" in style object {top: "50%", position: "relative", transform: "translateY(-50%)", color: "#231f20", marginLeft: "10px", …} : do not mix longhand and shorthand properties in the same style object. Check the render method of ShadowButton. See https://github.com/FormidableLabs/radium/issues/95 for more information.`

The code:

```
  background: 'linear-gradient(' + Globals.MY_YELLOW + ',' + Globals.MY_YELLOW + ') ' +
                'center/calc(100% + 15px) calc(100% + 15px) padding-box, linear-gradient(#fff,#fff) top right  ' +
                '/10px 10px border-box,  linear-gradient(#fff,#fff) bottom left/10px 10px border-box,  ' +
                'repeating-linear-gradient( 45deg,  transparent 0, transparent 1px,  #333 2px,#333 2px) border-box',
backgroundRepeat: 'no-repeat',
```

If I remove the `backgroundRepeat` line, my component renders wrong, but I get no warning. What can I do about this?

**Comment by kylecesmat** [comment]
The error message provides a link to a rather outdated issue number, apologies for that!

Radium is unable to process longhand & shorthand property declarations for the same CSS property. This means, your code for `background` is 'shorthand', where you declare a bunch of sub-properties together, where `backgroundRepeat` is 'longhand' and explicit. These do not merge.

The fix here should be to include `'no-repeat'` in your shorthand declarations per this documentation - https://developer.mozilla.org/en-US/docs/Web/CSS/background#Syntax

```
background: 'no-repeat linear-gradient(' + Globals.MY_YELLOW + ',' + Globals.MY_YELLOW + ') ' + 'center/calc(100% + 15px) calc(100% + 15px) padding-box, no-repeat linear-gradient(#fff,#fff) top right' + '/10px 10px border-box, no-repeat linear-gradient(#fff,#fff) bottom left/10px 10px border-box,  ' + 'no-repeat repeating-linear-gradient( 45deg,  transparent 0, transparent 1px,  #333 2px,#333 2px) border-box',
```

I'm closing this issue, let me know if you need any more direction!
