### ISSUE TITLE
@types/radium"' has no exported member 'StyleRoot'

### ISSUE THREAD

**Issue by jmh-git** [FormidableLabs/radium#1030]
I am using the following packages: 
```
"dependencies": {
    "@types/jest": "24.0.15",
    "@types/node": "12.0.10",
    "@types/radium": "^0.24.2",
    "@types/react": "16.8.22",
    "@types/react-dom": "16.8.4",
    "radium": "^0.25.2",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "react-scripts": "3.0.1",
    "typescript": "3.5.2"
  },
```
I also followed the instructions how to import radium and did it like this:
`import Radium, { StyleRoot } from 'radium';`

In my App, I wrapped the App-component JSX within the StyleRoot component like this:
```
<StyleRoot>
  <div className="App">
    <h1>My first React App</h1>
    <p className={dynamicClass.join(' ')}>Some text</p>
    <button
       style={myButtonInlineStyle}
       onClick={this.toggleNameHandler}>Toggle Name</button>
     {persons}
   </div>
</StyleRoot>
```
But when TypeScript compiles the code, I receive the following error in the line where the import is done (see above):
`Module '".../node_modules/@types/radium"' has no exported member 'StyleRoot'.  TS2305`

The index.d.ts member in node_modules/@types/radium, however exports the class StyleRoot like this:
```
export class StyleRoot extends React.Component<StyleRootProps> {
    }
```

**Comment by jmh-git** [comment]
I figured out that by embedding the code within
`<Radium.StyleRoot> ... </Radium.StyleRoot>  `
instead of just 
`<StyleRoot> ... </StyleRoot>`
everything works fine.  Sorry for the confusion and any extra circumstances.

**Comment by Nosnibor35** [comment]
> I figured out that by embedding the code within
> `<Radium.StyleRoot> ... </Radium.StyleRoot> `
> instead of just
> `<StyleRoot> ... </StyleRoot>`
> everything works fine. Sorry for the confusion and any extra circumstances.

Thanks that really helped me! I was even getting errors with 
`import Radium, { StyleRoot } from 'radium';`
But with using Radium.Style, that resolve it.
