### ISSUE TITLE
Style elements when a different element's browser state is changed

### ISSUE THREAD

**Issue by m59peacemaker** [FormidableLabs/radium#105]
Is there a proper way of styling other elements (siblings, children, parents!?) based on events/state like hover?

    .parent:hover .child {
      color: red;
    }

I've thought of `onMouseEnter={changeChildStyle} onMouseLeave={changeItBack}`, but that gets messy having to keep up with different versions of a style object and it seems to conflict with `getBrowserStateEvents`, as whichever comes first is overwritten.

**Comment by alexlande** [comment]
We don't have an API exactly like that for it (where it's confined to the style object), but this functionality will ship in Radium 0.12 with `getState`: https://github.com/FormidableLabs/radium/tree/master/docs/api#getstate
