### ISSUE TITLE
WebJar support

### ISSUE THREAD

**Issue by paulwehner** [FormidableLabs/radium#106]
Could you please provide a way to install Radium via a WebJar?

**Comment by alexlande** [comment]
Hey @paulwehner: I just published Radium to Bower, which should help with this. Once it's available in the Bower WebJars list, I'll deploy it there.

I can't guarantee that we'll keep it up to date after that, but Bower will stay up to date, and it looks like you'll be able to deploy new versions to WebJars whenever you need to update through this interface: http://www.webjars.org/bower

**Comment by alexlande** [comment]
@paulwehner: I just deployed the WebJar, so I think you should be good to go? The list on webjars.org isn't updated yet, but presumably will be. The modal that popped up said that it should be usable now.

**Comment by paulwehner** [comment]
Thanks! Much appreciated.

**Comment by alexlande** [comment]
Cheers! Thanks for checking out Radium.
