### ISSUE TITLE
Radium.getState - proposal for querying element state

### ISSUE THREAD

**Issue by ianobermiller** [FormidableLabs/radium#107]
It would be nice to be able to access Radium's internal knowledge about component interaction state. I propose the following simple function for controlled access to Radium's state, primarily after #101 is in:

```javascript
Radium.getState(state, key, value)

// Example

Radium.getState(this.state, 'button', 'isHovering')
```
- **state** - you'll usually pass `this.state`, but sometimes you may want to pass a previous state, like in `shouldComponentUpdate`, `componentWillUpdate`, and `componentDidUpdate`
- **key** - if you used multiple elements, pass the same `key=""` or `ref=""`. If you only have one element, you can leave it blank (`'root'` will be inferred)
- **value** - one of the following: `isHovering`, `isActive`, `isFocused` - alternatively, we could change this to `:hover`, `:active`, and `:focus` if that makes more sense
- **returns** `true` or `false`

This would primarily unlock #105, changing the style of one element when another has some interaction.

**Comment by alexlande** [comment]
Love this. I think `:hover`, etc makes sense to keep it consistent with the naming used in style objects.

**Comment by benoneal** [comment]
+1 This would also make testing components easier, to ensure that radium's knowledge of the component state is in sync with the components knowledge of its state.

**Comment by paulwehner** [comment]
Shouldn't this issue be closed out?
