### ISSUE TITLE
New API swaps abstraction for glue code.

### ISSUE THREAD

**Issue by benoneal** [FormidableLabs/radium#123]
Compared the the old API, the new API requires a LOT of handholding, with component render methods being filled with glue code which was neatly abstracted away in the old API, and the wrap implementation now makes abstraction layers between the app and your library impossible.  

In the old API, I had implemented a wrapping mixin which allowed me to do the following for all components: include the mixin, attach styles to the components' static method, and apply styles via my custom this.css([namespace]) method (which allowed me to chain things like vendor prefixing). Styles themselves declared what they looked like based on the state and props of the component with logical nesting. 

In the new API, I have to wrap each component in radium.wrap, attach styles as a variable, then glue state and props to the styles with a ton of completely inane "if blue, use blue" code, then wrap those in any processing methods I require, then apply them to elements via styles prop. Styles themselves can still (probably) declare what they look like based on state and props with nesting. 

Also, importantly for our app, we strongly prefer to create abstraction layers between libraries and the app (primarily through mixins), so that if we in future decide to switch libraries, or if a library introduces breaking changes to their API, we can simply modify the point of abstraction instead of having to manually propagate changes throughout hundreds of components. By requiring every component to be wrapped by radium, now my app has explicitly become a "radium app". I can't swap libraries without a complete sweep of all components. If you introduce breaking changes to how styles are applied, guess what? I have to manually change every single component. 

Both of these changes represent a severe regression for us. We are explicitly trying to abstract away trivial glue code and minimise the interface surface area with external libraries to promote rapid development which can be kept up-to-date with minimal effort.

**Comment by benoneal** [comment]
Here is an example of our current implementation of radium in our production app, using an atomic 'input' component (with irrelevant code collapsed removed): 

Mixin:
```
var _ = require('lodash');
var prefix = require('react-prefixr');
var { StyleResolverMixin, BrowserStateMixin, MatchMediaItem } = require('radium');

module.exports = _.merge({
  css: function(selector, mods) {
    return prefix(this.buildStyles(this.constructor.style[selector], mods));
  },
  attachEvents: BrowserStateMixin.getBrowserStateEvents,
  Events: BrowserStateMixin // must add: { ...this.attachEvents() } to top level element
}, StyleResolverMixin, MatchMediaItem);
```

Input Component:
```
var React = require('react/addons');
var Style = require('../../../lib/mixins/style');

module.exports = React.createClass({
  displayName: "Input",

  mixins: [Style, Style.Events ...],

  propTypes: { // leaving only the props relevant to styling
    disabled: React.PropTypes.bool,
    error: React.PropTypes.bool,
    hint: React.PropTypes.string,
    icon: React.PropTypes.string,
    spacing: React.PropTypes.oneOf(['compact', 'tight', 'loose']),
    width: React.PropTypes.oneOf(['full', 'wide', 'half', 'narrow', 'quarter'])
  },

  handleBlur: function() {
    ...
    this.radiumBlur();
    ...
  },

  renderIcon: function() {
    ...
    return icon && <Icon ... style={ this.css('Icon') }.../>;
  },

  renderMessage: function(bool) {
    return bool && (
      <div style={ this.css('Message') }>
        ...
      </div>
    );
  },

  render: function() {
    var css = this.css;
    ...

    return (
      <div className={ this.constructor.displayName } style={ css('Wrapper') }>
        <label style={ css('Label', { hasValue, disabled }) } ...>
          { props.label }

          <input { ...this.attachEvents() }
            style={ css('Input', { disabled }) }.../>

          { this.renderIcon() }
        </label>

        { this.renderMessage(...) }
      </div>
    );
  },

  statics: {
    style: require('./style')
  }
});
```

Input Stylesheet: 
```
var Wrapper = {
  ...

  modifiers: [
    { width: {
      full: { ... },
      wide: { ... },
      half: { ... },
      narrow: { ... },
      quarter: { ... }
    }},
    { spacing: {
      compact: { ... },
      tight: { ... },
      loose: { ... }
    }}
  ]
};

var Label = {
  ...

  states: [
    { error: {
      ...
    }},
    { focus: {
      ...
    }}
  ],

  modifiers: [
    { hasValue: {
      ...
    }},
    { disabled: {
      ...
    }}
  ]
};

var Input = {
  ...

  modifiers: [
    { disabled: { ... }}
  ]
};

var Icon = {
  ...

  states: [
    { error: { ... }},
    { valid: { ... }}
  ]
};

var Message = {
  ...

  states: [
    { error: {
      ...
    }},
    { focus: {
      ...
    }}
  ]
};

module.exports = { Wrapper, Label, Input, Icon, Message };
```
Every key on those styles represents an additional line of glue code I'd have to write into the component with the new API. Glue code which, it's worth noting, becomes *significantly* more complicated when it comes to nested interacting modifiers / states, as is the case with our button styles: 
```
var Button = {
  ...
  modifiers: [
    { thin: { ... }},
    { kind: {
      cta: {
        ...
        states: [
          { hover: {  }}
        ],
      },
      primary: {
        ...
        states: [
          { hover: { ... }}
        ],
        modifiers: [
          { reverse: {
            ...
            states: [
              { hover: { ... }}
            ]
          }}
        ]
      },
      secondary: {
        ...
        states: [
          { hover: { ... }}
        ],
        modifiers: [
          { reverse: {
            ...
            states: [
              { hover: { ... }}
            ],
          }}
        ]
      },
      tertiary: {
        ...
        states: [
          { hover: { ... }}
        ],
        modifiers: [
          { reverse: {
            ...
            states: [
              { hover: { ... }}
            ]
          }}
        ]
      }
    }},
    { disabled: {
      ...
      states: [
        { hover: { ... }}
      ]
    }},
    { noBorder: { ... }}
  ]
};

var Label = {
  ...
  modifiers: [
    { thin: {
      ...
    }}
  ]
};

var Icon = {
 ...
  modifiers: [
    { iconLeft: {
      ...
    },
    hasIcon: {
      ...
    },
    kind: {
      cta: { ... },
      primary: { ... },
      secondary: {
        ...
        modifiers: [
          { reverse: { ... }}
        ]
      },
      tertiary: {
        ...
        modifiers: [
          { reverse: { ... }}
        ]
      }
    }}
  ]
};

var Glow = {
  ...
  states: [
    { hover: {
      ...
    }}
  ],
  modifiers: [
    { kind: {
      cta: {
        ...
      },
      primary: {
        ...
        modifiers: [
          { reverse: {
            ...
          }}
        ]
      },
      secondary: {
        ...
        modifiers: [
          { reverse: {
            ...
          }}
        ]
      },
      tertiary: {
        ...
        modifiers: [
          { reverse: {
            ...
          }}
        ]
      }
    }},
    { disabled: {
      ...
    }}
  ]
};
module.exports = { Button, Icon, Glow, Label };
```

Honestly. Try it yourself. Make a component with two props which have two options each. Maybe ``` kind.oneOf(['primary', 'secondary']), contrast.oneOf(['light', 'dark']) ```. And each combination of these has a hover state and an active state. Try to glue that up without missing anything.

**Comment by alexlande** [comment]
Thanks @benoneal, this is helpful. /cc @ianobermiller 

Will read through more carefully and write up an actual response, but for now--

I'm confused about what you mean re: `states` though. States within modifiers (which are now just additional style objects added in the `style` array) are still merged with any previous modifiers + base styles. That behavior hasn't changed.

One preliminary idea for your other issues is that we could expose the equivalent of `buildStyles` to be used directly (along with some other methods for browser states, probably), allowing users to opt out of the wrap API and use something more similar to the old API.

**Comment by alexlande** [comment]
It seems like the two main issues here are:

1. You prefer the old prop maps to modifier behavior
2. You want to to build an abstraction layer between Radium + your app

Is that accurate? Easier to figure out how to help if we can break it down.

**Comment by benoneal** [comment]
Sorry, you're correct about ```states```: they don't affect the complexity of the glue code. 

Yeah pretty much. An abstraction layer is crucial so we aren't tied to any particular library (since modern js libraries [especially in cutting edge features such as js styles] change and die rapidly). And having props / state mapping to styles invisibly keeps components clean and simple. I'm not married to the specifics of how props map to modifiers (it could potentially be handled without the 'modifiers' array), but I have a strong preference for it to be handled under-the-hood, and easily identifiable to anyone writing / reading the stylesheet. 

I guess the ideal implementation of the styles themselves for me, might look like (since it's similar to most css pre-processor syntax): 
```
var El = {
    ...base styles,
    '&prop1': {}, // any boolean prop
    '&prop2': { // any string prop
        val: {},
        ':state': {} // any boolean state
    },
    '@breakpoint': {}
}
```
It 'reads' better too: ```El & prop2 of 'val' looks like this```, ```El @ this breakpoint looks like this```. 

But honestly syntax niceties don't bother me that much. I'd be happy with just those two issues being resolved.

**Comment by ianobermiller** [comment]
@benoneal thanks very much for bringing up all these issues. 

It sounds like you main issue is swapping the implicit mapping from prop+value to styles for very explicit including of styles manually. I can see that in your case this results in significantly more code, but I think almost all of it could be abstracted by a simple helper function that takes props and a style object and basically does the same thing that the previous Radium code did. The one difference for you is that your component styled sub-elements based on the interaction with the main element, which works slightly different in the new API now you have interactive styles on more than one element in a single component.

I suggest creating such a helper function, and then just invoking it like you would use buildStyles before:

```as
render: function() {
  var css = this.css;
  ...

  return (
    <div className={ this.constructor.displayName } style={ css('Wrapper') }>
      <label style={ styleFromProps(styles.Label, { hasValue, disabled }) } ...>
        { props.label }

        <input { ...this.attachEvents() }
          style={ styleFromProps(styles.Input, { disabled }) }.../>

        { this.renderIcon() }
      </label>

      { this.renderMessage(...) }
    </div>
  );
},

**Comment by benoneal** [comment]
If I have to write a helper to loop through props and (non-browser event) state to return an array mapping which styles to apply, why don't I just push the styles into that array, and then merge them in the return? Only now I've re-written the buildStyles() method, and have no use of Radium for that. 

I guess it's hard for me to see what Radium is providing now. Compared to other libraries (like react-style and such), the main selling point was the abstraction of props > modifiers, name-spaced media queries, and the convenient ```<Style>``` component (super useful as a fallback for when css selectors are necessary, such as implementing a css reset). Honestly the browserState stuff is pretty trivial. And before using radium, we were handling browserState in pretty much exactly the same way, only when needed. And truth is, it's only required for a small percentage of components: primarily buttons, links, and form elements. It *should* be the sort of thing you only opt into when needed, because it's not needed most of the time. 

We've lost name-spaced media queries (until we can use computed property keys in object literals), the abstraction of props > modifiers, and crucially from a business perspective: the ability to abstract out the library to insulate the app from vendor modules. For what? So we don't have to manually attach events on an element? And maybe manually trigger this.radiumMouseUp() *if* a component needs to do its own things on that same event? 

I just don't understand the reasoning behind this API change. Any convenience gained by wrapping components is surely lost tenfold by all the work now required to hook your styles up and being locked into using Radium.

**Comment by ianobermiller** [comment]
> it's hard for me to see what Radium is providing now

> the browserState stuff is pretty trivial

The amount of boilerplate required to wire up browser state is definitely non-trivial (add handlers, create callback methods, initial state, etc), especially when what you wanted to accomplish was changing some state on hover.  With Radium, we want to make things that are simple to use in CSS also simple to use in JS. Same with media queries, which are even more burdensome to use in a component (subscribe, unsubscribe, etc).

> it's not needed most of the time.

You're right, it isn't needed most of the time. But, when you do want to add a media query or state defined style, especially to a component that isn't just a building block (like Button), it's really easy to do so.

I'll also argue that the explosion of modifiers isn't needed most of the time, since only base components need so many options (the same "small percentage of components" you reference).

> We've lost name-spaced media queries (until we can use computed property keys in object literals)

Computed property keys are in ES6 and transformed by Babel: https://babeljs.io/docs/usage/transformers/#es6. You could also use a [purpose built transformer](https://www.npmjs.com/package/es6-computed-properties). Failing that, I've already proposed an alternative:

```as
Radium.defineCustomMedia('small', 'max-width: 320px');

var style = {
  width: '20%',
  '@media (--small)': {
    width: '100%'
  }
};
```

I'm not convinced it is worth pursuing, but feel free to open an issue and start the discussion.

> locked into using Radium

This is definitely something we can work on. You seem to have a very specific use-case in mind already; is there a more verbose abstraction of the `wrap` API (similar to the mixins + buildStyles + getBrowserStateEvents we had before) that you'd prefer to see as an alternative? Please open an issue and we can figure something out.

I'm closing this issue for now, since as a whole it isn't really actionable.
