### ISSUE TITLE
Control over inherited styles

### ISSUE THREAD

**Issue by benoneal** [FormidableLabs/radium#124]
Currently, applying styles to a component like so: ```<Component style={styleFromParent}/>``` results in that ```styleFromParent``` being merged over the top of *all* style declarations within that component. So if within that component we have: 
```
<div style={ style.wrapper }>
    <h1 style={ style.title }></h1>
    <p style={ style.copy }></p>
</div>
```
... then ```styleFromParent``` will be merged with each of ```style.wrapper```, ```style.title```, and ```style.copy```.

This has the potential to make it harder to manage components where parents need to modify the styles of their children (often in full apps with atomic components). 

I think it would be beneficial to allow control over how inherited styles are applied. I can think of two ways this could work. 
1. optionally add an additional arg to ```this.buildStyles(styles, inherit:bool)``` which would apply inherited styles only if true (defaults to false, see below)
2. optionally add a reserved key within the stylesheet, declaring where inherited styles apply, like: 
```
var Style = {
    _inherit: true, // defaults to false
    .... // continue styles here
}
```

Ideally, the existing behaviour (apply inherited styles to all buildStyles() calls), would be preserved, and only change in the presence of one of the two above methods. In other words, IF ```this.buildStyles(style, true)``` is ever called, then set inherit to false for all subsequent calls (problematic since it's order dependent), or if ```_inherit: true``` appears anywhere in the stylesheet, then ```styleFromParent``` is merged there but nowhere else. 

There may be a better way to implement this, but I'd like to see the ability to control how styles are inherited in children when passed in as props.

**Comment by alexlande** [comment]
Related to #75

**Comment by ianobermiller** [comment]
This shouldn't be an issue with the new API, correct? We don't merge in props.style by default.
