### ISSUE TITLE
React warnings

### ISSUE THREAD

**Issue by ryanfields** [FormidableLabs/radium#126]
I just updated to the new Radium API, made all the necessary changes, and now I'm getting the following warning numerous times in console.

```
Warning: Any use of a keyed object should be wrapped in React.addons.createFragment(object) before being passed as a child.
```

I can't figure out what's causing the warnings, but I'm getting a lot of broken behavior throughout my app and I suspect the root cause is whatever is triggering these warnings.  If I remove the Radium.wrap from all of my components, everything goes back to normal (aside from a complete loss of styling.)

I'm using React inside Meteor, but I don't currently see any reason why that would be causing problems.  Radium 0.10 worked without issue inside Meteor.  The Meteor-related code only interacts with my React components to call setState under certain conditions, and to register/unregister listeners when the component is mounted or removed.  It doesn't touch the rendering path at all.

**Comment by ianobermiller** [comment]
Can you provide a simple repro? I suspect it is due to our use of React.Children.map.

**Comment by ianobermiller** [comment]
Can you run in the debugger with "Pause on caught exceptions" enabled? I wonder if Radium is hitting the duplicate key error and throwing, and that is causing the problem.

**Comment by ianobermiller** [comment]
Closing as norepro for now. Please reopen if this is still happening. I believe it may have been fixed by the React.Children fixes as well.
