### ISSUE TITLE
Setup coveralls support

### ISSUE THREAD

**Issue by ianobermiller** [FormidableLabs/radium#136]
Can an admin for the project setup coveralls (https://coveralls.io) support? That way we can have  badge for code coverage and the service will also comment on PRs.

**Comment by ryan-roemer** [comment]
@ianobermiller -- Almost done with this. I've noticed we've got:

```js
    "collectCoverageOnlyFrom": {
      "modules/get-state.js": true,
      "modules/resolve-styles.js": true,
      "modules/wrap.js": true
    },
```

Should we open up coverage reports for all of `modules/*`?

**Comment by ianobermiller** [comment]
Probably, I'm sure we can properly test Style.
