### ISSUE TITLE
Radium.wrap breaks React.Children.only

### ISSUE THREAD

**Issue by chrisvfritz** [FormidableLabs/radium#139]
Using `Radium.wrap` breaks [elements requiring only one child](https://facebook.github.io/react/docs/top-level-api.html#react.children.only). The example I encountered this in is [react-bootstrap's `OverlayTrigger` component](https://github.com/react-bootstrap/react-bootstrap/blob/master/src/OverlayTrigger.js). Including this or similar elements anywhere in render will throw:

```
Uncaught Error: Invariant Violation: onlyChild must be passed a children with exactly one child.
```

**Comment by ianobermiller** [comment]
Hmm. Must be the use of React.Children.map.  If there is only one, we could
just unwrap it.
