### ISSUE TITLE
Release 0.12

### ISSUE THREAD

**Issue by alexlande** [FormidableLabs/radium#141]
We've got several new features and some bug fixes in. I think it's about time for 0.12.

@ianobermiller: Anything else you think we should get in beforehand? If not will release today.

**Comment by alexlande** [comment]
Actually-- it would be really nice to get the Enhancer in before-hand. Will take that for a test drive today, but it's looking good to me.

**Comment by mrtnbroder** [comment]
I just installed from master – does radium not support isomorphic apps? I get the following error: 

```
/Users/mbroder/Sites/prototype/node_modules/radium/modules/prefix.js:19
var domStyle = document.createElement('p').style;
               ^
ReferenceError: document is not defined
    at Object.<anonymous> (/Users/mbroder/Sites/prototype/node_modules/radium/modules/prefix.js:19:16)
    at Module._compile (module.js:428:26)
    at Object.Module._extensions..js (module.js:446:10)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (/Users/mbroder/Sites/prototype/node_modules/radium/modules/keyframes.js:3:14)
    at Module._compile (module.js:428:26)
    at Object.Module._extensions..js (module.js:446:10)
```

**Comment by alexlande** [comment]
We do. There are a couple of other issues holding up releasing the current stuff as well (see https://github.com/FormidableLabs/radium/pull/142 also).

Will plan to release by the end of the week.

**Comment by mrtnbroder** [comment]
Oh, alright. Nvm me then. Keep up the good work!

**Comment by awkaiser** [comment]
Cool, I'm looking forward to next NPM release with `Radium.Enhancer`, _and_ an example of what needs to be done for isomorphic apps (#143).

I had Radium working just fine in an isomorphic app roughly one month ago, but that code broke at some point during the transition from mixins to wrapped components. I don't mind, because `Enhancer` is a welcomed change and I'm not expecting a stable public API until 1.0 (updating my code to use `Enhancer` was easy), but this usage of `document` methods outside the browser is frustrating.

**Comment by ianobermiller** [comment]
We should be more diligent about touching browser-only methods. The test
tool, jest, doesn't help since it includes jsdom by default.

**Comment by ryan-roemer** [comment]
I'd suggest just adding some straight Node + mocha tests...

**Comment by alexlande** [comment]
Chatted with @ryan-roemer and came up with a good set of actions going forward for that:

1. Build up the examples to include server, client, and isomorphic rendering, then run the examples on CI to watch for explosions (see #143)
2. Add some peace of mind Mocha/Chai tests to test that server rendering behaves appropriately/doesn't explode with our features that use DOM methods. (ticket forthcoming)

That said, I don't think either of these necessarily need to block the 0.12 release. I'm thinking we have the following todos before 0.12:

- [ ] Fix current `document` and `window` server-side issues
- [ ] Document Enhancer
- [ ] Add Enhancer example
- [ ] Add Enhancer tests

**Comment by ianobermiller** [comment]
Already documented Enhancer before I merged :) I can add tests and examples now that you have the babel stuff in.

**Comment by mrtnbroder** [comment]
Will v0.12 support the v0.13 syntax of react? (class-based approach)

**Comment by ianobermiller** [comment]
Yes, the Radium.Enhancer is used for React class syntax.

**Comment by ianobermiller** [comment]
Looks like v0.12 is good to go!
