### ISSUE TITLE
Server-side Example

### ISSUE THREAD

**Issue by alexlande** [FormidableLabs/radium#143]
We should add a server-rendered example for easier isomorphic testing.

**Comment by jurgob** [comment]
if you go there:
https://github.com/jurgob/radium

I've created a branch with an isomorphic example

**Comment by ianobermiller** [comment]
@jurgob can you submit a PR? Thanks!

**Comment by jurgob** [comment]
I've created the PR:
https://github.com/FormidableLabs/radium/pull/315
