### ISSUE TITLE
radium.js.org

### ISSUE THREAD

**Issue by ianobermiller** [FormidableLabs/radium#148]
Thoughts on using https://radium.js.org as a canonical project URL? Would make us dependent on the folks at http://dns.js.org/, but would also give Radium an awesome domain.

**Comment by mrtnbroder** [comment]
why not http://radium.io/ ? :)

**Comment by ianobermiller** [comment]
That'd be good too!

**Comment by ianobermiller** [comment]
Since radium.js.org would be free, any objections, @alexlande, @colinmegill, @eastridge to using it as the canonicaly domain for Radium? If we want to keep it at http://projects.formidablelabs.com/radium/ that is fine too.

**Comment by eastridge** [comment]
I would like it to remain at the current address.
