### ISSUE TITLE
Is it possible to trigger ":hover" pseudo class on an element?

### ISSUE THREAD

**Issue by paulwehner** [FormidableLabs/radium#150]
If I use the ":hover" pseudo class, is there any way to force it to be triggered even if the element isn't being hovered at the moment. For example if the parent element is being hovered, and I want to tell the child to appear as if it was also hovered.

**Comment by colinmegill** [comment]
I would set a state variable and pass it as a prop to the child, and conditional style based on that.

**Comment by paulwehner** [comment]
So to be clear its not possible?

**Comment by colinmegill** [comment]
Well, it's possible in the way that I described. There are no classes and no inheritance, so it's not quite the way everyone is used to. You aren't doing `$(this).child().trigger('hover')`

**Comment by alexlande** [comment]
Hey @paulwehner:

We don't have an interface to allow you to easily apply a state like `:hover` to a component yourself, that's a Radium internal. I would recommend using `Radium.getState` for this, and treating the `:hover` styles on the non-hovered element as a modifier. Something like this: https://github.com/FormidableLabs/radium/blob/master/examples/app.jsx#L8-L19

**Comment by paulwehner** [comment]
Cool thanks.

**Comment by TigerC10** [comment]
For those looking for the proper highlighting from @alexlande: https://github.com/FormidableLabs/radium/blob/d19f85b442a31d5989cfee32445d29c696871c3b/examples/app.jsx#L8-L19

**Comment by alexlande** [comment]
Thanks @TigerC10!

**Comment by TigerC10** [comment]
I'm not super happy that we can't trigger a radium component's `:hover` event - and for that matter that we can't trigger the `:focus` and `:active` events either.  It _seems_ like it would be a fairly trivial thing to do, and for those that don't want to use it, they don't have to.  But for those that would - it'd be a LOT cleaner than trying to maintain a separate state and read from the style's `:hover` property and apply it when there is no hover actually taking place - then removing the `:hover` styles when applicable.
