### ISSUE TITLE
Use of `console.warn` needs a polyfill note or alternate library.

### ISSUE THREAD

**Issue by ryan-roemer** [FormidableLabs/radium#151]
`console.*` breaks IE8 and is used, e.g. https://github.com/FormidableLabs/radium/blob/63068d59462fa1eabe90e02b276f8b7e18b85441/modules/prefix.js#L115

Suggest either:

* Use a small, cross-browser abstraction like [`simple-console`](https://github.com/FormidableLabs/simple-console)
* Document that users need to polyfill (`simple-console` can do that, and there are other pure polyfills too).

**Comment by ianobermiller** [comment]
To keep it simple, should we just wrap it in `if (console)`?

**Comment by ryan-roemer** [comment]
```js
if (console)
```

is probably sufficient: https://developer.mozilla.org/en-US/docs/Web/API/Console/warn

We're not doing anything funky like `console.*.apply()` which gets really complicated and esoteric.

Could do "paranoid" version:

```js
if (console && console.warn)
```
