### ISSUE TITLE
Style component should take an object, not an array

### ISSUE THREAD

**Issue by alexlande** [FormidableLabs/radium#153]
Right now, the Style component takes an array of rules, which is technically correct but doesn't line up with the way we handle any of our other styles objects, which are all objects.

Should update `Style` so that it doesn't require such a verbose syntax.

**Comment by mrtnbroder** [comment]
+1 for that, I'm currently getting around this by using `assign`/`merge`, otherwise dynamic styles are not getting rendered server-side. (when using the array syntax)

**Comment by ianobermiller** [comment]
@mrtnbroder is this a separate bug you are reporting?
