### ISSUE TITLE
Support prefixing flexbox

### ISSUE THREAD

**Issue by wmertens** [FormidableLabs/radium#156]
Now that vendor prefixing has landed it would be nice to support flexbox. On Safari and IE, the display property needs to be prefixed.

Here's an example implementation:
https://gist.github.com/wmertens/78c840ce04b6e9a1193d#file-auto-vendor-prefixer-coffee-L37-L59

I'm not up to implementing this myself in Radium at the moment, so opening this issue instead.

Cc @ianobermiller

**Comment by ads1018** [comment]
+1

**Comment by bausmeier** [comment]
+1
