### ISSUE TITLE
Convert CSS syntax to style objects

### ISSUE THREAD

**Issue by mrtnbroder** [FormidableLabs/radium#162]
It would be awesome if we could write our styles like you can do it with react-style-syntax, e.g. https://github.com/js-next/react-style/blob/master/examples/0.13/syntax/Button.js

which allows 1:1 copying of css to radium and vice-versa. A killer feature!

**Comment by ianobermiller** [comment]
For simple blocks of style without pseudo-classes and media queries this is fairly simple. It does give the impression, however, that the written CSS will actually map to classes, which of course it will not with Radium.

I think a feature like this does not belong in Radium core, but would be a good candidate for a separate addon package.

**Comment by halt-hammerzeit** [comment]
Hello.
You might be interested in the module I wrote yesterday
https://github.com/halt-hammerzeit/react-styling

It transplies CSS-alike to JSON objects.
If you have any suggestions I'm open to conversations.

**Comment by halt-hammerzeit** [comment]
I can rewrite my module for seamless integration with Radium if you would be interested in it.
You'll get nice syntax and extra flexibiliy and I get extra pageviews)

**Comment by ianobermiller** [comment]
We may just recommend react-styling to use in addition to Radium. Feel free to submit a PR for the FAQ if you like! (e.g. "Can I write my styles using CSS syntax instead?")

**Comment by halt-hammerzeit** [comment]
@ianobermiller Oh, that would be nice, thanks, I'll pull something today

**Comment by halt-hammerzeit** [comment]
@ianobermiller pull request created

**Comment by ianobermiller** [comment]
Closing this for now, since react-styling can be used.
