### ISSUE TITLE
setState is not being called after wrapping component into Radium.Enhancer

### ISSUE THREAD

**Issue by mrtnbroder** [FormidableLabs/radium#163]
Either my tests are messy (they worked fine before) or Radium does some crazy stuff here, I'm not sure.

I have a simple flux-react app based on the v0.13 syntax and my tests are now failing at the point where it should call `this.setState` on `_onStoreChange`:

```javascript
class Container extends React.Component {

  static getStateFromStores() {
    return {
      firstScreen: ScreensStore.getState().get('screens').first()
    }
  }

  constructor(props) {
    super(props)
    this._onStoreChange = this._onStoreChange.bind(this)
    this.state = Container.getStateFromStores()
  }

  componentWillMount() {
    ScreensStore.addChangeListener(this._onStoreChange)
  }

  componentWillUnmount() {
    ScreensStore.removeChangeListener(this._onStoreChange)
  }

  _onStoreChange() {
    this.setState(Container.getStateFromStores())
  }

  render() {...}

}

export default Radium.Enhancer(Container)
```

```sh
FAILED TESTS:
  Container.jsx
    _onStoreChange()
      ✖ should call setState when being called
        PhantomJS 1.9.8 (Mac OS X)
      Expected spy setState to have been called.
```

This worked fine before wrapping it into `Radium.Enhancer`.

The test:

```javascript
describe('_onStoreChange()', () => {

    beforeEach(() => {
      Container = require('../Container.jsx')
      ContainerEl = React.createElement(Container)
      renderedRootElement = TestUtils.renderIntoDocument(ContainerEl)
      spyOn(renderedRootElement, 'setState')
    })

    afterEach(() => {
      renderedRootElement.componentWillUnmount()
    })

    it('should call setState when being called', () => {
      expect(renderedRootElement.setState).toBeDefined()
      expect(renderedRootElement.setState.calls.count()).toEqual(0)
      renderedRootElement._onStoreChange()
      expect(renderedRootElement.setState).toHaveBeenCalled()
      expect(renderedRootElement.setState.calls.count()).toEqual(1)
    })

  })
```

**Comment by ianobermiller** [comment]
Were you using class syntax before wrapping with Radium.Enhancer? With the new syntax, React no longer autobinds handlers, so this is a common issue.

**Comment by mrtnbroder** [comment]
Nope, I have been using the class-syntax before as well. Would you recommend to try `.bind`-ing my stuff where needed? Working on some other stuff now, wondering if that could fix my issue?

**Comment by ianobermiller** [comment]
NVM, looks like you are already calling `this._onStoreChange = this._onStoreChange.bind(this)`. I'll see if I can find a simple repro.

**Comment by mrtnbroder** [comment]
You could probably fork my boilerplate and try it with that one. Thats what my code is based on: https://github.com/mrtnbroder/isomorphic-react-webpack-boilerplate

**Comment by ianobermiller** [comment]
Might this work? http://stackoverflow.com/questions/16502267/issues-with-jasmines-spyon-tohavebeencalled-on-a-prototypal-method

**Comment by ianobermiller** [comment]
One more question; is it only the tests failing, or does it also fail when you test it in the browser?

**Comment by mrtnbroder** [comment]
It works with `.prototype`. so 

```
      spyOn(renderedRootElement, 'setState')
```
is now
```
      spyOn(Container.prototype, 'setState')
```

not sure if that is the correct way to do it though... but it looks like it is?

**Comment by mrtnbroder** [comment]
Thanks for taking a look @ianobermiller, feel free to close this if you want. Or dig in a bit deeper if you want.

It worked in browser btw.

**Comment by ianobermiller** [comment]
I believe this is expected, yes. Thanks for trying that! The only possible thing Radium could do is (dangerously) modify your component class instead of wrapping it.
