### ISSUE TITLE
Add alternatives to README

### ISSUE THREAD

**Issue by ianobermiller** [FormidableLabs/radium#164]
We should add a list of alternative tools for styling react components, and catalog how they compare with Radium. Some that I've run across:

- [x] https://github.com/js-next/react-style
- [x] https://github.com/martinandert/react-inline
- [x] https://github.com/petehunt/jsxstyle
- [x] https://github.com/jsstyles/react-jss
- [x] https://github.com/Wildhoney/ReactShadow
- [x] https://github.com/raphamorim/native-css
- [x] https://github.com/ericwooley/react-in-style
- [x] https://github.com/jhudson8/react-css-builder
- [x] https://github.com/blakeembrey/react-free-style
- [x] https://github.com/RickWong/react-inline-css
- [x] https://github.com/elierotenberg/react-statics-styles
- [x] https://github.com/nick/react-styl
- [x] https://github.com/hackhat/smart-css
- [x] https://github.com/chriskjaer/stilr

Not actively developed or unfinished:

- https://github.com/hedgerwang/react-styles
- https://github.com/chenglou/RCSS - deprecated
- https://github.com/VirtualCSS/planning

Not full CSS solutions:

- https://github.com/nmn/react-stylePrefixr - uses a list of properties
- https://github.com/wearefractal/react-responsive - for media queries
- https://github.com/matthewwithanm/react-mediaswitch - for media queries

Other resources:

- https://github.com/MicheleBertoli/css-in-js
- https://byjoeybaker.com/react-inline-styles - criticism of inline styles

**Comment by wmertens** [comment]
See also #125

**Comment by ianobermiller** [comment]
Work in progress, still need to add the last three:

Library|Syntax|Mechanism|Override mechanism|Compile-time step|Media Queries|Pseudo styles|CSS Syntax|Animations|ES6 Classes|Vendor Prefixes|Dynamic styles
--------|--------|--------|--------|--------|--------|--------|--------|--------|--------|--------|--------
[Radium](https://github.com/FormidableLabs/radium)|Plain objects, `{ ':hover': {…}` + `style` attribute|[Pure inline styles](https://github.com/FormidableLabs/radium#how-does-radium-work)|Object.assign|No|[Yes](https://github.com/FormidableLabs/radium/tree/master/docs/guides#media-queries)|Yes - :hover, :active, :focus|[Not yet](https://github.com/FormidableLabs/radium/issues/162)|[Yes](https://github.com/FormidableLabs/radium/tree/master/docs/api#keyframes)|[Yes](https://github.com/FormidableLabs/radium/tree/master/docs/guides#how-do-i-do-it-then)|Yes|Yes - anything can be done at runtime
[React Style](https://github.com/js-next/react-style)|`StyleSheet.create(…)` + `style` attribute|Converts to CSS|CSS overrides hack - `.foo,.foo.foo1,.foo.foo1.foo2.` (etc.)|[Optional](https://github.com/js-next/react-style#extracting-styles-into-css-at-build-time)|[Yes](https://github.com/js-next/react-style#support-for-media-queries)|[No](https://github.com/js-next/react-style#not-supported-css-features)|[Yes](https://github.com/js-next/react-style#syntax-helpers-for-writing-styles)|No|Yes|Yes, if using [webpack extraction plugin](https://github.com/js-next/react-style#extracting-styles-into-css-at-build-time)|Yes - using inline styles
[React Inline](https://github.com/martinandert/react-inline)|`StyleSheet.create(…)` + `class` attribute|Converts to CSS|Unknown|Yes|Yes|Yes - all that are supported by CSS|No|No|Yes|Yes, after extraction|Yes - using inline styles
[jsxstyle](https://github.com/petehunt/jsxstyle)|JSX props, `<Block marginLeft={12} color={Theme.COLOR} />`|Converts to CSS|Unknown|Yes|Not yet|Not yet|No|No|Yes|Yes, after extraction|Yes - using inline styles
[React JSS](https://github.com/jsstyles/react-jss)|Plain objects, `class` attribute|Converts to CSS|[extend plugin](https://github.com/jsstyles/jss-extend)|No|Yes|Yes?|No|No|Yes|[Yes](https://github.com/jsstyles/jss-vendor-prefixer)|Yes - using inline styles

**Comment by alexlande** [comment]
Awesome work @ianobermiller. I believe @SanderSpies is planning on implementing browser states in react-style (based on https://github.com/js-next/react-style/issues/94), so that might be worth adding.

**Comment by alexlande** [comment]
In addition, I'd love to see at least a note about the fallback styles thing (@JoeyBaker has a good blog post that touches on this).

**Comment by joeybaker** [comment]
@alexlande I'd also like to see that! :)

@ianobermiller that's an awesome list! I need to link to that from my post.

**Comment by alexlande** [comment]
The fallback styles this is really gnarly, unfortunately. I don't know what to do about it. (Convince the react team to allow arrays of style values?!?)

**Comment by joeybaker** [comment]
@alexlande ideally, it's something that a processor could do for you. I can't think of a need to handcode any of the fallbacks?

**Comment by alexlande** [comment]
Eh, I hardcode fallbacks often. Hex color vs rgba color, etc

**Comment by joeybaker** [comment]
I obviously agree, having control over the full~ish CSS API is important, could a processor figure out the rgb → hex conversion for you?

**Comment by ianobermiller** [comment]
Fallbacks shouldn't be hard; we can use the same mechanism that we use for
testing values in prefixer. If it isn't aupported, use the fallback.

**Comment by joeybaker** [comment]
Yup. Agreed.

**Comment by alexlande** [comment]
Client-side yeah, radium can handle it (and we should, that's a good point I hadn't really thought about).

**Comment by alexlande** [comment]
Re the hex vs rgba thing, you could automate a dumb fallback easily (`rgba(255,255,255,0.7)` becomes `#fff`!), but there's some more nuance there a lot of the time. If you use rgba to lighten or darken a color underneath the element, you'll need to fallback to a different shade of the underlying color instead.
