### ISSUE TITLE
Losing access to props and state in constructor

### ISSUE THREAD

**Issue by michaelgraham** [FormidableLabs/radium#169]
First off, thanks for Radium. I've enjoyed using it so far.

I've run into an issue when trying to set state in the constructor for a component enhanced by Radium. Here's an example:

```
class Checkbox extends React.Component {

  constructor (props) {

    super(props);
    this.state = { checked: props.defaultChecked };
  }

  ...
}
```

This works fine with the React component, but enhancing it with Radium causes this to break. In that case, `props` is undefined (and `this` is `RadiumEnhancer` with undefined `props` and `context` properties).

I see the same behavior whether I use `Radium.Enhancer(Checkbox)` or the ES7 decorator syntax, and whether I set state in the constructor or using ES7 property syntax.

I'm using Babel to compile and Radium v0.12.0.

Any guidance on this would be much appreciated. Thanks!

**Comment by ianobermiller** [comment]
Try using `master`, I believe this was just fixed in #165.

**Comment by michaelgraham** [comment]
@ianobermiller thanks for the prompt response.

When I try to install master using npm, I get `sh: rimraf: command not found` for `rimraf lib && babel --stage 0 modules/ -d lib/ && rimraf lib/__tests__ lib/__mocks__`. Any ideas about how to fix/get around this?

I'm new to npm, so I'm not sure if this is an issue on my side or with the package. Thanks for bearing with me!

**Comment by ianobermiller** [comment]
Hmm, I think we may need to move the dependency from dev; I'll take a look.

**Comment by thisbejim** [comment]
I'm losing access to props with es6 as well. If I bind a click function in my constructor "this" now refers to RadiumEnhancer rather than my component.

constructor(props) {
    super();
  this. _handleClick = this. _handleClick.bind(this);
 }

_handleClick() {
  console.log(this); // will be RadiumEnhancer not my component
  console.log(this.props.whatever); // will be undefined
  }
