### ISSUE TITLE
Release v0.12.1

### ISSUE THREAD

**Issue by ianobermiller** [FormidableLabs/radium#174]
Anything else we want to do before the v0.12.1 release?

Here are the user-facing changes:

- [x] Fixes to enhancer - 767050e3e13d464b45032c7f91a8dd1aac68a086
- [x] Cleaned up and fixed prefix - b88958ed03f68254b2b5b238dcb50400254afc99
- [x] Smaller distributed build - ff4378eadbbc669c93e91e35129f74a4319e9837

**Comment by alexlande** [comment]
Nah, it's ready to ship.

Sorry, haven't had time to test the flex prefixing thing. Hopefully today. Probably want to get a few other things in before 0.13 anyway.

**Comment by awkaiser** [comment]
I tried master just now and got this for an isomorphic app that rendered correctly on 0.12.0:

```
Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) rder:1px solid #CCC;-webkit-border-radiu
 (server) rder:1px solid #CCC;border-radius:4px;co
```

Prefixes not being generated when rendered server-side?

**Comment by ianobermiller** [comment]
@awkaiser That's correct; the prefixing is currently only client-side.

**Comment by awkaiser** [comment]
@ianobermiller Can that be resolved before 0.12.1, or is there reasoning behind having Radium only apply prefixes client-side?

**Comment by ianobermiller** [comment]
@awkaiser This will definitely not be resolved in v0.12.1. Server-side prefixing falls under the isomorphic category, which is not fully supported by Radium yet. It would require either preprocessing or using a different prefixer on the server, like autoprefixer.

**Comment by coudron** [comment]
Has there been an update to the server-side prefixing that fixes that portion of the isomorphic bugs?

This chart shows that the media queries are the only remaining task for full isomorphic support:
https://github.com/FormidableLabs/radium/blob/master/docs/comparison/README.md

**Comment by ianobermiller** [comment]
Not yet, I have some things in the works but have not landed anything. Basically looking at prefixing based on User Agent, which is a nightmare to maintain, and we can't really use anything from autoprefixer.
