### ISSUE TITLE
Update website to reflect new API

### ISSUE THREAD

**Issue by ianobermiller** [FormidableLabs/radium#177]
http://projects.formidablelabs.com/radium/ is woefully out of date. Is it backed by the gh-pages branch?

**Comment by alexlande** [comment]
It is, yeah. I'm perplexed as to how it's out of date, because https://github.com/FormidableLabs/radium/commit/568667940947edd9c1290988faab18ff3e449fe9, but can confirm that I'm seeing the old version of the copy on it at the moment too.

Bad gh-pages build, possibly?

**Comment by alexlande** [comment]
Nope-- just forgot to update the copy when we updated the code running the example. Fixing it now.

**Comment by alexlande** [comment]
Done!
