### ISSUE TITLE
Require 'react'

### ISSUE THREAD

**Issue by citelao** [FormidableLabs/radium#178]
The current webpack ends up with `require("React")` which throws warnings on my system when I include it.  Should it be `require("react")`?

https://github.com/FormidableLabs/radium/blob/master/webpack.config.js#L8

**Comment by ianobermiller** [comment]
The webpack config is correct; how are you using Radium? The typical way would be to `npm install radium`.

**Comment by citelao** [comment]
I have to admit I'm a little outclassed with webpack, but when I try bringing Radium from version 10 to version 12 in my project, I get all sorts of warnings about including "React" and "react"— I think webpack's implementation of UMD ends up writing out `require("React")` instead of `require('react')` which *might* be causing the issue.

**Comment by ianobermiller** [comment]
How are you using Radium? Can you point me to a sample repo?

**Comment by citelao** [comment]
I'm working on an internal project, but I'll check. I'll confess I have very little experience with Webpack.

All I know is using 12.x Radium includes "React" while 10.x includes "react." Probably some config glitch on my end.

**Comment by ianobermiller** [comment]
The distributed build of Radium (built with webpack) always had `require("React")`: https://github.com/FormidableLabs/radium/blob/1c7b08686408d1ac2b726b14161bb424efcd2c0b/dist/radium.js

**Comment by Sinewyk** [comment]
That's a mistake then. Similar but right > https://github.com/rackt/react-router/blob/master/lib/umd/ReactRouter.js#L7.

You can probably fix it easily by taking a look inside react-router webpack config files.

**Comment by ianobermiller** [comment]
@Sinewyk thanks for the pointer!

**Comment by citelao** [comment]
Thanks for the quick response on all of this! I'll see if it fixes my issue :)

**Comment by SOSANA** [comment]
@ianobermiller was checking out that radium blob you shared and curious why the use of /*****\ was used so much? Example saw it right after returning a function, never seen that before and it was every were throughout code

**Comment by divmain** [comment]
@SOSANA, that is an artifact of unminified webpack output.

**Comment by SOSANA** [comment]
@divmain Thanks :)

**Comment by citelao** [comment]
:+1: y'all are great
