### ISSUE TITLE
Curious if is there a Material Design component library using Radium?

### ISSUE THREAD

**Issue by SOSANA** [FormidableLabs/radium#195]
Hi all,

Curious if is there a Material Design component library using Radium?

**Comment by ianobermiller** [comment]
It looks like [material-ui](https://github.com/callemall/material-ui) handles the states directly instead of using a library like Radium: https://github.com/callemall/material-ui/blob/master/src/flat-button.jsx. Shouldn't be any problem using them both in the same app.

**Comment by SOSANA** [comment]
Thanks closing for now
