### ISSUE TITLE
Add SauceLabs tests

### ISSUE THREAD

**Issue by ianobermiller** [FormidableLabs/radium#199]
Free for open source projects, get Radium tested in tons of browsers: https://saucelabs.com/opensauce/

**Comment by ryan-roemer** [comment]
@ianobermiller -- If you get a PR going (maybe developing / kicking the tires with some Sauce Credentials you have), I'll jump in and add the encrypted `.travis.yml` secrets of 

```
  SAUCE_USERNAME
  SAUCE_ACCESS_KEY
```
