### ISSUE TITLE
-ms-flex-pack

### ISSUE THREAD

**Issue by skevy** [FormidableLabs/radium#205]
IE10 doesn't support justify-content...it needs "-ms-flex-pack". I can put in "-ms-flex-pack" in my styles specifically, but it tells me it's an unsupported CSS property in other browsers (which makes sense). Any ideas how to fix?

**Comment by ianobermiller** [comment]
You can submit a pr, it should be simple. Look at prefixer.js. We already
special case some properties for older IE.

**Comment by ianobermiller** [comment]
I'm also looking into a slightly different and more manual prefixing implementation as part of #201, which will fix this as well.

**Comment by Zenwolf** [comment]
Is the intent to input the standard and auto-generate the equivalent IE10 values at runtime without making the user manually add them? If so, it seems to also be missing things like:
```text
Standard                           IE 10 (2012 tween spec)
-------------------------------------------------------------
display: inline-flex              display: -ms-inline-flexbox
align-items: center               -ms-flex-align: center
justify-content: flex-end         -ms-flex-pack: end
justify-content: space-between    -ms-flex-pack: justify
align-content: center             -ms-flex-line-pack: center
align-self: flex-end              -ms-flex-align-item: end
flex-basis: 20%                   -ms-flex-preferred-size: 20%
flex-grow: 4                      -ms-flex-positive: 4
```

**Comment by ianobermiller** [comment]
Yes, that is the intent. As you said, most of them are missing.
