### ISSUE TITLE
Different rendering camelCase key on server and client

### ISSUE THREAD

**Issue by coderany** [FormidableLabs/radium#207]
Why this code now renders different on server and client

`const rules = {
  body: {
    margin: 0,
    fontFamily: Theme.fontFamily,
    fontWeight: 300,
    fontSize: Theme.px.fontSize
  }
}`

from console 
`Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) body{margin: 0;
font-family: 'Exo 2', sa
 (server) body{margin: 0;
fontFamily: 'Exo 2', san
`
difference in that on server it renders `fontFamily` and on client `font-family`

Before i upgraded to version 0.13.0 i use 0.12.0 and it was working well

**Comment by ianobermiller** [comment]
Thanks for reporting, this is probably a bug in Prefixer.

**Comment by ianobermiller** [comment]
BTW, I don't love that message: "lost many of the benefits of server rendering". Sure, you have lost some  potential performance benefits, but you still got markup to the user without any JS, so overall it is still a win ;)
