### ISSUE TITLE
require not defined

### ISSUE THREAD

**Issue by ccorcos** [FormidableLabs/radium#212]
When I try to include the distribution script in my file, I get an error:

```
Uncaught ReferenceError: require is not definedwebpackUniversalModuleDefinition @ radium.js:3(anonymous function) @ radium.js:10
```

**Comment by ianobermiller** [comment]
You're using `dist/radium.js`? 

When I use the latest `dist/radium.js` directly from github it works fine: http://jsbin.com/budaxu/1/edit?html,js,output

**Comment by ccorcos** [comment]
hmm. this is weird... let me get back to you on this.
