### ISSUE TITLE
body styles

### ISSUE THREAD

**Issue by ccorcos** [FormidableLabs/radium#213]
Is there a way to style the body with Radium?

**Comment by scottcorgan** [comment]
You can use the [`<Style />`](https://github.com/FormidableLabs/radium/tree/master/docs/api#style-component) component. I usually use this to define global styles on generic HTML elements.

**Comment by alexlande** [comment]
Yep :)

I like to include some global styles and normalize/reset with the `Style` component. You can also include a separate CSS file for that stuff, of course, but `Style` saves you an extra HTTP request.

**Comment by ccorcos** [comment]
sweet :+1:

**Comment by ccorcos** [comment]
Wait, I have to render the component for it to work on the body? That feels weird

**Comment by ianobermiller** [comment]
Yes, unfortunately. I suggest rendering the style component with body styles in your main App component.
