### ISSUE TITLE
styling like css :last

### ISSUE THREAD

**Issue by flyon** [FormidableLabs/radium#214]
I'm currently using the following setup in a bunch of places:

```
for(var key in object){ 
    items.push(<li>{object.value}</li>) 
}
return <ul>{items}</ul>;
```
CSS:
```li:last { border-bottom: 0px }```

I'm currently thinking of switchin to radium, but I'm wondering: 
how can I style the last element? The things is that since I loop through an object, not an array, I don't really know which item comes last. 

Is the only solution to first put all the object keys in an array?

**Comment by alexlande** [comment]
That would be my first instinct, yeah. You'll need some kind of numeric iteration to do first, last, or nth-child styling:

```
Object.keys(object).forEach(function (key, index) {
  // do stuff
}); 
```

**Comment by ianobermiller** [comment]
The third param to the callback is the array, so you can use it to check
the length and see if you are on the last item.

**Comment by flyon** [comment]
Yes I went with the array approach and it's working. Didn't think of Object.keys, that's a handy shortcut!
Tnx for the feedback that this is indeed the best way to do it.
