### ISSUE TITLE
Unsupported CSS property "flex" warning

### ISSUE THREAD

**Issue by chronotc** [FormidableLabs/radium#215]
This warning ```Unsupported CSS property "flex" warning``` appears whenever we run our Mocha test and the component has styles which have flex, flexGrow, ..etc.

```
  render(){
    var buttonStyles = {
      flex: '1 0 0'
    };

    return (
      <button style={buttonStyles}
              onClick={this.doSomething}>
        this is a button
      </button>
    );
  }
```

This only occurs when the component is wrapped with Radium().
```
module.exports = Radium(NumpadKey);
```

**Comment by ianobermiller** [comment]
For your tests, you'll want to make sure `ExecutionEnvironment`, module `exenv` is mocked as:

```as
{
      canUseDOM: true,
      canUseEventListeners: true
}
```

Then the prefixer will bypass the property checks.

**Comment by ianobermiller** [comment]
Were you able to get this working? Please reopen if not.
