### ISSUE TITLE
expose resolveStyles in API

### ISSUE THREAD

**Issue by scottcorgan** [FormidableLabs/radium#216]
I'm using Radium in a module where I want to handle the condition in which styles get resolved or if Radium is even used.

It would be helpful to expose the style resolver as method to get the benefit of Radium in external, custom logic.

Something like `Radium.resolveStyles` would be helpful.

**Comment by ianobermiller** [comment]
We had considered this, but resolveStyles is not enough. You also need the
component lifecycle methods to make sure everything is cleaned up
correctly. Why would you need to keep styles for being resolved or
selectively use Radium?

**Comment by scottcorgan** [comment]
I'm using a wrapper over React, using a more functional approach.  Since Radium requires either an ES6 class extend React.Component or and ES5 class using React.createClass, I'm having having a hard time  implementing any inline-style helper.

It's kind of a bummer most inline style modules are closely tied to React. It would be awesome to see an exposed API that is agnostic to the environment it is being used.

I'm not sure this is in the scope of Radium, but it does help with future-proofing and decoupling.

**Comment by ianobermiller** [comment]
Exposing the API isn't too hard. You need a few things:
- Somewhere to store state in a component instance
- Somewhere to call the lifecycle method to clean up after a component instance is unmounted
- Somewhere to call resolveStyles (this one is the easiest)

How might that look in your approach? It would be very little work for us to expose it, and if we can do it in a clean way without adding too much to the API surface I'd be happy to work with your more on this.

**Comment by scottcorgan** [comment]
I'm not sure. I'd have to continue to think about it. I'll open a PR if I have any ideas.

But, they main idea is that Radium would be an inline styles module rather than a React inline styles module. With that, styles can be applied in any environment.
