### ISSUE TITLE
No object Radium.Config or Radium.config

### ISSUE THREAD

**Issue by MaxSvargal** [FormidableLabs/radium#220]
From docs https://github.com/FormidableLabs/radium/tree/master/docs/api#configsetmatchmedia
Radium has no "Config" of "config" object in radium/dist bundle (i'm use webpack import).

Edit: commit with this feature will added 12 day ago. Maybe the time has come for new release?

**Comment by ianobermiller** [comment]
Ah yes, that hasn't been released to npm yet. Docs are uptodate with
master. I can cut a release this weekend if I have time.
