### ISSUE TITLE
Fallback expressions don't work when first is numeric

### ISSUE THREAD

**Issue by Dremora** [FormidableLabs/radium#221]
I'm trying to calculate height of an element based on the viewport height using `vh` units and fallback to the actual viewport height I'm injecting into the component as `height` property:

```javascript
    let backgroundStyle = {
      height: [`${height - headerHeight}px`, `calc(100vh - ${headerHeight}px)`]
    }
```

However, my component gets rendered with the following style
```css
height: 343px,calc(100vh - 64px)
```

packages:
```javascript
    "react": "0.13.3",
    "radium": "0.13.0"
```

I'm getting this CSS both on the server and on the client.

Interestingly enough, if I switch the order of the values:

```javascript
height: [`calc(100vh - ${headerHeight}px)`, `${height - headerHeight}px`]
```

I'm only getting the following CSS:

```css
height: calc(100vh - 64px)
```

**Comment by ianobermiller** [comment]
You have the order the same in both examples. calc should come first, as Radium will use the first value that can be applied successfully. Being rendered with a comma is definitely a bug, I'll try to get a repo.

**Comment by Dremora** [comment]
Apologies, the order in the 1st example should be:
```javascript
height: [`calc(100vh - ${headerHeight}px)`, `${height - headerHeight}px`]
```

I've just realized that the order is reversed compared to the native CSS fallback. How does this work on the server, where we don't know what is supported by the browser and what's not? Are all the declarations simply rendered in the reverse order?

**Comment by ianobermiller** [comment]
On the server, Radium renders the first value in the fallback array.

**Comment by Dremora** [comment]
Is it possible in case of server-side rendering to make it reverse the array and render **all** the values (so that browser will be the one doing the fallback)? Or it's simply not possible with inline CSS?

**Comment by alexlande** [comment]
It's not possible with React currently. I'm hopeful that the React team will change their minds on that one because it's an important use case. See https://github.com/facebook/react/pull/723 for some discussion.
