### ISSUE TITLE
repeating key name

### ISSUE THREAD

**Issue by paulwehner** [FormidableLabs/radium#222]
What is the correct way to approach a style option where they key is repeated multiple times in CSS. For example:

var style = {
        display: '-webkit-box',
        display: '-moz-box',
        display: '-ms-flexbox',
        display: '-webkit-flex',
        display: 'flex'
}

If I use the babel-loader, then this code will fail for having "Duplicate data property in object literal not allowed in strict mode". I'm just using the default babel-loader with webpack right now.

**Comment by alexlande** [comment]
@paulwehner: You can use fallback arrays for this: https://github.com/FormidableLabs/radium/tree/master/docs/guides#fallback-values

For this case, Radium handles the vendor prefixing for you, so you can just use `display: flex`

**Comment by paulwehner** [comment]
Awesome thanks for the quick response!

**Comment by paulwehner** [comment]
What other vendor prefixing does Radium do? For example "transition: opacity .25s linear" does it provide all the other options?

**Comment by ianobermiller** [comment]
No, we have not yet special cased values, other than a leading prefix. Same
would go for linear gradients. Please open a new issue for your specific
case, as it should be covered under prefixes.

**Comment by ianobermiller** [comment]
I don't think there is anything left to be done here.
