### ISSUE TITLE
Move tests from jest to karma

### ISSUE THREAD

**Issue by ianobermiller** [FormidableLabs/radium#225]
Jest just hasn't been moving very quickly development-wise. I wonder if we should move our tests to karma. We can use `karma-commonjs-plus` for mocking and `isparta-loader` to get proper code coverage reports again. Also, our tiny test suite takes ~2.5 seconds to run, which seems like way too long.

**Comment by alexlande** [comment]
I'd be for this. Jest is cool but doesn't seem to have much traction. This would let us not have the weird "stuck on node 0.10" thing anymore too.
