### ISSUE TITLE
npm Install fails for v0.13.0 on Windows 8.1

### ISSUE THREAD

**Issue by rghazarian** [FormidableLabs/radium#226]
Here's the error output from npm:
32432 error Windows_NT 6.3.9600
32433 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
32434 error node v0.12.0
32435 error npm  v2.5.1
32436 error code ELIFECYCLE
32437 error radium@0.13.0 postinstall: `node -e "require('fs').stat('lib', function(e,s){process.exit(e || !s.isDirectory() ? 1 : 0)})" || npm run prepublish`
32437 error Exit status 1
32438 error Failed at the radium@0.13.0 postinstall script 'node -e "require('fs').stat('lib', function(e,s){process.exit(e || !s.isDirectory() ? 1 : 0)})" || npm run prepublish'.
32438 error This is most likely a problem with the radium package,
32438 error not with npm itself.
32438 error Tell the author that this fails on your system:
32438 error     node -e "require('fs').stat('lib', function(e,s){process.exit(e || !s.isDirectory() ? 1 : 0)})" || npm run prepublish
32438 error You can get their info via:
32438 error     npm owner ls radium
32438 error There is likely additional logging output above.

**Comment by ianobermiller** [comment]
There should be some other logs before this, can you include the rest of them? There was an bug in the babel release 5.6.8 that you may have hit that has since been fixed.

**Comment by rghazarian** [comment]
Here's a link to the full output of [npm-debug.log](https://www.dropbox.com/s/laxnhcvcexulvfb/npm-debug.log?dl=0)
Thanks for your help.

**Comment by exogen** [comment]
@rghazarian can you see if this is working now with the latest release, v0.13.4?

**Comment by ianobermiller** [comment]
Please reopen if the issue persists.
