### ISSUE TITLE
How to merge Radium styles and explicit inline styles

### ISSUE THREAD

**Issue by mairh** [FormidableLabs/radium#227]
I am able to successfully import the styles using Radium in my react components. However, I am finding a bit confusing on how to merge styles from Radium and explicit inline styles

Original code:
```
<div className="forum-header" style={{ backgroundImage: this._getHeaderBgUrl() }}>
</div>
```

After using Radium and writing my css in JS (Thus removing `className` prop)
```
<div style={styles.forumHeader}>
```

Now my question is how do I merge the explicit inline style which was in my original code 
`style={{ backgroundImage: this._getHeaderBgUrl() }}` along with Radium style

This of course doesn't work
```
<div style={styles.forumHeader, backgroundImage: this._getHeaderBgUrl()}>
</div>
```

**Comment by ianobermiller** [comment]
Use an array, and Radium will merge it for you:

```as
<div style={[styles.forumHeader, {backgroundImage: this._getHeaderBgUrl()}]}></div>
```
