### ISSUE TITLE
Use console.warn instead of console.warning

### ISSUE THREAD

**Issue by angeloashmore** [FormidableLabs/radium#228]
In PR https://github.com/FormidableLabs/radium/pull/218, `console.warning()` is used several times for logging an error.

Shouldn't it be calling `console.warn()`? Safari is throwing an error:

```
undefined is not a function (evaluating 'console.warning')
```

**Comment by ianobermiller** [comment]
I thought so...for some reason I wrote `warning` :S Feel free to PR, or I'll get to it eventually.

**Comment by ianobermiller** [comment]
Oh nice, just saw the PR

**Comment by angeloashmore** [comment]
Yup, just submitted it
