### ISSUE TITLE
Keyframe helper with multiple transforms

### ISSUE THREAD

**Issue by morenoh149** [FormidableLabs/radium#233]
I attempted to make a keyframe animation like so
```javascript

var sunIconKeyframes = Radium.keyframes({
  '0%': {
    opacity: 0,
    transform: 'translate3d(0, 100%, 0)'
  },
  '100%': {
    opacity: 1,
    transform: 'rotate(360deg)'
  }
})
```
the idea being the element starts offset from the top and is animated rising while rotating. See [fadeInUp](https://github.com/daneden/animate.css/blob/9d4c59e5e5a1fbf149c13cb71a4448aba020882f/source/fading_entrances/fadeInUp.css#L4) But when I run this code only the first animation registers. Should this be documented?

**Comment by morenoh149** [comment]
I ended up doing this
```javascript
var sunIconKeyframes = Radium.keyframes({
  '0%': {
    opacity: 0,
    transform: 'rotate(-1turn) translateY(100%)',
    transformOrigin: '50% 75%'
  },
  '100%': {
    opacity: 1,
    transform: 'none'
  }
})
```

**Comment by ianobermiller** [comment]
If it works in CSS form it should work in radium, as radium converts to CSS
for animations.

Only caveat would be precedence under inline styles.
