### ISSUE TITLE
matchMedia export breaks IE11

### ISSUE THREAD

**Issue by ianobermiller** [FormidableLabs/radium#234]
Pull request #146 broke IE11. The matchMedia export overrides the built-in matchMedia function which causes IE to throw an Invalid calling object exception and will not load the page.

**Comment by azazdeaz** [comment]
I dont know how do you mean:
> matchMedia export overrides the built-in matchMedia function

it doesn't change the window.matchMedia(). I just tested some Radium examples with mediaqueries on win10/ie11/BrowserStack and they are working without any problem.
@ianobermiller @bunkat How can you reproduce [this](https://github.com/FormidableLabs/radium/pull/146#issuecomment-117342432)?

**Comment by bunkat** [comment]
It may be something else, but `invalid calling object` generally means that a built-in function has been hidden (Chrome and Firefox create shadow versions, IE throws an exception).  I'm using IE11 on Windows 7 and packaging using Webpack.

Looks like I'm calling `matchMedia` with a 'print' query when the exception is thrown.

![image](https://cloud.githubusercontent.com/assets/665885/8457514/ad622d32-1fc6-11e5-8896-1622c74e557c.png)

**Comment by ianobermiller** [comment]
Might be related to this [stackoverflow thread](http://stackoverflow.com/questions/25895127/invalid-calling-object-ie). It could be that we are aliasing `window.matchMedia` to a variable, and then calling it later. If we just wrap it in a function instead, that would help.

**Comment by ianobermiller** [comment]
I'm not able to reproduce this in IE11 using the following code ([jsbin](http://jsbin.com/torako/edit?js,output)):

```as
@Radium
class Example extends React.Component {
  render() {
    return (
      <div style={{
        '@media (min-width: 300px)': {
          color: 'green'
        },
        '@media print': {
          fontSize: '400%'
        }
      }}>
        hello
      </div>
    );
  }
}

React.render(<Example />, document.body);
```

Even so, I believe my proposal above would fix this.

**Comment by azazdeaz** [comment]
I think so, but i wasn't able to reproduce the bug so far. Doing this in ie11:
```jacascript
var mm = window.matchMedia
mm('print').matches
```
works well

**Comment by azazdeaz** [comment]
Okay, should i prepare a pull request with wrapped ```window.matchMedia```?

**Comment by ianobermiller** [comment]
Beat you to it, sorry!
