### ISSUE TITLE
Radium breaks getDefaultProps on IE

### ISSUE THREAD

**Issue by bobbyrenwick** [FormidableLabs/radium#235]
I've tested this on IE9/10 (internet is too slow to download an 11 VM right now) and created some examples on my fork that demonstrate that it is Radium that is responsible.

https://github.com/bobbyrenwick/radium/tree/test-out-ie

I can't see anything that makes it immediately obvious why this is happening

**Comment by ianobermiller** [comment]
This doesn't repro in IE11, the only one I have access to currently: 

```as
var Example = React.createClass({
  getDefaultProps() {
    return {
      text: 'hello'
    };
  },
  
  render() {
    return (
      <div style={{
        ':hover': {
          fontSize: '200%'
        }
      }}>
        {this.props.text || 'default not working'}
      </div>
    );
  }
});

Example = Radium(Example);

React.render(<Example />, document.body);
```

**Comment by bobbyrenwick** [comment]
@ianobermiller I had a brief look at this between talks at ReactEurope today and tracked it down to the [Enhancer](https://github.com/FormidableLabs/radium/blob/master/modules/enhancer.js#L11) which creates a subclass of the class you're wrapping.

This is because `defaultProps` becomes a static property of the component before you wrap it, and a [caveat of babel](http://babeljs.io/docs/advanced/caveats/#classes-10-and-below-) means that doesn't get copied to the subclass you create. I spoke to @sebmck about this and he suggested using the optional [spec.protoToAssign](http://babeljs.io/docs/advanced/transformers/spec/proto-to-assign/) in order to try and work around the issue. We tried that and it didn't work. So it seems that that in order to for Radium to support IE9/10 then we need to move away from using classes in the enhancer.

What do you think about that?
