### ISSUE TITLE
Warn on and ignore null or undefined values

### ISSUE THREAD

**Issue by paulwehner** [FormidableLabs/radium#245]
I made a stackoverflow outlining the issue:

http://stackoverflow.com/questions/31264376/reactjs-radium-altjs-uncaught-typeerror-cannot-read-property-tostring-of

**Comment by ianobermiller** [comment]
The only time prefixer calls `toString` is on the [value of a property when it is not a string][1]. So if you are seeing this error, you must be passing null or undefined as the value for some property. Radium should probably just warn you about this and ignore it.

  [1]: https://github.com/FormidableLabs/radium/blob/6438547c1073f5a71ab84395099e39e35903c933/modules/prefixer.js#L187
