### ISSUE TITLE
Update tests to use more specific/helpful Chai assertions

### ISSUE THREAD

**Issue by exogen** [FormidableLabs/radium#248]
These will give more helpful assertion failure messages.

Examples:
```
expect(Prefixer).to.have.property('cssPrefix', '-moz-');
```
and
```
expect(result.prop).to.have.deep.property('style.background', 'blue');
```

**Comment by ianobermiller** [comment]
Closing, this will happen as we migrate away from the module-level tests and instead test Radium as a blackbox, as in #386.
