### ISSUE TITLE
Create config file

### ISSUE THREAD

**Issue by rgerstenberger** [FormidableLabs/radium#25]
I think we need a place to store configuration like default included mixins/modules and variables. I'm not sure if there's an npm convention we want to follow or pave our own path or something else.

/cc @alexlande @colinmegill @aykayen

**Comment by alexlande** [comment]
@rgerstenberger: Can we close this given the addition of the radium-bootstrap config? Feels like this doesn't fit into Radium core.

**Comment by rgerstenberger** [comment]
Yeah, until we have enough modules to warrant different builds this is a non-issue.
