### ISSUE TITLE
Project site usage is outdated: Radium.wrap

### ISSUE THREAD

**Issue by levithomason** [FormidableLabs/radium#251]
The [project site](http://projects.formidablelabs.com/radium/) details usage via `React.createClass(Radium.wrap({...}))`.  This seems to have been removed and throws "not a function".

The README usage is `module.exports = Radium(Component)` or `Component = Radium(Component)` and works.

Thanks for cranking on this.

**Comment by ianobermiller** [comment]
@alexlande Do we just have to update the `gh-pages` branch to update the website?

**Comment by kenwheeler** [comment]
@ianobermiller yup

**Comment by ianobermiller** [comment]
Done!

**Comment by levithomason** [comment]
Nice.
