### ISSUE TITLE
componentWillReceiveProps changes the State but shouldComponentUpdate does not consider this change

### ISSUE THREAD

**Issue by af7** [FormidableLabs/radium#269]
Hello,

I use `componentWillReceiveProps` to change the State before rendering *and* also `shouldComponentUpdate` to determine whether to render (based on the State that `componentWillReceiveProps` does change):

````
componentWillReceiveProps(nextProps) {
var newValue = //do stuff here to calculate newValue ; 
this.setState({stateVar: newValue});
}
````

````
shouldComponentUpdate(nextProps, nextState) {
        var shouldUpdate = nextState.stateVar !== this.state.stateVar;
        return !!shouldUpdate;
    }
````

Based on my tests, the `nextState.stateVar` is *still* the old one, despite the `componentWillReceiveProps` did change it.

May I assume that this is *not possible* or is this a bug?

Thank you.

**Comment by ianobermiller** [comment]
Is this radium specific? If not, please post your question to stackoverflow.

**Comment by af7** [comment]
You are right, I saw a similar post here and thought I could ask, I have just created a stackoverflow post.

**Comment by alexlande** [comment]
Going to close this out. Best of luck with your issue!
