### ISSUE TITLE
Radium updates displayName to Radium(<component_display_name>)

### ISSUE THREAD

**Issue by theogravity** [FormidableLabs/radium#271]
I'm trying to obtain the component's `displayName`. When wrapping Radium around my component, the `displayName` is updated to `Radium(<display_name>)`. Is this intended? I want the original `displayName`.

**Comment by alexlande** [comment]
This is intentional and is meant to give a clear indication that the component is using Radium for debugging purposes. 

What's your use case for needing the original `displayName`?

**Comment by ianobermiller** [comment]
I'm open to removing the "Radium(...)" wrapper around displayName. Can you image if every decorator did the same? `Radium(Relay(autobound(Button)))` :-1:

**Comment by theogravity** [comment]
We have a custom workflow that involves using `react-docgen` and `react-styleguide-generator`. We'd like to map the displayName of the loaded component to a dictionary of displaynames, which contains metadata about that component.

**Comment by theogravity** [comment]
Here's an example of what we're trying to build, and how the wrapping gets in the way:

We're using `displayName` to auto-generate code examples based on the `props` of a component.

<img width="849" alt="screenshot" src="https://cloud.githubusercontent.com/assets/855434/8770444/fe99caee-2e66-11e5-8799-1f12a718166d.png">
