### ISSUE TITLE
Resolve styles on components passed as props

### ISSUE THREAD

**Issue by tony-kerz** [FormidableLabs/radium#276]
sometimes a component accepts a nested element as a property (e.g. [material-ui left-nav header property](http://material-ui.com/#/components/left-nav)), further it is allowable to specify the element in-line (vs a reference to a formally defined class).

here is an example (note the syntax in which the `header` property is passed to `MuiLeftNav`):

```
import React, {Component} from 'react'
import MuiLeftNav from 'material-ui/lib/left-nav'
import MenuItem from 'material-ui/lib/menu/menu-item'
import Radium from 'radium'

@Radium
class LeftNav extends Component {

  render() {
    let menuItems = [
      { route: 'home', text: 'Home' },
      { route: 'sign-in', text: 'Sign In' },
      { route: 'sign-up', text: 'Sign Up' },
      { type: MenuItem.Types.SUBHEADER, text: 'Resources' },
      {
         type: MenuItem.Types.LINK,
         payload: 'https://github.com/tony-kerz/react-scratch',
         text: 'GitHub'
      }
    ]

    return(
      <MuiLeftNav
        ref="leftNav"
        docked={false}
        menuItems={menuItems}
        header={ 
          <div
            onClick={this._onNavHeaderClick}
            style={styles.foo}> // <---------------------------------------------------- here...
            foo
          </div>
        }
        onChange={this._onLeftNavChange}
      />
    )
  }

  toggle() {
    this.refs.leftNav.toggle()
  }

  _onLeftNavChange = (e, key, payload) => {
    console.log('left-nav: olnc: e=%o, key=%o, payload=%o', e, key, payload)
    this.context.router.transitionTo(payload.route)
  }

  _onNavHeaderClick = () => {
    console.log('left-nav: ohc')
    this.context.router.transitionTo('home')
    this.refs.leftNav.close()
  }

  static contextTypes = {
    router: React.PropTypes.func
  }
}

let styles = {
  foo: {
    background: 'red',
    color: 'blue',
    ':hover': {
      cursor: 'crosshair',
      background: 'green'
    }
  }
}

export default LeftNav
```

however, radium doesn't seem to be working it's magic for the `style` property passed to that `div` for the `header` property.

i was thinking maybe to use something like `Radium.wrap` around the `div` but looks like `Radium.wrap` is being retired.

any syntax i can use for situations like this or would i need to create a formal class for the `div` and decorated it with `@Radium`
to get this to work...?

**Comment by ianobermiller** [comment]
Creating a class as you mentioned will work. We could also change radium to
resolve the styles of children passed as props, but then we'd incur that
iteration cost every time, although it is probably not a big issue.

**Comment by tony-kerz** [comment]
thanks ian,

first, thank you for `Radium`, i think it's great to augment react by supporting pseudo-class-selectors, media-queries and [this type of style-merging](https://github.com/callemall/material-ui/blob/b21bbfff04ecefc6341e4054f8f3987a9f96ae20/src/mixins/style-propable.js).

i think it would be a nice feature to resolve for children as sometimes children are only used in that one spot and creating a class is a bit of otherwise unnecessary typing.

if the iteration cost is significant enough to be of concern, could something like the deprecated `Radium.wrap` be applied as needed?

regards,
tony.

**Comment by ianobermiller** [comment]
I'm not sure if a wrapper would work; the only thing I can think of is that it would be a sentinal value that Radium knows about, which wouldn't really help the iteration cost. I think we can add the prop check in, and if it becomes burdensome revisit the perf issue then.

**Comment by tony-kerz** [comment]
after some research, i think this converges with the [issue of processing for non-dom elements](https://github.com/FormidableLabs/radium/issues/258#issuecomment-120894544).

in trying to simplify my example, i show a plain-old `div` being passed for the `header` property, but what i was really trying to do involved adding a `:hover` state to one element in an 'assembly' of pre-written material-ui components:

```
  render() {
     //...
    return(
      <LeftNav
        ref="leftNav"
        docked={false}
        menuItems={menuItems}
        header={
          <CardHeader
            title="Title"
            subtitle="Subtitle"
            avatar={
              <Avatar // <----------------------------------------------- wanted to add a hover state to this element...
                onClick={this._onNavHeaderClick}
              >
                A
              </Avatar>
            }
          />
        }
        onChange={this._onLeftNavChange}
      />
    )
  }
```

what i ended up having to do was write a wrapper for the material-ui `Avatar` component like so:

```
import React, {Component} from 'react'
import Avatar from 'material-ui/lib/avatar'
import Radium from 'radium'

@Radium
class ClickableAvatar extends Component {

  render() {
    return(
      <span
        onClick={this.props.onClick}
        style={styles}
      >
        <Avatar style={this.props.style}>
          {this.props.children}
        </Avatar>
      </span>
    )
  }
}

let styles = {
  ':hover': {
    cursor: 'pointer'
  }
}

export default ClickableAvatar
```
which seems like a bit more 'friction' when compared to using the vanilla material-ui component with conventional styling techniques like so:

```
      <LeftNav
        ref="leftNav"
        docked={false}
        menuItems={menuItems}
        header={
          <CardHeader
            title="Title"
            subtitle="Subtitle"
            avatar={
              <Avatar 
                className='clickableAvatar' //<----------------------------------------------- add class here
                onClick={this._onNavHeaderClick}
              >
                A
              </Avatar>
            }
          />
        }
        onChange={this._onLeftNavChange}
      />
```

and some plain-old css like:

```
.clickableAvatar:hover {
  cursor: pointer;
}
```

i think scenarios like this could be partially addressed by your 'sentinel' idea, but attempting to apply radium features to existing library components adds some additional wrinkles.

i get the general idea about what you were saying around event-handlers/on-mouse-enter/this.props (would be interested in a little more layman's detail), but sounds like that wouldn't be possible with non-radium library components unless there is some clever monkey-patching solution lurking just outside the realm of my javascript expertise.

interested in your thoughts on this family of use cases.

best,
tony.
