### ISSUE TITLE
setting key breaking nested radium components 

### ISSUE THREAD

**Issue by philholden** [FormidableLabs/radium#280]
I have:
* a table which is a Radium component
* a table row which is also a Radium component which contains `<td>`s

I want `:hover` on on both `<tr>` and the first `<td>` so I need to set a unique key prop on these elements. However as soon as I set a key, rendering breaks. Items are hovered but never unhovered. 

```html
      <tr style={[styles.tr]} key={row.id + 'b'}>
        <td
          style={[styles.td, styles.link, {cursor: 'pointer'}]}
          key={row.id + 'a'}>
          {row.name}
        </td>
```

```javascript
{
  tr: {
    ':hover': {
      background: '#eee',
      cursor: 'pointer'
    }
  },
  link: {
    textDecoration: 'underline',
    color: '#05C',
    cursor: 'pointer',
    ':hover': {
      textDecoration: 'none'
    }
  }
}
```

If I don't use keys and just add `:hover` to the `<tr>` it works fine:
```html
      <tr style={[styles.tr]} >
        <td>
          {row.name}
        </td>
```

As soon as I add a key to `<tr>` it breaks (items never return to unhovered style):

```html
      <tr style={[styles.tr] key={row.id}} >
        <td>
          {row.name}
        </td>
```

**Comment by philholden** [comment]
The only way I can get round it at the moment is to make the td into a component so I don't have to use keys.

**Comment by ianobermiller** [comment]
Did you find the problem? You shouldn't need to make another component to do this.

**Comment by philholden** [comment]
Yes sorry. I implemented a shouldComponentUpdate method which I forgot
about.
