### ISSUE TITLE
Resolve styles on elements returned from function as children

### ISSUE THREAD

**Issue by yanivtal** [FormidableLabs/radium#281]
Unless there's some user error, I think Radium does something that breaks react-motion. React-motion works by using Spring components to specify animation behavior. With the @Radium decorator I get the following Javascript error from the Spring's render method.

```
Uncaught TypeError: this.props.children is not a function
```
in the following code
```
render: function render() {
    var currVals = this.state.currVals;

    return _react2['default'].Children.only(this.props.children(currVals));
  }
```
React-motion works without Radium and Radium works without react-motion. Here's my render method:
```
render() {
    return (
      <Spring className="box" endValue={{val: this.state.isClosed ? 1 : 0, config: [90, 18]}}>
        {({val}) =>
            <img src={this.props.img}
                 style={[styles.img, this.imgStyle(val)]}
                 onMouseDown={this.handleMouseDown.bind(this)}/>
        }
      </Spring>
    );
  }
```
Any thoughts?

**Comment by yanivtal** [comment]
React-motion requires that the Spring component receives a single child as a return value to its children prop. Radium does something funny with the children?

**Comment by ianobermiller** [comment]
This has been fixed in master, check recent issues for "function".

**Comment by yanivtal** [comment]
I'm having trouble running from master because of the postinstall running Karma. When are you planning on bumping the version?

**Comment by ianobermiller** [comment]
The postinstall issue has already been fixed. I'll probably do a point release soon.

**Comment by yanivtal** [comment]
Cool I was able to link to that branch. Thanks!

**Comment by yanivtal** [comment]
Running on the latest master I no longer get the javascript error but my styles aren't being applied. In the style attribute I see: "0:[object Object];1:[object Object];".

When I remove the Spring component Radium does its thing correctly, but this is a problem on the Radium side. Code is the same as above.

**Comment by yanivtal** [comment]
I followed the original PR and it looks like the solution was just to ignore functions as children. Are there any plans to support Radium in functions as children? Seems like a pattern that's quickly catching on.

**Comment by mingfang** [comment]
I think I'm see similar compatibility problems with react-transitive-number.
```<TransitiveNumber>123</TransitiveNumber>``` works
```<TransitiveNumber>{this.state.someState}</TransitiveNumber>``` causes
```Uncaught TypeError: Cannot read property 'toString' of null``` inside TransitiveNumber.render().
The line looks like this ```var value = this.props.children.toString();```

**Comment by boyswan** [comment]
+1 coming across a handful of libraries using functions as children!

**Comment by ianobermiller** [comment]
We could do this by wrapping the function-child and calling resolveStyles on the result of it.

**Comment by ianobermiller** [comment]
@mingfang, can you provide a simple repro for this and open a new issue? I think it might be slightly different.
