### ISSUE TITLE
Possible to support WebkitOverflowScrolling?

### ISSUE THREAD

**Issue by mbrochh** [FormidableLabs/radium#290]
I keep getting tons of warnings in the console like this:

```
Unsupported CSS property "WebkitOverflowScrolling" in prefixer.js line 269
```

This is because of the following Radium style:

```
const styles = {
  scroll: {
    overflowY: "scroll",
    WebkitOverflowScrolling: "touch"
  },
}
```

Am I doing it wrong or does Radium not support this style?

**Comment by ianobermiller** [comment]
The prefixer checks if a value is supported by the browser and throws that warning if it isn't. Are you seeing this warning on a browser that supports the property?

**Comment by mbrochh** [comment]
Oh, I wasn't aware the the prefixer does it's magic on runtime based on the current browser. yea I'm seeing this on OSX Chrome, so I guess that feature is only available on Mobile Safari and I should just ignore those warnings. Thank you!

**Comment by ianobermiller** [comment]
@mbrochh You've explained it perfectly!
