### ISSUE TITLE
Incorrect hover state when mouse appears above element

### ISSUE THREAD

**Issue by qimingweng** [FormidableLabs/radium#291]
Imagine you have an element with hover properties defined. First, hover over an element, then create an element on top of it so that your focus has changed. Then, delete the covering element while still above the general area of the original element.

Thus, the mouse appears on the original element without a onMouseEnter call! There was technically no mouseEnter event!

My suggestion is that Radium maybe also listen to onMouseMove calls to simulate hover.

**Comment by ianobermiller** [comment]
Yes, `onMouseMove` is a good idea, although we have to be careful with the implementation to check if `:hover` is already true, so we avoid unnecessary `setState`s.

**Comment by masad-frost** [comment]
Any proper workarounds for this?

There's this idea of mutating state upon deleting the covering element.
```javascript
  deleteCoveringElement() {
    const styleState = this.state._radiumStyleState;
    $.extend(true, styleState, {mainElement: {':hover': false}});
    this.setState({
      _radiumStyleState: styleState,
      deleteCoveringElement: true,
    });
  }
```
But has the obvious side effect of having the hover state stuck to false unless your mouse triggers a onMouseEnter (i.e. mouse needs to go/be outside the element and enter again).

I'm not very familiar with how radium works, so I'm not sure if changing the state like that is healthy practice anyway.

**Comment by ianobermiller** [comment]
So I put together a [JSBin to test this](https://jsbin.com/wobudi/2/edit?js,console,output), and I think if we just implement mouseOver and treat it just like mouseEnter, we should be good as soon as the mouse moves, but not have to deal with the flood of events like we do with mouseMove.

> I'm not sure if changing the state like that is healthy practice anyway.

You're right, please don't use private radium fields. Those are considered internal to the library, and will be changed without notice.

**Comment by masad-frost** [comment]
That seems to work.

It looks like I misunderstood the issue at hand anyway. I was pointing out a parent child relationship, where mouseLeave is never registered if the element is deleted while your mouse is outside the area of the parent. Accordingly, the element will always be regarded as hovered, until you actually hover and then unhover. [Here's a JSbin](https://jsbin.com/jusavugomo/edit?js,console,output) to illustrate this. If this isn't clear enough, let me know, I can share a more elaborate bin or something.

In most cases I can think of, it's possible to change the relationship from parent child to sibling, where we have the current issue that's solvable by your suggest moueOver.

**Comment by ianobermiller** [comment]
Thanks for riffing on the bin with a more accurate example. Actually, if you [add mouseOver to your example](https://jsbin.com/mopoda/1/edit?js,console,output), you will see that it does get fired as soon as the mouse moves over the parent.

But  your point about `mouseLeave` not being called is valid and quite annoying. I can't think of a performant way for Radium to detect these cases.

**Comment by ianobermiller** [comment]
Closing, as there is a simple workaround by changing the element hierarchy.
