### ISSUE TITLE
Redundant resolveStyles on nested Radium components

### ISSUE THREAD

**Issue by ifsred** [FormidableLabs/radium#293]
Hello. I have an issue when I wrap Radium component inside another Radium component.

Here is an example: http://codepen.io/anon/pen/zGmyLd?editors=101

I think whats going on is that both of the components resolve styles on the blocks in following manner: `flex: 1` -> `WebkitFlex: 1` -> `WebkitFlex: 1px`, which obviously break things.

This is probably due to Radium resolving styles on `this.props.children`, is there a way to workaround this?

**Comment by ianobermiller** [comment]
This is a bug, nice catch! Yes, Radium is processing the rendered elements twice, and it was only visible because the prefixer didn't recognize WebkitFlex as a unitless number, and added px to it.
