### ISSUE TITLE
Alternatives to pseudo-elements

### ISSUE THREAD

**Issue by alexlande** [FormidableLabs/radium#3]
Need documentation on what to do instead of pseudo-elements (`::after`, `::before`).

**Comment by berbaquero** [comment]
As far as I can tell, you don't really _need_ pseudo-elements if you're inline-styling with React. 

A pseudo-element is just, well, an element; you can just create a `span` or `div` on your Component and style it as you wish in there.

Unless there's something I'm seriously missing.

**Comment by alexlande** [comment]
Agreed. The intention of this issue was to add a note to the docs about it, but I think it's clear that you just use a real element for that kind of thing.

**Comment by berbaquero** [comment]
Re-reading the original description, now I feel dumb. :P

Anyway, awesome work!

**Comment by alexlande** [comment]
Thanks!

**Comment by brandonwellsmmf** [comment]
Sorry, Where's the documentation located?  I can't seem to find how to accomplish "::before": {}

**Comment by dqisme** [comment]
how do you guys deal with pseudo elements like this in react inline styling:
`video::-webkit-media-controls {
    display:none !important;
}`

**Comment by alexlande** [comment]
@dqisme: You can't do those with inline styles, so you'll need to use CSS instead, either through the `Style` component or just with a traditional CSS file.

**Comment by dqisme** [comment]
@alexlande okay. i got that. thx,
