### ISSUE TITLE
Unique key error being swallowed in resolveStyles

### ISSUE THREAD

**Issue by ryan1234** [FormidableLabs/radium#300]
Context: Our React app had components that were rendering as null with no warnings or errors in the console. We traced it down to not adding keys on some elements that use Radium styles. The easy fix of course is to just add a key. =)

The problem is that the error that is _supposed_ to be bubbled to the console got swallowed somewhere along the way making life unpleasant.

Forgive the crudeness of my initial testing ... after installing the npm module, I went to `./node_modules/radium/lib/resolve-styles.js` and added two throw statements:

```{javascript}
var resolveStyles = function resolveStyles(component, // ReactComponent, flow+eslint complaining
renderedElement, // ReactElement
existingKeyMap) {
  // ReactElement
  existingKeyMap = existingKeyMap || {};

  //throw new Error('before');

  if (!renderedElement || renderedElement.props && renderedElement.props._radiumDidResolveStyles) {
    return renderedElement;
  }

  throw new Error('after');

  // Recurse over children first in case we bail early. Note that children only
  // include those rendered in `this` component. Child nodes in other components
  // will not be here, so each component needs to use Radium.
  var newChildren;
  var oldChildren = renderedElement.props.children;
```

The first error will bubble to the console. The second error gets swallowed ... somewhere. The error that talks about missing keys is a bit down in this function. I need a way to have it bubble up so I know what's going on.

Using Babel 5.8.19 and Radium 0.13.5. Decorating with `@Radium`.

**Comment by ianobermiller** [comment]
Sorry for the slow follow up, @ryan1234. Can you provide a simple repro for this bug?

**Comment by ryan1234** [comment]
I've spent the day trying to reproduce it in a small demo app and haven't been successful. I can reproduce it well in my work codebase, but not in the demo app.

My best guess at this point is something working with promises is swallowing the error. Maybe not Radium, but something else.

What I would love is to have a verbose debug mode with Radium that I can turn on that writes errors to the console in addition to throwing them. That way there is no chance of them being swallowed. =)

I'll keep looking though ...

**Comment by ianobermiller** [comment]
Do you know if this is Radium specific? Try removing Radium from your components and see if it still happens. Promises definitely have a tendency to swallow errors if you are not diligent about using `done` (there is an ESLint rule for that, BTW).

**Comment by ryan1234** [comment]
Removing the `@Radium` decorator fixes the problem. But really that just removes the error that is being thrown. 

I was originally pretty confident it was a Radium issue (hence the issue here =)), but now I think Radium is throwing an error, but something _else_ is consuming it. 

Hoping tomorrow has the answer. =) Thanks for the tip with eslint. I'll find that rule and add it. I'm not using promises explicitly on my own, but I'm using a ton of npm packages and my best guess is one of them is causing the issue.

**Comment by ianobermiller** [comment]
Are you using the react 0.14 beta? There is a known issue I am working on with that.

**Comment by ryan1234** [comment]
Seems to be a React issue.

https://github.com/facebook/react/blob/master/src/shared/utils/Transaction.js#L196

That's the function that as best I can tell is swallowing the error.

We're using React 0.13.3. 

If I put a `catch(e) { console.log(e); }` statement at https://github.com/facebook/react/blob/master/src/shared/utils/Transaction.js#L216, then I can see the Radium error in the console.

Tough to debug. :frowning:

**Comment by ianobermiller** [comment]
Hey @ryan1234, if this is still causing you trouble, or you can still repro it, please comment here and we'll reopen the issue.
