### ISSUE TITLE
Problems with React 0.14-beta2

### ISSUE THREAD

**Issue by dzannotti** [FormidableLabs/radium#303]
Anytime i try to use radium the following error pops up
```
Uncaught TypeError: Cannot define property:_radiumDidResolveStyles, object is not extensible._cloneElement @ resolve-styles.js:127  
resolveStyles @ resolve-styles.js:208(anonymous function)  
@ resolve-styles.js:181mapSingleChildIntoContext
@ ReactChildren.js:90traverseAllChildrenImpl
@ traverseAllChildren.js:98traverseAllChildrenImpl
@ traverseAllChildren.js:114traverseAllChildren
@ traverseAllChildren.js:180mapChildren
@ ReactChildren.js:116resolveStyles
@ resolve-styles.js:179render 
@ enhancer.js:40ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext 
@ ReactCompositeComponent.js:546ReactCompositeComponentMixin._renderValidatedComponent 
....
```

**Comment by ianobermiller** [comment]
Of course they probably locked down props. Should be ok without it, just means it will be enumerable.

**Comment by ianobermiller** [comment]
Another options, one I originally considered, is to use the private fields to check the owner:

```js
element._owner === component._reactInternalInstance
```

So we don't process an element if it is not owned by the component.

**Comment by dzannotti** [comment]
if my understanding is correct, in t he latter case it would support components as functions being wrapped by radium HoC which is even better, since currently i need to jump thru hoops for that :)

**Comment by ianobermiller** [comment]
Sorry, I'm not following you. Radium would still ignore the style property of custom components.
