### ISSUE TITLE
Radium not working for React TestUtil

### ISSUE THREAD

**Issue by ChengshuLi** [FormidableLabs/radium#309]
I created a React ComponentClass called Button that used Radium and tried to test it using React TestUtil 

I tried to look for all Buttons in my component tree by doing the following: testUtils.scryRenderedComponentsWithType(componentTree, Radium(Button)) 
But it returns an empty array.

I tried to debug in Chrome and realized that scryRenderedComponentsWithType is comparing each component instance with Radium(Button) to look for a match. The code is the following:
if (inst.constructor === type)  // then a match is found. 

I printed out inst.constructor (inst is a Button instance with Radium wrapper) and type (which is the parameter that I passed in, in this case it is Radium(Button)). Both of them are function Radium(Button)(). However, inst.constructor === type still returns false, which makes scryRenderedComponentsWithType returning an empty array because it can't find a component that has class type Radium(Button). 

Any advice would be very much appreciated! Thank you in advance!

**Comment by ianobermiller** [comment]
Can you please provide some sample code, preferably a working jsbin?

**Comment by AnSavvides** [comment]
@ChengshuLi I think if you created a [JSFiddle](https://jsfiddle.net/) showcasing this issue with a very simple scenario, that would be a lot easier to follow & reason about.

Also, check out [GitHub Flavored Markdown](https://help.github.com/articles/github-flavored-markdown/#fenced-code-blocks) for syntax highlighting to make your GitHub issue easier to read!

**Comment by ianobermiller** [comment]
I think you should just be passing `Button` to `scryRenderedComponentsWithType`. Whether or not `Button` uses `Radium` is an implementation detail, and doesn't actually matter in tests.

**Comment by ianobermiller** [comment]
Please reopen if this is still an issue.
