### ISSUE TITLE
Static class methods disappear in IE10 when using Radium

### ISSUE THREAD

**Issue by Zenwolf** [FormidableLabs/radium#313]
Static class methods are gone after wrapping the component class in `Radium(Foo)` in IE10 (using Babel to convert ES6):

*Simple example:*
```javascript
import Radium from 'radium';
import React from 'react/addons';

const TYPE_FOO = 'foo';

class Foo extends React.Component {
    static getTypeFoo() {
        return TYPE_FOO;
    }

    render() {
        return <div>Foo</div>
    }
}

export default Radium(Foo);
```

*Result in IE10:*
```javascript
Foo.getTypeFoo() // IE10 throws: Object doesn't support property or method 'getTypeFoo'
```

The above works fine in Chrome. It also works in IE10 when removing `Radium()` decorator.

**Comment by Zenwolf** [comment]
I believe that the confusion is that it is known ahead of time that, when using Babel for ES6 classes, extending a class requires manual static prop assignment in the inheriting class. But an end user has no idea that Radium is using classes under the hood without reading through the source code, so the assumption is that it should work out of the box.

After reading through the source code, I can change my class based on the implementation details of Radium:
```javascript
import Radium from 'radium';
import React from 'react/addons';

const TYPE_FOO = 'foo';

export class Foo extends React.Component {
    static getTypeFoo() {
        return TYPE_FOO;
    }

    render() {
        return <div>Foo</div>
    }
}

const Decorated = Radium(Foo);
Decorated.displayName = 'Foo';
Decorated.getTypeFoo = Foo.getTypeFoo;

export default Decorated;
```

**Comment by ianobermiller** [comment]
Ah right, Radium is only [copying a known set of static properties](https://github.com/FormidableLabs/radium/blob/8a2a19a659197fd480475a2fac03787c67a73420/modules/enhancer.js#L47-L62). It should probably just copy all of them.

cc @bobbyrenwick who added the static set

**Comment by bobbyrenwick** [comment]
@ianobermiller that sounds sensible, I had thought about that when I was working on the print styles stuff because they're static and forgot about it before we released.

**Comment by AnSavvides** [comment]
I just had the same issue come up, so [here's a potential fix for it](https://github.com/FormidableLabs/radium/pull/316).
