### ISSUE TITLE
Radium seems disabled

### ISSUE THREAD

**Issue by MetalMatze** [FormidableLabs/radium#314]
Hey devs. I'm trying to get my component to use Radium. It works with the normal styles. But `':hover'` and merging the styles in an array doesn't seem to work:

https://gist.github.com/MetalMatze/53c347fa584d53e41e93

Am I missing something?

The problem is that in line [119](https://gist.github.com/MetalMatze/53c347fa584d53e41e93#file-photoviewer-js-L119) I use the array syntax to merge. The result in the browser is `style="0:[object Object];1:[object Object];"`.

Thanks

**Comment by ianobermiller** [comment]
Radium purposely does not process the style prop of custom elements (in your example, Link). See #258 for more details. We have some ideas on how to fix this, but haven't yet done so.

**Comment by stephmilovic** [comment]
I'm having this issue too. That link isn't very helpful.

**Comment by ianobermiller** [comment]
@stephmilovic this is also answered in the FAQ: https://github.com/FormidableLabs/radium/tree/master/docs/faq#why-doesnt-radium-work-on-react-routers-link-or-react-bootstraps-button-or-someothercomponent
