### ISSUE TITLE
belle + radium bug

### ISSUE THREAD

**Issue by luisrudge** [FormidableLabs/radium#317]
Not sure where's the problem, so I'm cross posting this in the two repos. [https://github.com/nikgraf/belle/issues/170](Belle repo)

When using Radium with Belle, I get this error: `Uncaught TypeError: iterable.forEach is not a function`

Here's the repro: https://github.com/luisrudge/belle-radium-bug

**Comment by jpuri** [comment]
I debug the issue in radium + belle, and it came out that out 2 components - Select / ComboBox are not working well with radium. These components are structured like:

<Select>
  <Placeholder>Select Country</Placeholder>
  <Option value="USA">USA</Option>
  <Option value="UK">UK</Option>
</Select>

Select code expects to get an array of the nested components in props.children:

<img width="231" alt="screen shot 2015-08-16 at 11 38 39 pm" src="https://cloud.githubusercontent.com/assets/2182307/9303519/30bad9d6-44fc-11e5-8c94-d5f23b82d906.png">

But with radium this array is converted to object:

<img width="259" alt="screen shot 2015-08-16 at 11 38 58 pm" src="https://cloud.githubusercontent.com/assets/2182307/9303527/43f2126c-44fc-11e5-97c3-20a06fe36273.png">

This is breaking the 2 components :(

**Comment by AnSavvides** [comment]
The error itself is in `belle`'s source, in particular [in `helpers.js`](https://github.com/nikgraf/belle/blob/d38561fd3b190c9f544f81a7a7141fe823374cbe/src/utils/helpers.js#L40). The `filter` util is used inside both `ComboBox` and `Select`.

It looks like the `iterable` parameter passed to `filter` is not an `Array`, hence bad things happen.

@jpuri and @nikgraf are probably better suited to figure out what's happening exactly from `belle`'s side of things!

**Comment by jpuri** [comment]
Hey @AnSavvides , yep the error is coming from helpers.js. But helpers.js is expecting to receive an array, props.children give us array when we use Select and ComboBox.

When with radium props.children is getting converted to object and filter is breaking as its not made to filter Object values. That conversion from Array to Object in first place should ideally not happen.

**Comment by ianobermiller** [comment]
This isn't a Radium bug; belle should never manipulate this.props.children directly (e.g. by expecting it to be an array). Only the React.Children helpers should be used: https://facebook.github.io/react/docs/top-level-api.html#react.children

**Comment by jpuri** [comment]
This makes sense, we will refactor our code for that. Thanks a lot @ianobermiller.

**Comment by nikgraf** [comment]
We fixed the issue and cut a new release. The newest version works well with Radium :smile:

**Comment by luisrudge** [comment]
Awesome work all of you!

**Comment by ianobermiller** [comment]
@nikgraf Great to hear, thanks for the work everyone! Btw, Belle is really nice! Have you thought about building it using Radium? Would take away some of the repetitiveness. Either that, or do you have any tips on touch support for components? Radium adds mouseEnter and mouseLeave for hover effects, for instance, which I believe will cause the dreaded double-touch on mobile (I could be totally wrong about this, though).

**Comment by ianobermiller** [comment]
> Did you ever run into trouble just relying on those e.g. edge cases with screen readers or so on?

Never tested with screen readers, I never thought about what it would mean for them.

> I learned that it's quite an effort to make components behave intuitively on touch devices.

I noticed Belle has quite a bit of code for dealing with touch events, well done. It is hard space to get correct, and I think Radium could do more in this area.

> Another reason was that for more complex components we needed to implement styles like activeStyle as inline styles, because the pseudoClass :active won't work on a div.

FWIW, Radium writes pure inline styles, and doesn't use the `:active` pseudo-class of CSS. We probalby do the same thing you do.

**Comment by nikgraf** [comment]
Ahhh, didn't know. I need to dig deeper into Radium :smile:
