### ISSUE TITLE
JavaScript Friendly Pseudo Class & Media Query Syntax

### ISSUE THREAD

**Issue by aldendaniels** [FormidableLabs/radium#318]
Just a syntax idea. Feel free to close if you don't like:

**Today**
```javascript
import Radium from 'radium';
let smallScreenSize = '768px';
let styles = {
  row: {
    display: 'flex',
    flexDirection: 'row',
    ':hover': {
      backgroundColor: '#fafafa'
    },
    [`@media (max-width: ${smallScreenSize})`]: {
      flexDirection: 'column'
    }
  }
};
```

**Suggestion**
```javascript
import Radium, {media} from 'radium';
let smallScreenSize = '768px';
let styles = {
  row: {
    display: 'flex',
    flexDirection: 'row',
    onHover: {
      backgroundColor: '#fafafa'
    },
    [media({maxWidth: smallScreenSize})]: {
      flexDirection: 'column'
    }
  }
};
```

**Comment by aldendaniels** [comment]
The media helper could simply construct the `@media(...)` string.

**Comment by ianobermiller** [comment]
I'm not a big fan of increasing the surface area of Radium, but I do like the nicer DX in this proposal. It truly is cumbersome to write `':hover'`. On the flip side, though, with `':hover'` it is very obvious when you go back and read the code that it is doing something special. @alexlande, thoughts?

I think this would be better implemented as a Radium plugin. I'll open an issue on that topic separately.

**Comment by AnSavvides** [comment]
I like using `':hover'`, it's something I am used to seeing and know what to expect. On the flip side your suggestion looks a little more React-y, which is nice in itself. Having this as a plugin would be a nice compromise so that people can go with whatever works best for them :+1:

**Comment by aldendaniels** [comment]
:+1:  to plugin architecture

**Comment by scottcorgan** [comment]
Plugins are a great idea. Reduces the initial size of Radium, and allows us to add what we need when we need it.

**Comment by alexlande** [comment]
Agreed on all counts. I think the `:hover` and `@media` syntax has a good balance-- it's a little bit cumbersome to type, which helps to clarify that it does something special.

**Comment by ianobermiller** [comment]
Yay plugins! https://github.com/ianobermiller/radium-plugin-friendly-pseudos

**Comment by aldendaniels** [comment]
@ianobermiller - Very cool! Nice work.
