### ISSUE TITLE
Radium plugin architecture

### ISSUE THREAD

**Issue by ianobermiller** [FormidableLabs/radium#319]
I think we could implement Radium in a cleaner way with a concept of plugins. Many of the things in Radium today are basically plugins, just at different levels:

**Process the style prop into a new style prop only**
`style => style`
- prefixer
- array merging
- syntax proposal in #318

**Resolve props + state into new props**
`(props, state) => props`
- `:hover`, `:active`, `:focus` resolvers
- `@media` resolver

**Comment by alexlande** [comment]
This is an excellent idea.

**Comment by ianobermiller** [comment]
Implemented in #348
