### ISSUE TITLE
Bug: Passing through props breaks radium

### ISSUE THREAD

**Issue by aldendaniels** [FormidableLabs/radium#322]
**Scenario**
```javascript
@Radium
class ParentComponent extends Component {
  render() {
    <ChildComponent onClick={handler} style={styles} />
  }
}

@Radium
class ChildComponent extends Component {
  render() {
    <div {...this.props}>...</div>
  }
}
```

**Result**
Radium fails to activate for `ChildComponent`.

I think this has to do with `_radiumDidResolveStyles` being passed through props.

**Disclaimer**
I'm new to Radium. Please let me know if I'm missing something.

**Comment by AnSavvides** [comment]
@aldendaniels maybe I am missing something, but this seems to work fine for me?

```js
import React from "react";
import Radium from "radium";

@Radium
class ParentComponent extends React.Component {
  render() {
    const styles = {
        backgroundColor: "black",
        width: "400px",
        height: "400px",
        color: "white"
    };

    return <ChildComponent style={styles} />;
  }
}

@Radium
class ChildComponent extends React.Component {
  render() {
    return <div {...this.props}>Testing</div>;
  }
}

React.render(React.createElement(ParentComponent), document.getElementById("content"));
```

Output:
<img width="411" alt="screen shot 2015-08-19 at 12 37 33 pm" src="https://cloud.githubusercontent.com/assets/2316326/9355230/1ab5e346-466f-11e5-9968-a83ae0ee2309.png">

**Comment by aldendaniels** [comment]
Hey Andreas, thanks for taking a look. This example doesn't leverage any
radium-specific features, which you would need to do in order to duplicate.
Try setting style to an array of multiple style objects, and see if that
breaks. If it doesn't then I'll try to stand up a demo repo duplicating the
issue.

**Comment by aldendaniels** [comment]
Just saw your edit. I'll try to isolate the issue and post a demo repo.

**Comment by AnSavvides** [comment]
:+1: A demo showcasing this issue would be very helpful!

As an aside, this example also covers the array of multiple style objects use case and works fine:

```js
@Radium
class ParentComponent extends React.Component {
  render() {
    const styles = {
        backgroundColor: "black",
        width: "400px",
        height: "400px",
        ":hover": {
            color: "red"
        }
    };

    const moreStyles = {
        color: "pink"
    }

    return <ChildComponent style={[styles, moreStyles]} />;
  }
}

@Radium
class ChildComponent extends React.Component {
  render() {
    return <div {...this.props}>Testing</div>;
  }
}

React.render(React.createElement(ParentComponent), document.getElementById("content"));
```

**Comment by clessg** [comment]
I think I may have tripped across a related (or the same) issue. [See this CodePen.](http://codepen.io/cgaudreau/pen/JdQzrN?editors=001)

**Comment by aldendaniels** [comment]
@clessg - Thanks for posting - yes, this does look like the same issue.

**Comment by aldendaniels** [comment]
@AnSavvides - sorry for not getting back with a demo - I've (for now) stopped using radium in the project my current project in favor of vanilla inline styles and hadn't found the time to stand something up. Happily, @clessg's codepen demonstrates the issue.

**Comment by ianobermiller** [comment]
Ugh, I strongly suspected there would be issues with this props-based approach to avoiding double-processing. Easy repro:

```
  it('resolves styles if an element has children', () => {
    @Radium
    class Inner extends Component {
      render () {
        return (
          <Inner style={[{color: 'blue'}, {background: 'red'}]}>
            {this.props.children}
          </Inner>
        );
      }
    }

    @Radium
    class Outer extends Component {
      render () {
        return (
          <Inner>
            Some text child
          </Inner>
        );
      }
    }

    var output = getRenderOutput(<TestComponent />);

    expect(output.props.style).to.deep.equal(
      {color: 'blue', background: 'red'}
    );
  });

**Comment by ianobermiller** [comment]
Actually, the real issue here is that `Stuff` does `var {a, b, c, ...rest} = this.props;`, and then spreads `rest` into the top level div. This is a common pattern, and actually ends up spreading `_radiumDidResolveStyles` as well, which tells Radium to skip processing that node.

**Comment by aldendaniels** [comment]
:+1:

Thanks!

**Comment by clessg** [comment]
Issue is fixed on my end. Thanks!
