### ISSUE TITLE
Problem rendering pseudo classes

### ISSUE THREAD

**Issue by mairh** [FormidableLabs/radium#324]
I am not particulary sure whether this bug is caused by my code or this is something Radium specific. I am able to merge, pass media queries properly using Radium, but I can't get `:hover` `:active` and `:focus`pseudo classes working.

A sample implementation of my code looks like:

```
<Link 
    style={sampleStyles} 
    ref="viewTopic" 
    to="viewTopic" 
    params={{slug: this.props.forumSlug, topicId: topic.id}}> 
    {topic.title}
</Link>
```
```
let sampleStyles = {
    color: "rgba(0, 0, 0, 0.87)",
    ":hover": {
        color: "red"
    }
};
```
I get the following error in console:
```
<a href="/f/e5e0770df705-1d16-6436-fa92-8b4257df4b53" style="color:rgba(0, 0, 0, 0.87);:hover:[object Object];">Dummy Topic 29</a>
```

**Comment by AnSavvides** [comment]
@mairh could you provide us with a working code snippet that showcases this? A [JSFiddle](https://jsfiddle.net/) would help, or alternatively just copy-pasting some code here that I can just take and copy paste myself to run locally. From a first glance, what you are doing should work, assuming `Link` is a `Radium`-enabled class.

**Comment by mairh** [comment]
@AnSavvides Sorry, that was my bad. `Link` from `react-router` wasn't enabled to use `radium`. Wrapping `radium` in Link component `module.exports = radium(Link);` solved the issue.

Closing the ticket now!! Thanks anyway
