### ISSUE TITLE
Allow passing optional configuration to @Radium

### ISSUE THREAD

**Issue by ianobermiller** [FormidableLabs/radium#325]
Radium only has one configuration option, and it is global (Radium.Config.setMatchMedia). Globals are bad. Instead, you should be able to pass a configuration object to `@Radium`, as described in #258. Would also be useful for plugins, #319.

```js
@Radium // <-- works as normal

@Radium() // <-- same as above

@Radium({
  matchMedia: somethingFancyOnTheServer,
  resolveCustomElements: true,
  plugins: [x, y z],
}) // <-- config!
```

You'd be able to have project level settings of Radium by creating a simple module:

```js
// MyRadium.js
module.exports = Radium({
  // special snowflake config
});

// CoolComponent.react.js
var MyRadium = require('./myradium');
@MyRadium
class CoolComponent extends Component { }
```

One trick is that Radium already only takes one parameter. So we must either detect whether it is config or component (components must be functions, so this wouldn't be too bad) or make a bigger breaking change to always require parens.

**Comment by AnSavvides** [comment]
This sounds good and useful :+1: 

I think detecting whether we have a config or component is a good way to go rather than a bigger refactor, unless doing a refactor would enable us to do other things more easily in the future.

**Comment by ianobermiller** [comment]
Yep, I like that you can still use plain old `@Radium`

**Comment by ianobermiller** [comment]
This has been released for a while now!
