### ISSUE TITLE
pseudo class ":valid" doesn't get triggered

### ISSUE THREAD

**Issue by markoshust** [FormidableLabs/radium#333]
Seems as though ":focus" gets triggered fine, however ":valid" doesn't get triggered on input elements.

**Comment by ianobermiller** [comment]
`:valid` is not a supported pseudo selector in Radium. Typically with React you will have your validation logic in JavaScript. Assuming there is a DOM API for validity, this would be a good idea for a plugin (the plugin system in is in the works).

**Comment by markoshust** [comment]
Validation is in logic (in JS), however I'd like to style the input element with a green border around the input box when `:valid` is true. Using "pattern" attribute.

**Comment by alexlande** [comment]
@markoshust: In Radium at present, you would handle that by tracking the validity of the form input somewhere (perhaps in the component's state), and applying a style object based on the valid state:

```
style=[
  componentStyles.base,
  this.state.inputIsValid && componentStyles.isValid 
]
```

**Comment by markoshust** [comment]
Ok, thank you for the workaround, I'll implement this in interim. I do believe this should still be built into Radium, as the workaround creates the need to write double-validation on an input element which already has the validation pattern worked in (and this is strictly for styling invalid input elements) http://www.w3schools.com/cssref/sel_valid.asp

**Comment by ianobermiller** [comment]
Mark, to avoid doing it twice, only do it in JavaScript, and not in CSS.

**Comment by markoshust** [comment]
Ok -- that is actually an option. Thanks.

**Comment by ianobermiller** [comment]
Enjoy https://github.com/ianobermiller/radium-plugin-validity-pseudos.

There are some bugs in Radium that this plugin exposes, so it currently only works with master until I do an npm release.
