### ISSUE TITLE
Allow style to be a deeply nested array

### ISSUE THREAD

**Issue by richardfickling** [FormidableLabs/radium#334]
I'm just getting started with React and Radium, so it's entirely probable that this suggestion is unnecessary because I'm doing something fundamentally wrong. I'd like for Radium to be able to merge deeply nested style arrays to deal with component inheritance. For example, there's a table in my app:
```
Row = Radium(React.createClass({
  style: {
    main: {
      width: '100%'
    }
  }

  render: ->
    <div style={ [@style.main, @props.style] }> { @props.children } </div>
}))

CustomRow = Radium(React.createClass({
  style: {
    main: {
      height: '86px'
      borderBottom: '1px solid blue'
    }
  }

  render: ->
    <Row style={ [@styles.main, @props.style] }> { @props.children } </Row>
}))

CustomTable = React.createClass({
    render: ->
      <div>
        <CustomRow style={ background: 'red' } />
        <CustomRow style={ background: 'white' } />
      </div>
})
```

This doesn't work because @props.style in the `<Row>`s is an array, so the `<div>`'s style prop is a nested array, which Radium doesn't support (https://github.com/FormidableLabs/radium/blob/master/modules/resolve-styles.js#L49)

Is there a "suggested" way to handle component inheritance in situations like this?

If the solution is adding support for nested arrays, I'm happy to make the PR, but I didn't want to do that without asking for a better solution first.

**Comment by ianobermiller** [comment]
Hmm, yes this does seem like a legitimate use case, and could rather easily be added to mergeStyles if you want to do so.

**Comment by ianobermiller** [comment]
I also have plugin support mostly complete, and this would be a good candidate for a plugin.

**Comment by almost** [comment]
Would there be any downside to including this as a default behaviour? It's very useful when making components and I'd guess it wouldn't add much in the way of complexity of slowdown?

**Comment by ianobermiller** [comment]
Not at all, I'd accept a tested PR with the change.

**Comment by bobbyrenwick** [comment]
:+1: It's great to see this being supported! At the moment we `flatten` out any arrays in our bottom level components in order to achieve the same thing.
