### ISSUE TITLE
Using getState with :focus on input

### ISSUE THREAD

**Issue by geoRG77** [FormidableLabs/radium#336]
Hi,
I'm trying to style a different element based on focus to input but seems that `getState` doesn't work with inputs. The example from documentation (hover on button) works great.

Here is my example:
```jsx
import Component from '../components/component.react'
import Radium from 'radium'
import React from 'react'

@Radium
export default class EmailInput extends Component {

  render() {
    return (
      <div>
        <input
          style={styles.input}
          placeholder='Your email address'
        />
        {Radium.getState(this.state, 'input', ':focus') ? (
          <span>{' '}Focusing!</span>
        ) : null}
      </div>
    )
  }
}

const styles = {
  input: {
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: 'black',
    ':focus': {
      borderColor: 'red'
    }
  }
}
```

Thanks!

**Comment by ianobermiller** [comment]
We can probably add an error message here. "button" in the example is not
the button element, but the key added to the element. In our case you'll
need to add a key as well to the input element, and reference that in
getState.

**Comment by geoRG77** [comment]
Thanks, I'm blind :(
