### ISSUE TITLE
Allow extracting stylesheet

### ISSUE THREAD

**Issue by natew** [FormidableLabs/radium#338]
Just wondering what the thoughts are on this. I'd like to do an isomorphic serve on first load that serves all non-interactive styles in a stylesheet on first load, then continues with radium from there.

Would require integrating classname support, all we'd need from Radium is a `Radium.currentStyles()` hook so we can get all the styles in a tree, write to string, and flatten them into classnames.

**Comment by ianobermiller** [comment]
Currently the only thing making Radium non-universal is the prefixer, which I've had plans to rewrite for ages now. Extracting style sheets would also be required for proper media query support. You can probably fake it pretty well by guessing the screen resolution from the user agent and using the server-side media query polyfill (assuming you mainly want to target phones and tablets). In general, rendering to a stylesheet and using classnames is a non-goal for Radium. There are [many other libraries](https://github.com/FormidableLabs/radium/tree/master/docs/comparison) that do exactly that.
