### ISSUE TITLE
Media queries do not work for nested elements

### ISSUE THREAD

**Issue by peterKaleta** [FormidableLabs/radium#339]
Hi Guys

I've followed docs on 13.8 ver and run into this errors

```
const styles = {

  elA:{
     normal + media query styles
  }

  elB:{
     normal + media query styles
  }

}

<div styles={styles.elA}>
    <div styles={styles.elB}/>
</div>
```

Media queries won't be applied on elB

**Comment by alexlande** [comment]
Hey @peterKaleta: when styling multiple elements with media queries or browser states, Radium requires a `key` on each component. That might be causing your issue. See https://github.com/FormidableLabs/radium/tree/master/docs/guides#styling-multiple-elements-in-a-single-component

**Comment by peterKaleta** [comment]
@alexlande sorry for not stating this in a more explicit manner - I've placed both refs and keys on the components. 

in the code below class `display none` doesn't get applied to closeBtn:

```
//skimmed version
import React from 'react';
import {Button} from 'react-bootstrap';
import radium from 'radium';
import Icon from 'react-fa';

const styles = {

  wrapper: {
    border : '1px solid #000',    
    '@media (min-width: 1024px)': {
      right: 200
    },

  },
  
  wrapperVisible: {
    right: 200
  },
  
  closeBtn: {
    display: 'inline-block',
    color: '#ccc',
    '@media (min-width: 1024px)': {
      display: 'none'
    },
  }
  
};

@radium
class SessionLog extends React.Component {

  static displayName = 'SessionLog';

  static propTypes = {
   ...
  }

  static defaultProps = {
    isLogVisible : true
  }

  render() {

    return (
      <div ref='wrapper' key={1} 
          style={[ styles.wrapper,
                 this.props.isLogVisible && styles.wrapperVisible]}>
      
          <Button ref='button' key={2} style={styles.closeBtn}>
            <Icon name='close'/>
          </Button>
        
      </div>
    );
  }
}

export default SessionLog;
```

**Comment by ianobermiller** [comment]
The problem is not with media queries; it is that Radium does not resolve the `style` prop of custom components, which is your example is `Button` from `react-bootstrap`. See the [FAQ: Why doesn't Radium work on SomeComponent?](https://github.com/FormidableLabs/radium/tree/master/docs/faq#why-doesnt-radium-work-on-somecomponent).

**Comment by peterKaleta** [comment]
Thanks @ianobermiller !
