### ISSUE TITLE
Heard you were doing bootstrap can you do foundation apps classes too?

### ISSUE THREAD

**Issue by tirams** [FormidableLabs/radium#340]
Please do a port of foundation-apps styles since you are doing bootstrap 
http://foundation.zurb.com/apps/

**Comment by alexlande** [comment]
Hey @tirams, thanks for the interest! We're not working on `radium-bootstrap` anymore, it was too much of a maintenance burden for anyone on the team to keep up with. I think that Radium ports of Bootstrap or Foundation are a great idea for a community project though.

In the meantime, Radium works very well when used in conjunction with an existing framework like Foundation. You can see some discussion of that here: https://github.com/FormidableLabs/radium/issues/323
