### ISSUE TITLE
Unsupported CSS property "webkitOverflowScrolling$"

### ISSUE THREAD

**Issue by basarat** [FormidableLabs/radium#345]
The error along the lines `Unsupported CSS property "webkitOverflowScrolling$" in component "Tabs"` will show if we have the following: 

```js
var scroll = {
    webkitOverflowScrolling: 'touch',
    overflow: 'auto'
};
```

Note that just `overflowScrolling: 'touch',` doesn't work either (error : `Unsupported CSS property "overflowScrolling$" in component "Tabs"`)

**Comment by alexlande** [comment]
Hey @basarat! This is a known issue and a quirk of the prefixer in Radium. On the plus side, it won't negatively impact your application as these warnings are stripped out in production, so it just adds some noise to your console during development. You can find some more discussion of the issue in #290.

The short version is that the prefixer logs a warning if it hits a prefixed property that isn't supported by the current browser. You'll notice that on iOS devices where `-webkit-overflow-scrolling` is supported, you won't see the warning.

**Comment by basarat** [comment]
Cheers. Sorry I couldn't find it in the issues before, thanks for the link :rose:
