### ISSUE TITLE
Silence "Unsupported CSS" warnings during tests

### ISSUE THREAD

**Issue by levithomason** [FormidableLabs/radium#350]
Per [this comment](https://github.com/FormidableLabs/radium/issues/215#issuecomment-113533291) in #215 I am attempting to bypass css checks during tests.  I believe I am supposed to provide a mock `exenv` module during tests to accomplish this.

We're using Webpack so I am aliasing calls to the `exenv` module and pointing them instead to this mock:

```js
// exenv-mock.js
const exenv = {
  canUseDOM: true,
  canUseEventListeners: true
};

export default exenv;
```

This did not silence the warning so I also tried providing a global `ExecutionEnvironment` variable that resolves the `exenv-mock.js` above.  This also did not silence the warnings.

I am sure I am missing something simple.  Any help appreciated.

**EDIT**
We're using karma + mocha + phantomjs for this particular test.

**Comment by ianobermiller** [comment]
If you are using phantom why are you seeing warnings? Is it for CSS that is only supported in a specific browser?

**Comment by levithomason** [comment]
1) my question exactly :-)

2) the warnings are for flex and flex flow.

**Comment by ianobermiller** [comment]
I think my comment was wrong; you want to set the exenv vars to `false`, not `true`.

Are you sure `flex` and `flex-flow` are supported on PhantomJS? These errors may just be legitimate.

**Comment by levithomason** [comment]
Setting either of those key values to false causes this error:

```
ERROR in Loader
node_modules/radium/node_modules/babel/index.js?stage=0 didn't return a function
@ ./~/radium/lib/keyframes.js 6:27-43
```

We're on phantomjs 1.9.18.  

Really, I just want to silence all warnings during unit tests with phantomjs.  Since none of our phantomjs tests depend on styles, the warnings are not helpful but do clutter the test output.

I may poke around in the prefixer for a solve.  Thanks for digging in on this.

**Comment by ianobermiller** [comment]
We are also planning to move away from the DOM-based prefixer in the near future, which should solve this issue.

**Comment by levithomason** [comment]
OK, good to know.  The warnings aren't a deal breaker, so we're just ignoring them for now.  Will wait for the update.  Gonna close this issue in light of that.  Thanks for the followup.
