### ISSUE TITLE
window.getComputedStyle() has known issues in firefox

### ISSUE THREAD

**Issue by stijndeschuymer** [FormidableLabs/radium#351]
When used in an iFrame with display: 'none'
window.getComputedStyle() returns null  (used in prefixer)

I know this is actually a firefox issue, but as long as its there, this breaks my application.
I haven't had the time to look for a solution

https://bugzilla.mozilla.org/show_bug.cgi?id=548397

**Comment by ianobermiller** [comment]
Can you explain a little more about what you are doing? Why does the hidden iFrame need to use Radium at all?

**Comment by stijndeschuymer** [comment]
I'm building a 'Salesforce Canvas app' with React and Radium's inline style features.
Its basically a normal webapp that's embedded on salesforce.com in an iframe.
I don't have control over the iframe or how its displayed, I only own the content ...

**Comment by ianobermiller** [comment]
Fixed with use of inline-style-prefixer.
