### ISSUE TITLE
Radium on stateless components (react 0.14 rc1)

### ISSUE THREAD

**Issue by boyswan** [FormidableLabs/radium#353]
Is/will there a way to use Radium on React's new stateless components? 

E.g.
`````javascript
export default ({ text }) => 
	<div style={Style.container}>
		<div style={Style.body}>
			<p style={Style.text}> {text} </p>
		</div>
	</div>
`````

Trying

`````javascript
export default Radium(foo)
`````
also fails.

**Comment by ianobermiller** [comment]
Well, Radium would have to convert the stateless component into a stateful component, since Radium uses state to store the various interaction states.

**Comment by arush** [comment]
Would it be a good idea to add an option to Radium if the developer knows that the particular Component instance will not require interaction and therefore state?

**Comment by ianobermiller** [comment]
Sorry, I'm not sure what you mean. You cannot have a purely stateless component and use Radium at the same time. We could probably make Radium work with stateless components by converting them into stateful components.

**Comment by arush** [comment]
So what if I knew that I was making a component that didn't require :hover, :active or any kind of interaction but it did need other functionality that Radium provides, e.g. vendor-prefixing, media queries, style merging... would it be worth making Radium support these cases? Would it provide any performance benefit?

**Comment by ianobermiller** [comment]
Media queries also require state. You could easily do this now by using the `plugins` config option, and omitting the things you didn't care about. There wouldn't be a significant performance benefit though (and if the perf cost of Radium is measurably high, we should do something about that anyway).

FWIW, stateless components are nice because they are easier to reason about and very simple. Adding Radium to a stateless component doesn't change any of that, since all the details are hidden anyway.

**Comment by arush** [comment]
Awesome thanks for helping me understand that better! [p.s. accidentally deleted my comment above so if you have it in an email somewhere you could paste it in for future readers of this thread, thx!]

**Comment by alexlande** [comment]
:+1: @arush's deleted comment:

> So what if I knew that I was making a component that didn't require :hover, :active or any kind of interaction but it did need other functionality that Radium provides, e.g. vendor-prefixing, media queries, style merging... would it be worth making Radium support these cases? Would it provide any performance benefit?

**Comment by ianobermiller** [comment]
I think we should be able to detect this relatively easily, and just wrap it as React does: https://github.com/facebook/react/blob/e5c3fb14fa3427b331b66785d94aef404ce66156/src/renderers/shared/reconciler/ReactCompositeComponent.js

```js
var isStatelessComponent = !component.prototype || !component.prototype.render;

var statefulComponent = isStatelessComponent ? 
  class { render() { component(this.props, this.context); } } : 
  component;

**Comment by kumarharsh** [comment]
Instead of converting the stateless component to a stateful one, can you expose different functions from Radium which, for example, do the 'auto-prefixing', 'style-merging', etc, so that the developer can manually do those?

**Comment by quirinpa** [comment]
@kumarharsh +1

**Comment by ianobermiller** [comment]
The idea is that radium should just work with stateless components:

```as
let MyStatelessComponent = (props) => (
  <div style={{':hover': {color: 'red'}}}>{props.children}</div>
);

MyStatelessComponent = Radium(MyStatelessComponent);

**Comment by okbel** [comment]
When I try to use something array like, like this:
      <button
        style={[
          styles.base,
          styles[this.props.kind]
        ]}>
        {props.children}
      </button>

It doesn't work

**Comment by evtuhovdo** [comment]
You should use decorator.

@Radium

**Comment by nschwan94** [comment]
`    let ListContext = ({ item }) => {
      if (item.context !== undefined) {
        const actionContainer = {
          border: '1px solid #D6D7D9',
          borderRadius: '5px',
          background: '#FFFFFF',
          marginTop: '5px',
          padding: '10px',
        }
        const accordionItemAction = {
          backgroundColor: '#FFFFFF',
          padding: '10px',
          margin: '10px',
          ':hover': {
            backgroundColor: variables.bkGrayLightest,
            cursor: 'pointer',
          },
        }
        return (
          <div style={actionContainer}>
            {item.context.map(actions =>
              <p style={[accordionItemAction]}
                key={uuid.v4()}>{actions.action}</p>,
            )}
            {this.props.study && (
              <div>
                <p key={uuid.v4()} style={[accordionItemAction]}>Export table for editing</p>
                <p key={uuid.v4()} style={[accordionItemAction]}>Import revisions</p>
              </div>
            )}
          </div>
        )
      }
      return null
    }
    ListContext = Radium(ListContext)
`

this is not properly showing the hover styles of my p tags. What am I doing wrong here?
