### ISSUE TITLE
Support position: sticky (safari / mobile safari)

### ISSUE THREAD

**Issue by theogravity** [FormidableLabs/radium#354]
Unable to use `position: sticky` in Radium (gives an unsupported value). 

http://caniuse.com/#feat=css-sticky

**Comment by ianobermiller** [comment]
The prefixer should be changing it to `position: -webkit-sticky`. Is that not happening?

**Comment by theogravity** [comment]
Sorry, apparently I was testing in Chrome instead of Safari. It is doing the prefix properly in Safari.
