### ISSUE TITLE
object-assign need to be a dependency.  It's only a devDependency

### ISSUE THREAD

**Issue by gregthebusker** [FormidableLabs/radium#357]
I'm getting this error after upgrading to 0.14.
Module not found: Error: Cannot resolve module 'object-assign' in node_modules/Radium/lib

I think its because object-assign is only in devDependency, but something else needs it.

**Comment by ianobermiller** [comment]
Fixed in 21d12b96fcbeba75d02665f6f08d88a89ab63944
