### ISSUE TITLE
resolveStyles breaks this.props.children if children is an object, not an array

### ISSUE THREAD

**Issue by richardfickling** [FormidableLabs/radium#358]
This issue is related to #317, but is different enough that I thought I'd post a new issue instead of commenting there.

react-router sets `this.props.children` to be a [keyed object](https://github.com/rackt/react-router/blob/master/docs/api/Route.md#components). `_resolveChildren` uses `React.Children.map` to iterate over that object, and the result of calling that map function is a broken object that can't be used anywhere.

My gut tells me this is an issue with react-router, but an issue posted there was [closed with the explanation](https://github.com/rackt/react-router/issues/1968) that: "`this.props.children` is an opaque type that is being used by many different React libraries to mean something other than just node, array, or `null`. In react-motion's <Spring> component, for example, this.props.children is a function."

In any case, the interaction between these two libraries is causing issues. Can we fix this on the radium side (e.g. check [`childrenType`](https://github.com/FormidableLabs/radium/blob/master/modules/resolve-styles.js#L45) before calling `React.Children.map`)?

**Comment by ianobermiller** [comment]
IMO `react-router` should be passing those "named children" as props instead. Components expect `this.props.children` to be an opaque type that can be processed by `React.Children`. `react-router` is breaking that expectation.

This is not the same as `react-motion`, where they've created a component that *accepts* a different type for `children`. `react-router` is *passing* a different type of child to normal components, one that is not inline with the rest of React.

As for Radium working around this, I'm not sure it is possible; both are objects, so I don't know how we would distinguish.

**Comment by richardfickling** [comment]
Agreed. In the betas for react-router 1.0.0, the named children were in fact passed as props. I'm not sure why the decision was made to put them in children (although I guess it makes sense, in some ways). Would be great if @mjackson could chime in here.

**Comment by ianobermiller** [comment]
Please reopen this if it is still a problem, but it seems to be working? Perhaps you are using React 0.14? Our tests are all against the latest stable version.

**Comment by mjackson** [comment]
@ianobermiller Thank you for making that distinction. That's important. I think you're right. When we're *passing* `children` to someone else, we should probably give them a type they can expect.

**Comment by ianobermiller** [comment]
@mjackson Oddly enough my test case with a keyed object works just fine, and `React.Children.map` does what you'd expect (it keeps arrays as arrays, and keyed objects and keyed objects).

Thanks for following up on this issue!
