### ISSUE TITLE
How could we implement image sprites with radium?

### ISSUE THREAD

**Issue by toddw** [FormidableLabs/radium#361]
On a page with lots of small images, a very common technique to minimizing the amount of network requests is to use image sprites like this one
![alt sprite](https://www.icloud.com/system/cloudos/15E.bda4a27/en-us/packed-1.png)

I'm using webpack to get references to my image assets and so that gives the option of base64 encoding images. I thought that was my answer to image sprites since the image would be encoded into the javascript and therefore I could have all of the small icons come down as 1 request along with the main javascript file. The new issue is that, we have a universal app, so we render the html on the server side for the first request. If I base64 encode a 2k image that is repeated on a list of 50 items (which is a very common thing to do), well then I'm spitting out the base64 encoded image 50 times and making my initial payload 100kb bigger.

How are other people dealing with this problem?

**Comment by ianobermiller** [comment]
I know uncompressed output size matters in terms of parsing, but your gzipped size must not be that much bigger. One thing you could do is have a class that just adds the background image, and then do the rest in Radium. Inline styles and CSS can co-exist where necessary.

**Comment by toddw** [comment]
I have also come to the conclusion that this is no longer a pressing issue with HTTP2 and SPDY, at least not for my use cases.

**Comment by ianobermiller** [comment]
:+1:
