### ISSUE TITLE
Custom Plugins Example

### ISSUE THREAD

**Issue by ronag** [FormidableLabs/radium#363]
Looking into plugging in autoprefixer while waiting for user agent support in the prefixer for server side rendering.

However, some examples in regards to plugin configuration would be useful.

**Comment by ianobermiller** [comment]
Hey Robert, where did you expect to find this information? Chances are if
you didn't see it right away someone else will have the same problem.

**Comment by ronag** [comment]
There is an example for `config.matchMedia` however `config.plugins` is empty. We should probably add something like.

```javascript
import Radium from 'radium'
import { Plugins } from 'radium'

const myCustomPlugin = ({componentName, style}) => {
  return style
}

export default function style(component) {
  return Radium({
    plugins: [
      Plugins.mergeStyleArray,
      Plugins.checkProps,
      Plugins.resolveMediaQueries,
      Plugins.resolveInteractionStyles,
      Plugins.prefix,
      Plugins.checkProps,
      myCustomPlugin
    ]
  })(component)
}

```

**Comment by ianobermiller** [comment]
Yeah you're totally right, I forgot to add that. We'll get the docs updated asap. Your custom plugin should probably go between prefixer and checkProps, btw.
