### ISSUE TITLE
Passing styles as props

### ISSUE THREAD

**Issue by bsbeeks** [FormidableLabs/radium#364]
We are currently using Radium in all of our components. We have a use case where Component A is passing styles as props to Component B. Then Component B is using Radium to combine some default styles with the passed in styles:

```javascript
// Component A
const React = require('react');
const Radium = require('radium');

const styles = {
  red: {
    color: 'red'
  },
  green: {
    color: 'green'
  }
};

const ComponentA = React.createClass({
  render () {
    return (
      <ComponentB style={[styles, this.props.showGreen && styles.green]} />
    );
  }
});

module.exports = Radium(ComponentA);
```

```javascript
// Component B
const React = require('react');
const Radium = require('radium');

const styles = {
  color: 'yellow'
};

const ComponentB = React.createClass({
  render () {
    return (
      <div style={[styles, this.props.style]}>I should be green</div>
    );
  }
});

module.exports = Radium(ComponentB);
```

Unfortunately this isn't working because `this.props.style` is an array. If we pass in a single style object as the ComponentB style prop, then it works perfect.

Is there currently a way to address this use case in Radium?

**Comment by ronag** [comment]
`style={[styles].concat(this.props.style)]}`?

**Comment by bsbeeks** [comment]
@ronag thanks for the suggestion! We are actually doing that right now as a temporary fix. It would be nice if Radium could handle nested arrays.

**Comment by ronag** [comment]
@bsbeeks: I see, then I guess this issue is more about whether Radium should flatten (or not) the array passed into `style`.

**Comment by bsbeeks** [comment]
I guess I spoke too soon. It looks like the mentioned use case does work. In our specific components we were placing `...{this.props}` after `style={[styles, this.props.style]}` and so `this.props.style` was overwriting the Radium generated styles.

**Comment by ianobermiller** [comment]
Yeah, we recently shipped support for nested style arrays: https://github.com/FormidableLabs/radium/blob/master/CHANGELOG.md#0140-september-15-2015
