### ISSUE TITLE
Simplify release process

### ISSUE THREAD

**Issue by ianobermiller** [FormidableLabs/radium#369]
Let's setup `semantic-release` and `commitizen` to simplify and automate the release process. Great video guide to all of it here: https://egghead.io/lessons/javascript-how-to-write-a-javascript-library-automating-releases-with-semantic-release

**Comment by ianobermiller** [comment]
We should probably also be more diligent about squashing PRs before merging.

**Comment by ianobermiller** [comment]
After stewing on this for a bit, it might be nice, but is probably more work than it is worth to setup. Also, how do you handle multiple breaking changes only causing a single major version bump? (perhaps semantic-release accomodates this, but I don't really know).

**Comment by ianobermiller** [comment]
cc @knowbody if you have some time to set this up, I think this would solve the whole "Radium is never updated" thing :), and make my life a whole lot easier

**Comment by knowbody** [comment]
On my flight back to London. I'll look at it when I land.




On Sun, Dec 27, 2015 at 8:47 PM -0800, "Ian Obermiller" <notifications@github.com> wrote:












cc @knowbody if you have some time to set this up, I think this would solve the whole "Radium is never updated" thing :), and make my life a whole lot easier

**Comment by alexlande** [comment]
Closing this out. We've got publishr now helps make this a little less painful.
