### ISSUE TITLE
If this.props.children is an array, make sure to return an array from resolveChildren

### ISSUE THREAD

**Issue by polkovnikov-ph** [FormidableLabs/radium#370]
When the Radium is set on the outer component, `this.props.children` are no more an array, but some strange object with `.0` and `.1` fields. There's no diagnostic in console, and this kind of behaviour is highly misguiding, unless this is a bug.
```javascript
var React = require('react');
var Radium = require('radium');

var A = (React.createClass({
	/* propTypes: {children: _.length === 2} */
	render() {
		console.log(this.props.children);
		debugger;
		return (<div>
			<div>
				{this.props.children[0]}
			</div>
			<div>
				{this.props.children[1]}
			</div>
		</div>);
	}
}));

module.exports = /*Radium*/(React.createClass({
	render() {
		return (<A>
			<div>
				1
			</div>
			<div>
				2
			</div>
		</A>);
	}
}));
```

**Comment by polkovnikov-ph** [comment]
This seems to be a react bug. `ReactElementValidator.cloneElement` does this.

**Comment by polkovnikov-ph** [comment]
This is done by `React.Children.map` that returns not a children object, but a fragment. You cannot use it in `_resolveChildren`, because it breaks existing code. I don't think it's valid to have a fragment in `this.props.children` at all.

**Comment by ianobermiller** [comment]
Your code should not expect children to be an array, it should always use the `React.Children.*` helpers to manipulate `this.props.children`. 0.14 has `React.Children.toArray` for this very case. Also, you should probably reconsider [positional children as an API](http://ianobermiller.com/blog/2015/05/17/react-anti-pattern-positional-children/) anyway.

**Comment by polkovnikov-ph** [comment]
This is a good objection from a philosophical point of view, yet it doesn't change the fact that `radium` changes semantic of the program in the place it's not supposed to, and, worse, `react` swallows that exception. It's `radium`'s responsibility to call `React.Children.toArray` or `console.warn` for older versions of `react`, not programmer's one.

**Comment by ianobermiller** [comment]
Sorry, this is not a philosophical view, it is a practical view, and is specified in the React documentation:

> this.props.children is an opaque data structure: use the React.Children utilities to manipulate them.

https://facebook.github.io/react/docs/multiple-components.html#children

From a pragmatic standpoint, Radium *could* accommodate code that isn't using the `React.Children` helpers by converting children back to an array if it was originally an array.

**Comment by ronag** [comment]
`Radium could accommodate code that isn't using the React.Children helpers by converting children back to an array if it was originally an array.`

How? Whatever you do will be wrong since the property is in all practical and philosophical senses undefined.

**Comment by ianobermiller** [comment]
@ronag, thanks for chiming in. I wouldn't say it is undefined; there is conflicting information in the documentation regarding children as an array or object. For instance, this guide on [Type of the Children props](https://facebook.github.io/react/tips/children-props-type.html).

**Comment by ianobermiller** [comment]
This appears to work, which is odd. What version of React did you see this error in?

**Comment by ianobermiller** [comment]
Please reopen if you can still repro this.

**Comment by polkovnikov-ph** [comment]
Reproed with React 0.13.3.

**Comment by polkovnikov-ph** [comment]
@ianobermiller Reopen?

**Comment by ianobermiller** [comment]
Since React 0.14.x has been out awhile now, and assume this issue longer exists there, I'm going to close it.
