### ISSUE TITLE
Fix npm postinstall script on Windows

### ISSUE THREAD

**Issue by mjackson** [FormidableLabs/radium#377]
Just thought I'd let you guys know that the `||` operator [apparently doesn't work on Windows](https://github.com/rackt/history/issues/73#issuecomment-146693329). I copied [your `postinstall` script](https://github.com/FormidableLabs/radium/blob/688f081476685270733cffb464cea4f145609612/package.json#L22), so I just thought I'd let you know ;)

Cheers!

**Comment by ianobermiller** [comment]
I'm not sure `||` is the problem, as it is definitely [supported on Windows](https://www.microsoft.com/resources/documentation/windows/xp/all/proddocs/en-us/ntcmds_shelloverview.mspx?mfr=true). We also have [AppVeyor builds](https://ci.appveyor.com/project/ryan-roemer/radium/build/job/bod14fljs09cvuod) that check every commit on Windows. From the logs, it is running just fine:

```
> radium@0.14.1 postinstall C:\projects\radium
> node -e "require('fs').stat('lib', function(e,s){process.exit(e || !s.isDirectory() ? 1 : 0)})" || npm run lib
 
 
> radium@0.14.1 lib C:\projects\radium
> npm run babel && rimraf lib/__tests__ lib/__mocks__
 
 
> radium@0.14.1 babel C:\projects\radium
> rimraf lib && babel modules/ -d lib/
