### ISSUE TITLE
warning about unsupported css property

### ISSUE THREAD

**Issue by haohcraft** [FormidableLabs/radium#378]
I have some style like below

```

const styles = {
	StockName: {

		base: {
			width: 100
		},
		ticker: {
			fontSize: 25,
			lineHeight: '25px'
		},
		company: {
			fontSize: 16,
			lineHeight: '16px'
		}
		
	},

	StockPriceItem: {
		wrapper: {
			width: 400,
			padding: '10px 0px',
			display: 'flex',
			justifyContent: 'space-between',
			alignItems: 'flex-end'
		}
	}

}
```

when I applied it on the `<div style={[styles.StockName.base]}></div>` it would throw `Unsupported CSS property "base$" in component "StockPriceItem"`

Any idea about this?

**Comment by ianobermiller** [comment]
Sounds like you are accidentally passing `styles.StockName` at some point, since `base` is a property there.

**Comment by haohcraft** [comment]
You are right. Thanks a lot.
