### ISSUE TITLE
Pseudo classes

### ISSUE THREAD

**Issue by ron116** [FormidableLabs/radium#380]
Do you have a plan add support pseudo classes like ::selection, ::before, ::after ?

**Comment by alexlande** [comment]
There are no plans to support additional pseudo-selectors. Most of them (like `:nth-child`) are best handled through your own JS logic in Radium components. Things like `:before` and `:after` can be handled with separate non-semantic elements like `i`, and things like `:selection` aren't possible to replicate with inline styles.

There's some documentation on the subject here: https://github.com/FormidableLabs/radium/tree/master/docs/faq#how-do-i-use-pseudo-selectors-like-checked-or-last
