### ISSUE TITLE
is at-rule @supports supported?

### ISSUE THREAD

**Issue by newsiberian** [FormidableLabs/radium#381]
Hello, this is pretty rare use case, but is there a native way to do the following in Radium? 
[MDN about '@supports'](https://developer.mozilla.org/en-US/docs/Web/CSS/@supports)
```
@supports (scroll-snap-type: mandatory) or (-webkit-scroll-snap-type: mandatory) {
	#wrapper {
		height: 100vh;
	}
}
```

**Comment by alexlande** [comment]
Afraid not. Radium doesn't support `@` rules or pseudo-selectors outside of a narrow subset (`@media`, `@keyframes`, `:hover`, `:focus`, `:active`.

To accomplish this sort of styling, you would need to either use CSS with `@supports` or use JavaScript feature detection like Modernizr.
