### ISSUE TITLE
Unsupported CSS property "WebkitAppRegion" in component

### ISSUE THREAD

**Issue by gabrielbull** [FormidableLabs/radium#388]
Hello,

If trying to add app-region in electron as per: https://github.com/atom/electron/blob/master/docs/api/frameless-window.md#draggable-region

you get the following error: `Unsupported CSS property "WebkitAppRegion" in component`

**Comment by ianobermiller** [comment]
Awesome to hear you are using Radium with Electron. A

**Comment by gabrielbull** [comment]
Nope, this is the only property that Electron requires. Thanks!

**Comment by gabrielbull** [comment]
I believe you somehow fixed the issue with 0.14.3

**Comment by ianobermiller** [comment]
Fixed with use of inline-style-prefixer.

**Comment by rgbkrk** [comment]
How did you end up doing this?

**Comment by ianobermiller** [comment]
What do you mean? Radium didn't do anything to explicitly support electron
props.

**Comment by rgbkrk** [comment]
Sorry, I google stumbled my way over here after someone added this property to make our Electron App draggable. It's React that seems to be conflicting, not Radium. Sorry to bother.
