### ISSUE TITLE
Unsupported CSS property "scale" in component

### ISSUE THREAD

**Issue by VasilyShelkov** [FormidableLabs/radium#390]
Hello,

if trying to add the scale property I get the following error: Unsupported CSS property "scale" in component.

Same applies to:
OTransition
MsTransition
MozTransition
WebkitTransition

On a related note, is there a list somewhere of supported CSS properties?

awesome work with Radium, enjoying using it with the ES7 decorator :D

**Comment by ianobermiller** [comment]
Hey @VasilyShelkov, there are all sorts of weird bugs we run into with the prefixer, this sounds like one of them, along with #388. All should be solved by #374.

**Comment by VasilyShelkov** [comment]
Thanks for the rapid reply, just wanted to make you aware of it since I love Radium and really wanna keep using it :+1:

**Comment by ianobermiller** [comment]
Fixed with use of inline-style-prefixer.
