### ISSUE TITLE
Unnecessary vendor prefixing in Safari

### ISSUE THREAD

**Issue by sebastiansandqvist** [FormidableLabs/radium#392]
I have an element with the property: `textDecoration: 'none'`, but when running it in Safari I get the following console warning: `Unsupported CSS value "none" for property "WebkitTextDecoration"`

This version of Safari supports textDecoration unprefixed, so I am not sure why this error occurs in the first place. Interestingly, though, the desired style is still applied.

**Comment by ianobermiller** [comment]
Fun! Another weird one. Should be solved by #374.

**Comment by ianobermiller** [comment]
Fixed with use of inline-style-prefixer.
