### ISSUE TITLE
Radium breaks React.PropTypes.instanceOf()

### ISSUE THREAD

**Issue by arush** [FormidableLabs/radium#393]
ES7 decorators are not truly decorators since they affect the original Component's API - this is because they wrap the original Component instead of non-destructively adding additional functionality.

This means the following code generates a warning:
```
class SomeComponent extends React.Component {
  propTypes: {
    someKey: React.PropTypes.instanceOf(RadiumDecoratedComponent),
  ...
```
`Warning: Failed propType: Invalid prop someKey supplied to SomeComponent, expected instance of RadiumEnhancer.`

Here we actually want to enforce the instance type that Radium wrapped, we dont want to enforce a `RadiumEnhancer` instance to be passed to `someKey`.

Is there any solution to this?

**Comment by ianobermiller** [comment]
This isn't Radium. `instanceOf` is not the proper way to check if a passed in node is an element of a specific component (https://facebook.github.io/react/docs/glossary.html). Check out this JSBin, which fails without even using Radium: https://jsbin.com/yodadu/1/edit?html,js,console,output.

React doesn't actually have a built-in validator for elements of a certain type, but you can write a custom validator like this: https://jsbin.com/yodadu/2/edit?html,js,console,output

```as
@Radium
class Child extends React.Component {
  render() {
    return <span>Child3</span>;
  }
}

@Radium
class Parent extends React.Component {
  static propTypes = {
    child(props, propName, componentName) {
      if (props[propName].type !== Child) {
        throw new Error('Invalid prop `child` supplied to `Parent`, expected element of type `Child`.')
      }
    }
  }
  
  render() {
    return <div>{this.props.child}</div>;
  }
}

React.render(<Parent child={<Child />} />, document.body);
```

**Comment by arush** [comment]
Awesome, thanks for the detailed explanation!
