### ISSUE TITLE
Using radium breaks VelocityReact

### ISSUE THREAD

**Issue by basarat** [FormidableLabs/radium#394]
Library : https://github.com/twitter-fabric/velocity-react

If I add Radium decorator on the component -> then -> transitions don't happen anymore. Probably because both libraries work off of style property.

> This issue is mostly for tracking / search-ability of surprise moment for new users. Refs : https://github.com/twitter-fabric/velocity-react/issues/41 :rose:

**Comment by ianobermiller** [comment]
Thanks for reporting, I'll take a look when I've got some time.

**Comment by basarat** [comment]
Workaround : https://github.com/twitter-fabric/velocity-react/issues/41#issuecomment-156005158 :rose:

**Comment by ianobermiller** [comment]
Closing, as there is a valid workaround posted above.
