### ISSUE TITLE
A question regarding passing Array of styles to components

### ISSUE THREAD

**Issue by kumarharsh** [FormidableLabs/radium#396]
Hi, I'm working on a large-ish project, which uses Radium. I'm kind-of learning it hands-on. There is one thing which I don't understand:

Say I have a third-party component `<Map>`, which accepts `style` as a prop which I can pass. Almost all components (which accept developer-defined styles) define the propType as:

```js
propTypes: {
  ...
  style: React.PropTypes.object,
}
```

But using Radium, we can send-in **arrays** of styles like so:
```jsx
<div>
  <Map style={[styles.default, styles.theme]}/>
</div>
```

 for which we'll have to override the propType declaration in the third-party component. This is not possible in many cases such as when getting components via npm or bower. Can't radium *merge* the arrays into object **before** passing it to the component, so that the component gets an object instead of an array?

**Comment by ianobermiller** [comment]
In order to use Radium with a third party component, you must wrap it in `Radium`, e.g.

```
var Map = require('Map.react');
Map = Radium(Map);
```

We could change the Radium function to also modify the propTypes of the passed-in component, changing `style: PropTypes.object` to `style: PropTypes.oneOfType([PropTypes.array, PropTypes.object])`.

**Comment by kumarharsh** [comment]
@ianobermiller of course, I am wrapping them with Radium. I had initially assumed that wrapping in `Radium()` merges the passed styles **before** passing it into the component... Although I'm not aware of Radium's inner workings to know if it's an easy or a hard thing to do.

Your suggested approach seems good too. Although I did come across a component (React-Dropzone) where passing in an array will not work. [See the code here](https://github.com/paramaggarwal/react-dropzone/blob/bcef08ff1b79d98928982018f96bf4ea26e6447f/index.js#L155-L165)

```js
    if (activeStyle && this.state.isDragActive) {
      appliedStyle = {
        ...style,
        ...activeStyle
      };
    }
```

Now, I'm not sure how popular that style of coding is right now, but your current suggested solution (passing an array of styles) won't work in this case. Any thoughts?

**Comment by ianobermiller** [comment]
Sorry, I left out my original explanation and just kept the solution.

Radium changes the `style` prop from an array to an object **after** the parent component `render`s, and before the child component is ever instantiated (its just an element at that point). Unfortunately, PropType checking happens when ReactElement's are created, which is during the parent component `render`.

So my proposal is just to tweak the `PropType`s of a Radium-wrapped component such that it accepts an array for that initial `render`. Radium will still only pass a `style` object, however.

**Comment by kumarharsh** [comment]
Oh, I see. Another possible solution could be that Radium could expose the function which merges styles, so developers can call that manually before passing in the styles to the component. 

Something like:
```jsx
<div>
  <Map style={Radium.merge(styles.default, styles.theme)}/>
</div>
```

Although I'm presuming this may have it's own side-effects...

**Comment by ianobermiller** [comment]
The merge function does not have side effects, so this is also a possibility.

**Comment by kumarharsh** [comment]
Wow! :+1:

**Comment by jsu93** [comment]
pls try this https://github.com/jsu93/babel-plugin-styles
