### ISSUE TITLE
Configuring Radium

### ISSUE THREAD

**Issue by ianobermiller** [FormidableLabs/radium#397]
Little history first: originally, Radium had no configuration. Then we introduced a global setter for the `matchMedia` function. Not liking the global state, I changed `matchMedia` to be configured via an options hash passed to `Radium({..})`, and proposed wrapping the result in a module (see the docs). After actually trying this same thing (but with userAgent instead), I realized this approach doesn't really work for things you only set once (`matchMedia`), and doesn't work at all for things you need to set on every request, like `userAgent`. For example:

```js
let myMatchMedia = window.matchMedia;
function setMatchMedia(newMatchMedia) {
  myMatchMedia = newMatchMedia;
}

function ConfiguredRadium(component) {
  return Radium({
    matchMedia: myMatchMedia,
  })(component);
}
```

Looks fine on the surface, right? Wrong. The `Radium` function, or `ConfiguredRadium` in this case, is only called **once** per component, when the module is loaded. So they only way to make `setMatchMedia` work is to call it before any of your components that use `Radium` are loaded. Ugh. 

Turns out there are three ways you might want to configure Radium, split into groups by when and how often they are configured:

1) Static configuration, e.g. changing the default plugins for all components
2) Static configuration per component, e.g. adding a single plugin or tweaking a single setting for an individual component
3) Dynamic configuration that changes (say per request when rendered server side), e.g. userAgent

The existing configuration mechanism works fine for 1 and 2, but completely fails at 3. In fact, it isn't even possible, since Radium is only configured once per component!

I'm open to suggestions for solving this, but here is my idea so far:

- Keep the existing mechanism for static configuration, except move it to `Radium.configure()` so it is more explicit. We also need to make sure the configured object that is returned has all the statics you expect on Radium, so you don't need to import `ConfiguredRadium` and `Radium`; you should just be able to replace Radium. I'm not set on the rename, but we definitely need the statics copied.
- Create `Radium.Container` that passes dynamic config down the tree via context. `Container` would be optional, only needed if you have dynamic config. Could even be named `Radium.DynamicConfigContainer` or something crazy. Context would allow us to pass configuration down at `render`-time as opposed to module load time.

Thoughts?

**Comment by ianobermiller** [comment]
So, without resorting to global state, the only way to pass data down the tree transparently is `context`, the same mechanism used in React Router and Redux. My current thoughts are:

- Eliminate the existing configuration via `@Radium({...})`. Just use `@Radium` everywhere
- Any component using Radium can take a special prop, `radiumConfig`. `radiumConfig` will contain everything the existing config has, plus dynamic things like `userAgent` for server-side rendering.
- If the `radiumConfig` prop is present, it will also transfer it down the component tree via context

This should keep the API simple, no more `ConfiguredRadium` nonsense, and cover all of the use cases above.

**Comment by ianobermiller** [comment]
Thought about this some more, and realized that the `userAgent` also needs to get passed to `<Style>` and `keyframes`. `<Style>` is easy, since it is in the component tree and can just grab it from `context`. `keyframes` is a bit trickier. Right now it is usually called once at module initialization. Instead, I propose that `keyframes` returns an opaque object that Radium resolves at runtime to an animation name, e.g. `{animationName: Radium.keyframes({...})}`. That way we can use the userAgent to prefix the keyframes.

I also propose that we merge PrintStyleSheet, Style, the keyframes injected style, and media queries (which need to be in CSS for SSR). Instead of having all these different mechanisms, you will add Radium to the root of your app, render Radium.Stylesheet once, and all the different things that need CSS, including selectors like `:visited`, can render to this special stylesheet by passing data up through context. This would make everything in Radium work seamlessly using server side rendering, without any discrepencies.

**Comment by bausmeier** [comment]
I have been struggling with server side rendering as was considering switching away from Radium because of it. Your proposed solutions sound good to me :+1:

**Comment by ianobermiller** [comment]
Yes, we'll have the SSR story cleaned up soon.

**Comment by ianobermiller** [comment]
I've landed the changes for this, but haven't yet fixed keyframes. I'm happy to do an interim release, though.

**Comment by doctyper** [comment]
:+1: interim release.

**Comment by ianobermiller** [comment]
Done, and released.
