### ISSUE TITLE
:hover style not working in combination with ReactRouter <Link />

### ISSUE THREAD

**Issue by laurenskling** [FormidableLabs/radium#398]
Not sure who should be the one to fix this; but in my attempt to get Radium working i got stuck using :hover on my ReactRouter's <Link /> component. The code is simple:

`<Link style={styles.main} to="/">test</Link>`

and:
```
var styles = {
    main: {
      backgroundColor: 'blue',
          ':hover': {
               backgroundColor: 'green' 
          }
    }
};
```

debugging i see this: style="background-color:blue;:hover:[object Object];"
So who's handling this wrong, Radium or React Router?

**Comment by laurenskling** [comment]
Just found something about this in the FAQ, so sorry!
https://github.com/FormidableLabs/radium/tree/master/docs/faq

**Comment by ianobermiller** [comment]
No worries, glad you found a solution!

**Comment by nmaves** [comment]
Is there a workaround when using ES6?

**Comment by ianobermiller** [comment]
Works just fine using ES6 import syntax as well:

```js
import {Link as ReactRouterLink} from 'react-router';
const Link = Radium(ReactRouterLink);
