### ISSUE TITLE
Need interface for ReactTransitionGroup

### ISSUE THREAD

**Issue by alexlande** [FormidableLabs/radium#4]
The high level `ReactCSSTransitionGroup` module won't work with this approach because we don't have classes and external stylesheets. While users could create stylesheets solely for that purpose, it would be nice to have an interface that works with the more low level `ReactTransitionGroup` module and inline styles for complex UI animations.

http://facebook.github.io/react/docs/animation.html#low-level-api-reacttransitiongroup

**Comment by moretti** [comment]
I guess it would also make sense to extend CSSTransitionGroup allowing you to provide your own inline styles (and classnames?) during transitions.

**Comment by whodidthis** [comment]
https://github.com/adambbecker/react-style-transition-group

**Comment by alexlande** [comment]
@whodidthis Very cool! Will add a note to the docs recommending it :)

**Comment by whodidthis** [comment]
Have not tried it, but seems useful if it works

**Comment by alexlande** [comment]
This was added to the FAQ a while back: https://github.com/FormidableLabs/radium/tree/master/docs/faq#how-can-i-use-reactcsstransitiongroup-without-any-classes

**Comment by moretti** [comment]
I'd probably recomend react-motion instead of react-style-transition-group
https://github.com/chenglou/react-motion
https://www.youtube.com/watch?v=1tavDv5hXpo

**Comment by alexlande** [comment]
Hmm, I agree in general that it's a better solution, but react-motion works the same way whether you're using inline styles or CSS. The intention here was to provide guidance for folks who need replacements for CSS-based solutions.
