### ISSUE TITLE
.babelrc references 'stage': 0 which is no longer valid in babel 6

### ISSUE THREAD

**Issue by cly** [FormidableLabs/radium#402]
See: https://github.com/babel/babel/issues/2572

**Comment by AnSavvides** [comment]
Radium is currently using Babel `5.8.x`, so it's not a problem - yet! Worth keeping in mind when we decide to move to Babel `6` :+1:

**Comment by cly** [comment]
So in my own project I'm using babel 6, and when I use webpack to try to bundle radium with my source I am getting the error.

```
Module build failed: ReferenceError: [BABEL]...Unknown option:....babelrc.stage
```

The error also references babel-core from my projects babel.

**Comment by cly** [comment]
Am I bundling it incorrectly? Do you know if there's a way during the bundling process to use the webpack config, babelrc and babel version of radium for the radium portion? And then use babel 6 for the rest of my stuff?

**Comment by alexlande** [comment]
@cly: Typically, I wouldn't expect you to transpile Babel with Radium yourself. We handle that part as part of our prepublish step. In most projects I work on, we only transpile our local application code with Babel. You can do that by either adding an explicit `include` option in your loader config, or by setting `exclude: /node_modules/`.

**Comment by cly** [comment]
Gotcha, so include radium as a separate dependency. Okay let me try that. Thanks!

**Comment by cly** [comment]
fyi solved it with something like:

```
const path = require('path')
const webpack = require('webpack')

config = {
    entry: {
        IndexPage: './src/page/IndexPage.js',
        Vendors: ['react', 'color', 'radium']
    },
    module: {
        loaders: [
            {
                test: /\.js$/,
                loader: 'babel',
                include: [
                    path.join(__dirname, 'src')
                ]
            },
            {
                test: /\.json$/,
                loaders: ['json-loader']
            }
        ]
    },
    output: {
        path: path.join(__dirname, 'dist'),
        filename: '[name]Bundle.js'
    },
    plugins: [
        new webpack.optimize.CommonsChunkPlugin('Vendors', 'VendorsBundle.js')
    ],
    devtool: 'source-map'
}

module.exports = config
```
