### ISSUE TITLE
React 0.14.2 stateless component function defaultProps

### ISSUE THREAD

**Issue by Zenwolf** [FormidableLabs/radium#403]
It appears as if `Radium 0.14.3`  is blocking the `defaultProps` and/or `propTypes` properties set on a stateless function component. When the function is passed props, no defaultProps are filled in and the actual properties that were not explicitly passed values are not present in the props arg.

As per the React 0.14 blog entry, stateless component functions can have `defaultProps` and `propTypes` as static properties even though they do not have lifecycle methods.

**Comment by ianobermiller** [comment]
Oops, you are totally right. Changing `ComposedComponent` to `component` [here](https://github.com/FormidableLabs/radium/blob/ab734ca35abe6338601ec48082066c000c0f6718/modules/enhancer.js#L104) should solve it.
