### ISSUE TITLE
:hover works very slow with many rows!

### ISSUE THREAD

**Issue by bsdo64** [FormidableLabs/radium#405]
I made SPA with many post threads in one page.
I wanted to thumb buttons so I coded with some keys
````js
<a key={post_id+'thumbUp'} style={styles.up} >Like</a>
<a key={post_id+'thumbDown'} style={styles.down} >Dislike</a>
<a key={post_id+'commentButton'} style={styles.comment} >Comment</a>
````

````js
var styles = {
  up : {
    ':hover': 'red'
  }
  down : {
    ':hover': 'red'
  }
  comment : {
    ':hover': 'red'
  }
}
````

That's it in one thread. Each Page has over 50~ threads. but when I mouse over that tags, it changes very slow.

Below I captured some reports. 
I take mouse over three tags and stopped. and that indicates one of that. It takes over 250ms. 
Why this is so slow and, How can I optimize that?

![2015-11-07 6 06 09](https://cloud.githubusercontent.com/assets/5698928/11014481/c045f6a8-857a-11e5-992d-283b809d4b27.png)

**Comment by bsdo64** [comment]
Oh It throw error     

> var existingOnMouseEnter in resolve-interaction-styles-plugin.js:31

 and I think similar issue #367 
![2015-11-07 6 30 33](https://cloud.githubusercontent.com/assets/5698928/11014533/cd0605c4-857d-11e5-9f99-17d89cb1a260.png)

**Comment by bsdo64** [comment]
I tried with 5~10 row it's speed is okay, but over 100~150 row the speed is being slow down... ah..

**Comment by ianobermiller** [comment]
Can you create a jsbin with the issue? It sounds like you might be doing too much within a single component. Since Radium uses `setState`, every hover on any element rendered within a component will cause the entire component to rerender.

Also, if you can provide a repro of the `existingOnMouseEnter` issue, that would be fantastic.

**Comment by bsdo64** [comment]
Thank you very much!
As you said 'every hover on any element rendered within a component will cause the entire component to rerender' helps me.

[This jsbin](http://jsbin.com/kitirejeda/edit?html,js,output) is what I made works slow.
Maybe It can be faster when I seperate components. I'll check out! Thanks! :)

**Comment by ianobermiller** [comment]
Yup, making each row into a component (good practice anyway) dramatically improves perf: https://jsbin.com/qugava/1/edit?html,js,output.

**Comment by bsdo64** [comment]
I solved this problem. I have to keep in mind these logic in other things. Thank you!
