### ISSUE TITLE
Unsupported CSS property ":before" in component "Question"

### ISSUE THREAD

**Issue by JavonEich** [FormidableLabs/radium#406]
<button style={styles.btnClick}>click</button>
var styles = {
    btnClick: {
        border: 'none',
        marginLeft: '5px',
        backgroundColor: "red",
        ':before': {
            content: '..',
            display: 'inline-block'
        },
        ':active': {
            backgroundColor: '#005299',
            transform: 'translateY(2px)'
        }
    }
};

:before 伪类不支持额，怎么破？
还有:active 在PC上有效果，在手机上怎么就没有了呢

**Comment by ianobermiller** [comment]
Radium does not support the :before and :after pseudo selectors. Just add
another node to your rendered HTML.

**Comment by JavonEich** [comment]
OK，thx！

**Comment by ianobermiller** [comment]
I added `:before` and `:after` to the FAQ explicitly, I hope it is more clear now. Thanks for using Radium!
