### ISSUE TITLE
Struggling with something that would be easy in CSS

### ISSUE THREAD

**Issue by TheSisb** [FormidableLabs/radium#409]
In CSS you can do:
```css
.parentClass:hover .childClass {
  display: block;
}
```

In React with Radium I can't figure out how to do this exactly, so instead I bind a onMouseOver/onMouseOut on the wrapping div.

The problem that arises as a consequence, is that with CSS the :hover is still in effect when hovering over the child element because it is contained in the parent element.  With onMouseOut, the event fires as soon as I mouse away from the parent element and the child element is hidden abruptly. I tried to give the child element its own mouseover/mouseout events, but the parent event always fires before the child event so it never has a chance to trigger and thus instantly hides.

Any ideas how I can solve this?

**Comment by ianobermiller** [comment]
https://github.com/FormidableLabs/radium/tree/master/docs/guides#styling-one-element-depending-on-anothers-state

Should probably merge "guides" with "faq"
