### ISSUE TITLE
Convert modifiers, states, and mediaQueries to arrays

### ISSUE THREAD

**Issue by alexlande** [FormidableLabs/radium#41]
Order matters for these.

**Comment by alexlande** [comment]
Need to figure out the best syntax for this. Two options:

```
modifiers: [
  {
    color: {
      red: {
        background: 'red'
      },
      blue: {
        background: 'blue'
      }
    }
  },
  {
    size: {
      large: {
        fontSize: 24
      },
      small: {
        fontSize: 10
      }
    }
  }
]
```

```
modifiers: [
  {
    name: 'color',
    values: {
      red: {
        backgroundColor: 'red'
      },
      blue: {
        backgroundColor: 'blue'
      }
    }
  },
  {
    name: 'size',
    values: {
      large: {
        fontSize: 24
      },
      small: {
        fontSize: 10
      }
    }
  }
]
```

**Comment by alexlande** [comment]
/cc @per-nilsson @eastridge @ryan-roemer @colinmegill @rgerstenberger @kenwheeler @aykayen @paulathevalley 

Sorry to /cc everybody but would appreciate anyone's opinions here.

The current (incorrect because it's not an array) version is this for comparison:

```
modifiers: {
  color: {
    red: {
      background: 'red'
    },
    blue: {
      background: 'blue'
    }
  },
  size: {
    large: {
      fontSize: 24
    },
    small: {
      fontSize: 10
    }
  }
}
```

**Comment by eastridge** [comment]
Is there ever a case where there could be multiple top level modifiers for the first syntax? Like so: ```
modifiers: [
  {
    a: {...},
    b: {...}
  },
  {
    c: {...}
  }
]
```

Option b (array with objects containing `name`) seems like the better option.

**Comment by eastridge** [comment]
Bah, I already changed my mind, I like option a (first) better.

**Comment by kenwheeler** [comment]
+1 on option a

**Comment by per-nilsson** [comment]
OPT A!

**Comment by alexlande** [comment]
@rgerstenberger also said option a earlier, like a true trendsetter

:ship:

**Comment by alexlande** [comment]
In answer to your question @eastridge: nope. There will only ever be a single key in the top level objects. No `a: {}, b: {}`
