### ISSUE TITLE
getChildContext returning function

### ISSUE THREAD

**Issue by marudor** [FormidableLabs/radium#412]
I assume this is a typo.
The getChildContext method of the RadiumEnchancer returns a function instead of an actual Object.
a simple function call fixes this.
```javascript
const superChildContext = super.getChildContext ?
        super.getChildContext :
        {};
```
to
```javascript
const superChildContext = super.getChildContext ?
        super.getChildContext() :
        {};
```

notice the function call on super.getChildContext if it exists.

**Comment by ianobermiller** [comment]
Ouch, I should have added a test for that. Good catch.
