### ISSUE TITLE
How to style <body> and <html> with radium?

### ISSUE THREAD

**Issue by fractall** [FormidableLabs/radium#419]
I've seen the documentation saying about <Style /> but could not find the right way to use it. If I target document.body it erases everything...

**Comment by ianobermiller** [comment]
You can either:

1. Use the [&lt;Style&gt; component](https://github.com/FormidableLabs/radium/tree/master/docs/api#style-component) (docs have an example with html and body)
2. Use CSS
3. Don't style HTML/body unless you absolutely have to (e.g. height: 100% and that kind of stuff)
