### ISSUE TITLE
Problem installing Radium 0.15.2

### ISSUE THREAD

**Issue by mairh** [FormidableLabs/radium#421]
I am using `babel "6.1.19"` and this is the error I get when I try to upgrade Radium from `0.14.*` to `0.15.*`

![screen shot 2015-11-16 at 11 16 03](https://cloud.githubusercontent.com/assets/4072250/11178296/96fe3acc-8c54-11e5-9eca-ede6661a4c3f.png)

Post install
![screen shot 2015-11-16 at 11 25 45](https://cloud.githubusercontent.com/assets/4072250/11178340/d4927b6e-8c54-11e5-88a1-73cdc39250c6.png)

Does it have to do with the different Babel version Radium is using?

**Comment by mairh** [comment]
I believe you are tranapiling the post install beaed on the host babel. However, radium should transpile the library beforehand using your own babel package.

**Comment by hillmanov** [comment]
I just ran into this issue this morning as well trying to set up a new project. Any workarounds for the time being?

**Comment by mairh** [comment]
@hillmanov You can use `0.15.1` version for a workaround.

**Comment by ianobermiller** [comment]
@hillmanov how are you installing Radium? I am not able to reproduce this locally, and for some reason NPM downloads all the files when I install.

**Comment by ianobermiller** [comment]
Can someone please verify that 0.15.3 fixes the issue?

**Comment by isTravis** [comment]
@ianobermiller I had this error earlier. Confirming that 0.15.3 fixed it for me.

**Comment by mairh** [comment]
Closing the issue since it is solved in v 0.15.3

**Comment by ianobermiller** [comment]
Excellent, glad to know the fix worked. Sorry for the busted release!
