### ISSUE TITLE
Can't get :hover to work

### ISSUE THREAD

**Issue by fractall** [FormidableLabs/radium#425]
Sorry for the probably silly question. But no matter what I can't get hover to work. Also de @Radium decorator doesn't parse. Here's my code:

```
class Buttons extends React.Component {
    render() {
        return (
            <div style={style.container}>
                <button style={style.buttonB}>SIGN UP</button>
                <button style={style.buttonB}>LEARN MORE</button>
            </div>
        )
    }
}
```
```
const style = {
    buttonB: {
        border: 'solid #FFFCEB 2px',
        ':hover': { border: 'solid #0088FF 2px' }M
        borderRadius: 33,
        width:117,
        height:34,
        color: '#FFFCEB',
        background: 'transparent',
        margin: '50px 25px 0 0',
        fontSize: 14,
        letterSpacing: 0.5,
        fontFamily: 'Avenir next',
        outline: 'none'
    }
}
```

**Comment by edgesoft** [comment]
Do you have babel stage 0 or do you allow decorators? You can also export the class as.
```
module.exports = Radium( Buttons );
// using ES6
export default Radium( Buttons );
```

**Comment by edgesoft** [comment]
@fractall Maybe this is a typo but ```':hover': { border: 'solid #0088FF 2px' }M``` you have a ```M```  and not a ``` , ``` after

**Comment by fractall** [comment]
Cheers @edgesoft ! module.exports worked fine!

**Comment by YashGadle** [comment]
@fractall How did it work? It's not working for me. And did you try to give a unique key to every Radium Element?

**Comment by dmitrisi4** [comment]
I had the same problem. You just had to remove the `key` property and it is worked.
