### ISSUE TITLE
Sharing styles between Radium and CSS/Sass

### ISSUE THREAD

**Issue by greaber** [FormidableLabs/radium#428]
I'm working on a site that is not an SPA and uses React only for a few components.  Most of the site is rendered traditionally on the server, and we use some jQuery for progressive enhancement.  We are using Bootstrap and Sass.

I would like to use inline styles, and in particular Radium, to style the React portions of the site.  I am interested in recommendations about the best way to do this smoothly without having to move the non-React portions of the site into React or overly sacrifice the purity of inline styles by using tons of classes in React.

One thought I had is that if I can extract all configurable styles (colors, fonts, sizes, etc.) into a data structure then I could potentially share them between the React and non-React portions of the site.  However, there is still the issue that this data structure should be a JavaScript object for React but probably a collection of Sass variables for the rest of the site.  It seems like it might not be hard to translate from one of these formats to the other, but I haven't found any existing tool to do it so far.  Am I thinking about this in the right way or barking up the wrong tree?

**Comment by ianobermiller** [comment]
You have a couple options. If you want to share variables between JS and Sass, I suggest creating a JS file with all your constants. You can then write a simple node script that outputs the constants in a form that Sass recognizes, and run that before the rest of your build.

If you'd like to take entire chunks of CSS, you might try using [react-styling](https://github.com/halt-hammerzeit/react-styling) as a build step to convert entire CSS files into JavaScript consumable modules.

cc @halt-hammerzeit
