### ISSUE TITLE
Radium removes context

### ISSUE THREAD

**Issue by natew** [FormidableLabs/radium#432]
Seems like my context gets removed. When I have a component that sets a context, `getChildContext` doesn't get called. If I remove Radium wrapper, it gets called properly.

**Comment by natew** [comment]
Was going to test this further but got this far:

- Using React.createClass
- Wrap with Radium
- Added log in Radium and it is actually merging the getChildContext
- Added log in getChildContext in my component and it's not called
- Remove Radium and it logs.

**Comment by natew** [comment]
Figured out why, Radium is returning the function (getChildContext) rather than calling it and returning it's object. And the getChildContext() function returned from a React.createClass has displayName as a property.

(put a debugger where React throws the error)

![image](https://cloud.githubusercontent.com/assets/12100/11358578/984e1210-9228-11e5-9bb2-639b8b83761e.png)

**Comment by ianobermiller** [comment]
Yes, I haven't pushed a new release yet. Fixed with #418.

**Comment by natew** [comment]
@ianobermiller thanks!
