### ISSUE TITLE
Utility functions in the API

### ISSUE THREAD

**Issue by williamboman** [FormidableLabs/radium#433]
Does the Radium API expose any utility functions such as determining whether the current viewport matches a certain media query e.g.

```jsx
{ Radium.is('@media (max-width: 769px)') &&
    <div>You are on a small viewport!</div>
}
```

more practical example;

```jsx
<Container>
    <header>Really long name here {Radium.is(breakpoints.min('sm')) && lorem ipsum}</header>
</Container>
```

**Comment by ianobermiller** [comment]
Nope. You can do it yourself using [`matchMedia`](https://developer.mozilla.org/en-US/docs/Web/API/Window/matchMedia), same as Radium does.

I'm also considering moving media queries to generate CSS so they work better with server-side rendering, which would mean Radium would no longer use `matchMedia`.
