### ISSUE TITLE
Question on shouldComponentUpdate

### ISSUE THREAD

**Issue by edgesoft** [FormidableLabs/radium#434]
I use a weird statement to see if I need to update my component. I guess there must be a better way then this. Any suggestions?

```js
if( nextState._radiumStyleState.main ){
  if( this.state._radiumStyleState.main ){
    if( nextState._radiumStyleState.main[':hover'] !== this.state._radiumStyleState.main[':hover'] ){
	  return true;
    }
  }else{
    if( nextState._radiumStyleState.main[':hover']  ){
      return true;
    }
  }
}
```

**Comment by ianobermiller** [comment]
https://github.com/FormidableLabs/radium/blob/master/docs/api/README.md#getstate

You can pass nextState directly to Radium.getState for this exact use case. Please do not access Radium private state, as the names and implementation are subject to change without a major version bump.
