### ISSUE TITLE
Generic error for unique key creation

### ISSUE THREAD

**Issue by tquetano-r7** [FormidableLabs/radium#441]
When items with dynamic styles do not have a unique key, you throw an error that is incredibly generic and makes it very difficult to trace. The error is located in resolve-styles.js in the _buildGetKey function.

If you were to provide any additional information (such as renderedElement.type) then tracing back the problem would be improved, especially for components that have a variety of nested children that could potentially be the issue.

**Comment by ianobermiller** [comment]
How's this?

> Radium requires each element with interactive styles to have a unique key, set using either the ref or key prop. Key "one" is a duplicate. Component: "TwoSquares". Element: "div".

**Comment by tquetano-r7** [comment]
That's perfect! Thanks for getting on this so quickly. :)
