### ISSUE TITLE
Include dist folder in package.json?

### ISSUE THREAD

**Issue by MeanwhileMedia** [FormidableLabs/radium#445]
For those of us who like to share node_modules with the client? I really want to use radium but would rather not start using bower in my current project.

**Comment by jedrichards** [comment]
What problem are you seeing? As far as I can see Radium publishes compiled ES5 at `lib/index.js` referenced via the `main` property in package.json. I'm using it happily with npm/Browserify ...

**Comment by MeanwhileMedia** [comment]
I'm not currently using browserify but rather an AMD/require.js setup, so I was hoping to have access to the fully compiled dist/radium.min.js in the npm module with no additional steps. Thanks for the response.

**Comment by ryan-roemer** [comment]
@ianobermiller @alexlande  -- Something changed between https://github.com/FormidableLabs/radium/compare/v0.15.2...v0.15.3 such that

* https://npmcdn.com/radium@0.15.2/dist/radium.min.js -- Does exist
* https://npmcdn.com/radium@0.15.3/dist/radium.min.js -- Does not exist.

Does the properly making `files: ["lib"]` an array somehow _exclude_ other files in source like `dist/`?  (Apologies if my npm/package.json-fu is weak here...)

**Comment by jedrichards** [comment]
I'm not sure, and the npm docs are not clear, but I think `files` array in package.json acts as a whitelist. So everything else is ignored? That might be why the `dist` stuff is now missing ...

**Comment by ianobermiller** [comment]
Yes, that was my intention, to exclude unnecessary files from npm. I
suppose we can whitelist the dist directory. React router, for example, has
the UMD build in npm files.

**Comment by MeanwhileMedia** [comment]
Makes sense to me @ianobermiller. Npm is generally regarded as node-only modules. For some edge cases though I think it would be cool to have the dist folder available. Wouldn't hurt, right?

**Comment by ryan-roemer** [comment]
Dist is in source and as NPM is being used as a general frontend dep source. I would strongly recommend keeping it in NPM. Also for npmcdn.

I would be totally surprised to by design not have dist published...
