### ISSUE TITLE
Story for distributing component libraries w/ Radium

### ISSUE THREAD

**Issue by jedrichards** [FormidableLabs/radium#449]
Hey guys, just wondering if you have a story or some docs around approaches for distributing component libraries that make use of Radium?

Specifically I'm thinking of a npm library that exposes a bunch of Radium-enhanced components, which could then be used in another React project (either ES6 `import` or ES5 `require`)?

Would the parent project have to define radium as a dependency, or could it be compiled into the component library somehow?

Thanks!

**Comment by ianobermiller** [comment]
You could certainly compile Radium into the library using webpack or browserify to create a single file build. Alternatively, add Radium as a peer dependency and compile your components down to ES5 before putting them in NPM.

**Comment by jedrichards** [comment]
Thanks that sounds sendible, will pop back if any Qs :)
