### ISSUE TITLE
getState doesn't work with function component

### ISSUE THREAD

**Issue by leocristofani** [FormidableLabs/radium#453]
Hello, I'd like to use getState with a function component, but it does not work for me. Most probably I'm doing something wrong, or didn't read the docs completely. See pseudo component below:
```
const component = props => {
  return (
     <div key='container'>
         ...
         {Radium.getState(this.state, 'container', ':hover') ? <AnotherComponent /> : null}
      </div>
   );
}
```
Maybe I have to change `this.state` with something else? Thanks!

**Comment by duhduhdan** [comment]
Functional components are _stateless_ components. This means they should only be used for [composing other components](https://facebook.github.io/react/blog/2015/10/07/react-v0.14.html#stateless-functional-components). You're better off handling conditional rendering of components in a stateful component.

**Comment by leocristofani** [comment]
Makes sense duhduhdan. Thanks for the quick response.

**Comment by ianobermiller** [comment]
If you used the `function` syntax, Radium could [call your stateless component](https://github.com/FormidableLabs/radium/blob/285985e5a4c1855a2d1bf1512b5e52c3634bd305/src/enhancer.js#L48) with the `this` value of the stateful component wrapper it creates. But most uses of stateless components I've seen use arrow-methods, which already have `this` bound.

We should add something to the docs for this.

**Comment by vimniky** [comment]
@ianobermiller 
hi ianobermiller !
Here's my confusion :
```javascript

const Aconponent = (props, context) => {
   return <div> hi! there</div>
}

export default Radium(Acomponent)

```
What's wrong with the above code ? 
Thanks !

**Comment by ianobermiller** [comment]
@vimniky, are you saying that Radium is no longer working correctly with stateless functional components? The code you posted should work fine.
