### ISSUE TITLE
Homepage update to stack.formidable.com/radium

### ISSUE THREAD

**Issue by david-davidson** [FormidableLabs/radium#459]
Hey @ianobermiller and @alexlande,

Just a heads-up that we (Formidable) are hosting our GitHub Pages sites under `stack.formidable.com` now, not `projects.formidablelabs.com`. The old link is 301-redirected to stack.formidable.com/radium, so it'll keep working, but I've updated the "homepage" field at the top of the repo to the new URL.

Thanks!
(You can go ahead and close this immediately; just wanted to make sure you're in the loop. :+1:)

**Comment by alexlande** [comment]
:+1:
