### ISSUE TITLE
How to override styles on a component children

### ISSUE THREAD

**Issue by erwagasore** [FormidableLabs/radium#461]
Consider this case where I have Charfield components already styled individually but I want to change its styles if they are part of a Wrapper component "FieldGroup" for example
```
<FieldGroup>
<Charfield name="search" />
<Charfield name="location" />
</FieldGroup>
```
Is there a way to handle this case? Thank you.

**Comment by ianobermiller** [comment]
There is no generic way to handle this in Radium. This is one of the aspects of CSS that we are trying to avoid. If you want to change the style of a component, pass props to it. Changing style or behavior based on parent component makes a component less predictable.

While I'm not sure what you are trying to change, here is an example:

```as
<CharField type="compact" name="search" />
<CharField type="default" name="search" />
```

**Comment by erwagasore** [comment]
Thanks makes sense.
