### ISSUE TITLE
Radium not working and blocking api requests as well

### ISSUE THREAD

**Issue by YonasBerhe** [FormidableLabs/radium#462]
Hello, 

I'm having a tough time using Radium for the first time in one of my React applications. I have successfully imported Radium into my project, but I can't quite get myself up and running.  My app uses the random user api which I use to retrieve random information about people(willing people).I  scaffolded my application using a Yeoman generator called React Webpack.  

I have tried to initialize Radium in my class with in my code using 

```
export default Radium(FakeUser); 
```

I have gotten no luck. The line of code ends up hoisting itself above my ReactDOM.render, stopping my ajax request to the API. 

It would be really nice to to start using Radium in my work, so please help me out. 

@kenwheeler

**Comment by kenwheeler** [comment]
@YonasBerhe what is the exact error that you're getting?

**Comment by kenwheeler** [comment]
can you post a gist of the file?

**Comment by YonasBerhe** [comment]
The error below occurs only when I rap Radium around my class FakeUser. 

```
Error
Uncaught TypeError: Cannot read property '0' of undefined
```
```
export default Radium(FakeUser);
```
[MainComponentGist](https://gist.github.com/YonasBerhe/ce2fea747650ee7d9d5c)
[RepoForProject](https://github.com/YonasBerhe/fakeUser)

**Comment by ianobermiller** [comment]
Looks like you are wrapping the FakeUser component with Radium **after** you render it. See this gist for the correction: https://gist.github.com/ianobermiller/78eec7c7684869d07757

The link to the repo no longer works. Sorry for our delay in getting back to you!

**Comment by YonasBerhe** [comment]
No worries... Thanks for getting back to me. 


``` 
FakeUser = Radium(FakeUser);
```

Added the code above to my project with no problems. Now I'm trying to test Radium by using the button component in my project. 

``` 
<Button kind="primary">Radium Button</Button>
```

I keep getting the following error: 
```
adjacent JSX elements must be wrapped in an enclosing tag
```
Any thoughts as to why this error is occurring?

[UpdatedGist](https://gist.github.com/YonasBerhe/a0e40f20eb539107ef4d)
[*RepoForProject](https://github.com/YonasBerhe/RandomUserReact)

**Comment by alexlande** [comment]
@YonasBerhe: React component `render` methods always have to return a single top level element/component. In your example, you're returning two `div` elements next to each other. You've got an extra closing `</div>`: https://gist.github.com/YonasBerhe/a0e40f20eb539107ef4d#file-gistfile1-txt-L28

**Comment by ianobermiller** [comment]
Closing, assuming the original issue is solved.

**Comment by YonasBerhe** [comment]
Thanks for the help!
