### ISSUE TITLE
Can't configure a standalone style component.

### ISSUE THREAD

**Issue by uipoet** [FormidableLabs/radium#463]
Attempting to render a style component server-side only.

Here is what I naively assumed would work out of the box:

```javascript
import {Style} from 'radium';

const userAgent = req.headers['user-agent'];
const style = renderToStaticMarkup(<Style radiumConfig={{userAgent}} rules={rules}/>);

response.write(`<!doctype html><html><head>${style}</head></html>`);
response.end();
```

I've tried passing configuration via radium's component and directly on the style component. Either way, I get this error message:

```bash
Either the global navigator was undefined or an invalid userAgent was provided.
```

Here is the wackier way I've tried to no avail:

```javascript
import radium, {Style} from 'radium';

const userAgent = req.headers['user-agent'];
const ServerStyle = radium({userAgent})(Style);
const style = renderToStaticMarkup(<ServerStyle rules={rules}/>);

response.write(`<!doctype html><html><head>${style}</head></html>`);
response.end();
```

**Comment by uipoet** [comment]
Found a working solution:

```javascript
import radium, {Style} from 'radium';

const userAgent = req.headers['user-agent'];
const ServerStyle = radium(props => props.children);
const style = renderToStaticMarkup(
  <ServerStyle radiumConfig={{userAgent}}>
    <Style rules={rules}/>
  </ServerStyle>
);

response.write(`<!doctype html><html><head>${style}</head></html>`);
response.end();
```

Please consider adding the radiumConfig property to the style component for this use case.

**Comment by ianobermiller** [comment]
Thanks for the detailed report and workaround. We can definitely check for `radiumConfig` on the Style object itself.

**Comment by uipoet** [comment]
Great! Thank you for taking a look. I'll stay subscribed to see the issue resolved. Next year, time permitting, I'll get better acquainted with your project so I can submit pull requests for such features.

**Comment by uipoet** [comment]
Gratitude!
