### ISSUE TITLE
Large number of render() calls when applying multiple media queries

### ISSUE THREAD

**Issue by Hogewind** [FormidableLabs/radium#465]
I have the following code, with multiple media queries applied to a single div:

```
import Radium from 'radium';
import React from 'react';

class RenderTest extends React.Component
{
	count = 0;
	render()
	{
		this.count++;
		console.log("*** Rendering RenderTest.jsx (" + this.count + ") ****");

		return (
			<div style={style.base}>
				Test
			</div>
		);
	}
}

var style =
{
	base:
	{
		border: "1px solid red",
		"@media (min-width: 500px) and (max-width: 749px)":
		{
			width: "50%"
		},
		"@media (max-width: 750px) and (max-width: 999px)":
		{
			width: "33%"
		},
		"@media (max-width: 1000px) and (max-width: 1249px)":
		{
			width: "25%"
		},
		"@media (max-width: 1250px)":
		{
			width: "20%"
		}
	}
};
export default Radium(RenderTest);
```

The code works as expected, but triggers a large number of render() calls:
* Initial page-load: render() is called once
* Resizing page to the arbitrary width of 400px : 4 additional calls to render()
* Maximize to screen: 6 additional calls to render()
* Resizing page to 400px: 6 additional calls to render()
* The pattern repeats from here: all further resizing triggers 6 calls.

Things I noticed:
* The number of render-calls seem to grow exponentially with the number of applied media-queries to the element. 
* Applying a single media-query works fine. 
* Making small size adjustments to the window (between the borders of the queries) works great and does not trigger any renders. 
* The react state object seems to be identical in each of the duplicate calls.

I am rather new to both React and Radium, so I hope I didn't miss anything obvious.

**Comment by ianobermiller** [comment]
Thanks for the detailed bug report! We'll check this out, it looks like only one media query should be active at a time, so when resizing you should only see at most two calls to render (deactivating one, and activating another). We should even be able to debounce though. 

> The number of render-calls seem to grow exponentially with the number of applied media-queries to the element.

This is most disturbing to me! Thanks again.

**Comment by Hogewind** [comment]
Thank you!
