### ISSUE TITLE
Allow definition of styles in nested objects

### ISSUE THREAD

**Issue by eastridge** [FormidableLabs/radium#47]
We should allow definition of margin, border, padding etc via an object:

```
{
  margin: {
    top: '1px'
  }
}
```

vs `marginTop` in this case.

**Comment by eastridge** [comment]
An immediate case that could make it hairy is interop between values. If I define the style as `marginTop`, once initialized can I modify via `margin.top` and visa versa?

**Comment by colinmegill** [comment]
I'm not sure I agree yet - what's wrong with enforcing `"1 0 0 0"`?

**Comment by eastridge** [comment]
After more thought, this is very low priority, closing.
