### ISSUE TITLE
Published Radium 0.15.3 does not include dist/radium.min.js

### ISSUE THREAD

**Issue by coopy** [FormidableLabs/radium#471]
It seems the dist files were not published with `v0.15.3`.

These URLs 404:
- https://npmcdn.com/radium@0.15.3/dist/radium.js
- https://npmcdn.com/radium@0.15.3/dist/radium.min.js

These URLs are 200 OK:
- https://npmcdn.com/radium@0.15.2/dist/radium.js
- https://npmcdn.com/radium@0.15.2/dist/radium.min.js

I think the only solution is to publish a patch 0.15.4 that includes the dist files.

**Comment by ryan-roemer** [comment]
@coopy -- Captured in https://github.com/FormidableLabs/radium/issues/445 and fixed in `master` I believe. We may need a new publish.

**Comment by ianobermiller** [comment]
Thoughts on removing `dist` from github, but still publishing it on npm, and just directing users to npmcdn for single files and bower?

**Comment by knowbody** [comment]
@ianobermiller great idea, I was going to mention that too. All we need to do is have `.gitignore` where we include the `dist` directory and then have separate empty `.npmignore` as `.npmignore` overrides `.gitignore`

More in the [documentation](https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package).

**Comment by coopy** [comment]
[bower install via npmcdn](https://github.com/rackt/redux/issues/944#issuecomment-155628932) works well. Let's add it to the documentation.

**Comment by ianobermiller** [comment]
I don't think we even need npmignore if we specify files in package json,
do we?

**Comment by knowbody** [comment]
yeah either blacklist or whitelist

**Comment by ianobermiller** [comment]
Fixed in 0.16
