### ISSUE TITLE
Expose a method to merge style arrays

### ISSUE THREAD

**Issue by kumarharsh** [FormidableLabs/radium#483]
Radium should expose the mergeStyleArray plugin for direct use within our code, in cases when using Radium might be *overkill* (pure components without `:hover` states), or when using Radium is *impossible*, such as with **third-party libraries** like React-Select (https://github.com/JedWatson/react-select).

Then we can just use `Radium.mergeStyles([a, b, c])` in the `render()` method, and be done with it.

---
This issue is raised from the discussion in https://github.com/FormidableLabs/radium/issues/396

**Comment by ianobermiller** [comment]
If you don't have any nested styles (e.g. `:hover`), merge styles is equivalent to using [Object.assign](https://www.npmjs.com/package/object-assign) or object spread:

```js
const style = {...a, ...b, ...c};
```

Also worth noting that you *can* use Radium with third-party libraries, like react-select, by wrapping it upon import:

```js
var Select = require('react-select');
var RadiumSelect = Radium(Select);
```

**Comment by kumarharsh** [comment]
@ianobermiller In most cases, this does the trick, but there are several cases when this falls short:

1. When using CSS which has to be prefixed, like `flex`. A plain merge won't do the trick here, I'd still like to use radium's prefixer.
2. Select has not just a `style` prop, but also `wrapperStyle`, `menuContainerStyle` and `menuStyle`. Radium is not merging styles in those props, and passing in an array of styles into Select is not possible. It requires only an object.
3. As I had said earlier, why have to overhead of converting a pure component to a stateful component when in many cases all that is needed is a `merge`.

Now I know that I can go ahead and use a separate library for merging, but then Radium already does that and I don't want to blow up the code size unnecessarily.

**Comment by ianobermiller** [comment]
I'm not sure I understand your points:

1. Radium's merging does not do prefixing; that happens as a separate step. We could expose this, but I'd rather not open up the API surface for such a case. You could just use `inline-style-prefixer` directly, the same way Radium does.
2. Yes, this is true, Radium will not touch props other than style. Please open a separate issue if you'd like to address this use case.
3. You can use Radium with a pure component all the same (of course Radium converts it to a stateful component, so I understand if you'd like to avoid that). As mentioned in (1), [`mergeStyles`](https://github.com/FormidableLabs/radium/blob/master/src/merge-styles.js) has nothing to offer if you don't have nested styles.

As to a separate library, `objectAssign` is a useful primitive, and if you are transpiling with Babel you should use the nicer spread syntax anyway.

**Comment by kumarharsh** [comment]
Yes, I'm already using babel's spread syntax, which is really nice. I understand your point in using `inline-style-prefixer` directly. My bad for mixing up mergeStyles and the prefixer.

Yes, I'd like point number 2 to be addressed though.

There would be several libraries which would be accepting style props for different sub-components within the main component (case in point: react-select or react-dropzone), so it'd be very helpful if there'd be a way to solve this problem.

**Comment by ianobermiller** [comment]
Thanks for opening the new issue about point 2. Do you feel the rest of your points were covered? While it would be nice to run Radium on a standalone style object, it only works for a limited subset, mainly just the prefixer.

**Comment by kumarharsh** [comment]
Yes, with your explanation I think it *should* be enough. Point number 3 is an optimization thing. I don't have data to support the amount of hit due to Radium wrapping pure components. If someone does come up with it, I think you can look into it then.

**Comment by ianobermiller** [comment]
React doesn't optimize pure functional components much **yet**. They plan
to add more optimizations in the future, though.

**Comment by kirkchris** [comment]
We're also running into this and I wasn't sure the resolution that came to this. We are attempting to use [react-textarea-autosize](https://github.com/andreypopp/react-textarea-autosize) which accesses the `style` prop assuming it's an object and then extends it. This breaks radium styling since we are passing in as an array.

We do have a nested style--`:focus`--so need the support of `mergeStyles`. For now I've gotten around it by just including the function in our codebase, however it would be awesome if it could be accessed some way via the `Radium` import, so we don't have to worry about maintaining/updating it separately.

Any thoughts on this? Or ideas on an alternate way to solve this?
