### ISSUE TITLE
radium/node_modules/babel/index.js didn't return a function

### ISSUE THREAD

**Issue by Andyccs** [FormidableLabs/radium#484]
When using "radium": "^0.15.3" with "webpack": "^1.12.9", Webpack cannot bundle my React component, and show the following error:

```
Version: webpack 1.12.9
Time: 7891ms
   [0] multi main 52 bytes {0} [built]
    + 70 hidden modules

ERROR in Loader /Users/andyccs/Codes/sqat-stylechecker/website/node_modules/radium/node_modules/babel/index.js didn't return a function
 @ ./~/radium/lib/index.js 9:16-37

ERROR in Loader /Users/andyccs/Codes/sqat-stylechecker/website/node_modules/radium/node_modules/babel/index.js didn't return a function
 @ ./~/radium/lib/index.js 17:33-74

ERROR in Loader /Users/andyccs/Codes/sqat-stylechecker/website/node_modules/radium/node_modules/babel/index.js didn't return a function
 @ ./~/radium/lib/index.js 21:23-52

ERROR in Loader /Users/andyccs/Codes/sqat-stylechecker/website/node_modules/radium/node_modules/babel/index.js didn't return a function
 @ ./~/radium/lib/index.js 25:16-38

ERROR in Loader /Users/andyccs/Codes/sqat-stylechecker/website/node_modules/radium/node_modules/babel/index.js didn't return a function
 @ ./~/radium/lib/index.js 29:17-39

ERROR in Loader /Users/andyccs/Codes/sqat-stylechecker/website/node_modules/radium/node_modules/babel/index.js didn't return a function
 @ ./~/radium/lib/index.js 33:21-48

ERROR in Loader /Users/andyccs/Codes/sqat-stylechecker/website/node_modules/radium/node_modules/babel/index.js didn't return a function
 @ ./~/radium/lib/index.js 13:15-35
```

To solve this problem, I have to manually remove `./node_modules/radium/node_modules/babel` folder from `./node_modules/radium`.

Why `"babel": "^5.8.23"` is included in `dependencies` section of `package.json`?

**Comment by Andyccs** [comment]
Note: This [commit](https://github.com/FormidableLabs/radium/commit/0669b5cd2917e02f75fbe50597198aa73262a7a6) has replace `babel` dependency with a list of babel 6 dependency.

**Comment by ianobermiller** [comment]
Babel is in `dependencies` so that Radium works fine when npm installed directly from git, because the `lib` directory then needs to be built in `postinstall`. Can you provide a minimal repo with your setup so that I can reproduce the issue? Thanks!

**Comment by Andyccs** [comment]
Here is the minimal repo: https://github.com/Andyccs/radium0.15.3issue484

**To reproduce the bug**

```Shell
npm install
webpack
```

**To resolve the bug**

```Shell
rm -rf node_modules/radium/node_modules/babel
webpack

# In MAC OSX
open public/index.html
```

**Comment by Andyccs** [comment]
In you webpack.config.js you need to exclude node_modules/ directory:

```Javascript
var node_modules_dir = path.resolve(__dirname, 'node_modules');
...

module.exports = {
  ...
  module: {
    loaders: [{
      test: /\.js$/,
      exclude: [node_modules_dir], // I miss this line!
      loaders: ['babel']
    }, ...]
  },
  ...
};
```

**Comment by ianobermiller** [comment]
Alternatively, only *include* your source directory:

[`include: path.join(__dirname, 'src')`](https://github.com/ianobermiller/nuclearmail/blob/master/getWebpackConfig.js#L27)
