### ISSUE TITLE
Style-keeper.js throwing an error in v0.16.0

### ISSUE THREAD

**Issue by ads1018** [FormidableLabs/radium#486]
Just pulled down release v0.16.0 and style-keeper.js is throwing an error `Uncaught TypeError: Cannot read property 'indexOf' of undefined`.

It's occurring on line 21 in style-keeper.js. I think `this.__listeners` is scoped to the wrong `this`

**Comment by ianobermiller** [comment]
Excellent, was hoping to release 0.16.1 tonight ^^

**Comment by ianobermiller** [comment]
Are you doing anything out of the ordinary? I can't repro this in the examples.

**Comment by ads1018** [comment]
Awesome! Glad I could assist. @ianobermiller: Amazing work with the new release ;)
