### ISSUE TITLE
Fix keyframes prefix

### ISSUE THREAD

**Issue by dongmei761** [FormidableLabs/radium#488]
Why I always got "@-webkit-keyframes {...}" ? How can I remove the prefix when using IE or Firefox? Or maybe I used Radium.keyframes in a wrong way?

**Comment by dongmei761** [comment]
I think the reason may be that I'm using server side rendering with V8

**Comment by dongmei761** [comment]
I saw this line "var keyframesPrefixed = '-webkit-keyframes';" in keyframes.js, but why you set the prefix to a static string?

**Comment by ianobermiller** [comment]
Oops, good catch! I meant to use [`InlineStylePrefixer.prefixedKeyframes`](https://github.com/rofrischmann/inline-style-prefixer/blob/1de35719522956cf64134376ec274596e1891fc9/modules/Prefixer.js#L32)!
