### ISSUE TITLE
StyleRoot causes Invariant Violation: Element type is invalid

### ISSUE THREAD

**Issue by isTravis** [FormidableLabs/radium#489]
Thank you thank you thank you! So excited to have 0.16.1!

I've been trying to integrate it but have been running into the challenge that wrapping my App in `<StyleRoot>` causes the following: 

```
Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components). Check the render method of `Component`.
Error: Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. Check the render method of `Component`.
```
I've tried wrapping it around a few different places (each time ensuring that I'm not wrapping direct children - but wrapping react elements) - and I get the same error. I've tried wrapping it above and below `<ReactRouter>` and `<Intl>` (two wrapper components that use context heavily) - but still the same error regardless.

As checks: 
1. The `<StyleRoot>` wrap should be above or below the location that I set `radiumConfig={{userAgent: req.headers['user-agent']}}`?
2. Would asynchronous code mess up StyleRoot at all? I have a few promise-based actions that dispatch on server-side render. I'm wondering if the StyleRoot component is trying to do its business before they're finished. 

Wanted to see if anything immediate came to mind. If not - I'll try to slim down the codebase and post a simple repo with the error.

**Comment by ianobermiller** [comment]
1. You can set `radiumConfig` directly on `StyleRoot` if you want, or you can put it above
2. Async code shouldn't mess up `StyleRoot`

If you do have the time to slim it down, I'll take a look, I don't think I can figure out any more from your description.

**Comment by isTravis** [comment]
Right - sorry about the vagueness. I suppose I was just probing to see if it was a known thing you had bumped into during development and I was making a common mistake. 

Here's a repo: [https://github.com/isTravis/radium0.16.1SSRbug](https://github.com/isTravis/radium0.16.1SSRbug).  
- `server.js` and `client.js` are in `/src`. I've tried wrapping my ReduxRouter in these files in the same manner as #496 but no luck. 
- I've also tried wrapping my main this.props.components injection in `/src/helpers/Html.jsx`- this is the location generating the error right now.
- I've tried wrapping the inner content of `/src/components/App.jsx` - also no luck.

**Comment by isTravis** [comment]
Hmmm - removing all media queries and style root instances gives me the same bug. 

I initially thought it was with `<StyleRoot>` because when I installed 0.16.1, I got the 'To use CSS with media queries please use....' error. I fixed that by adding the StyleRoot - but then got the 'Invariant violation'. 

So - I thought it was with `<StyleRoot>` but it seems to be with v0.16.1 more broadly (that is - with no media queries and no StyleRoots anywhere - I get the same bug which did not exist in 0.15.x).

**Comment by Dindaleon** [comment]
@isTravis Did you get it to work? I just got mine to work with an universal app, so if I can help you out, let me know. I would be glad to do so.

**Comment by isTravis** [comment]
Wondering if it's a Babel 6 issue. We have a few dependencies that are forcing us to stay at Babel 5 for the moment - and I notice that all the Radium is examples are using Babel 6.
