### ISSUE TITLE
Issue configuring Radium on a server side rendering App

### ISSUE THREAD

**Issue by Dindaleon** [FormidableLabs/radium#496]
I followed the guide for setting Radium up. I wrapped my styled component with the `@Radium` connector and configured the server and client as follows:

server:
```javascript
<Provider store={ store } key="provider">
  <IntlProvider
    key={ store.getState().user.data.locale }
    locale={ store.getState().user.data.locale }
    messages={ lang[store.getState().user.data.locale] }>
    <StyleRoot style={{ userAgent: request.headers['user-agent'] }}>
      <ReduxRouter/>
    </StyleRoot>
  </IntlProvider>
</Provider>
```

client:
```javascript
 ReactDOM.render(
    <Provider store = { store } key="provider">
      <ConnectedIntlProvider>
        <StyleRoot style={{ userAgent: navigator.userAgent }}>
          <ReduxRouter
            children = { getRoutes(store) } />
        </StyleRoot>
      </ConnectedIntlProvider>
    </Provider>,
    root
  );
```

These are the errors I am getting:

On the server:
```
Radium: userAgent should be supplied for server-side rendering. See https://github.com/FormidableLabs/radium/tree/master/docs/api#radium for more information.
Either the global navigator was undefined or an invalid userAgent was provided. Using a valid userAgent? Please let us know and create an issue at https://github.com/rofrischmann/inline-style-prefixer/issues
```

On the client:
```
Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) ctid=".1kcxxrwd0jk.$/=10"><div class="md
 (server) ctid=".1kcxxrwd0jk.$=10"><div class="mdl
```

**Comment by isTravis** [comment]
Unless there are new docs I have missed - the style attribute is the wrong place to be specifying `userAgent:`. Check the docs here [https://github.com/FormidableLabs/radium/tree/master/docs/api#configuseragent](https://github.com/FormidableLabs/radium/tree/master/docs/api#configuseragent). You need to pass it in with `radiumConfig={{userAgent: req.headers['user-agent']}}`

The extra `/` in the reactid is something I don't know enough about - sorry I can't help with that.

**Comment by Dindaleon** [comment]
@isTravis great! `radiumConfig` fixed the issue on the server side. I don't know where I got `style` from. Weird!

I still have the issue on the client side.

**Comment by ianobermiller** [comment]
@Dindaleon thanks for referencing the docs, I'll make some changes to clear that up.

**Comment by Dindaleon** [comment]
@ianobermiller no problem! I would like to re-open this issue as I have yet to fix the issue on the client side.

```
Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) ctid=".1kcxxrwd0jk.$/=10"><div class="md
 (server) ctid=".1kcxxrwd0jk.$=10"><div class="mdl
```

I dont understand why is that `/` being added on the client.

**Comment by ianobermiller** [comment]
I don't think it has anything to do with Radium. Does removing Radium make it go away?

**Comment by Dindaleon** [comment]
Yes I checked that, removing Radium makes it go away.

**Comment by isTravis** [comment]
Having solved all my other SSR issues - I'm also bumping into this `/` problem as well, @Dindaleon .

From your small chunks of code - our stacks look similar (Redux Router, IntlProvider, Radium `/` bug). Have you traced it to anything suspicious?

**Comment by Dindaleon** [comment]
@isTravis I kind of managed to remove all warnings (client/server) by following the example provided here: https://github.com/FormidableLabs/radium/tree/master/examples

What I am trying to do now is to get the `userAgent` from the headers on the server side and dispatch it to a reducer or pass it down from the server to my `App` component. However, the `/` problem persists no matter what alternative I take.

As the demo indicates, as long as you configure the `userAgent` in your top component, all warnings go away. The only thing that stays is the `/` in most of `data-reactid` elements.

**Comment by isTravis** [comment]
@Dindaleon Not using bluebird. Most of my stack started from (and is still similar to) [https://github.com/erikras/react-redux-universal-hot-example](https://github.com/erikras/react-redux-universal-hot-example). 

But wait - are you thinking that the `useragent` needs to also be passed in on the client side to avoid server/client mismatch? I thought the role of passing `useragent` to the server would that it would then mimic what will happen clientSide. 

Right - I have no warning or errors from Radium - everything is chugging along now (and no media query flicker is heavenly) - but the extra `/` characters are causing the server/client mismatch error which sorta kills the whole SSR performance win.

**Comment by ianobermiller** [comment]
On which element is it complaining about the reactid? Can you provide a minimal repo as an example?

**Comment by isTravis** [comment]
Here's a repo: [https://github.com/isTravis/radium0.16.1SSRbug](https://github.com/isTravis/radium0.16.1SSRbug). To start it: 
```
npm install 
npm run dev
```

In `/src/helpers/Html.js` (which is imported and used by `src/server.js` and `src/client.js`) there are two possible return statements. One has `this.props.components` wrapped in `<StyleRoot>` tags and the other has it wrapped in `<div>` tags. The former caused a data-reactid mismatch, while the latter works with no warnings.

**Comment by Dindaleon** [comment]
@isTravis remove the `@Radium` connector from the Html helper file and the `/` will go away. 

My setup is very similar to yours, I am connecting my `App` component to Radium like this: `export default Radium(App);`

And this is what I am returning from App:

```
<StyleRoot radiumConfig={{ userAgent: userAgent }} >
    <Layout {...this.props} />
</StyleRoot>
```

The only thing I need to do now is passing the `request.headers['user-agent']` to my App component. I would appreciate if you could help me out with that.

**Dumb question:** Do we need to connect every component where we use radium or is it enough to connect our top component? I see the example connects every component where Radium is used.

**Comment by isTravis** [comment]
Thanks @Dindaleon. Removing the @Radium from `/src/helper/Html.js` doesn't make my `/` mismatch error go away. Did that get the sample repo running for you with no errors in the console using StyleRoot?

You **do** need to wrap every component in `Radium(Component)`. Not just the top most component. 

What does your server-side render file look like? Could you provide a simple repo? Instead of getting the userAgent into an action->reducer->connected prop, could you just pass it manually down the componentTree props until you eventually reach your App? 

Or - you don't need userAgent to be passed in with `<StyleRoot>` - you can pass it in higher if you like. In the repo I shared above - you can see that I'm passing it into <Html> in my server.js file - above Redux Router and all.

**Comment by ianobermiller** [comment]
Looks like it is something to do with the way React Router renders; if I move `StyleRoot` inside of `App`, the problem disappears.

**Comment by isTravis** [comment]
@ianobermiller Amazing! Yes! As soon as I move StyleRoot below React Router in the tree, everything is peachy. Thank you so much! Three months later - all SSR warning/errors are gone :smile: - weeee!

**Comment by Dindaleon** [comment]
@isTravis Please let me know how you would pass down the `userAgent` from the server down to the `App` component, I checked your demo but I am doing it in a different way. Once the `userAgent` data gets to my `Html` is already too late and there is no way to pass it to the `App` component because it already loaded up,  my repo: github.com/Dindaleon/hapi-react-starter-kit

@ianobermiller Is it possible to have a high order component for setting up the `userAgent` the same way `react-intl` and `react-redux` do? So we dont have to configure it in the inner components. (the `App` component in my case).

**Comment by ianobermiller** [comment]
Sure, you can pass `userAgent` to any component up in the stack decorated with `Radium`, as long as the components farther down pass along the `context`.

```jsx
@Radium
class RadiumConfig extends Component {
  render() { return this.props.children };
}

// Usage
<RadiumConfig radiumConfig={{userAgent: userAgent}}>
  // ... rest of app
</RadiumConfig>

**Comment by Dindaleon** [comment]
Thanks, however, I went a different way and set the `userAgent` in a Redux reducer. Everything is working good so far. I will report back if anything comes up.

**Comment by hawsome** [comment]
@ianobermiller, your example shows you passing `radiumConfig` as a `prop`, is there a way for Radium to accept it from the `context`?

**Comment by ianobermiller** [comment]
@hawsome the context key used is internal to Radium, so you have to use a Radium-enhanced component in order to set it.

**Comment by hawsome** [comment]
@ianobermiller I actually figured out how to pass it to all my children as `context` by using `StyleRoot`:
```javascript
import {StyleRoot} from 'radium'
...
<StyleRoot radiumConfig={this.props.radiumConfig}>
  {/* children go here */}
</StyleRoot>
```
