### ISSUE TITLE
Error while using StyleRoot in v0.16.1 with React Router

### ISSUE THREAD

**Issue by ads1018** [FormidableLabs/radium#500]
I've wrapped my top level component in StyleRoot and it works great! However, when transitioning to a new route (I'm using React Router) Radium throws this error:
`Cannot read property 'setState' of undefined`. 

It seems the function `_onChange()` on line 36 in `style-sheet.js` is scoped to the wrong `this`. Adding the following to the constructor fixes this bug:
`this._onChange = this._onChange.bind(this);` I submitted a pull request for this here #499. 

Fixing this does however introduce a warning when transitioning to a new route: `Warning: setState(...): Cannot update during an existing state transition (such as within `render`). Render methods should be a pure function of props and state.` Any ideas what's causing that?

**Comment by ianobermiller** [comment]
I guess `setState` is being called during render of something, because that is when Radium actually runs. Probably adding a setTimeout(..., 0) around the setState in StyleSheet would fix it.

**Comment by ads1018** [comment]
Thanks. I added this to the setState in StyleSheet:

    _onChange() {
      setTimeout(() => {
        this.setState(this._getCSSState());
      }, 0);
     }

It got rid of that warning but now I'm seeing a new warning:
`setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component.` Now sure what that's about.

**Comment by ianobermiller** [comment]
Ugh, yeah. You'll have to keep track of isMounted now;

```js
componentDidMount() { this._isMounted = true; }
componentWillUnmount() { this._isMounted = false; }
_onChange() {
  setTimeout(() => {
    this._isMounted && this.setState(this._getCSSState());
  }, 0);
 }

**Comment by ads1018** [comment]
Bingo. Thanks! I'll update my pull request with the above.

**Comment by ads1018** [comment]
Going to reopen this until the pull request is merged.

**Comment by almasakchabayev** [comment]
Can you guys bump the version up with this update
