### ISSUE TITLE
Hash of media query should also contain mediaQuery string itself

### ISSUE THREAD

**Issue by pristas-peter** [FormidableLabs/radium#502]
When mediaQuery hash is resolved in media-queries-plugin, only content of rule is hashed.

When you have different media queries that have same content and the first media query overrides the second (test rule has higher precedence), because of CSS cascade the wrong rule is sometimes applied, because css class has the same name, but the rules in stylesheet for mediaQueries are after the previous ones... 

This line should fix it in media-queries-plugin:

from:
const mediaQueryClassName = 'rmq-' + hash(ruleCSS);
to:
const mediaQueryClassName = 'rmq-' + hash(query + ruleCSS);

**Comment by ianobermiller** [comment]
Sorry, I'm not sure I understand. If the CSS rules are identical, why does it matter? I'm happy to include the query in the hash, it shouldn't break anything.

**Comment by pristas-peter** [comment]
<div>
    <div style={{
        @media and (min-width 2px): {
            height: 4
        }
        @media and (min-width 4px): {
            height: 2
        }
    }}/>
    <div style={{
        @media and (min-width 1px): {
            height: 2
        }
    }}/>
</div>


the second div element has media query which covers all queries of the first, since the classname in first element would be the same as the classname in second and it is the last classname in first element , the first media query in first element would never be applied because of the CSS stylesheet

hope the example makes it clearer

**Comment by coopy** [comment]
Fixed via https://github.com/FormidableLabs/radium/pull/503 and released in [`v0.16.2`](https://github.com/FormidableLabs/radium/releases/tag/v0.16.2)

**Comment by coopy** [comment]
Thanks for the report and PR, @pristas-peter! This was causing us issues today in `v0.16.1`.
