### ISSUE TITLE
AppVeyor build is failing

### ISSUE THREAD

**Issue by coopy** [FormidableLabs/radium#506]
The AppVeyor build has been failing since https://github.com/FormidableLabs/radium/commit/c4e8e8388c8732cd3638915c4981649cdf45ea53. 

First failing build: https://ci.appveyor.com/project/ryan-roemer/radium/build/1.0.617
Build history: https://ci.appveyor.com/project/ryan-roemer/radium/history

Let's fix it, and add a badge to the README.

**Comment by ianobermiller** [comment]
Looks like something to do with the prefixer on IE9.

**Comment by coopy** [comment]
This is a great ticket for somebody to pick up. It's causing false negatives for the `greenkeeper.io` PRs.
