### ISSUE TITLE
Selectors not working inside React-router's Link component

### ISSUE THREAD

**Issue by Dindaleon** [FormidableLabs/radium#509]
Hi there, I cannot get selectors such as `hover`, `focus`, `active` to work inside react-router's `Link` component.

Here is my code:

```javascript
import React, { Component, PropTypes } from 'react';
import radium from 'radium';
import { Link } from 'react-router';

const styles = {
  base: {
    fontSize: 16,
    backgroundColor: 'none',
    color: '#000',
    border: 'none',
    borderRadius: '0.3em',
    padding: '0.4em 1em',
    margin: '2px',
    outline: 'none',
    overflowX: 'auto',

    '@media (min-width: 992px)': {
      padding: '0.6em 1.2em'
    },

    '@media (min-width: 1200px)': {
      padding: '0.8em 1.5em'
    }
  },

  item: {
    margin: 0,
    border: 'none',
    padding: '0 24px',
    height: '48px',
    lineHeight: '48px',
    textDecoration: 'none',

    ':hover': {
      backgroundColor: '#2196F3'
    },

    ':focus': {
      border: '2px solid #2196F3',
      margin: '1px',
    },

    ':active': {
      border: '2px solid #2196F3',
      margin: '1px',
    }
  },

  accent: {
    backgroundColor: '#d90000',

    ':hover': {
      backgroundColor: '#FF0000'
    },
    ':focus': {
      backgroundColor: '#FF0000'
    },
    ':active': {
      backgroundColor: '#990000'
    }
  }
};

class TextField extends Component {
  render() {
    return (
      <div style={ styles.item }>
       {
        this.props.items.map( (menuItem, index) => {
          return <Link key={ `menu.item${ index }` } style={ styles.item } to={ '/' + menuItem.to }>{ menuItem.text }</Link>;
        })
      }
      </div>
    );
  }
}

TextField.propTypes = {
  children: PropTypes.any,
  color: PropTypes.string,
  items: PropTypes.array,
  onClick: PropTypes.func,
  style: PropTypes.string
};

export default radium(TextField);

```

**Comment by ianobermiller** [comment]
`Link` may not be designed to work this way. From [the FAQ](https://github.com/FormidableLabs/radium/tree/master/docs/faq#why-doesnt-radium-work-on-somecomponent):

>  In order for resolving style on a custom element to work, that element needs to actually pass that style prop to the DOM element underneath, in addition to **passing down all the event handlers** (onMouseEnter, etc). Since Radium has no control over the implementation of other components, resolving styles on them is **not safe**.

**Comment by Dindaleon** [comment]
Yes, I should have known this. Just fixed it.

**Comment by ianobermiller** [comment]
How did you fix it?

**Comment by Dindaleon** [comment]
@ianobermiller Not really a fix, I just removed the `Link` component and used html `a` tags with an `onClick` handler that controls the history state with the help of react-router's function `pushState`

I am implementing material design tabs for my app: https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0B3T7oTWa3HiFZWZ6dndJX09Zak0/components_tabs_tabtouchtarget.webm

radium is awesome! Keep it up.

**Comment by ianobermiller** [comment]
Looking at the source, `Link` does just pass all its props to the anchor tag: https://github.com/rackt/react-router/blob/master/modules/Link.js#L131

Can you create a simple example jsbin that shows the problem? It should work.

**Comment by Dindaleon** [comment]
This is how I was trying to do it:

```javascript
this.props.items.map( (menuItem, index) => {
  return <Link key={ `menu.item${ index }` } style={ styles.item } to={ '/' + menuItem.to }>{ menuItem.text }</Link>;
})
```

And this is how I am doing it now:

```javascript
this.props.items.map( (menuItem, index) => {
  return <a key={ `menu.item${ index }` } href={ menuItem.to } style={ [ this.getItemStyle(), this.state.selectedItem === menuItem.to && this.styles.selectedItem ] } data-to={ menuItem.to } onClick={ this.handleClick }>{ menuItem.text }</a>;
})
```

I did wrap the component with `radium` and `StyleRoot`

**Comment by ianobermiller** [comment]
Did you wrap `Link` directly with Radium? `Link = Radium(Link)`?

**Comment by Dindaleon** [comment]
I did not do that. Is that what I should have done?

I only wrapped the component where I placed `Link`

    export default radium(TextField);

**Comment by ianobermiller** [comment]
Yes, you must wrap `Link`. See the FAQ for more info: https://github.com/FormidableLabs/radium/tree/master/docs/faq#why-doesnt-radium-work-on-somecomponent

@coopy would be interested to know what you're using Radium for!

**Comment by Dindaleon** [comment]
Awesome thanks, I will try it soon, for now I will keep it the way I have it.

Sure @coopy, let me know if there is anything I can be of help for.

**Comment by Dindaleon** [comment]
@ianobermiller @coopy I just updated my starterkit and implemented a theming system powered by Radium, I hope you take a look at it. Themes can be switched on the fly. I am developing a light and a dark theme based on google's material design.

https://github.com/Dindaleon/hapi-react-starter-kit

**Comment by chrisdobler** [comment]
@ianobermiller - I tried wrapping the link like you mentioned, but it gives me an error.
