### ISSUE TITLE
Issue with well in example

### ISSUE THREAD

**Issue by pssdbt** [FormidableLabs/radium#51]
The example of a dynamic background color in computed-well.jsx appears to be broken. It looks like it's trying to pass a styles object in as the additionalModifiers parameter to buildStyles(), which doesn't work. A simple fix for me was removing buildComputedStyles() all together and instead just checking for this.state.dynamicBg and updating accordingly in getStyles(), but I'm not sure if that's a best practice.

**Comment by alexlande** [comment]
Thanks! The examples in this repo have not received the love they should have. Will take a look at this one.

For more robust examples, check out http://projects.formidablelabs.com/radium-bootstrap/. It has some cool things going on (particularly a nice `computed` implementation for the button themes).

**Comment by pssdbt** [comment]
Ah, this is much nicer! I figured the examples would get an update eventually, very cool. Thanks!
