### ISSUE TITLE
Add a way to define keyframe css animations

### ISSUE THREAD

**Issue by TimothyKrell** [FormidableLabs/radium#52]
It would be nice to be able to specify [keyframe animations](https://developer.mozilla.org/en-US/docs/Web/CSS/@keyframes) for an element in the component itself in javascript.

Thanks for this awesome library!

**Comment by alexlande** [comment]
Agreed! I seem to remember that @ianobermiller was working on something like this. Maybe it's something we could use in Radium?

**Comment by ianobermiller** [comment]
Yeah, pretty simple really: https://github.com/ianobermiller/nuclearmail/blob/master/src/js/CSSAnimation.js

Usage:

```
var pulseAnimation = new CSSAnimation({
  '0%':   {width: '10%'},
  '50%':  {width: '50%'},
  '100%': {width: '10%'},
});

// then use it later
{
  animation: pulseAnimation + ' 3s ease 0s infinite',
}

**Comment by alexlande** [comment]
Nice! Will spend a little time to figure out how best to integrate something along those lines. (As an aside, going to dig into NuclearMail more thoroughly, very interested to see how everything fits together.)

**Comment by benoneal** [comment]
+1 any progress on this?

**Comment by alexlande** [comment]
This is in and will ship with Radium 0.12.
