### ISSUE TITLE
Is it possible to add auto prefixing to the properties values?

### ISSUE THREAD

**Issue by Dindaleon** [FormidableLabs/radium#525]
Like this:

```
background: -webkit-linear-gradient(top,  #3f77a4, #8bb6d0, #6e80b8 70%, #26447c);
background: -moz-linear-gradient(top,  #3f77a4, #8bb6d0, #6e80b8 70%, #26447c);
background: -o-linear-gradient(top,  #3f77a4, #8bb6d0, #6e80b8 70%, #26447c);
background: -ms-linear-gradient(top,  #3f77a4, #8bb6d0, #6e80b8 70%, #26447c);
background: linear-gradient(top,  #3f77a4, #8bb6d0, #6e80b8 70%, #26447c);
```

**Comment by ianobermiller** [comment]
This should already be happening. Cc @rofrischmann

**Comment by rofrischmann** [comment]
@Dindaleon @ianobermiller Yep, it should add those prefixes depending on your userAgent. If you're testing within a browser that does not need prefixed linear-gradients, you will not see prefixes either :P

**Comment by Dindaleon** [comment]
I tested it on different browsers, one being Chrome v47.0.2526.111 m and the other safari 5.1.7 The prefix was not added in either.

I had to add it manually for the gradient to show up.

Then I thought that my radium setup was not working properly and tested it with other properties and it added the prefixes.

I see that there are some `linear-gradients` that need the prefix while others don't.

It would be interesting if somebody else could test it as well.

**Comment by rofrischmann** [comment]
I found the problem. Don't ask me why, but I only checked `background` and `backgroundImage` to include gradients. This must have been some negative information e.g. coming from w3schools.com. 
See ( https://github.com/rofrischmann/inline-style-prefixer/issues/54 )

It got fixed and will be released as soon as the transition plugin is ready as well.

**Comment by Dindaleon** [comment]
Awesome!
