### ISSUE TITLE
Enormous data-reactid: does radium generate any keys inside?

### ISSUE THREAD

**Issue by polkovnikov-ph** [FormidableLabs/radium#528]
I have a problem with Chrome Developer Tools showing Elements tab because of enormous `data-reactid`. I've just [asked](https://github.com/facebook/react/issues/5846) React devs for the possible reasons, and they report that this is related to long keys. Though my code doesn't use anything except small natural numbers for keys. There're only two libraries: in the project `radium` and `react`.

Does `radium` generate those keys (e.g. for `hover` elements)? How to counteract this issue? Do you have any plans on generating shorter keys?

**Comment by ianobermiller** [comment]
Radium itself does not generate any keys, but React.Children.map might.
react-id will be removed in a future version, hopefully not long from now.

**Comment by polkovnikov-ph** [comment]
I've already upgraded to 0.15, and performance problems went away.

Could you also comment on [another issue](https://github.com/FormidableLabs/radium/issues/527), please, so I could help with further investigation? That's still a blocker for me.
