### ISSUE TITLE
Testing broken while using StyleRoot in v0.16

### ISSUE THREAD

**Issue by LeoAJ** [FormidableLabs/radium#529]
Try to update to version 0.16

I used `StyleRoot` to wrap the entire app in the top component and it works fine, but the testing was broken because the testing used shallow render in `TestUtils` module to render each single component one by one, in that way the child component did not wrap with `StyleRoot`, so the test was broken. Any way to solve this problem? Thanks!

Attached the error message;

<img width="1439" alt="screen shot 2016-01-13 at 12 54 08 pm" src="https://cloud.githubusercontent.com/assets/492921/12307913/1c3bf916-b9f7-11e5-998c-a5d6d2f94b29.png">

**Comment by ianobermiller** [comment]
Currently you cannot render a component requiring `StyleRoot` on its own. We could perhaps have a test mode or some other simple method that just ignores this error for testing.

**Comment by mairh** [comment]
I had the same problem with my teets but I eneded up wrapping `StyleRoot` component on my tests too. the following example is just a basic test
```
import React from "react";
import should from "should";
import TestUtils from "react-addons-test-utils";
import {injectTheme} from "../../lib/ContextUtils";
import Landing from "site/components/Landing";
import I18n from "shared/components/I18n";
import RadiumWrapper from "shared/components/RadiumWrapper";

describe("Landing", () => {
    let LandingComponent;
    let LandingWithContext;

    before(() => {
        LandingWithContext = injectTheme(Landing);
    });

    beforeEach(() => {
        LandingComponent = TestUtils.renderIntoDocument(
            <RadiumWrapper><LandingWithContext /></RadiumWrapper>
        );
    });

    it("should create a new instance of Landing", () => {
        should.exist(LandingComponent);
    });

    it("should display content in English by default", () => {
        const components = TestUtils.scryRenderedComponentsWithType(LandingComponent, I18n);
        should(components[0].state.locale).be.eql("en_US");
    });
});
```

and `RadiumWrapper` consist the `StyleRoot` component

```
import React from "react";
import {StyleRoot} from "radium";

class RadiumWrapper extends React.Component {
    render() {
        return (
            <StyleRoot>
                {this.props.children}
            </StyleRoot>
        );
    }
}

export default RadiumWrapper;
```

**Comment by doctyper** [comment]
I'm also running into this issue. Our project has dozens of tests, so adding a wrapper for each test is not really an option.

Would you consider demoting the error to a warning?

**Comment by ianobermiller** [comment]
It truly is an error, so making it a warning will be worse for usability. We can look more earnestly into a test mode, instead. A global flag on `Radium` should be fine, e.g. `Radium.enableTestMode()`.
