### ISSUE TITLE
Ability to customize selector for media queries

### ISSUE THREAD

**Issue by natew** [FormidableLabs/radium#538]
Hey guys, just got up onto Radium 0.16.

Looking at the new media query stuff it looks nice, though I need a way to customize the selector that's output.

I see this:

```js
@media (max-width: 850px) .rmq-7fb329ee { ... }
```

What I'd ideally want is a way to customize that to:

```js
@media (max-width: 850px) #myapp tagName.rmq-7fb329ee { ... }
```

To work well with my other styles. Going to explore this and perhaps open PR, just wanted to open here to track it.

**Comment by natew** [comment]
Actually, noticed the !important flags being added. That works for me.

**Comment by ianobermiller** [comment]
Yup, the only way to override inline styles is using `!important`.

**Comment by natew** [comment]
Actually I was overriding CSS styles in that case so it would work I think, but the !important does the trick anyway.
