### ISSUE TITLE
Don't add className prop if empty

### ISSUE THREAD

**Issue by epsitec** [FormidableLabs/radium#539]
I've noticed that the static markup produced by calling `ReactDOMServer.renderToStaticMarkup()` with a radium enabled component changed from this:

```html
<div style="x:0;font:Roboto, sans-serif;y:2px;">Hello</div>
```

to this:

```html
<div style="x:0;font:Roboto, sans-serif;y:2px;" class=" ">Hello</div>
```

Is there any valid reason for adding an empy `class=" "` attribute on the `<div>`?

**Comment by epsitec** [comment]
If you want to have a look at failing tests, you can check out this playground project:
https://github.com/epsitec-sa/react-usage/commit/5b8eebcd473778ebb58477445f02fb1913182409

There are three failing tests which worked with 0.15.3 and now fail because of the addition of `class=" "` in the generated HTML output.

**Comment by williamboman** [comment]
To piggyback on this issue, I'm having problems with Radium not `.toString()`-ing style property values. From `0.15.3` to `0.16.2` as well.

**Comment by ianobermiller** [comment]
> Is there any valid reason for adding an empty `class=" "` attribute on the `<div>`?

Nope, no good reason at all. Should be avoidable.

> I'm having problems with Radium not .toString()-ing style property values

@williamboman may you please open a new issue, preferably with a JSBin repro?

**Comment by williamboman** [comment]
> @williamboman may you please open a new issue, preferably with a JSBin repro?

#549
