### ISSUE TITLE
Hover does not work with react-bootstrap

### ISSUE THREAD

**Issue by hgezim** [FormidableLabs/radium#545]
I checked out your example for hover and replaced `button` with `react-bootstrap`'s button and hover state never returns true:

```jsx
var BB = require("react-bootstrap").Button;

var {Style, StyleRoot, PrintStyleSheet} = Radium;

//
// Radium with ES6 class syntax
//
class HoverMessage extends React.Component {
  render() {
    return (
      <div>
        <BB key="button" style={{display: 'flex', ':hover': {}}}>Hover me!</BB>
        {Radium.getState(this.state, 'button', ':hover') ? (
          <span>{' '}Hovering!</span>
        ) : null}
      </div>
    )
  }
}
HoverMessage = Radium(HoverMessage);
```

**Comment by ianobermiller** [comment]
https://github.com/FormidableLabs/radium/blob/master/docs/faq/README.md#why-doesnt-radium-work-on-react-routers-link-or-react-bootstraps-button-or-someothercomponent

**Comment by hgezim** [comment]
Thanks a bunch!

Thanks,
-Gezim

Gezim Hoxha
Entrepreneur
780.802.4837(C)

**Comment by ianobermiller** [comment]
:+1:

**Comment by hgezim** [comment]
It seems that even with the solution proposed in #324, `getState` still doesn't work. Any ideas, @ianobermiller?

**Comment by ianobermiller** [comment]
@hgezim  Most likely react-bootstrap's button is not passing through all of the props to actual dom element. You could test this by manually passing onMouseEnter and seeing if it is fired.
