### ISSUE TITLE
Autoprefix for all user agent

### ISSUE THREAD

**Issue by oliviertassinari** [FormidableLabs/radium#546]
I'm working on the server-side rendering, my `renderToString()` is taking too much time (100 ms +).
So I have added some memoization. This memoization is taking the `user-agent` as a parameter.

Is it possible making radium apply the prefixes for a large number of browsers?
I would be able to remove the `user-agent` as a parameter of the memoization. This would increase my `index.html` size, but reduce the memory usage of my server. That's a trade-off I'm willing to take.

**Comment by ianobermiller** [comment]
Yes, this is possible, as `inline-style-prefixer` does support it. `inline-style-prefixer` added a special API for this, `prefixAll`, and Radium could call that API if, say, you pass `all` as the `userAgent`.

**Comment by oliviertassinari** [comment]
Alright, so I'm not mistaking, that's something that's currently not supported by radium but you would accept a pull request to address it. I also have to address it at the `material-ui` level.
I will probably submit a PR.

**Comment by ianobermiller** [comment]
Yes, I'd take a PR for this.

**Comment by doctyper** [comment]
@oliviertassinari have you seen [radium-plugin-prefix-all](https://github.com/rofrischmann/radium-plugin-prefix-all)? This is what I use to solve this use-case.

**Comment by oliviertassinari** [comment]
> The plugin, while nice for basic cases, is not quite ideal, because the prefixer isn't fully pluggable. It is used directly by keyframes, style, and media queries, so none of those would be affected by swapping the plugin.
