### ISSUE TITLE
Radium fails to invoke toString() properly ([object Object])

### ISSUE THREAD

**Issue by williamboman** [FormidableLabs/radium#549]
This only happens when wrapping with `StyleRoot`, i.e. `>=0.16`. edit: seems like it works fine on `0.16.3`, which isn't public yet?

[JS Bin repro](https://jsbin.com/kozogomowa/1/edit?html,js,output)

**Comment by ianobermiller** [comment]
`0.16.3` was just a test publish, I forgot to add `-test`.

This is already fixed in master, by ff9c565346e93cead6de3fcd4c8c3b2245241634.

**Comment by williamboman** [comment]
> 0.16.3 was just a test publish, I forgot to add -test.
> 
> This is already fixed in master, by ff9c565.

:+1:. Would you recommend using `0.16.3` for now, or wait for a proper release?
