### ISSUE TITLE
StyleRoot breaks server-side rendering

### ISSUE THREAD

**Issue by NgoKnows** [FormidableLabs/radium#551]
So currently I am rendering on the server side like this:

```javascript
<StyleRoot radiumConfig={radiumConfig}>
    <RouterContext {...renderProps} />
</StyleRoot>
```

and on the client side:

```javascript
<StyleRoot>
    <Router history={browserHistory}>
        {Routes}
    </Router>
</StyleRoot>
```

and Routes looks like this: 

```javascript
    <Route path='/' component={Sample}>
        <Route path="a" component={A} />
        <Route path="b" component={B}/>
    </Route>
```

I get this error :
Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) id=".26uipr1xq80.0.$/=10">sample text</div><styl
 (server) id=".26uipr1xq80.0.$=10">sample text</div><style

I have found that if I removed the StyleRoot, from both the client and server-side rendering, that the error disappears, and I have no idea why this is happening.

I've figured out that this only happens when there are multiple routes, when there is only one route, there is no error such as:
```javascript
    <Route path='/' component={Sample}>
        <Route path="a" component={A} />
    </Route>
```

but when there are multiple routes like I had before, there is an error.

**Comment by ianobermiller** [comment]
See workaround in #496, this was a bug I fixed in React. More discussion in #544.

**Comment by NgoKnows** [comment]
Awesome, thanks for the response!

**Comment by ianobermiller** [comment]
No problem, let me know if that doesn't work for you.
