### ISSUE TITLE
Align code standards with those in Victory (defaults/configurations/walmart/es6-react)

### ISSUE THREAD

**Issue by tptee** [FormidableLabs/radium#554]
Victory uses `defaults/configurations/walmart/es6-react` and we'd like this to become out canonical style for future repos, including the component library under the `radium` umbrella. As Radium becomes an aggregator, this would be a good time to convert `radium-style` to match the new ESLint configuration.

**Comment by tptee** [comment]
In https://github.com/FormidableLabs/builder-victory-component/tree/master/config/eslint, there are extra config files for test and coverage that expose some globals to ESLint. It would help to split the `npm run-script lint` script into separate ones targeted for production, test, coverage, etc. Check out the `package.json` of https://github.com/FormidableLabs/builder-victory-component for an example (uses Builder).

**Comment by kylecesmat** [comment]
Closing in favor of https://github.com/FormidableLabs/radium/issues/969
