### ISSUE TITLE
Unable to combine multiple pseudo element selectors in a single declaration in the Style Component

### ISSUE THREAD

**Issue by thefivetoes** [FormidableLabs/radium#562]
## Current Behavior
Combining multiple pseudo element (placeholder) selectors as a single key within the Style Component results in the selector being ignored.

For example: 
```js
'::-webkit-input-placeholder, :-moz-placeholder, ::-moz-placeholder, :-ms-input-placeholder': {
  color: 'red',
  lineHeight: 1
}
```

Results in the following: 
![screen shot 2016-01-26 at 5 55 29 pm](https://cloud.githubusercontent.com/assets/2514127/12598259/1f4d638c-c457-11e5-985a-0ad45ba9228b.png)

## Expected Behavior
The placeholder text should be red:
![screen shot 2016-01-26 at 5 55 14 pm](https://cloud.githubusercontent.com/assets/2514127/12598273/3699c9fe-c457-11e5-8326-530ca36bf0a3.png)

[The docs for the Style Component](https://github.com/FormidableLabs/radium/tree/master/docs/api#style-component) illustrate that some selectors can be grouped: `'h1, h2, h3': {`, but to achieve the result above, the selectors need to be broken out individually:

```js
'::-webkit-input-placeholder': {
  ...defaultPlaceholderStyles
},

':-moz-placeholder': {
...defaultPlaceholderStyles
},

'::-moz-placeholder': {
...defaultPlaceholderStyles
},

':-ms-input-placeholder': {
...defaultPlaceholderStyles
}
```

**Comment by alexlande** [comment]
You would have the same problem writing normal CSS: http://jsbin.com/xucalox/edit?html,css,output

It's inconvenient, but I don't know if it should be the `Style` component's responsibility to check for these cases (or even if we reliably could, as it's possible with any pseudo-selectors that aren't supported everywhere).

**Comment by thefivetoes** [comment]
Ah seems like a valid argument. Feel free to close this as you see fit.
Thanks

**Comment by alexlande** [comment]
Cool, going to close this one out. Thanks!
