### ISSUE TITLE
getState() not working with Redux

### ISSUE THREAD

**Issue by leopoldjoy** [FormidableLabs/radium#588]
Hello,

I am trying to use Radium's getState() functionality in my Redux application. Here's what my code looks like:

    import React, {Component, PropTypes} from 'react';
    import {connect} from 'react-redux';
    import { pushState } from 'redux-router';
    
    import Radium from 'radium';
    
    @connect(
      state => ({ radiumConfig: { userAgent: state.browser.userAgent}, radiumState: state.browser}),
      {pushState})
    @Radium
    export default
    class MyComponent extends Component {
      static propTypes = {
        radiumState: PropTypes.object
      }
      render() {
        const {radiumState} = this.props;
        return (
          <div>
            <div style={[{color: 'black'},
              (Radium.getState(radiumState, 'inputKey', ':focus')) ?
                {backgroundColor: 'red'} : {backgroundColor: 'green'}
              ]}>
              Title
            </div>
            <input type="text" key="inputKey" ref="title" placeholder="This is already here..." />
          </div>
        );
      }
    }

I know that I am not doing this correctly with `radiumState`, since `radiumState` is one of the reducers inside my multi-reducer. I feel like getState() wants direct access to the state object, but I feel like that violates the Redux design-pattern. I can't quite figure it out...

**Comment by bORm** [comment]
```
import React, {Component, PropTypes} from 'react';
import {connect} from 'react-redux';
import { pushState } from 'redux-router';

import Radium from 'radium';

@Radium
export default
class MyComponent extends Component {
  render() {
    var radiumState = {inputKey: {':focus': {}}};
    return (
      <div>
        <div style={[{color: 'black'},
          (Radium.getState(this.state, 'inputKey', ':focus')) ?
            {backgroundColor: 'red'} : {backgroundColor: 'green'}
          ]}>
          Title
        </div>
        <input type="text" key="inputKey" ref="title" placeholder="This is already here..." style={radiumState.inputKey} />
      </div>
    );
  }
}
```

**Comment by leopoldjoy** [comment]
@bORm Thank you! That helped clear things up for me.
