### ISSUE TITLE
Style Objects as Model Injects

### ISSUE THREAD

**Issue by zoomclub** [FormidableLabs/radium#59]
Style Objects look like simple JSON documents. This means that there must be a way to define and store them outside a components render function then fetch and inject them, right? 

This way a component could use whatever exchangeable Style Object (JSON document) might be activated. So, if Firebase is used a Firebase ref in the component could be set to a given Style Object.

Love Radium just hope the inject approach works so I do not need to hardwire styles directly into a component. Having injectable Style Objects and good performance that does not re-render styles if not needed would be fantastic!

**Comment by colinmegill** [comment]
They are javascript - not JSON.

padding: isMobile() ? "10px" : "20px",
ᐧ

**Comment by alexlande** [comment]
That is an important distinction. That said&mdash; Style objects are just JS objects that Radium parses based on your component's props, state, and context. You could very easily define them outside of components or share them between multiple components.

```js
var externalStyleObject = require('../my-external-style-object-foo.js');

var CoolComponent = React.createClass({
  mixins: [ StyleResolverMixin ],

  render: function () {
    return (
      <div style={this.buildStyles(externalStyleObject)}>
        {this.props.children}
      </div>
    )
  }
});
```

**Comment by zoomclub** [comment]
Super, thanks for the clarification and confirmation.

**Comment by alexlande** [comment]
No problem! Thanks for checking Radium out, let us know if you have any more questions as you go,
