### ISSUE TITLE
A guide to compare Radium and SASS

### ISSUE THREAD

**Issue by PrimeObjects** [FormidableLabs/radium#592]
Hello, 

Can Radium do basic features supported by SASS today (http://sass-lang.com/guide)? If yes, do you have a quick doc to explain how to? 

e.g.

SASS - variable 
$bgcolor: #333;
body {
  background-color: $bgcolor;
}

Radium - ES6
this.bgColor = "#333";
this.bodyStyle = {backgroundColor: this.bgColor}

Thanks
Gary

**Comment by ianobermiller** [comment]
Radium is inline styles, so everything is just JavaScript. You can have a
module, for instance, that exports all of the colors you use in your app.
You can then import/require that module, and use the colors:

```js
var Colors = require('./my-app-colors');

var styles = {
  someComponent: {
    backgroundColor: Colors.offWhite,
    color: Colors.accent,
  }
};

On Tue, Feb 16, 2016 at 9:37 AM Gary Zhang <notifications@github.com> wrote:

> Hello,
>
> Can Radium do basic features supported by SASS today (
> http://sass-lang.com/guide)? If yes, do you have a quick doc to explain
> how to?
>
> e.g.
>
> SASS - variable
> $bgcolor: #333 <https://github.com/FormidableLabs/radium/issues/333>;
> body {
> background-color: $bgcolor;
> }
>
> Radium - ES6
> this.bgColor = "#333 <https://github.com/FormidableLabs/radium/issues/333>
> ";
> this.bodyStyle = {backgroundColor: this.bgColor}
>
> Thanks
> Gary
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FormidableLabs/radium/issues/592>.
>

**Comment by ianobermiller** [comment]
Radium is inline styles, so everything is just JavaScript. You can have a module, for instance, that exports all of the colors you use in your app. You can then import/require that module, and use the colors:

```js
var Colors = require('./my-app-colors');

var styles = {
  someComponent: {
    backgroundColor: Colors.offWhite,
    color: Colors.accent,
  }
};
```

**Comment by PrimeObjects** [comment]
Hi Ian,
I understand, I have already started using Radium. I just feel that if we define a class or object for a web project that is using Radium and just for style. Then it should be able to replace SASS and should be more powerful.

**Comment by ianobermiller** [comment]
Sorry, I'm not really sure what you're asking for. You can do everything (and so much more) that SASS can do when you are just using JavaScript.

**Comment by PrimeObjects** [comment]
Yes, I'm thinking it will be helpful to write a guide for all SASS developers so they understand how they can do the same by using Radium. It will help more people acquire Radium.

In the future, people will not develop a master SASS file, instead they develop a master Radium class. When developer need any styles, they can use mixin or props to consume the styles defined in the master Radium class.
