### ISSUE TITLE
Style Objects for other targets

### ISSUE THREAD

**Issue by zoomclub** [FormidableLabs/radium#60]
Style Objects seem close to a design pattern I found many things in my app segmenting into, so I quite like the concept. React does not just target the DOM, it is also targeting iOS and Android via React Native. I assume Radium is meant to work with these targets as well?

In addition, I am interested in targeting the 2D Canvas element. In my flow of model data to a view component I'd hope to render some data to the DOM and most of it to a 2D Canvas via a custom filter function. To route to a Canvas element I match IDs on specific datums and fetch glyphs from a OTF or TTF font. Then I'd like to style those glyphs JIT before rendering them to the Canvas.

Would there be any issue with using the Style Object in such a way? Can the Style Object be extended with new style categories?

**Comment by alexlande** [comment]
Interesting! As a very broad goal-- yes, we would really like to support environments like React Native. I'm hopeful that we'll be able to do that.

Regarding this specific use case-- I don't see a reason you couldn't use style objects for this purpose, no. For normal Radium usage style objects include CSS rules that are applied to the element's `style` attribute, but you could in principal use Radium to resolve any set of data based on the concepts of modifiers, states, media queries, etc.

Could you give me an example of what you mean by new style categories? I would expect that you could assign modifiers to fit whatever use case you need if standard modifiers + states don't cover it: https://github.com/FormidableLabs/radium/blob/master/docs/guides/overview.md#assigning-modifiers

**Comment by zoomclub** [comment]
I was thinking that having the option of defining new style categories might help with creating the Style Objects I require. My own 'style objects' are plain JSON documents and follow a specific tree structure that is suited for their purpose. I will have to see yet how that matches the existing Style Object categories.

In the getStyles function the return value is a tree structure that looks like plain JSON. The mixins then include functions to resolve each category of styles in a given Style Object. This reveals several possible enhancements:

1) It would be good to allow the tree structure in the return value to be injected into the getStyle function as an argument. This would make it possible to inject exchangeable tree structures that would be returned.  The exchangeable tree structures can then just be plain JSON documents fetched from a store like Firebase or some other store.

2) This could then also be opened up so that if the tree structure has its own categories then a handler function for custom categories can be added to the resolving mixin.

3) The resolver mixin produces a CSS string to apply to DOM elements. For use with a Canvas element there would be no need for CSS, rather given values of a State Object would be computed, based on a JIT response to the model data being processed. 

Let me explain this further:

In my scenario I have another JSON document in memory as state, this document defines the complete structure of data I want rendered to a Canvas or the DOM. The target view component is layered so there are Canvas and DOM layers. This document would then be parsed and rendered as its structure is stepped through.

On each step the parsing would be processing a unique section of the document structure. The step would determine the type of data it is processing and at this point compute values in a Style Object. This computation would then also involve fetching the right font glyph to render. So, the computation would be a combination of doing layout and glyph fetching based on the datums encountered in a given step.

Putting it all together there is: a JSON document that is the source of the datums being stepped through (this is state that is edited by tools), a activated Style Object that defines how the datums should layout and be decorated by the right glyphs, a font that supplies the glyphs. 

The total flow is then an assembly line that converts pure datums into a graphic representation in the view. If a different Style object or font is activated then the datums of a given source document render differently. This flow is the best way to handle the many representation variations in my particular domain.

I'm thinking Radium might just work for this extended rendering scenario?

**Comment by alexlande** [comment]
@zoomclub: Yes, based on your description, I think Radium should be able to handle that scenario as is (although you would need to modify your object structure to fit into `modifiers`, for this case).

> The resolver mixin produces a CSS string to apply to DOM elements. For use with a Canvas element there would be no need for CSS, rather given values of a State Object would be computed, based on a JIT response to the model data being processed.

Radium doesn't produce a CSS string, it just returns a resolved style object. The styles don't become CSS until they're applied to a component's `style` attribute. This should be a good thing for your use case, as you won't be dealing with CSS and won't need to apply the resolved style object with the `style` attribute.

**Comment by zoomclub** [comment]
Great! Any chance of allowing for injectable JSON values into the getStyles function? Is the required JS file in the snippet below just the JSON portion of the getStyles function? It would be great if the JSON and JS aspect were separate, so the JSON can be swapped independently and easily edited from the UI.

var externalStyleObject = require('../my-external-style-object-foo.js');

**Comment by alexlande** [comment]
Definitely! `my-external-style-object-foo.js` in that example is just a reference to a standalone Style Object in an external file. You could get some JSON and parse it to get your style object easily.

**Comment by zoomclub** [comment]
Maybe things have not always been so smooth as they now are with React and Radium. So, just to be sure your saying that I can inject the following into the getStyles return or a styles var from my store? If so, then I'm very joyous :)

      padding: '1.5em 2em',
      border: 0,
      borderRadius: 4,
      color: '#fff',
      cursor: 'pointer',
      fontSize: 16,
      fontWeight: 700,

      states: [
        { hover: {
          background: color('#0074d9').lighten(0.2).hexString()
        }},
        { focus: {
          boxShadow: '0 0 0 3px #eee, 0 0 0 6px #0074D9',
          outline: 'none'
        }}
      ],

      modifiers: [
        { kind: {
          primary: { background: '#0074D9' },
          warning: { background: '#FF4136' }
        }}
      ]

**Comment by alexlande** [comment]
Yep! It's just a plain JS object, so you could store that wherever you want. Load it as JSON with Ajax, or from Firebase, or as a separate module that you import in.
