### ISSUE TITLE
Builds without client side vendor prefixing

### ISSUE THREAD

**Issue by alexlande** [FormidableLabs/radium#605]
Something that I've been thinking a little bit about lately is providing better support for Radium builds without client side vendor prefixing. For some cases, the page weight and performance hit from client-side prefixing through `inline-style-prefixer` outweighs the benefits. This is particularly true for projects like https://github.com/FormidableLabs/victory, which is fairly large and is working on improving rendering performance.

Right now, it's obviously possible to opt out of inline-style-prefixer, and in theory it should be possible to handle prefixing as a build step through a Babel plugin like https://github.com/UXtemple/babel-plugin-react-autoprefix (or manually).

I think it would be nice to better surface this option, either by documenting it or by providing a second preset plugin configuration in addition to the default one. As part of this, we should test the previously mentioned babel plugin with Radium and contribute to it/fork it/make our own depending on the results of that test.

**Comment by divmain** [comment]
_Note to self/@alexlande:_ looks like `babe-plugin-react-autoprefix` will not be a good fit - it'll only work if the styles are passed as an object-literal to the `style` prop, ala `<Component style={{ color: "red" }}>`.  I'll look into more robust options.

**Comment by rofrischmann** [comment]
You might also consider providing an alternative prefixer plugin that uses [inline-style-prefix-all](https://github.com/rofrischmann/inline-style-prefix-all) which was extracted from inline-style-prefixer and optimized. It adds all static prefixes (so no userAgent evaluation etc.) and only has 3.3kb gzipped.
It still affects runtime performance, but might be a good alternative according bundle size.

**Comment by alexlande** [comment]
That's a really good point, thanks @rofrischmann. I'm wondering-- what's the benefit of `inline-style-prefixer` over `inline-style-prefix-all`? That seems like it would be a sensible default.

**Comment by rofrischmann** [comment]
@alexlande Basically dynamic prefixer (inline-style-prefixer) is kind of more "intelligent" as it only adds prefixes if they're actually needed within the current environment. So there're less styles to interpret (which is guess is not a big deal for modern browsers), but also less markup which is especially useful for server-side rendering.
*e.g. `display:flex` will be transformed to either `-webkit-flex`, `-ms-flexbox`, `-webkit-box`, `-moz-box` or just stay `flex` while the static version (-prefix-all) produces `display: -webkit-box;display:-ms-flexbox;display:-moz-box;display:-webkit-flex;display:flex`.

I would recommend using the dynamic prefixer for server-side rendering and if the file size actually is not a problem (let the user decide), but perhaps use the static version for production builds and as default on npm as well.

**Comment by alexlande** [comment]
Got it. Makes sense to me to default to prefix-all and let people opt into the full prefixer. As far as server-side renders go, I've got to think that the extra page weight from including prefixes would be fairly low once gzipped, with a side benefit of providing better support before JS kicks in and the correct prefix was applied. Of course, that would only work if React supported fallback properties. Since it doesn't, the extra page weight wouldn't have any benefit.

**Comment by ssudoku** [comment]
"Right now, it's obviously possible to opt out of inline-style-prefixer"
@alexlande 
Could you guide me on how I can do this? I want to disable auto-prefixing on certain components while letting other components do it. I couldn't find the right information in the docs.

**Comment by alexlande** [comment]
@ssudoku: Afraid I misspoke on this one-- it's not currently possible to opt out of inline-style-prefixer, and definitely isn't on a component-by-component basis.

**Comment by alexlande** [comment]
Planning to switch to inline-style-prefixer v3 and use the static prefixer (https://github.com/FormidableLabs/radium/issues/918).
