### ISSUE TITLE
Element style state not saved in original(grand?) parent when direct parent is wrapped in Radium

### ISSUE THREAD

**Issue by masad-frost** [FormidableLabs/radium#618]
I'm pretty bad with words, so I'll use the simple example ([JSBin](https://jsbin.com/miqifuboba/edit?js,output)) below as a reference.

My expected behavior, hovering over the words 'radiumized child' and 'normal child' make 'YOU HOVERED!!!' show. What actually happens is that it only shows when you hover over normal.

My conclusion is that the style state of the `<span ...>radiumized child<span>` is not saved in the `Main` component instead, it gets saved in the component it's passed to as a child. I don't know if this is intentional behavior, but it's certainly weird, why does radium take control of children like that?

``` javascript
const React = require('react');
const Radium = require('radium');

class NormalComponent extends React.Component {
  render() {
    return (
      <div>
        {this.props.children}
      </div>
    )
  }
}

const RadiumizedComponent = Radium(NormalComponent);

@Radium
class Main extends React.Component {
  render() {
    const hoverStyle = { ':hover': {color: 'blue'} }
    const didHover = Radium.getState(this.state, 'raduimizedChild', ':hover') ||
                     Radium.getState(this.state, 'normalChild', ':hover')
    return (
      <div>
        <RadiumizedComponent>
          <span key="radiumizedChild" style={hoverStyle}>
            radiumized child
          </span>
        </RadiumizedComponent>
        <NormalComponent>
          <span key="normalChild" style={hoverStyle}>
            normal child
          </span>
        </NormalComponent>
        {didHover && <div>YOU HOVERED!!!</div>}
      </div>
    );
  }
}
```

**Comment by masad-frost** [comment]
Just to clarify, this is an issue because [this workaround](https://github.com/FormidableLabs/radium/tree/master/docs/faq#why-doesnt-radium-work-on-react-routers-link-or-react-bootstraps-button-or-someothercomponent) mentioned in the FAQ falls short

**Comment by alexlande** [comment]
You're right, it's odd that the state is passed down to `RadiumizedComponent` when you're applying styles to children of that component.

Separately, your code sample has a typo: `raduimizedChild`. (It's still broken with the typo fixed, to be clear, just wanted to rule out that the typo was causing the problem.)
