### ISSUE TITLE
SVG's stroke-miterlimit value is being co-erced to pixels

### ISSUE THREAD

**Issue by kumarharsh** [FormidableLabs/radium#620]
Hi, while setting styles to an SVG element, I go this error, when if I'm specifying the `strokeMiterlimit` as either `0` or `'0'`, Radium is converting it to `0px`, which is invalid.

**Comment by ianobermiller** [comment]
This may be `inline-style-prefixer`; Radium only adds `px` to non-whitelisted non-zero numbers: https://github.com/FormidableLabs/radium/blob/cc89d153ebcb416233e6c1698d56874107682aa6/src/append-px-if-needed.js#L43-L46

cc @rofrischmann please correct me if I'm wrong :)

**Comment by rofrischmann** [comment]
inline-style-prefixer does not transform any values (except of prefixing some). That's actually a problem with React as they do not list it as a unitless value right now: 
https://github.com/facebook/react/blob/20e1acb7dddcb811f8ea436ef95df5258e33c639/src/renderers/dom/shared/CSSProperty.js#L43

**Comment by ianobermiller** [comment]
Thanks @rofrischmann, that was my suspicion as well after looking at that code. FWIW, React 15 warns on number strings like `'0'` and will not longer prefix them in 16.

**Comment by rofrischmann** [comment]
@kumarharsh FYI: I already did a PR to React once to add new unitless properties, I am about to push ~10 more I found out are missing soon. `strokeMiterlimit` is one of those. I guess they might even land within 15 (as the other PR also got merged immediately)
