### ISSUE TITLE
Consider removing decorator syntax from docs

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/radium#622]
Since it is not supported in babel 6, maybe decorator syntax should be removed from the docs, or at least not presented as the blessed approach.

**Comment by tptee** [comment]
I'd second this, especially since Babel 6 respects that the decorator proposal has changed.

**Comment by ianobermiller** [comment]
Fine with me; the only annoying part is that if you use class syntax, you need to either export the wrapped object directly or rebind it to a different name:

```js
class Button extends Component { }
const RadiumButton = Radium(Button);
// or
module.exports = Radium(Button);
export default Radium(Button);

**Comment by masad-frost** [comment]
I'm not familiar with the decorators proposal, do the changes affect Radium at all?

Dropping [this plugin](https://www.npmjs.com/package/babel-plugin-transform-decorators-legacy) here for people who want to continue using decorators with Babel 6. Decorators are really convenient.

@ianobermiller In addition to being unable to reference components before they're evaluated. I'm a fan of this style:
```js
class App extends Component {
...
   <Button />
...
}

@Radium
class Button extends Component { ... }
```

**Comment by alexlande** [comment]
I knew this ticket was around here somewhere 🤕 . Closing in favor of #924
