### ISSUE TITLE
Breaks react-transform-hmr w/babel6 and webpack hot module replacement plugin

### ISSUE THREAD

**Issue by gigavinyl** [FormidableLabs/radium#624]
For some reason, any component that uses radium will not hot reload but other components will work just fine. I've tried @gaearon 's solution in #219 of exporting with:
```js
module.exports = Radium(App);
module.exports.App = App;
```
to no avail (I supsect this is because the aforementioned issue relates to the react-hot-reloader module while I'm using react-transform-hmr with the babel-preset-react-hmre).

**Comment by ianobermiller** [comment]
AFAIK this is not specific to Radium: https://medium.com/@dan_abramov/hot-reloading-in-react-1140438583bf. Feel free to comment for a reopen if there is something actionable on our part.

**Comment by gaearon** [comment]
Actually I don’t think there should be any problem here. In my article I talk about problems with higher order components, but Radium seems to *inherit* the current component. Additionally, Radium doesn’t take any “config” object to `Radium` call so it doesn’t matter that Babel plugin doesn’t see your Radium class, because it sees the inner class just fine.

I just checked and hot reloading both `render()` function and style definitions works fine for me with Radium and `react-transform-hmre`. Can you provide an example reproducing the issue?

**Comment by gaearon** [comment]
I amended the article to mention React JSS instead of Radium because that’s the one that I think has problems with `react-transform-hmre`. Radium looks fine in my testing.

**Comment by gigavinyl** [comment]
@gaearon This is probably caused by n00biness on my part (I'm still quite new to react) but the component I want to have radium support is:
```jsx
// shared/components/Button.jsx
import React, { Component, PropTypes } from 'react';
import Radium from 'radium';
import color from 'color';
import colorVars from '../colors';

class Button extends Component {
  render() {
    return (
      <button className="button" style={styles[this.props.kind]} onClick={this.props.onClick}>{this.props.children}</button>
  );}
}

const styles = {
  primary: {
    color: '#FFF',
    background: colorVars.primary,
    ':hover': {
      background: color(colorVars.primary).lighten(0.2).hexString(),
    },
  },
  secondary: {
    color: '#555',
    borderColor: colorVars.secondary,
    ':hover': {
      borderColor: color(colorVars.secondary).darken(0.5).hexString(),
    },
  },
};

Button.propTypes = {
  kind: PropTypes.oneOf(['primary,', 'secondary']).isRequired,
  onClick: PropTypes.func.isRequired,
};

module.exports = Radium(Button);
```
and the component that I want to use 'Button' in is:
```jsx
//shared/PostListItem/PostListItem.jsx
import React, { PropTypes } from 'react';
import { Link } from 'react-router';
import Button from '../Button';

function PostListItem(props) {
  return (
    <div className="single-post">
      <h3 className="post-title ">
        <Link to={`/post/${props.post.slug}-${props.post.cuid}`} onClick={props.onClick}>
          {props.post.title}
        </Link>
      </h3>
      <p className="author-name">By {props.post.name}</p>
      <p className="post-desc">{props.post.content}</p>
      <p className="post-action"><Button kind="primary" onClick={props.onDelete}>DeletePost</Button></p>
      <hr className="divider" />
    </div>
  );
}

PostListItem.propTypes = {
  post: PropTypes.shape({
    name: PropTypes.string.isRequired,
    title: PropTypes.string.isRequired,
    content: PropTypes.string.isRequired,
    slug: PropTypes.string.isRequired,
    cuid: PropTypes.string.isRequired,
  }).isRequired,

  onClick: PropTypes.func.isRequired,
  onDelete: PropTypes.func.isRequired,
};

export default PostListItem;
```
Any changes to those two files will not hot reload but other components, such as a header, will hot reload.
