### ISSUE TITLE
Let prop based styling be optional

### ISSUE THREAD

**Issue by natew** [FormidableLabs/radium#628]
I've been using a branch of radium for a while to support this functionality, but would love to see it merged into master.

I find prop based styling pretty confusing. I think as a plugin it would allow people to opt out of using it, which would make radium more useful overall.

Thoughts? I could help with a PR.

**Comment by alexlande** [comment]
@natew Sorry, I'm having a hard time understanding this one. What do you mean by prop based styling, exactly?

**Comment by ianobermiller** [comment]
And can you point the the branch of Radium you've been using instead?

**Comment by natew** [comment]
@ianobermiller Sorry I missed this. My branch wasn't done very cleanly but here it is:

https://github.com/motion/radium/commits/master
