### ISSUE TITLE
Remove object values from inline style

### ISSUE THREAD

**Issue by imtoo** [FormidableLabs/radium#634]
Hi,

we are using this kind of structure for defining styles:

```js
const font = {
  fontFamily: 'Source Sans Pro, sans-serif',
  fontWeight: 'normal',
  fontSize: '14px',
  bold: {
    fontWeight: 'bold',
  },
  italic: {
    fontStyle: 'italic',
  }
}

<div style={[font, font.bold]}>bold text</div>
```

and result is working correctly but we are seeing 
![screenshot 2016-03-18 09 45 01](https://cloud.githubusercontent.com/assets/1922079/13872915/1a050a32-ecee-11e5-8012-dfa5689e5953.png)

`bold: [object Object]` would be great if radium can automatically strip those objects out.

What do you think?

**Comment by braposo** [comment]
Hey @imtoo, what do you think about using something like `font.base` for the base styles instead?

```js
const font = {
  base: {
    fontFamily: 'Source Sans Pro, sans-serif',
    fontWeight: 'normal',
    fontSize: '14px',
  },
  bold: {
    fontWeight: 'bold',
  },
  italic: {
    fontStyle: 'italic',
  }
}

<div style={[font.base, font.bold]}>bold text</div>
```

This way you don't need to include the entire font object, which is causing the issue you mentioned.

Just a suggestion while I was searching for another issue :stuck_out_tongue_closed_eyes:

**Comment by Rokt33r** [comment]
:+1: Not only multiple styles for one component, cascade styling also becomes better if it is possible.

```jsx
<div
  className='Workspace-info'
  style={styles.info}
>
  <div
    className='Workspace-info-userName'
    style={styles.infoUserName}
  >
  </div>
  <div
    className='Workspace-info-tags'
    style={styles.infoTags}
  >
    <TagSelect/>
  </div>
...
</div>
```
Hard to recognize how deep the cascading level of component
`this.info.user.name` vs `this.info.userName`

```jsx
<div
  className='Workspace-info'
  style={styles.info}
>
  <div
    className='Workspace-info-userName'
    style={styles['info-userName']}
  >
  </div>
  <div
    className='Workspace-info-tags'
    style={styles['info-tags']}
  >
    <TagSelect/>
  </div>
...
</div>
```
this is the less suck way

```jsx
<div
  className='Workspace-info'
  style={styles.info}
>
  <div
    className='Workspace-info-userName'
    style={styles.info.userName}
  >
  </div>
  <div
    className='Workspace-info-tags'
    style={styles.info.tags}
  >
    <TagSelect/>
  </div>
...
</div>
```
and I think this is the best option as long as Radium automatically removes object values

**Comment by imtoo** [comment]
@braposo Yes, you're right. That's how we usually work with inline styles, but within the example I mentioned it seems little bit cleaner.

I was wondering if anybody else would like to use this approach as well or if there is a plan to remove these unnecessary objects. Thanks guys for sharing your knowledge, I'll discuss it with my team. :+1:

**Comment by ianobermiller** [comment]
I think it is reasonable for Radium to do a final pass and remove object values that don't have a custom `toString`.

**Comment by jfschwarz** [comment]
@ianobermiller I just submitted a PR for this: #703
