### ISSUE TITLE
Support for -webkit-inner-spin-button and -webkit-outer-spin-button

### ISSUE THREAD

**Issue by Dindaleon** [FormidableLabs/radium#649]
I did a search on it and could not find anything, so I wonder if there is support for those properties or you plan to offer support?

**Comment by alexlande** [comment]
Radium doesn't support most pseudo-elements, and I wouldn't expect support to be added for these especially given that they're browser-specific.

You could add them with CSS, or using the `Style` component (https://github.com/FormidableLabs/radium/tree/master/docs/api#style-component).

**Comment by TigerC10** [comment]
I think #510 relates to this, though.
