### ISSUE TITLE
Flow issues when wrapping component

### ISSUE THREAD

**Issue by NgoKnows** [FormidableLabs/radium#659]
So I have a component like this which I am wrapping with Radium

```
// @flow
import React, { Component } from 'react';
import Radium from 'radium';

type Props = { name: string };
class Sample extends Component {
    static defaultProps = {};
    state: void;
    props: Props;

    render() {
        return (
            <div>Hello {this.props.name}</div>
        );
    }
}

export default Radium(Sample);
```

However when using this, flow can't seem to analyze proper usage of the component when I import it and do something such as 

```
<Sample />
```

and it doesn't catch the omission of the name prop.

Is there any way around this?

**Comment by NgoKnows** [comment]
With flow 0.23, there is now an option `esproposal.decorators=ignore` that you can include in .flowconfig and it will ignore decorators on classes. So if you decorate your class with Radium, flow will essentially ignore it, meaning behavior of flow would be the same as if you didn't wrap your component in Radium.

So if anyone is trying to get flow working with Radium, best option is use the decorator and add that line to .flowconfig.

**Comment by dainyl** [comment]
Hi I've added the types for Radium 0.19 into [https://github.com/flowtype/flow-typed](flow-typed), and props are now supported!  However, they will not work with annotations, and you have to add an extra type for Stateless Functional Components.

The usage is as follows:

Stateless Functional Components
```
// @flow
import React from 'react';
import Radium from 'radium';
import type { FunctionComponent } from 'radium'

type Props = {
    a: number,
    b: string
};

const MyComponent: FunctionComponent<Props, void> = (props: Props) => <div>{props.a} {props.b}</div>

export default Radium(MyComponent);
```

Class Components
```
import React from 'react';
import Radium from 'radium';

type Props = {
    a: number,
    b: string,
};

type State = { };

class MyComponent extends React.Component<void, Props, State> {
    render () {
        return <div>{this.props.a} {this.props.b}</div>;
    }
}

export default Radium(MyComponent)

```

Please see the tests for more examples https://github.com/flowtype/flow-typed/blob/master/definitions/npm/radium_v0.19.x/test_radium-v0.19.x.js including some with a custom configured Radium

**Comment by alexlande** [comment]
Closing this one. Thank you for that @dainyl!

(Hey @NgoKnows! 👋 )
