### ISSUE TITLE
How do I use radium in tsx?

### ISSUE THREAD

**Issue by Naixor** [FormidableLabs/radium#669]
I just use `@Radium` in tsx, and it does not work. How do I do?

**Comment by froatsnook** [comment]
You need to either run `tsc` with `--experimentalDecorators` or add it to your `tsconfig.json` as documented [here](https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Decorators.md).  Alternatively, you could do the tsx equivalent of:

```javascript
import React, { Component } from "react";
import Radium from "radium";

class Test extends Component {
  render() {
    ...
  }
}

export default Radium(Test);
```

which is documented [here](https://github.com/FormidableLabs/radium#usage)

**Comment by alexlande** [comment]
Thanks @froatsnook!
