### ISSUE TITLE
Functional lib for styles

### ISSUE THREAD

**Issue by kof** [FormidableLabs/radium#670]
I am thinking of creating a functional library all around styles. Currently browser have very bad and inconsistent API for doing all this, we could combine our efforts efforts.

If you are interested, lets discuss it on [gitter](https://gitter.im/jsstyles/jss) and/or this [issue](https://github.com/jsstyles/jss/issues/204). I would like to hear about your use cases.

**Comment by alexlande** [comment]
Sounds cool, thanks for the heads up! Will definitely read through that issue.
