### ISSUE TITLE
How do I add multiple animations to keyframes?

### ISSUE THREAD

**Issue by Dindaleon** [FormidableLabs/radium#675]
I have this spinner:

```
const rotate = radium.keyframes({
  '100%': {
    transform: 'rotate(360deg)'
  },
}, 'rotate');
const dash = radium.keyframes({
  '0%': {
    strokeDasharray: '1,200',
    strokeDashoffset: '0'
  },
  '50%': {
    strokeDasharray: '89,200',
    strokeDashoffset: '-35'
  },
  '100%': {
    strokeDasharray: '89,200',
    strokeDashoffset: '-124'
  },
}, 'dash');
const color = radium.keyframes({
  '100%, 0%': {
    stroke: 'red'
  },
  '40%': {
    stroke: 'blue'
  },
  '60%': {
    stroke: 'green'
  },
  '80%, 90%': {
    stroke: 'yellow'
  }
}, 'color');

  loader: {
    position: 'absolute',
    width: '100px',
    height: '100px',
    left: '50%',
    top: '20%'
  },
  circular: {
    animation: 'q 2s linear infinite',
    animationName: rotate,
    height: '100px',
    position: 'relative',
    width: '100px'
  },
  path: {
    strokeDasharray: '1,200',
    strokeDashoffset: '0',
    animation: 'dash 1.5s ease-in-out infinite, color 6s ease-in-out infinite',
    animationName: dash,
    strokeLinecap: 'round'
  }
```

On the `path` class I have two animations, one for `dash` and another one for `color`
How can I handle this with radium?

**Comment by techniq** [comment]
I'm also interested in how (if possible) to accomplish this.

**Comment by ianobermiller** [comment]
It is currently not possible to add multiple animations.

**Comment by Dindaleon** [comment]
And what would a quick fix be for this issue?

**Comment by sassanh** [comment]
I'm interested too.

**Comment by techniq** [comment]
@Dindaleon @sassanh - I ultimately switched to [styled-components](https://github.com/styled-components/styled-components), which supports multiple animations as well as passing in props when creating keyframes.  You can see an example I created [here](http://codepen.io/techniq/pen/JErwzX?editors=0010)

**Comment by Dindaleon** [comment]
@ianobermiller hi there, will this be ever implemented? I love radium and I like it better over others alternatives. I checked styled-components but it is not that good for my own needs.

**Comment by jaredbrookswhite** [comment]
I've made a PR to handle this, #909. Handles multiple animations by passing an array of Keyframes objects.
