### ISSUE TITLE
Text decoration on links

### ISSUE THREAD

**Issue by willhalling** [FormidableLabs/radium#678]
I am trying to remove underline on hover state. I've added:

`  ':hover': {
      color: textColourHover,
      textDecoration: 'none'
    },`

...but doesn't appear to work. Any ideas? Thanks.

**Comment by froatsnook** [comment]
Here's some code I just wrote that works:

```javascript
import React, { Component } from "react";
import Radium from "radium";

@Radium
class TestComponent extends Component {
  render() {
    return (
      <a href="#" style={styles.link}>test link</a>
    );
  }
}

const styles = {
  link: {
    color: "white",
    textDecoration: "none",
    ":hover": {
      textDecoration: "none",
      color: "white",
    },
  },
};

export default TestComponent;
```

Are there errors in your console?

**Comment by willhalling** [comment]
Thanks for code snippet @froatsnook. Your comment allowed me to see an error in my code; my :hover selector was outside the link object. 

Please close.

**Comment by froatsnook** [comment]
Hey @willhalling, glad I could help.  I can't close since I'm not a contributor.  But I think you can close since it's your issue!

**Comment by willhalling** [comment]
Thanks @froatsnook. I've now closed.
