### ISSUE TITLE
If browser states are order agnostic, allow for them to be listed as obj rather than arr

### ISSUE THREAD

**Issue by colinmegill** [FormidableLabs/radium#68]
@eastridge suggests supporting both

**Comment by alexlande** [comment]
Browser states are not order agnostic. Multiple can apply at the same time, so order of instantiation matters (if a Radium user adds `active` styles *after* `hover` styles, `active` styles will take precedence if there is overlap).

**Comment by colinmegill** [comment]
That was easy :)
