### ISSUE TITLE
keyframes animation broken when react renders

### ISSUE THREAD

**Issue by Dindaleon** [FormidableLabs/radium#681]
I see that keyframes animations stop whenever react renders. Is it possible to fix this?

In my case, I have a loading spinner to indicate content is being fetched. This spinner has some keyframes animation. So, whenever react renders, this animation stops until react finishes rendering.

**Comment by alexlande** [comment]
Hey @Dindaleon! React rendering should generally not interfere with keyframe animations. In most cases, after React diffs the new render state, the old element that the animation is applying to shouldn't be replaced by a new copy, and the animation should work fine.

If you can provide a reproduction of your issue, add it here and I'll re-open this to take a look. Thanks!
