### ISSUE TITLE
Controlling where style tag is output in final markup

### ISSUE THREAD

**Issue by headquarters** [FormidableLabs/radium#683]
I was wondering if there is a way to output the inline `<style></style>` tag Radium produces *before* the markup it's styling. I couldn't find this mentioned in the documentation or in searching for "style tag" in the project issues or code, so I apologize if I overlooked this somewhere. 

The reason for the question is that placing the inline style tag before its corresponding markup is analogous to placing stylesheets in the `<head></head>` to avoid flashes of unstyled content. I noticed in the examples that the style tag is produced after the corresponding markup so there is a slight flash of unstyled content.

**Comment by alexlande** [comment]
Hey @headquarters! There's no way to change the position of the `style` element now. I don't know if we want to increase the API surface to allow it, but agree that it would be preferable for the element to come before content to minimize FOUC.

The relevant code is here: https://github.com/FormidableLabs/radium/blob/master/src/components/style-root.js#L35-L38

@ianobermiller mentioned in https://github.com/FormidableLabs/radium/issues/626 that the order couldn't be switched, but I wasn't clear on why that is and haven't revisited it.

There's some overlap with that other issue, but I think we should leave this one open as the other ticket had some other issues beyond the order of the `style` element.

**Comment by ianobermiller** [comment]
Try switching the order. If server rendering still works, it should be fine.

**Comment by headquarters** [comment]
I started looking into this and switching the order worked fine with server rendering, but I couldn't visually tell a difference so I'm going to keep doing some investigating. Especially with server rendering it seems like having the style block being parsed first would be a good idea, but it may just be a local optimization.  I'm thinking the FOUC is probably caused by the gap in time between styles loaded in the `<head>` and styles loaded in the body, not the gap in time between styles loaded before the component in the body versus after the component.

**Comment by alexlande** [comment]
Closing in favor of #626
