### ISSUE TITLE
Don't apply :hover if disabled

### ISSUE THREAD

**Issue by philiptzou** [FormidableLabs/radium#686]
I found Radium doesn't support :disabled so far but this might be a good idea since :active, :focus and :hover are already supported.

**Comment by ianobermiller** [comment]
https://github.com/FormidableLabs/radium/tree/master/docs/faq#how-do-i-use-pseudo-selectors-like-checked-last-before-or-after

**Comment by philiptzou** [comment]
@ianobermiller I see. But actually :disabled is quite different than other pseudo selectors.

For example, the "disabled" attribute of "reset" button is controlled by a state that if other inputs/textareas are all empty. In this case a click on the reset button will clean all other inputs/textareas box and cause itself disabled.

In traditional CSS, the style `:hover`, `:active` and `:focus` can be overridden by `:disabled`. But since we are using JS events to simulate the behavior, at least the `:hover` behavior is still working and there's no way to override it.

**Comment by philiptzou** [comment]
In another hand... I think my problem actually is: should `:hover` be disabled when the element has the attribute "disabled"?

**Comment by ianobermiller** [comment]
That seems fair!

**Comment by jooyunghan** [comment]
Check this PR, #689 

I had the same problem and made some workaround. I hope this change will help you.

**Comment by alexlande** [comment]
Resolved by #689
