### ISSUE TITLE
Hover breaks if button disabled

### ISSUE THREAD

**Issue by niksajanjic** [FormidableLabs/radium#687]
If button is disabled and radium styles contain styling for hover attribute it will apply that styling on hover but will not remove it after hover away:

    <button type='button' disabled={true} style={styles.button}>I'm button</button>

    let styles = {
      button: {
        backgroundColor: 'blue',
        ':hover': {
          backgroundColor: 'red'
        }
      }
    }

In this example button will be rendered as blue initially, but on hover, it will become red as expected. But the problem arises when you hover away, although it would be expected to have a button go back to original blue color, it will actually stay red forever.

Additional: Even after this bug gets fixed it makes it difficult for the user to style button on hover if it can possibly be disabled. So we have to leave ':hover' styling as an ​empty object and then use Readium.getState to know when button is hovered and then apply our own styling in case button is hovered but not disabled. This was very easy with CSS ':hover:disabled', but with Radium it has to be additionally complicated:

    <button type='button'
                 disabled={this.props.disabled}
                 key='button'
                 style={[styles.button, Radium.getState(this.state, 'button', 'hover') && !this.props.disabled &&
                             styles.buttonHovered]}>
      I'm button
    </button>

    let styles = {
      button: {
        backgroundColor: 'blue',
        ':hover': {}
      },
      buttonHovered: {
        backgroundColor: 'red'
      }
    }

EDIT: Referenced here https://github.com/FormidableLabs/radium/issues/686
If that pull request with :disabled props gets merged this issue can also be closed.

**Comment by alexlande** [comment]
Thanks @niksajanjic! Going to close this issue in favor of #686. Will work on landing that PR to resolve this.
