### ISSUE TITLE
Tests?

### ISSUE THREAD

**Issue by jquense** [FormidableLabs/radium#70]
Just that really. What is the testing story? We are more than a little reticent to really use something with no tests (no critique on the quality of the product tho!). But some amount of assurance against regressions and bugs across releases would be appreciated, along with just the additional implicit documentation tests provide about expected behavior.

Thanks for the great library we have really been enjoying it :)

**Comment by alexlande** [comment]
Funny story-- at @FormidableLabs we're pretty strict about testing and similarly are very hesitant to use OSS libraries without a good test suite. It's time for us to get moving on this one.

**Comment by jquense** [comment]
:+1:

**Comment by alexlande** [comment]
Done, and with 100% coverage.

**Comment by tmcw** [comment]
:racehorse: well done!
