### ISSUE TITLE
JS vs Media Query best practice?

### ISSUE THREAD

**Issue by jerrybotticelli** [FormidableLabs/radium#700]
My main layout component has a resize event listener that saves window width, height and some other info in an object that I can pass down to other components as a prop. 

```
const { browserInfo } = this.props;
var style = {
 wrap: {
   padding: browserInfo.breakPoint === '480' ? '10px 15px' : '10px 5px'
  }
}
```

Should I use this throughout or reserve it for situations that require more complex stuff that media queries cannot handle as easily? Is there a performance concern when using this approach over media queries?

**Comment by alexlande** [comment]
There will probably be a performance cost to using a resize listener. I might opt for `matchMedia` instead, if you were concerned about that. I can't say with certainty whether the perf hit would be a problem for your app, but it would be something to be aware of.

A benefit to using built in media queries with Radium is improved server-side rendering support. Your components will have the correct styles applied before client-side JS kicks in. If you're not server-side rendering, it may not matter so much.
