### ISSUE TITLE
SVG changing color on hover?

### ISSUE THREAD

**Issue by jerrybotticelli** [FormidableLabs/radium#701]
https://jsfiddle.net/m854ho2e/
That's how I've been handling changing SVG colors via the parent element's hover state.

How would I go about doing this efficiently with Radium? I did manage to get it working using the Style Component in each svg's parent element...

```
<Style scopeSelector=".svgParentClass:hover .svgPathClass" rules={{ fill: 'red' }} />
```

This is going to add a bunch of style tags in my app though. Any way to place these into the same style element that all the media queries are placed in down at the bottom of my layout?

**Comment by alexlande** [comment]
@jerrybotticelli: You should be able to apply the style object with the `fill` property directly to the `path` element, without having to use the `Style` component separately. If that doesn't work, please let me know!

Separately, you might consider setting a CSS rule like this globally: `svg { fill: currentColor; }`

Then, you could change the `color` style on the element containing the SVG and the correct color will propagate down. See https://css-tricks.com/cascading-svg-fill-color/ for more information on this technique.
