### ISSUE TITLE
Interacting with 3rd party libraries that set inline styles

### ISSUE THREAD

**Issue by lalitkapoor** [FormidableLabs/radium#702]
Hi, If I set a style property, say `color: yellow`, and then a 3rd-party library adds it's own inline styles which sets color to red. How do you go about clearing that out and making the color yellow again?

Here's a jsfiddle to illustrate this scenario: https://jsfiddle.net/cd9ej2v0/6/

Steps to reproduce in the jsfiddle:

1. If you click the on off button you will see that the text color stays yellow
2. If you click the simulate 3rd party lib button you will see the text turn red
3. Now if you press the on/off button the text color will never go back to yellow

Other properties defined in my style object get applied/removed appropriately, but I can't make it go back to yellow.

Thanks.

**Comment by ianobermiller** [comment]
React doesn't really play well with other libraries; this isn't a Radium issue in particular. In general, you should either control a subtree 100% with React or 100% by a third party. Mix and matching will usually not work well.

**Comment by lalitkapoor** [comment]
@ianobermiller Thanks for the feedback! Appreciate it.
