### ISSUE TITLE
How to overwirte basic styles?

### ISSUE THREAD

**Issue by onecompany** [FormidableLabs/radium#707]
I know radium extends basic styles by putting in an array,is there a way to overwirte them ？

And,where should I write the basic styles?

**Comment by alexlande** [comment]
To allow for overwriting styles, your component should merge styles passed in to the `style` prop in your style array. For example:

```
render() {
  return (
    <div
      style={[ baseStyles, extraStyles, this.props.style ]}
    />
  );
}
```

You might also look at a pattern recently shared in our Gitter chatroom: https://gitter.im/FormidableLabs/radium?at=57247c624a7c24bd6109b122
