### ISSUE TITLE
Possible optimization

### ISSUE THREAD

**Issue by edgesoft** [FormidableLabs/radium#708]
I was running this project [https://github.com/garbles/why-did-you-update](https://github.com/garbles/why-did-you-update) and it seems to complain about Stylesheet and StyleRoot re-rendering when nothing changed.

**Comment by ianobermiller** [comment]
Good point, it probably wouldn't hurt to throw `shouldComponentUpdate` on both of them

**Comment by doctyper** [comment]
@ianobermiller @alexlande Will you accept a PR that does this? It should be an easy perf win for Radium.

**Comment by ianobermiller** [comment]
Sure!
