### ISSUE TITLE
getState only works if you pass a style to the elementKey

### ISSUE THREAD

**Issue by MechJosh0** [FormidableLabs/radium#709]
I've noticed that `getState` will only work if you pass a style to the element that references the `elementKey`. The style being passed can be blank, as long as it's being passed a `:hover`.

Either the documentation should state that the element must have a `:hover` reference, or it's a possible bug. Or I could be missing something here, if so please let me know.

See below for example code. It will work fine, but if you comment out either the `style.button` or `style.button:hover` it'll break the `getState`.

```
import React from 'react';
import Radium from 'radium';

const style = {
  text:{
    background: 'green'
  },
  button: {
    ':hover': {
    }
  }
};

class MyExample extends React.Component {
  render()
  {
    return (
      <div>
        <button key="button" style={style.button}>Hover me!</button>
        <div style={[Radium.getState(this.state, 'button', ':hover') && style.text]}>When you hover, I should be green.</div>
      </div>
    );
  }
}

export default Radium(MyExample);
```

**Comment by ianobermiller** [comment]
This came up before, we should definitely add a note to the docs. I think this is what we want, because we don't want to add event listeners to _every_ element, but I agree it is not intuitive.

**Comment by niksajanjic** [comment]
Am I misunderstanding you or docs do have that explained:

https://github.com/FormidableLabs/radium/tree/master/docs/api#getstate

> Note that the target element specified by elementKey must have the state you'd like to check defined in its style object so that Radium knows to add the handlers. It can be empty, e.g. ':hover': {}.

**Comment by ianobermiller** [comment]
thanks @niksajanjic, I thought I added that already!
