### ISSUE TITLE
Question: why are things like Babel included as production dependencies?

### ISSUE THREAD

**Issue by callumlocke** [FormidableLabs/radium#710]
from package.json:
```js
  "dependencies": {
    "array-find": "^1.0.0",
    "babel-cli": "^6.3.15",
    "babel-core": "^6.3.15",
    "babel-plugin-add-module-exports": "^0.2.0",
    "babel-plugin-transform-decorators-legacy": "^1.2.0",
    "babel-plugin-transform-es2015-modules-commonjs": "^6.7.4",
    "babel-preset-es2015-loose": "^6.1.3",
    "babel-preset-react": "^6.3.13",
    "babel-preset-stage-1": "^6.3.13",
    "exenv": "^1.2.0",
    "inline-style-prefixer": "^1.0.3",
    "rimraf": "^2.4.0"
  },
  "devDependencies": {
    "babel-eslint": "^6.0.0",
    ...
```

Just curious, why are all those deps in dependencies, not devDependencies?

**Comment by ianobermiller** [comment]
So that we can build for you if you install directly from git: https://github.com/FormidableLabs/radium/blob/2fb6a0b79e0d2795608e68cfc8851050c5019169/package.json#L28

We've talked about removing this many times. I don't know for sure, but I'll bet git installs are a small fraction (1/1000?) of NPM installs.

**Comment by donatasbacius** [comment]
+1 for removal, otherwise every "npm install" of radium pulls in a lot of cruft.

**Comment by ryan-roemer** [comment]
Over in Victory-land, we're considering doing what a lot of React projects are doing which is do a last minute git dirty swap with moving the `postinstall`-necessary dependencies to `devDepencies` on `npm publish` in a manner that are **not** committed to git source.

This has the nice effect of installations from `npm` are tight and have only what is needed while git installations still work with the existing `postinstall` flow.

Here's our current strawman: https://github.com/FormidableLabs/victory/issues/186#issuecomment-223872054  Only kink is utilizing various lifecycle things from publishing with `npm version` which I'm not sure we do here.

**Comment by ryan-roemer** [comment]
Stepping back here, we _don't_ publish babel deps to `npm`. Just in git source. Looking at: https://npmcdn.com/radium@0.17.1/package.json we have:

```js
  "dependencies": {
    "array-find": "^1.0.0",
    "exenv": "^1.2.0",
    "inline-style-prefixer": "^1.0.3",
    "rimraf": "^2.4.0"
  },
```

Looking in git logs, it looks like @ianobermiller already did this months back. Am I perhaps missing something?

**Comment by jmcriffey** [comment]
@ryan-roemer It does look like the npm install is quick and doesn't include any of the cruft, so maybe @callumlocke is not ware of the removal of babel dependencies before publishing to npm. If so, is this currently not an issue @callumlocke?

**Comment by alexlande** [comment]
Closing this one in favor of #731. *phew*

**Comment by ianobermiller** [comment]
@ryan-roemer Ah yes, I totally forgot about https://github.com/FormidableLabs/radium/commit/90f353b8c1845bed43b32bd2d5c9b6f8883d49b2
