### ISSUE TITLE
Radium not working when used as decorator

### ISSUE THREAD

**Issue by germtb** [FormidableLabs/radium#713]
I am using Radium for:

```javascript
const divStyle = {
  fontSize: '25px',
  marginLeft: '20px',
  marginRight: '20px',
  marginBottom: '20px',
  ':hover': {
    fontWeight: 'bold'
  },
};

class MenuButton extends React.Component {
  render() {
    return (
      <div style={divStyle} key={'div'}>
        <img src={this.props.img}/>
        <div>  {this.props.text} </div>
      </div>
    );
  }
}

MenuButton = Radium(MenuButton);
export {MenuButton};
```

And that works well, but if I use it as:
```javascript
const divStyle = {
  fontSize: '25px',
  marginLeft: '20px',
  marginRight: '20px',
  marginBottom: '20px',
  ':hover': {
    fontWeight: 'bold'
  },
};

@Radium
class MenuButton extends React.Component {
  render() {
    return (
      <div style={divStyle} key={'div'}>
        <img src={this.props.img}/>
        <div>  {this.props.text} </div>
      </div>
    );
  }
}

export {MenuButton};
```

It doesn't work. Babel should be correctly configured since everything works as it should, except for the `hover` that Radium should be taking care of. Am I missing something?

**Comment by niksajanjic** [comment]
With this code I can't be sure what is exact reason but I'll assume you are using Babel 6 which doesn't support decorators by default which means you will have to install babel-plugin-transform-decorators-legacy and add it to the .babelrc  file as plugin.

Here's the explanation why Babel 6 doesn't support decorators:
https://babeljs.io/docs/plugins/transform-decorators/

Here's how to install this module to enable decorators:
http://technologyadvice.github.io/es7-decorators-babel6/

**Comment by alexlande** [comment]
Sounds like this is resolved, thanks @niksajanjic!

If you're still having trouble @germtb, let me know 👍 .
