### ISSUE TITLE
Radium fails if it is not the last wrapper on a component

### ISSUE THREAD

**Issue by thefivetoes** [FormidableLabs/radium#718]
I have a number of other higher order components that are wrapping my component, and have found that if Radium isn't the last wrapper, it does not work. 
# Example

I have a fork that updates the Radium example Button component, by adding a `buttonWrapper` higher order component: https://github.com/thefivetoes/radium/blob/broken-example/examples/components/button.jsx You can toggle the working/nonworking version by swapping the export and commented export at the bottom of the file.
# Summary of the example linked above

Using the Radium examples as starting point and adding a new `buttonWrapper` higher order component: 

``` js
const wrapButton = (Component) => {
  class ButtonWrapper extends React.Component {
    componentWillMount() {
      console.log('Wrapped Button Will Mount');
    }

    render() {
      return <Component {...this.props} {...this.state} />;
    }
  }
  return ButtonWrapper;
};
```
## "Proper" wrapping order

So the above example works fine if I wrap the `Button` with `Radium`, then the entire component with `wrapButton`

``` js
module.exports = wrapButton(Radium(Button));
```

<img width="312" alt="screen shot 2016-05-31 at 7 35 11 pm" src="https://cloud.githubusercontent.com/assets/2514127/15693996/130c9d3a-2768-11e6-8553-c56c94a81b9b.png">
## Out of order wrapping

...but it fails if the order is switched:

``` js
module.exports = Radium(wrapButton(Button));
```

<img width="322" alt="screen shot 2016-05-31 at 7 34 58 pm" src="https://cloud.githubusercontent.com/assets/2514127/15693998/17283262-2768-11e6-8b9e-499f8347c27a.png">
# Expected Behavior

Ideally, wrapping order would not matter. If another library _also_ insisted on being the first wrapper, we would essentially have to pick between that library and Radium.

**Comment by ianobermiller** [comment]
Were you able to debug to see why this is the case?

**Comment by stevenmusumeche** [comment]
@thefivetoes is this still an issue for you?
