### ISSUE TITLE
:hover tag renders entire component 

### ISSUE THREAD

**Issue by deadlocked247** [FormidableLabs/radium#724]
I understand that this is the intended functionality, but is there any way we can get css hovering sometime in the future instead of rerendering entire DOM elements for something as simple as a background color change? Doesn't seem efficient especially if there are nested components as well.

**Comment by alexlande** [comment]
It's a possibility for sure. (A likely one, even!)

See https://github.com/FormidableLabs/radium/issues/510 for more discussion on this issue.
