### ISSUE TITLE
Add `publishr` for optimal npm and git installation support.

### ISSUE THREAD

**Issue by jmcriffey** [FormidableLabs/radium#731]
Ideally Radium should be installable and optimized for both the npm package and the git repo. We want to be able to build and publish Radium without bogging down the main (npm) install path, but it is also advantageous to enable installing from git. Lastly, we want this process to be reliable.

We need to do a few things to accomplish those objectives:
- [x] Publish build dependencies as production dependencies in the git repo.
  - Why? You need these to `npm install` the git repo.
- [x] Publish build dependencies as devDependencies in the in the npm package.
  - Why? Babel takes a long time to install and it isn't needed for the pre-built package.
- [x] Publish `.npmignore` in the npm package.
  - Why? You save space and time if you only include the pre-built files.
- [x] Publish a different `.npmignore` in the git repo.
  - Why? The npm install command honors `.npmignore` during an install from a git repo.
- [x] Use the postversion hook to make changes.
  - Why? The prepublish hook can be unreliable. See #656.

We've been kicking around a few ideas, and I like the idea of declaring fields in `package.json` to reconcile the differences in those dependencies and ignores. We then would use a full npm version/publish lifecycle and re-write the `package.json` and `.npmignore` files depending on those shared fields.

A `package.json` file would look something like this:

``` json
{
  "dependencies": {
    "array-find": "^1.0.0",
    "babel-cli": "^6.3.15",
    "babel-core": "^6.3.15",
    "other-bulky-build-dependency": "^1.0.0"
  },
  "devDependencies": {
    "eslint": "^2.5.3"
  },
  "npmDependIgnore": [
    "^babel",
    "other-bulky-build-dependency"
  ],
  "npmFileIgnore": [
    "/*"
    "!/lib"
    "!/dist"
   ]
}
```

Our goal here to is remove `babel-cli`, `babel-core`, and `other-bulky-build-dependency` from npm's version of `package.json` and add `/*`, `!/lib`, and `!/dist` to npm's version of `.npmignore`. We could do that by using 2 new fields that dictate the differences in the git and npm repos. Our publishing lifecycle would then look like the following:
- postversion
  - Save a new `package.json` file with `npmDependIgnore` packages removed from `dependencies`.
  - Save a new `.npmignore` file with `npmFileIgnore` files added.
- postpublish
  - Revert the `package.json` file.
  - Revert the `.npmignore` file

Any thoughts or opinions relating to the above?

**Comment by ryan-roemer** [comment]
Great start!

Off-the cuff comments:

1. Let's get a top-level field namespace for this if doing in `package.json`. Something evoking `npmPublish` or in that vein.
2. View `postpublish` as just "nuclear git reset"
3. Allow arbitrary file creation / overwriting. Something like:

```
  "npmPublish": {
    "files": {
      ".npmignore": "/*\n!/lib\n!/dist"
    }
  }
```

thoughts?

**Comment by jmcriffey** [comment]
1. Yep, we definitely should have a well-named, top-level namespace.
2. Sounds good.
3. That is an interesting possibility, and would definitely be a feature request for any tool that did this. It seems like simple files would work inside the actual `package.json` file, but maybe we would need to just have those map to replacement files to handle more complex cases.

That would give us something like:

```json
"npmPublish": {
    "files": {
      ".npmignore": ".npmignore.npmPublish"
    }
}
```

**Comment by jmcriffey** [comment]
@ryan-roemer @alexlande, I've got an MVP of a tool up and running at https://github.com/jmcriffey/publishr. I've been able to install test repos from both npm and github and I believe I've addressed all of the major issues outlined above. Publishr also uses itself to publish to npm.

The tool currently works like this:

1. Add `publishr postversion` and `publishr postpublish` to your npm scripts and commit.
2. Call `npm version [major | minor | patch | etc]` or something similar.
3. Publishr does its magic replacing files and dependencies.
4. Call `npm publish`.
5. Publishr cleans up the git repo.

I've run into a couple of weird cases that might cause issues:

- I'm currently using `git clean -df && git checkout .` for a quick clean up of the repo, but I will end up needing to be smarter about that. I ultimately don't want to remove untracked files that I didn't create; I also don't want to leave new untracked files laying around. I think I'll have to do something along the lines of keeping track of the files I modify and create, then checkout or delete those specific files as needed.
- The tool is currently making the user be explicit by calling both commands, but I could see something like `publishr publish patch` to seamlessly handle both `npm version` and `npm publish` for you.

There are a few decisions I made just to get things working, so I'd love any/all feedback. I'm also not set on the name, so if anyone can think of a better one let me know. Thanks!

**Comment by jmcriffey** [comment]
Also, here is what it might look like in Radium:

https://github.com/jmcriffey/radium/blob/chore-addPublishr/package.json

**Comment by jmcriffey** [comment]
@ryan-roemer @alexlande I've got publishr fixed and tested at https://github.com/FormidableLabs/publishr. We should be good to go once I get some feedback and we decide a few things:

1. Should there be a single publishing command in publishr, or should the end user call `npm version` and `npm publish`?
2. What is the ideal way to handle an error in either of the postversion or postpublish scripts? Since we are running scripts _after_ the commands, we might be limited to giving helpful error messages.

**Comment by ryan-roemer** [comment]
For `2` may make sense to have a `--dry-run` feature for both scripts to check as much as we can before the publish...

For `1` it's probably best not in `publishr` as a single command. Let's just document best practices for hooking up.

**Comment by jmcriffey** [comment]
I am leaning the same way for `1`.  I also like the idea of having a dry run for `2` and documenting a publishing pipeline that includes the dry run first.

**Comment by ryan-roemer** [comment]
@jmcriffey -- If you get a second, can you open a PR for this for Radium? Realized this was the impetus for you _creating_ `publishr` and we still haven't added it here... 😉 

/cc @alexlande

**Comment by ryan-roemer** [comment]
Implemented in https://github.com/FormidableLabs/radium/pull/914
