### ISSUE TITLE
Add EsLint, JsCs

### ISSUE THREAD

**Issue by ryan-roemer** [FormidableLabs/radium#74]

**Comment by alexlande** [comment]
Do we need JSCS if we're using ESLint? ESLint does style conformance checking as well.

**Comment by ryan-roemer** [comment]
@alexlande -- I still find JsCs can control a _lot_ more style things that eslint. See, e.g.:

* https://github.com/FormidableLabs/full-stack-testing/blob/master/.eslintrc VS
* https://github.com/FormidableLabs/full-stack-testing/blob/master/.jscsrc
