### ISSUE TITLE
Using :hover within media query

### ISSUE THREAD

**Issue by dhunninghake** [FormidableLabs/radium#740]
Hey guys,

I'm trying to change a property on hover that is already defined within a media query. It runs correctly but doesn't get applied because of the !important tag on `background: 'red'`:

```javascript

var style = {
  '@media (min-width: 320px)': {
    background: 'red',
    ':hover': {
      background: 'blue'
    }
  }
};
```

Thoughts on how to get around this specificity issue?

Thanks!

**Comment by alexlande** [comment]
Hmm, I don't have a good answer for this one at the moment. We've been talking about generating CSS for pseudo-selectors (or even all styles), which would probably be the path forward here. See https://github.com/FormidableLabs/radium/issues/510

Going to close this one in favor of that issue.
