### ISSUE TITLE
onChange gets executed on pageload

### ISSUE THREAD

**Issue by jwamsterdam** [FormidableLabs/radium#741]
Hi, 

I have the following code implemented in React Burger Menu:

    {<RadiumCheckbox checked={this.props.settings.stops.nonstop} onChange={this.changeStops('nonstop')}>Non-stop</RadiumCheckbox>}

But what happens is that the onChange function gets executed on page load, and that the onChange is not working when you click the Checkbox.

I have litte experience with Radium, but this notation was advised to me at the React Burger Menu Github.. Any ideas or help how to get this working?

Many thanks!

**Comment by jmcriffey** [comment]
It looks like you are calling the changeStops method instead of binding it. If that method doesn't return another method, that would be why it isn't working. Maybe try:

```js
RadiumCheckbox checked={this.props.settings.stops.nonstop} onChange={this.changeStops.bind(this, 'nonstop')}>Non-stop</RadiumCheckbox>
```

I hope that helps!
