### ISSUE TITLE
Modifiers aren't included from Props.style

### ISSUE THREAD

**Issue by jquense** [FormidableLabs/radium#75]
`buildStyles()` includes `props.style` in its calculation, which is great, since it allows for overriding styles from the outside. However it assumes `props.style` is a flat, normal style object. This may be by design but It feels like it would be a lot more useful it it accepted a Radium style style definition, That way I could pass in new behaviors for Modifiers (or override modified styles).

**Comment by alexlande** [comment]
Hmm, interesting.

This is a pattern I've thought about a little bit, and it's definitely important. So far, I've been thinking that this should be the component's responsibility:

```xml
<MyComponentFoo additionalStyles={someExtraStyleObject} />
```

```js
var MyComponentFoo = React.createClass({
  render: function () {
    var baseStyles = { [a style object] };
    var styles = merge({}, baseStyles, this.props.additionalStyles);

    return ( <div styles={this.buildStyles(styles)} /> );
  }
});
```

I'm not completely opposed to baking this into Radium, and it makes some sense conceptually. I'm a little concerned it might blur the line between the `style` attribute/prop and Radium more. The original thought behind merging in `this.props.style` is that it works the way you would expect a React component without Radium would work. That is-- it's a clear way to add styles that take precedence (as if you were using traditional CSS stylesheets and then included an inline style), and Radium will respect whatever you pass in.

I don't want to break that behavior (where `this.props.style` is the final source of truth). Maybe we could make a separate reserved prop for this use case?

```xml
<MyComponentFoo radiumOverrides={someRadiumStyleObject} />
```

**Comment by jquense** [comment]
I can definitely appreciate not wanting to break assumptions about the `style` prop, I'm not sure whether in this case its a still a good idea or not. Having a different prop might be a bit annoying, but if its possible to use it instead of the normal `style` prop i think i'd be ok with it.

I do tend to thing that this sort of thing really should be in Radium proper and not the responsibility of component makers, because in some cases normal `merge` doesn't cut it. Take this example from trying to implement bootstrap modals with Radium

```less
 // basic fade
.fade {
  opacity: 0;
  .transition(opacity .15s linear);
  &.in {
    opacity: 1;
  }
}

 /* modal fade (adds a slide animation as well) */
 .fade .modal-dialog {
    .translate(0, -25%);
    .transition-transform(~"0.3s ease-out");
  }
```

In this case [I wanted to implement](https://github.com/jquense/radium-bootstrap/blob/modal/modules/components/fade.jsx) a basic `<Fade />` component. It's relatively straight forward I use `in` as a modifer, and toggle that modifier via some state change to enable the animation. really elegant.

I figure great that works, now I just need to pass in some style overloads when using it in the modal component. I'd like to just do something like:

```jsx
 var overrides = { 
   transform: 'translate(0, -25%)',
   transition: 'transform 0.3s ease-out',
   modifiers:  [
     {  in: { transform: 'translate(0, 0)' } }
   ]
 }

<Fade style={overrides}/>
```
bam done, but no dice, for obvious reasons. There is one caveat taht makes this especially annoying. I can't just merge in the styles using a `_.merge` because I don't want to override `transition` here I want to append to it (`'opacity .15s linear, transform 0.3s ease-out`). This would be annoy except that computed styles make this nice and simple to deal with (different question as to whether radium should also just handle this case transparently).

To get around this I can create a new `<SlideFade/>` component like so:

```js
render: function(){
      var modifiers = { in: this.state && this.state.in }
      var style = this.buildStyles({
        transform: 'translate(0, -25%)',
        transition: 'transform 0.3s ease-out',
        modifiers:  [
          { in: { transform: 'translate(0, 0)' }}
        ]
      }, modifiers);

      return (
        <Fade {...this.props} 
          style={style} 
          onShow={()=> this.setState({ in: true })}
          onHide={()=> this.setState({ in: false })}
        >
          {this.props.children}
        </Fade>
      );
  }
```

But I think we can all agree that this a lot more verbose, and requires that I have an understanding of `<Fade/>` internal modifier logic (for `in` in this case).

I don't really know the best way to deal with all this, but I did think it might be helpful to share the  thought process, and struggle that lead to this issue,

**Comment by alexlande** [comment]
Thanks, that's helpful.

For now, I'm thinking a separate reserved prop (`radiumOverrides`) is the best way to go. That way we don't lose the existing `style` behavior but can better handle this use case.

**Comment by alexlande** [comment]
Given that we don't have modifiers period anymore, going to close this one out.
