### ISSUE TITLE
Media query inside media query?

### ISSUE THREAD

**Issue by 123ndy** [FormidableLabs/radium#757]
I am trying to place a media query inside a media query (to load the right picture for the screen). But it does not seem to work. Is this not possible?

```
'@media (min-width: 641px)': {
    backgroundImage: `url(/images/somethingSmall.jpeg)`,
    '@media (minDevicePixelRatio: 2), (minResolution: 144dpi)': {
     backgroundImage: `url(/images/somethingBig@2.jpeg)`,
  }
},
```

**Comment by jmcriffey** [comment]
You should be able to achieve that with `and` for your media queries. Try something like:

```js
{
  "@media (min-width: 641px)": {},
  "@media (min-width: 641px) and (min-device-pixel-ratio: 2), (min-resolution: 144dpi)": {}
}
```

**Comment by alexlande** [comment]
Yep. Not planning on implementing nested media queries at the moment.

**Comment by 123ndy** [comment]
@jmcriffey Thank you. @alexlande Alright :)
