### ISSUE TITLE
Conflicting event handlers

### ISSUE THREAD

**Issue by guigrpa** [FormidableLabs/radium#76]
There are two related issues here, one minor and one major:

* The minor one is that the `BrowserStateMixin` defines event handlers with names that follow too strictly :grinning: React's conventions, such as `_handleFocus`, `_handleMouseEnter` and so on. That's good, but it clashes with any such functions we may already have in our own components. *Suggestion*: maybe prefix Radium's handlers with a Radium-specific prefix?

* The **major** one is that, if I'm not doing something wrong, this same mixin prevents the use of my own event handlers (if declared *before* `{...this.getBrowserStateEvents()}`) or Radium's handlers (if declared *after* `{...this.getBrowserStateEvents()}`)

**Comment by alexlande** [comment]
You are correct on both counts!

In most of our usage, individual components have been relatively generic + haven't included their own listeners that conflict with Radium (only ones passed down as props), so this never really occurred to me.

I'm thinking one solution will solve both of these issues. We can rename the event listeners to something Radium namespaced: `RadiumMouseEnter`, then if you need to use your own handlers on the same events, you can just do this:

```xml
<button
  {...this.getBrowserStateEvents()}
  onMouseEnter={this.handleMouseEnter}
/>
```

```js
handleMouseEnter: function () {
  this.RadiumMouseEnter();

  // Do whatever your listener should do.
}
```

It's not transparent, but I think it's clean enough to document this as an edge case with a workaround.

**Comment by guigrpa** [comment]
That would be great, thanks!
