### ISSUE TITLE
Poor Stateless component detection in enhancer.js

### ISSUE THREAD

**Issue by CreepGin** [FormidableLabs/radium#762]
The current detection logic: 

`if (!ComposedComponent.render && !ComposedComponent.prototype.render)`

will error out when `ComposedComponent.prototype` is undefined, which will be the case when you use lambdas to define the component. 

```js
var ff = () => {}
undefined

typeof ff.prototype
"undefined"

var bb = function(){}
undefined

typeof bb.prototype
"object"
```

**Comment by alexlande** [comment]
Resolved by #771. I'll plan to tag a release tomorrow morning 👍
