### ISSUE TITLE
Hover state question

### ISSUE THREAD

**Issue by sunny-mittal** [FormidableLabs/radium#77]
I'm having an issue getting hover states to work. I've followed along with the examples as closely as possible but I'm clearly missing something. Here is the relevant code for the styles (in CoffeeScript):

```
getStyles: ->
    {
      height: @props.globalStyles.newGameButtonHeight
      backgroundColor: @props.globalStyles.newGameButtonColor
      borderRadius: @props.globalStyles.newGameButtonBorderRadius
      color: '#fff'
      margin: 'auto'
      padding: 10
      position: 'absolute'
      top: '50%'
      left: '50%'
      cursor: 'pointer'
      transform: 'translate(-50%, -50%)'
      transition: 'background-color 0.3s'
      states: [
        {
          hover: {
            backgroundColor: @props.globalStyles.newGameButtonHoverColor
          }
        }
      ]
    }
```
All the regular styles work just fine, but the hover state isn't getting triggered. Is there something I'm missing? I'm using the StyleResolverMixin and the BrowserStateMixin. Thanks for your help!

**Comment by alexlande** [comment]
Hey @sunny-mittal: Your style object looks right. You probably haven't included the browser state event listeners on your component. We may need to improve the documentation on this one, it isn't immediately obvious. From the overview guide:

```js
<button
  {...this.getBrowserStateEvents()}
  style={styles}>
```

> The getBrowserStateEvents() method returns a hash of events that Radium uses to set browser state on a component.

**Comment by sunny-mittal** [comment]
Oh! Yep, that'll do it. Thanks!

**Comment by alexlande** [comment]
No problem!

**Comment by cinder92** [comment]
Hello i have same issue here! 

` {...this.getBrowserStateEvents()}`

is not solving the issue and there is an error saying that getBrowserStateEvents is undefined

**Comment by alexlande** [comment]
Hi @cinder92, this ticket is pretty old and is referencing an outdated API. The getting started guide is a good place to look for guidance on using Radium, including pseudo-selectors like `:hover`. https://github.com/FormidableLabs/radium/tree/master/docs/guides#how-do-i-do-it-then

If you're still having trouble, feel free to open a new ticket with a reproduction of your bug and we can check it out!
