### ISSUE TITLE
Can I use Radium with Material UI?

### ISSUE THREAD

**Issue by CasperHK** [FormidableLabs/radium#772]
I see that Radium is a set of tools to manage inline styles on React elements so can I use it with Material UI? Recently, I want to make a hover effect with Material UI but I don't know how to make it. I have tried [this solution](http://stackoverflow.com/a/28369384/2828227) but I cannot make it work. Therefore, can Radium help me solved it easily?

```
const styles = {
	card: {
		height: 200,
		width: 200,
		margin: 10,
	},
	cardHover: {
		backgroundColor: "rgba(98, 252, 105, 0.65)",
	},
        ...
        ...
}
```

How to give Card component a hover effect?
```
export default class Project extends React.Component {
	render() {
		return (
			<Card style={styles.card}>
				<div style={styles.img}>
					XXX
				</div>
				<h4>YYY</h4>
				<div>ZZZ</div>
			</Card>
		);
	}
}
```

**Comment by jmcriffey** [comment]
Yep, you'll need to use the `:hover` pseudo-class selector to make that work.

```js
const styles = {
    card: {
        height: 200,
        width: 200,
        margin: 10,
        ":hover": {
            backgroundColor: "rgba(98, 252, 105, 0.65)"
        }
    }
};
```

Here is more information in the documentation:

https://github.com/FormidableLabs/radium/tree/master/docs/guides#browser-states

**Comment by nateshmbhat** [comment]
I am trying to use Paper component and style it with radium , but the hover styles are not being applied when hovering.
```
<Paper style={{ backgroundColor : 'red' , ":hover" : {backgroundColor:'green' } }}>
<h1> Hi </h1>
</Paper>
```
