### ISSUE TITLE
Get flow-bin up to date

### ISSUE THREAD

**Issue by alexlande** [FormidableLabs/radium#776]
We haven't updated `flow-bin` since version `0.21` came out in February, and there are a lot of new Flow errors since then. We need to update to the latest version and get caught up again.

**Comment by freddi301** [comment]
0.35.0

**Comment by jameskraus** [comment]
0.53.0

**Comment by jameskraus** [comment]
PR: https://github.com/FormidableLabs/radium/pull/922

**Comment by alexlande** [comment]
Resolved by #922, thanks again @jameskraus!
