### ISSUE TITLE
Failing when used in TypeScript.

### ISSUE THREAD

**Issue by philcockfield** [FormidableLabs/radium#777]
I've created minimal a sample repo to demonstrate the problem: https://github.com/philcockfield/radium-typescript-fail

Details in README repeated here:

---------

# Failure Example - Radium and TypeScript
This React sample is taken from https://www.typescriptlang.org/docs/handbook/react-&-webpack.html

## Run
    npm install
    webpack

Then open `index.html` in browser.

## Error
When rendering a Radium enchanced component like this:

```js
@Radium
export class Hello extends React.Component<HelloProps, {}> {
    render() {
        return <h1>Hello from {this.props.compiler} and {this.props.framework}!</h1>;
    }
}
```

or this

```js
export class HelloComponent extends React.Component<HelloProps, {}> {
    render() {
        return <h1>Hello from {this.props.compiler} and {this.props.framework}!</h1>;
    }
}
export const Hello = Radium(HelloComponent);

```

The same error occurs at runtime:

![error](https://cloud.githubusercontent.com/assets/185555/16833121/e94ea95e-4a01-11e6-8957-50dd8e262c94.png)

If the Radium aspect of this is commented out the component renders fine.

![works](https://cloud.githubusercontent.com/assets/185555/16833189/3f0613e6-4a02-11e6-9ce2-7994223213f8.png)

**Comment by raymondsze** [comment]
I get this error too even not using typescript...

**Comment by raymondsze** [comment]
I found the solution right now.
babel-plugin-transform-class-properties
babel-plugin-transform-es2015-classes
add these 2 plugins to your babel config, problem will be solved.

**Comment by frederickfogerty** [comment]
@raymondsze I use typescript w/ babel (to compile ES6 -> ES5) and I use those as well to fix this issue

**Comment by philcockfield** [comment]
Cool - that move works for me too.  Alas, can't go totally pure TypeScript.  C'est la vie.

Thanks @raymondsze and @frederickfogerty.
