### ISSUE TITLE
Targeting elements with a class

### ISSUE THREAD

**Issue by sunny-mittal** [FormidableLabs/radium#78]
Hello,
Sorry to use GitHub issues to ask questions, but if I can figure this out, I think I'll be on my way to successfully using Radium! I saw in one of the examples that a scoped selector could be used to target children (i.e. using the 'scoped-selector' class on the `<p>` tag to target a nested `<span>`), but is it possible to target the element with the class itself? Meaning, in your example, how would you go about styling `p.scoped-selector`? Would I have to instead wrap everything in another sectioning tag, put the class on that, and target the first/only child?

**Comment by alexlande** [comment]
Hey @sunny-mittal, no worries about asking questions, happy to help! (Also it's a good way to find out where the docs can be improved :smile:.)

You're right that there's no way to use the `Style` component with `scopeSelector` to target the element matching the `scopeSelector` directly. I'm not sure if it's necessary, but I'd be open to exploring it more if it would be useful.

The intention is that you would apply inline styles to the parent component, and use `Style` + `scopeSelector` for descendants of that component:

```xml
<p
  class="scoped-selector"
  style={this.buildStyles(styles)}
>
  <Style
    scopeSelector=".scoped-selector"
    rules={this.buildStyles(dynamicContentStyles)}
  />
  {paragraphContent}
</p>
```

The reason for that is that `Style` is mostly meant for edge-cases that would be difficult without selectors, like user generated content (for example, rendering markdown as HTML and applying styles to generated `<a>` tags).
