### ISSUE TITLE
0.17.2 takes `content: 'none'` literally unlike 0.17.1

### ISSUE THREAD

**Issue by bebraw** [FormidableLabs/radium#780]
In 0.17.1 `content: 'none'` would yielded 'none'. In 0.17.2 it seems to yield `"none"`. This is a breaking change.

Looks like it was caused by https://github.com/FormidableLabs/radium/pull/719 .

Related: https://github.com/interactivethings/catalog/issues/155 .

**Comment by alexlande** [comment]
Thanks, will get a patch out for this asap

**Comment by alexlande** [comment]
This is fixed in `0.18.0`
