### ISSUE TITLE
We need something like nth-child

### ISSUE THREAD

**Issue by sassanh** [FormidableLabs/radium#785]
Well I know most of the times you're using an array iteration to generate elements and you can simply check index to simulate nth-child but that's not what's going on all the time.
Suppose that I have a form like this:

```
<div style={styles.registerDialogField}>
    <input
        ref='register-firstname'
        name='firstname'
        placeholder={gettext('firstname')}
    />
</div>
<div style={styles.registerDialogField}>
    <input
        ref='register-lastname'
        name='lastname'
        placeholder={gettext('lastname')}
    />
</div>
<div style={styles.registerDialogField}>
    <input
        ref='register-email'
        name='username'
        placeholder={gettext('email')}
    />
</div>
<div style={styles.registerDialogField}>
    <input
        ref='register-cell-phone'
        name='cell-phone'
        placeholder={gettext('cell-phone')}
    />
</div>
<div style={styles.registerDialogField}>
    <input
        ref='register-national-id'
        name='national-id'
        placeholder={gettext('national id')}
    />
</div>
<div style={{...styles.registerDialogField, clear: 'right'}}>
    <input
        ref='register-password'
        name='password'
        type='password'
        placeholder={gettext('password')}
    />
</div>
<div style={styles.registerDialogField}>
    <input
        ref='register-password-confirm'
        name='password-confirm'
        type='password'
        placeholder={gettext('confirm password')}
    />
</div>
```

Now what if I need to add a padding to elements with even index? I should change `style={styles.registerDialogField}` to `style={{...styles.registerDialogField, paddingLeft: '1rem'}}` manually for all elements with even index. Now if I want to add a field on top of list I should manually (or with help of macros in my editor) move the styles. It's not the way it should be. It's dirty. It depends on editor's macros how fast you can change your code.

Solutions:

Style prop can be a `object` OR a `function`. In case it's a function Radium calls it with index and children length as parameters and it returns the style.

Another solution would be style prop has a function in one of its fields  like (`style.generator` for example) that takes index and children length and returns additional styles that should override the ones defined in style prop.

**Comment by alexlande** [comment]
As a hack, you could move those components into an array and render them, at which point you would have access to the index and length :trollface: 

This is an interesting idea, but I'm not sure that it's a large enough use case to add even more features to Radium. Separately, there's an ongoing discussion over generating real CSS instead of inline styles for pseudo-selectors, which would mean that `nth-child` and anything else would work. See #510

**Comment by sassanh** [comment]
@alexlande https://github.com/FormidableLabs/radium/issues/510 is good idea but generally I think if `Radium` wants to be a replacement for css for react it needs to support all its features and as you know css has lots of features. Css has lots of features in a dirty architecture, Radium needs to offer all those features in an intuitive and optimum architecture. So I guess either it's issue 510 or maybe a new feature to Radium it needs to eventually support it.

**Comment by clouless** [comment]
I have a nice solution you can adapt to your needs.

**Preview**

  * ![nth-child](https://cloud.githubusercontent.com/assets/12599965/16923582/396f076e-4d1b-11e6-932c-50d624b8f6ae.gif)

**JSbin**

  * https://jsbin.com/quruvuy/54/edit?js,output

Now you can reorder your divs and still the even rows get grey backgrounds.

**Comment by sassanh** [comment]
Thanks @clouless, I like your solution but I think if Radium is not going to have https://github.com/FormidableLabs/radium/issues/510 it needs to implement a more general version of your snippet and provide it to users as a utility component. Otherwise everyone using Radium who wants to keep his code clean and wants to be able to code fast needs to implement it himself or copy it from here or there or install a package probably called `radium-helpers`.

**Comment by alexlande** [comment]
Going to close this in favor of #510. I don't think that Radium's scope is going to increase to include extra utility components for things like this. @clouless's JSbin is a great example of how to accomplish things like this in Radium as it is today.
