### ISSUE TITLE
radium@0.18.1 postinstall?

### ISSUE THREAD

**Issue by 123ndy** [FormidableLabs/radium#794]
When doing `npm install radium --save` I get this response:

```
> radium@0.18.1 postinstall /Users/ole/Documents/webapps/rewebapp/node_modules/radium
> cd lib || npm run lib
```

This did not happen when I was installing 0.17.1 back in the days. Why do I get asked to do this? (I also get `missing script: lib`, when trying to do it).

(After updating to `0.18.1`, I also get an error with `radium-grid`: https://github.com/FormidableLabs/radium-grid/issues/58)

**Comment by alexlande** [comment]
Hrm. I'll try to repro this (and push a new version if it's broken) later today. Sorry about that!
