### ISSUE TITLE
Use of context causes react-redux performance issue

### ISSUE THREAD

**Issue by foiseworth** [FormidableLabs/radium#811]
TLDR: if you use react-redux and radium together then you're likely to encounter an issue where you experience degraded performance.

react-redux issue: https://github.com/reactjs/react-redux/issues/366

I opened this issue to discuss mitigation and also to make people aware of this issue. As a temporary fix I have forked radium and remove the getChildContext call from the enhancer.

This PR to react-redux fixes the issue but its not clear when or if it will land: https://github.com/reactjs/react-redux/pull/416

**Comment by alexlande** [comment]
Thanks, good to know!

**Comment by alexlande** [comment]
That `react-redux` PR landed and was released early this year, so this shouldn't be an issue anymore.
