### ISSUE TITLE
display: flex is changed into display: -moz-box;  on firefox 48 mobile

### ISSUE THREAD

**Issue by realcr** [FormidableLabs/radium#815]
I am using Firefox 48 on an HTC Sensation XL with Android.
Before Radium:

```
    loginWrapper: {
        display: "flex",
        flexDirection: "column",
        flexWrap: "nowrap",
        alignItems: "center",
    },
```

After Radium on Firefox 48 on mobile device (**The bogus behaviour**):

```
    loginWrapper: {
        display: -moz-box;
    },
```

After Radium on Firefox 48 on my desktop, which is **the expected behaviour**:

```
    loginWrapper: {
        display: flex;
        flex-flow: column nowrap;
        align-items: center;
    }
```

I assume that the problem might be related to user agents, so I include here the relevant user agents:

Desktop firefox 48:

```
navigator
Navigator { permissions: Permissions, mimeTypes: MimeTypeArray, plugins: PluginArray, doNotTrack: "unspecified", battery: BatteryManager, oscpu: "Linux x86_64", vendor: "", vendorSub: "", productSub: "20100101", cookieEnabled: true }
navigator.userAgent
"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:48.0) Gecko/20100101 Firefox/48.0"
```

Mobile firefox 48:

```
navigator
Navigator { permissions: Permissions, mimeTypes: MimeTypeArray, plugins: PluginArray, doNotTrack: "1", battery: BatteryManager, oscpu: "Linux armv7l", vendor: "", vendorSub: "", productSub: "20100101", cookieEnabled: true }
navigator.userAgent
"Mozilla/5.0 (Android 4.2.2; Mobile; rv:48.0) Gecko/48.0 Firefox/48.0"
```

How can this be solved?

**Comment by ratiotile** [comment]
Could this be related to issue #818 ?
I can confirm that in Chromium 51, `flex: display` is rendered as:

```css
    -webkit-box-align: center;
    -webkit-box-pack: center;
```

**Comment by realcr** [comment]
I opened a pull request at the inline-style-prefixer:
https://github.com/rofrischmann/inline-style-prefixer/pull/96
to fix this issue.

**Comment by realcr** [comment]
@ratiotile: Can you send you exact userAgent string? Your issue might be related. Write 
```
navigator.userAgent
```
at your browser console. I will check it against inline-style-prefixer's browser identifier util. You can also check it yourself against the code at https://github.com/rofrischmann/inline-style-prefixer/blob/master/modules/utils/getBrowserInformation.js

**Comment by ratiotile** [comment]
"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/51.0.2704.79 Chrome/51.0.2704.79 Safari/537.36"

**Comment by realcr** [comment]
I get that
```
getBrowserInformation("Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/51.0.2704.79 Chrome/51.0.2704.79 Safari/537.36")
```
results in:
```
{ name: 'Chromium',
  chromium: true,
  version: 51,
  blink: true,
  linux: true,
  a: true,
  prefix: { inline: 'Webkit', css: '-webkit-' },
  browser: 'chrome',
  osversion: NaN }
```
which is somewhat reasonable. I don't know where you problem comes from. I did manage to reproduce it by installing chromium (51.0.2704) on Ubuntu 16.04 and redering {display: "flex"}. We should dig some more into this.

**Comment by begincalendar** [comment]
When I use Chromium, `display: flex` gets rendered as:
```
    -webkit-box-orient: vertical;
    -webkit-box-direction: normal;
    -webkit-box-pack: justify;
    -webkit-box-align: center;
```
...and Chromium doesn't render things properly.

When I use Chrome, `display: flex` gets output and Chrome renders it as it should.

**Comment by omryr** [comment]
was this fixed?

**Comment by alexlande** [comment]
This should have been fixed in an inline-style-prefixer upgrade, and we'll plan on upgrading to the latest shortly to resolve any lingering prefixer issues.
