### ISSUE TITLE
SyntaxError using Create React App

### ISSUE THREAD

**Issue by henrylingumi** [FormidableLabs/radium#816]
Hi I'm trying to use Radium with Create React App, I've installed Radium but struggling for ideas as to why it wouldn't work:

```
client:47 ./src/components/Blackboard.js
Module build failed: SyntaxError: /src/components/Blackboard.js: Unexpected token (5:0)
  3 | import Radium from 'radium'
  4 | 
> 5 | @Radium
    | ^
  6 | class Blackboard extends Component {
  7 | 
  8 |   render() {
```

Please let me know if you have any ideas.

**Comment by ianobermiller** [comment]
We should probably add something to the documentation about getting started with decorators. They are an ES2017 proposal and not included in a basic Babel setup like you have with `create-react-app`. You can instead use the functional version `export default Radium(Component);`.

**Comment by alexlande** [comment]
Closing in favor of #924.
