### ISSUE TITLE
Flexbox broken in Chromium

### ISSUE THREAD

**Issue by ratiotile** [FormidableLabs/radium#818]
I have a Radium wrapped component which uses the `display: 'flex', alignItems: 'center'`  style. In Chromium `Version 51.0.2704.79 Built on Ubuntu 14.04, running on LinuxMint 17.1 (64-bit)` the rendered css is missing `display: 'flex'`, and only contains `align-items: 'center'`. Removing the Radium wrapper around the component: `Radium(class ...)`, causes it to render correctly.

Firefox on the same machine, and Chrome under Windows both render correctly.

**Comment by realcr** [comment]
I managed to reproduce this problem on Ubuntu 16.04. Firefox and Chrome on the same machine work correctly.

**Comment by philiptzou** [comment]
Maybe related with #822.

**Comment by dmatteo** [comment]
## tl;dr;
Please publish a new minor or patch of `radium` and this will be fixed as well

## Longer version:
The problem seems to be `inline-style-prefixer-all@1.0.4`, which is a dependency of `inline-style-prefixer@1.x`. Radium `0.8.1` depends on it.
 
I was able to workaround this problem by forking `radium` and using `npm link` from master, since you've updated your dependency over `inline-style-prefixer` to be `^2.0.1`, which does not depend on `inline-style-prefixer-all` anymore.

This fixed the issue, or actually, removed the problematic dependency

**Comment by dmatteo** [comment]
Obviously, installing from radium/master works as well.

**Comment by limpbrains** [comment]
Please publish new version of the radium, with this fix

**Comment by puzzfuzz** [comment]
Any movement on this? We just ran into this issue as well after updating to the latest stable. Seems pretty major to just not support flex on Chromium?

**Comment by Outpox** [comment]
Can also reproduce in Vivaldi (which is based on Chromium).

**Comment by pcorpet** [comment]
0.8.2 has been released, this should be resolved now.

**Comment by ratiotile** [comment]
Thanks! I will test it soon.

**Comment by omryr** [comment]
did this work for anyone? im trying to support a chromium based browser (yandex) and display: flex
turns to : 
    -webkit-box-align: stretch;
    -webkit-box-direction: normal;
    -webkit-box-orient: vertical;

**Comment by pcorpet** [comment]
It worked for me.

**Comment by ratiotile** [comment]
The new version fixed the problem.

**Comment by cjimmy** [comment]
I'm not sure why, but this is still happening to me. I have an inline style that includes `display: 'flex'` and when it shows up in Chrome or Firefox, that line is not present in the inline style. When I remove Radium, it's fine. Oddly, this is not the case when running a local dev server, but only in production. 

I'm on Radium 0.19.6 and the aforementioned module `inline-style-prefixer` is at `^2.0.5`. Any thoughts on why this is happening?
