### ISSUE TITLE
Eliminate modifiers

### ISSUE THREAD

**Issue by ianobermiller** [FormidableLabs/radium#82]
In my quest to simplify Radium, I propose we eliminate modifiers. Instead, if we implement something like #80, we can make the style object accept an array, and apply provided styles in order (ignoring non-object ones) [1]. Also, in this way, the component author can choose whether or not to include this.props.style. Finally, each state can specify :hover or :active states, and the merging would have to be somewhat intelligent about it [2]. I posit that this behavior is less magical than modifiers, and much more explicit & flexible.

[1]
```js
var Button = React.createClass(Cesium.wrap({
  propTypes: {
    use: PropTypes.oneOf(['default', 'special']),
    style: PropTypes.object,
  },

  render(): any {
    return (
      <button
        type="button"
        style={[
          styles.root,
          (this.props.use === 'default') && styles.default,
          (this.props.use === 'special') && styles.special,
          this.props.style
        ]} />
    );
  }
}));

var styles = {
  root: {
    border: 'none',
    borderRadius: '2px',
    cursor: 'pointer',
    lineHeight: '30px',
    margin: 0,
    padding: '1px 16px',
    verticalAlign: 'top',

    ':active': {
      padding: '2px 15px 0 17px',
    },
  },

  default: {
    background: Colors.gray1,
    color: Colors.black,

    ':hover': {
      background: Colors.gray1.darken(5),
    },
  },

  special: {
    background: Colors.accent,
    color: Colors.white,

    ':hover': {
      background: Colors.accent.darken(5),
    },
  },
};
```

[2]
```js
// Merge style objects. Special casing for props starting with ';'; the values
// should be objects, and are merged with others of the same name (instead of
// overwriting).
function _mergeStyles(...styles: Array<Object|boolean>): any {
  var styleProp = {};

  styles.forEach(style => {
    if (!style || typeof style !== 'object') {
      return;
    }

    var styleObj: Object = style; // flow :(

    Object.keys(styleObj).forEach(name => {
      if (name.indexOf(':') === 0) {
        styleProp[name] = styleProp[name] || {};
        Object.assign(styleProp[name], styleObj[name]);
      } else {
        styleProp[name] = styleObj[name];
      }
    });
  });

  return styleProp;
}
```

**Comment by alexlande** [comment]
I tend to think that the convenience of handling modifiers is one of our better features. Your example is ok for a couple of modifiers (although still a bit verbose for such a common behavior, IMO):

```js
style={[
  styles.root,
  (this.props.use === 'default') && styles.default,
  (this.props.use === 'special') && styles.special,
  this.props.style
]}
```

For radium-bootstrap buttons, you would probably want to do something like this:

```js
style={[
  styles.root,
  this.props.kind && styles.kind[this.props.kind],
  this.props.size && styles.size[this.props.size],
  this.props.block && styles.block,
  this.props.disabled && styles.disabled,
  this.props.active && styles.active,
  (this.props.active && this.props.kind === 'link') && styles.activeLink,
  this.props.style
]}
```

This feels like a lot of boilerplate to me. If you want to be really explicit about modifiers, you can do the same thing with the `additionalModifiers` + `excludeProps` parameters in `buildStyles()` (https://github.com/FormidableLabs/radium/tree/master/docs/api#buildstyles)

```js
var styles = this.buildStyles(radStyles, {
  (this.props.use === 'default') && styles.default,
  (this.props.use === 'special') && styles.special,
}, true);
```

**Comment by ianobermiller** [comment]
The nice thing about the `conditional && style` syntax is that it covers all of the cases, reducing three concepts (modifiers, additionalModifiers, and excludeProps) into one. I am fairly strongly opinionated on this one, as I really dislike the "magical" connection of props -> modifiers. Perhaps renaming `modifiers` to something that indicates that they are styles that get applied due to props, like `stylesByProp` might help?

**Comment by alexlande** [comment]
Right, but it means that you need to explicitly handle modifiers every time. I would expect most people to only use `additionalModifiers` and `excludeProps` as necessary or if they want completely explicit modifier handling.

I think optimizing for the most common use case (where modifiers are based on props) makes sense.

I don't have particularly strong feelings about renaming modifiers to something like `stylesByProp`, except that I prefer `modifiers` because a modifier is a general CSS concept, not something specific to React or Radium.

**Comment by alexlande** [comment]
@ianobermiller: Welp, given the way React Native handles this, I am more open to this idea. It makes sense to me that Radium would align as closely as possible to the implementation there.

http://facebook.github.io/react-native/docs/style.html#using-styles

**Comment by ianobermiller** [comment]
Good point! I forgot all about that in React Native. Do you mind if I do this in the same pull request as the wrap conversion, or would you prefer them to be separate?

**Comment by alexlande** [comment]
I'm fine with it all being in one PR.

**Comment by colinmegill** [comment]
Looking forward to this
ᐧ

**Comment by alexlande** [comment]
Done!
