### ISSUE TITLE
Having a hard time understanding why you need <StyleRoot>

### ISSUE THREAD

**Issue by FarhadG** [FormidableLabs/radium#828]
I've included it at the top level of my apps, however, I'm still unclear as to why the `StyleRoot` is needed and where it's necessary. Is it always needed? If not, when should you include it? If it is, what is it meant for?

Thank you. Sorry, I read the guides several times but still unclear for me...

**Comment by ianobermiller** [comment]
`StyleRoot` is required for plugins that add CSS; currently only keyframes, media queries, and `:visited` require it. There is more information about `StyleRoot` in the docs: https://github.com/FormidableLabs/radium/tree/master/docs/api#styleroot-component
