### ISSUE TITLE
Uncaught TypeError: this.getBrowserStateEvents is not a function

### ISSUE THREAD

**Issue by mrbarde** [FormidableLabs/radium#831]
Get browser state seems to not be working

```
<div style={styles.search.container}>
    <form {...this.getBrowserStateEvents()} style={styles.search.form}>
        <input type="text" style={styles.search.input} />
	<button type="submit" style={styles.search.button}></button>
    </form>
</div>
```
Am I missing something her?

**Comment by Aweary** [comment]
Hey @mrbarde, I believe `getBrowserStateEvents` was removed from the API a long time ago. See https://github.com/FormidableLabs/radium/issues/80. What version are you using?

If you're using the latest, you can see the latest API docs [here](https://formidable.com/open-source/radium/docs/api).

**Comment by alexlande** [comment]
Yep, that's correct. Thanks @Aweary!
