### ISSUE TITLE
Any tuto on how to test react component wrapped in Radium?

### ISSUE THREAD

**Issue by thomasdola** [FormidableLabs/radium#847]
I have some buttons that only show on ':hover'. 
Am testing to see that the buttons are rendered but enzyme 'shallow' cannot see them render.
Is there any way to simulate the 'hover' state? Then i can check to see if they show or not?
any help is much appreciated ...

**Comment by acondiff** [comment]
Any answer for this?

**Comment by philpl** [comment]
@acondiff You can simulate events using enzyme: https://github.com/airbnb/enzyme/blob/master/docs/api/ShallowWrapper/simulate.md

You'd probably want to use `.simulate('mouseEnter')`.
