### ISSUE TITLE
Do you have a plan to support mobile style? like :active

### ISSUE THREAD

**Issue by JimmyVV** [FormidableLabs/radium#856]
this repository is so good, but now, I  am focusing on mobile development. so what a pity. I fing this repository cound resolve the pseudo-selectors on mobile like :active. And I think active state is the most important thing in mobile.

**Comment by grant** [comment]
There should be support for pseudo-classes like `:active` as shown in the README.

https://github.com/FormidableLabs/radium#usage

**Comment by JimmyVV** [comment]
Yeah, I know, I mean you don't supprt pseduo-classes like `:active` on mobile.

**Comment by lifeiscontent** [comment]
@grant from my testing, I can't seem to get `:active` pseudo classes to work. `:hover` works fine though.

**Comment by alexlande** [comment]
Hey all, check out https://github.com/FormidableLabs/radium/issues/63 for more details on this one. Short version is that it's definitely a goal, but ideally Radium would generate CSS rather than using pure inline styles, which would solve this and lots of other problems too.
