### ISSUE TITLE
Wrapping App component in StyleRoot throws error

### ISSUE THREAD

**Issue by RajeshSivanesan** [FormidableLabs/radium#858]
import React, {Component} from 'react';
import {AppRegistry, View} from 'react-native';
import {App} from '..';

export class newApp extends Component {
	render() {
		return (
			<StyleRoot>
				<App>...</App>
			</StyleRoot>
		);
	}
}

AppRegistry.registerComponent('appname', () => newApp ) ;

Getting Error as Expected a component class, but got [object object]. If i remove style root I am able to load the components, but in my project I need to use keyframes, during that it asks me to wrap the app component under styleRoot. 

Please help me in fixing this issue.

**Comment by ryan-roemer** [comment]
Can you update to latest radium and check if this is still an issue?

If it is, can you open up a small repository with code + steps to reproduce the issue you see? Thanks!

**Comment by ryan-roemer** [comment]
Closing as `no repro`. Feel free to open with a reproduction if this is still an issue. Thanks!
