### ISSUE TITLE
Anyway to have a label respond to :focus CSS

### ISSUE THREAD

**Issue by nizarayari** [FormidableLabs/radium#859]
Is there any way to have a label tag style respond when I focus in an input.

I have something like:

html:
`<input style={styleLogin.input} key={1} type="text" id="Username" required="required"/>
  <label htmlFor="Username">Email Adress</label>`

I tried something like that because that how it works in css(input:focus + label):
`styleLogin:{
        input:{
        fontWeight: '400',
         ':focus + label': {
          color: '#9d9d9d',
          transform: 'translate(-12%, -50%) scale(0.75)'
        }
    }
}`

**Comment by daniloprates** [comment]
You can use Radium's [getState][1]. Have a look in this [example fiddle][2].

[1]: https://github.com/FormidableLabs/radium/tree/master/docs/guides#styling-one-element-depending-on-anothers-state

[2]: https://jsfiddle.net/daniloprates/u35wv3hh/1/

**Comment by alexlande** [comment]
Thanks for helping on this one @daniloprates 🤘
