### ISSUE TITLE
Radium and React.PureComponent

### ISSUE THREAD

**Issue by walshie4** [FormidableLabs/radium#861]
From the README
>How does Radium work?
>
>Following is a short technical explanation of Radium's inner workings:
>
>Wrap the render function
>Recurse into the result of the original render
>For each element:
>Add handlers to props if interactive styles are specified, e.g. onMouseEnter for :hover, wrapping existing handlers if necessary
>If any of the handlers are triggered, e.g. by hovering, Radium calls setState to update a Radium-specific field on the components state object
>On re-render, resolve any interactive styles that apply, e.g. :hover, by looking up the element's key or ref in the Radium-specific state

Hello!  I recently upgraded past [React v15.3.0](https://github.com/facebook/react/releases/tag/v15.3.0) which adds `React.PureComponent`.  Curious how Radium impacts these components, specifically their performance.  

EDIT - Did some poking around through the source and found https://github.com/FormidableLabs/radium/blob/master/src/enhancer.js#L49. Looks like it is wrapped in a normal component. ☹️

**Comment by ianobermiller** [comment]
The code you pointed to is only for stateless components, which wouldn't get, and shouldn't need the benefits of `PureComponent` anyway. For normal classes, Radium inherits from the existing class, preserving whichever base class you originally had.
