### ISSUE TITLE
Comparison with glamor

### ISSUE THREAD

**Issue by planttheidea** [FormidableLabs/radium#871]
Considering its recent rise in popularity (it is espoused by Next.js), I think that including [glamor](https://github.com/threepointone/glamor) in the comparison would be advantageous.

**Comment by ianobermiller** [comment]
I'd happily accept a PR :)

**Comment by alexlande** [comment]
I think I'm going to close this one out, and probably drop the CSS-in-JS comparison table. It was great at the time but it's out of date now and probably doing more harm than good. Lots of great libraries in this space these days, and it would be cool if someone else wanted to put together a nice comparison of them.
