### ISSUE TITLE
import radium (using lower case 'r') not working.

### ISSUE THREAD

**Issue by kjetilge** [FormidableLabs/radium#872]
In my Meteor, react, apollo project I'm currently forced to import radium like this:
```
import Radium from 'Radium'
```
If I try
```
import Radium from 'radium'
```
I get:
```
Uncaught Error: Cannot find module 'radium'
```

But when I use kadira/storybook it looks for 'radium' not 'Radium'. Any idea what to do about this ?

**Comment by jameskraus** [comment]
I don't really understand why storybook would be looking for a variable called 'radium', but have you tried `const radium = Radium'?

Also, kadira/storybook is the old version of storybook, you could always upgrade to the [latest version ](https://github.com/storybooks/storybook)

**Comment by ryan-roemer** [comment]
@kjetilge -- I don't use Meteor, so can you put together a small project publicly with steps to reproduce the issue?

The `package.json:name` is lower-case `radium` (cf https://www.npmjs.com/package/radium). And it should be `import Radium from 'radium'` or `const Radium = require('radium')`. Something is going on weird in the meteor setup if this is not the case. And `from 'Radium'` shouldn't work except maybe on like case-insensitive file systems (which is actually applicable on Mac OS).

**Comment by ryan-roemer** [comment]
No reproduction, so closing.
