### ISSUE TITLE
Testing with Jest - Invariant Violation

### ISSUE THREAD

**Issue by fi5u** [FormidableLabs/radium#873]
When testing my React component (which uses Radium) with Jest, I get the error:
```
Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in.
```

However, when I remove the call to Radium from my component, the test passes. I'm exporting the component like this:
```
export default Radium(MyComponent)
```

Is there anything special I should do to test files using Radium?

**Comment by sawatsky** [comment]
I am getting the exact same issue.
This works:
`export default (props) => { return <div>Testing</div> }`

However, when I wrap the function in Radium:
`export default Radium((props) => { return <div>Testing</div> });`

I receive this error:
**Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in.**

Versions:
"jest": "~18.1.0",
"react": "^15.4.2",
"radium": "^0.19.1",

**Comment by ryan-roemer** [comment]
@sawatsky @fi5u -- Can either of you confirm if this issue is still present in modern Radium?

I attempted to open a failing regression test, but the following code passed:

```diff
diff --git a/src/__tests__/fixtures/export-wrapped.js b/src/__tests__/fixtures/export-wrapped.js
new file mode 100644
index 0000000..cf10329
--- /dev/null
+++ b/src/__tests__/fixtures/export-wrapped.js
@@ -0,0 +1,8 @@
+import React from 'react';
+import Radium from 'index';
+
+// Fixture for regression test
+// https://github.com/FormidableLabs/radium/issues/873
+export default Radium(() => (
+  <div style={{color: 'blue', ':hover': {color: 'red'}}} />
+));
diff --git a/src/__tests__/radium-test.js b/src/__tests__/radium-test.js
index 6432b4e..79df47a 100644
--- a/src/__tests__/radium-test.js
+++ b/src/__tests__/radium-test.js
@@ -8,6 +8,8 @@ import ReactDOM from 'react-dom';
 import TestUtils from 'react-dom/test-utils';
 import {getRenderOutput, getElement} from 'test-helpers';
 
+import Wrapped from './fixtures/export-wrapped';
+
 describe('Radium blackbox tests', () => {
   let sandbox;
 
@@ -770,6 +772,19 @@ describe('Radium blackbox tests', () => {
   });
   /* eslint-enable no-console */
 
+  // Regression test
+  // https://github.com/FormidableLabs/radium/issues/873
+  it('handles default wrapped exports', () => {
+    const output = TestUtils.renderIntoDocument(<Wrapped />);
+    const div = getElement(output, 'div');
+
+    expect(div.style.color).to.equal('blue');
+
+    TestUtils.SimulateNative.mouseOver(div);
+
+    expect(div.style.color).to.equal('red');
+  });
+
   describe('config', () => {
     it('receives config from radiumConfig prop', () => {
       const plugin = sinon.spy();
```

If it's still an issue on modern Radium can you either (1) (preferable) open a PR with a failing regression test like I have attempted above, or (2) a sample minimal repository that exposes the issue with install and error reproduction steps?

Thanks!

**Comment by fi5u** [comment]
Radium is no longer part of our testing process, so unfortunately I cannot confirm if this is still an issue.

**Comment by ryan-roemer** [comment]
OK. Thanks for the note!
