### ISSUE TITLE
bower installation is missing most of the library

### ISSUE THREAD

**Issue by dmatteo** [FormidableLabs/radium#875]
The library is not present when running `bower install --save radium`.

All I get in return is:
```
app/assets/javascripts/bower_components/radium
├── LICENSE-examples.md
├── bower.json
├── interfaces
│   └── inline-style-prefixer.js
├── karma.conf.ie.js
└── npm-scripts
    └── move-babel-to-dependencies.js
```

There is no `dist`

---

Version `v0.16.0` seems to be the last one to have a `dist` folder.
I then disappears in `v0.16.1` and later versions.

Looking at the tag history, the culprit seems to be the fact there actually is no `dist` folder anymore, starting with tag `0.16.1`. 

Is this on purpose or simply somebody forgot to compile for bower in the past year or so? 😄

**Comment by ryan-roemer** [comment]
`dist` was removed from git source with https://github.com/FormidableLabs/radium/commit/e121b73783952af2a60b30f6bc402f790ec7aa87

`dist` is present via:

1. `npm` registry
2. taking an `npm` `git` dependency on this repo (which will build `dist` from scratch as a part of `npm` install lifecycle)

Fortunately for bower, everything in the npm registry is available on the web via the awesome https://unpkg.com/. So, for example, you can just take bower deps on:

1. Dev: https://unpkg.com/radium@0.18.1/dist/radium.js
2. Prod: https://unpkg.com/radium@0.18.1/dist/radium.min.js

We probably should:

1. Update the README
2. Remove https://github.com/FormidableLabs/radium/blob/master/bower.json

/cc @alexlande @ianobermiller

**Comment by dmatteo** [comment]
That makes sense. Everybody is ditching bower these days, including unpkg

> We do NOT recommend JavaScript libraries use Bower. Bower places additional burdens on JavaScript package authors for little to no gain. unpkg is intended to make it easier to publish code, not harder, so Bower support will be removed in January 2017. Please move to npm for installing packages and stop using Bower before that time. 

I wish I could do that as well 😄 
Because of how the app is structured, I can't go the `npm git` way either, at least not out of the box.

Anyway, npm + browserify + some moving around will do the trick.

Thanks!

**Comment by ryan-roemer** [comment]
Actually, I meant in your `bower.json`, you should be able to:

```js
"dependencies": {
  "radium": "https://unpkg.com/radium@0.18.1/dist/radium.min.js"
}
```

And that should work straight up with bower. You lose some things like the ability for bower to determine if there's an updated version, etc., but importantly it (1) should work within your existing bower build pipeline, and (2) will remain reliable no matter what unpkg does with structural bower support (for `bower.json` and other things).

Put another way, URLs to a single JS file on the internet should categorically always work with bower.

**Comment by dmatteo** [comment]
That's interesting, I didn't know bower could do that.

Thanks a lot!
