### ISSUE TITLE
Throws error on widnows 7: npm run universal

### ISSUE THREAD

**Issue by rajivkulkarni** [FormidableLabs/radium#876]
![image](https://cloud.githubusercontent.com/assets/4139581/23083466/6910b598-f523-11e6-8924-0cebac9d49c8.png)

**Comment by stefvhuynh** [comment]
Were you able to get this to work? Perhaps another process was running on that port?

**Comment by ryan-roemer** [comment]
Closing as likely just another process. Feel free to reopen if it looks like something related to Radium itself. Thanks!
