### ISSUE TITLE
Styling third party components

### ISSUE THREAD

**Issue by Glazy** [FormidableLabs/radium#881]
Using 'react-typeahead' and want to style this component using Radium. Component takes custom styles in a prop but you have to supply class names.

How can I style this component?

**Comment by Rom2711** [comment]
Two ways come to mind, 
1) apply radium within the react-typeahead package
2) Wrap the react-typeahead in  wrapper component and style the wrapper

Personally, I don't believe path #1 is sustainable.  

A third solution that's not a solution in this case, would be to only use components that allow control of component styling to be inverted.

**Comment by Glazy** [comment]
You're right, editing the package is unsustainable and sadly wrapping the react-typeahead component in a wrapper isn't really a feasible solution either.

Will have to find another way to style it, thanks anyway!
