### ISSUE TITLE
why is old version of package in npm server

### ISSUE THREAD

**Issue by juwoni** [FormidableLabs/radium#882]
inline-style-prefixer is still old version, how can i solve this problem?
https://npmcdn.com/radium@0.18.1/package.json
 "dependencies": {
    "array-find": "^1.0.0",
    "exenv": "^1.2.0",
    "inline-style-prefixer": "^1.0.3",
    "rimraf": "^2.4.0"
  },

**Comment by ianobermiller** [comment]
Because we haven't released to NPM in a long time :)

fixed in 310a376
