### ISSUE TITLE
Docs: ‘View Radium Docs’ button broken in Firefox 52

### ISSUE THREAD

**Issue by ludovicofischer** [FormidableLabs/radium#883]
I’m using Firefox 52 on Fedora (Linux) 25. When I load http://formidable.com/open-source/radium/ and click the ’View Radium Docs’ button, nothing happens. 
When I click on the same button in Chrome 57, http://formidable.com/open-source/radium/docs loads.
I don’t see any console errors in Firefox.

**Comment by ryan-roemer** [comment]
cc @eliseworthy @redfieldstefan

**Comment by redfieldstefan** [comment]
Fixed in `radium-docs` via https://github.com/FormidableLabs/radium-docs/pull/44
