### ISSUE TITLE
v0.18.2 breaks repositories that still support React 0.14.x

### ISSUE THREAD

**Issue by ahoym** [FormidableLabs/radium#885]
Hello!

I've started noticing that libraries that support react 0.14.x, but have `radium` as a dependency, are starting to choke up errors saying a component can't extend from `undefined`. Going through your recent history, it looks like you patch bumped to `0.18.2`, but are now extending from `React.PureComponent` instead of `Component` now, because of this #868.

`PureComponent` was introduced in react 15, so any library that supports 0.14.x but pins radium at `^0.18.0` or even `~0.18.0` will be breaking for consumers of their libraries.

**Comment by ianobermiller** [comment]
Ah, radium should probably list React in peerDependencies. Then at least you'd know this at install time.
