### ISSUE TITLE
Editing element styles in Chrome dev-tools

### ISSUE THREAD

**Issue by Venryx** [FormidableLabs/radium#888]
The Chrome dev-tools seem unable to edit the styles of Radium-enabled elements at runtime.

I edit the css in the "styles" panel of the "Elements" tab, and as soon as I hit "enter", the style/property just reverts back to its original value.

This is true whether I edit an existing style/css-prop, or whether I add a new one.

Here's a gif demonstrating the issue:
![](http://i.imgur.com/X3oGJ1t.gif)

Any idea how to "override" the Radium-set styles using the dev-tools?

I like using the dev-tools for quickly testing font-sizes and the like, but at the moment I'm forced to edit the source files for Radium components. (either that or give it a temporary id, and add a "style" tag with "!important" applied, which is also a pain)

**Comment by lopis** [comment]
I tried this but couldn't reproduce your issue in Chrome nor in Firefox so something more specific to your case might be happening.

**Comment by stefvhuynh** [comment]
I was also unable to reproduce this issue.

**Comment by Venryx** [comment]
I don't know what the cause is, but if other people aren't having it occur, then I guess the issue can be closed. (for my project, I just transitioned away from Radium for the really common elements, like buttons -- which mostly works around the problem)

If it causes substantial headaches again later, I'll re-open the issue and try to provide a repro case.
