### ISSUE TITLE
Element queries

### ISSUE THREAD

**Issue by akomm** [FormidableLabs/radium#890]
What do you think about using [css-element-queries](https://github.com/marcj/css-element-queries) to provide element queries in addition to media? Specifically the [ResizeSensor](https://github.com/marcj/css-element-queries/blob/master/src/ResizeSensor.js).

**Comment by stefvhuynh** [comment]
hello @akomm, is there a reason accessing the nodes directly via `refs` wouldn't work for your use case?

**Comment by alexlande** [comment]
This would be cool, but probably out of scope for the library. With our media queries using plain CSS now, and other styles potentially converging on the same, I don't expect that we'll build in more utilities for run-time style calculation.

That said, this could be done outside of Radium, I'd expect.
