### ISSUE TITLE
Publish: Switch to `publishr` and also move `rimraf` to `devDependencies` on npm registry publication.

### ISSUE THREAD

**Issue by ryan-roemer** [FormidableLabs/radium#894]
Our bespoke publication swapping script misses `rimraf` because it only greps on `babel` in https://github.com/FormidableLabs/radium/blob/master/npm-scripts/move-babel-to-dependencies.js#L6

`rimraf` isn't actually a real prod dependency.

Task:

- [ ] Remove `move-babel-to-dependencies.js` (because it will not work in the future. See #900 )
- [ ] Refactor to use https://github.com/FormidableLabs/publishr and regex swap on babel and rimraf ( @jmcriffey could you help us here?)
- [ ] Update documentation for `npm version` preferred workflow with `publishr`.
- [ ] Update `postinstall` to be removed on npm publish. And remove `cd lib || ` section. Same as Victory does it. See #794 
- [ ] Check all other tickets to close.

**UPDATE**: Because of #900 we need to do `publishr`

/cc @christianalfoni

**Comment by ryan-roemer** [comment]
_Adding `bug` tag since this can break webpack / etc. since rimraf is a Node-only dependency_

**Comment by jmcriffey** [comment]
I'm happy to help with setting Radium up to use Publishr. The one caveat is that we have to shift to a npm version workflow if it is not already common practice here. I'm also happy to help by updating the `move-babel-to-dependencies.js` script. I think both paths are relatively trivial to implement, so we just need to decide which one we want to go with.
