### ISSUE TITLE
position vendor prefix not working in Safari

### ISSUE THREAD

**Issue by zikangyao** [FormidableLabs/radium#896]
I used ```position: sticky``` in my project, and it's working properly in Chrome, but turns out that it's problematic in Safari, I inspected the element, and ```position: sticky``` doesn't even show up. Would it suppose to be automatically transformed to ```position: -webkit-sticky``` ?

**Comment by stefvhuynh** [comment]
The issue seems to be within the `inline-style-prefixer v2.0.5` dependency for safari versions 10+. For safari versions under 10, using `position: sticky` works for me. I've filed an issue with them here: https://github.com/rofrischmann/inline-style-prefixer/issues/126.

**Comment by stefvhuynh** [comment]
`inline-style-prefixer` has fixed this issue. We will need to migrate over to their next release when it happens to fix this issue.

**Comment by zikangyao** [comment]
Hey Stefan, so glad to meet you here. Thank you for keeping me posted regarding the issue we run into. I will try the latest version of ```inline-style-prefixer``` and see if it solves the problem.

**Comment by zikangyao** [comment]
Also should I use 3.0.3?

**Comment by stefvhuynh** [comment]
oh hey ZK. i didn't realize it was you! yeah, looks like the maintainer made another release to 3.0.3 that should have the fix. hope things are going well at op.
