### ISSUE TITLE
Mismatch between radium registry metadata and registry package files

### ISSUE THREAD

**Issue by iarna** [FormidableLabs/radium#900]
You all are mutating your `package.json` in your `prepublish` script in a way that's unsupported.

What happens when you do this is that the version of the `package.json` published to the `registry` is the version that existed before your `prepublish` script was run. This is problematic because it's _this_ version that's used to determine what to install. This means that removing things from your `dependencies` in your `prepublish` wasn't actually reducing what `npm` installed.

By registry version, I mean things like [https://registry.npmjs.org/radium/0.18.2](https://registry.npmjs.org/radium/0.18.2).

Prior to `npm@4.5.0` we would write the `package.json` we got from the registry into the installed module in your `node_modules`. This meant that those were always in sync, which meant that while your tarball had a `package.json` with a smaller dependencies list, it had no impact on the initial or subsequent installs.

Starting with `npm@4.5.0`, we started requesting filtered versions of the `package.json` information from the registry. These filtered versions are sufficient for us to determine what modules to install for you, but are otherwise (intentionally) incomplete. So as of `npm@4.5.0` we no longer write out the version of the `package.json` we got from the registry and instead leave the version from the tarball. 

Because your tarball has a `package.json` that's different, this means that users are told that npm has installed extraneous modules. ([npm/npm#16517](https://github.com/npm/npm/issues/16517))

Going forward we're going to:

* Patch npm to copy over as much information from the `package.json` in the registry version. This will have the short term impact of no longer having these extra dependencies marked as extraneous. It will also make npm@4 and npm@5 match older versions of npm@4 and npm@3's behaviors.

* Add a publish-time validator that rejects publishes when these two are out of sync.

* Possibly patch `npm publish` to reread its `package.json` after each lifecycle script.

What you all should do:

* Publish a new version that has is out of alignment between the two. This means not running `deps-fix` and `deps-restore` in the publish lifecycles.

As an aside:

Am I correct in thinking that you're doing this so that your module is installable via git (eg `npm install github:FormidableLabs/radium`) in addition to via the registry?

**Comment by ryan-roemer** [comment]
@iarna -- Thanks for the detailed writeup, and I haven't completely digested this, but yikes! I think we always assumed we could do any git-dirty changes before things got published and whatever actually ended up in the registry's version of `package.json` would control.

In a lot of our other projects, we use https://github.com/FormidableLabs/publishr to do something similar, leveraging `npm version` workflows with `postversion` mutating package.json and then `postpublish` restoring it. Is that approach also likely to fall afoul with current / future npm plans like here?

I'll dig into your comment and links more tomorrow / next week..

**Comment by iarna** [comment]
Pairing _postversion_ and _postpublish_ lifecycles should work fine, as the `package.json` will be updated before you run `npm publish`.

**Comment by ryan-roemer** [comment]
Whew!

Yeah, in a project where we use that we use that approach and `publishr` we have:

- https://registry.npmjs.org/victory/0.18.4
- https://unpkg.com/victory@0.18.4/package.json

which match and notably _don't_ have dependencies like `builder`, etc. that get swapped on publish to devDependencies and then reverted for the real git state of https://github.com/FormidableLabs/victory/blob/master/package.json

@jmcriffey @alexlande @ianobermiller -- I think we want to switch to `publishr` soon and do these tickets along the way:

- https://github.com/FormidableLabs/radium/issues/894
- https://github.com/FormidableLabs/radium/issues/731 (just close this one).

**Comment by ryan-roemer** [comment]
@iarna -- I'll try and confirm we've fixed the problem on our end after we switch to `publishr`

To answer your original query which I missed -- Yes, we do this to support `git:`-based dependencies which need to build things not in git -- usually `dist/` and `lib/` -- from scratch (great for PR-ing, temporary working sub-dependencies, etc.).

Finally, thank for the very detailed and useful comment. We ❤️ y'all over in `npm`-land. Keep up the awesome work!

**Comment by iarna** [comment]
It'll be a while before you can rely on it, but soon, soon you'll get to stop having to special case installs from git! (@zkat and I worked out the remaining details last night and:  https://twitter.com/maybekatz/status/860363896443371520)

**Comment by ryan-roemer** [comment]
@iarna -- I think we've fixed this in this PR https://github.com/FormidableLabs/radium/pull/914 and npm release `radium@0.19.2`+. If you get a chance to check things out, please do let us know if anything looks wrong with our new scheme for publishing.

Thanks!!!
