### ISSUE TITLE
Add inline-style-prefixer plugins

### ISSUE THREAD

**Issue by obituz** [FormidableLabs/radium#901]
Hi,

is there any way to use the [inline-style-prefixer](https://github.com/rofrischmann/inline-style-prefixer) plugins in radium? I'd like to use ```position: sticky``` [(plugin)](https://github.com/rofrischmann/inline-style-prefixer/blob/master/modules/dynamic/plugins/position.js) and it's not very comfortable to write two classes for a single property which is the current workaround:

```javascript
classA: {
   position: 'sticky'
},
classB: {
   position: '-webkit-sticky'
} 
```

Thanks in advance and for this nice lib!

**Comment by kylecesmat** [comment]
We do not intend to expose these plugins, we depend on `inline-style-prefixer` for basic prefixing and don't intend to expand that.
