### ISSUE TITLE
Animations not working as expected in IE

### ISSUE THREAD

**Issue by caddac** [FormidableLabs/radium#904]
I am using Radium keyframes to build a fade-in animation. The animations work as expected in Chrome, however in IE 11 they do not work at all. One interesting thing I noticed is that if I remove & add the animation name in IE Developer Tools (by unchecking and checking the 'animation-name' style) the animation works. 

I'm using the latest version of Radium. I tried to create a JsBin to reproduce the issue but the instructions to include Radium in JsBin don't seem to work anymore.

**Comment by stevenmusumeche** [comment]
closing in favor of #912
