### ISSUE TITLE
Styles hot loading

### ISSUE THREAD

**Issue by sbalay** [FormidableLabs/radium#905]
I've used create-react-app to bootstrap my application and everytime I change a style on a component the whole webapp reloads.
Is there a way to avoid that? The desired behaviour would be to hot load the styles without refreshing the browser.

**Comment by alexlande** [comment]
Sorry, I don't think there is. If I remember right, create-react-app's hot reloading does work on functional components, so those at least shouldn't trigger a full page reload, but otherwise this is just a limitation of hot reloading and keeping styles in component logic rather than CSS.
