### ISSUE TITLE
Suppress ref warning

### ISSUE THREAD

**Issue by austincondiff** [FormidableLabs/radium#906]
I get this warning when using a ref in an element that is a direct child of a TransitionGroup...
`Warning: string refs are not supported on children of TransitionGroup and will be ignored. Please use a callback ref instead: https://facebook.github.io/react/docs/refs-and-the-dom.html#the-ref-callback-attribute`

I use the ref here...
`<div ref={item.id + 'Menu'} ...`

...so that I can use it here to use Radium to change my view depending on the hover state of the element above.
`{(Radium.getState(this.state, item.id + 'Menu', ':hover')) ? (...`

Any way to suppress these warnings or am I going about this wrong?

**Comment by haxxxton** [comment]
@acondiff, [the docs](https://github.com/FormidableLabs/radium/tree/master/docs/api#getstate) say you can use either `ref=""` or `key=""`, have you tried using `div key={item.id + 'Menu'} ...` ? or is the element used as part of a loop?

This is related to #908 or vice versa
