### ISSUE TITLE
Using .getState with refs callback

### ISSUE THREAD

**Issue by haxxxton** [FormidableLabs/radium#908]
Had a quick look around the issues, and documentation and couldnt find any mention of how to correctly use this. Any help would be appreciated.

Currently, [React Docs](https://facebook.github.io/react/docs/refs-and-the-dom.html) say that use of [string based refs is legacy/deprecated](https://facebook.github.io/react/docs/refs-and-the-dom.html#legacy-api-string-refs), and instead should [use a callback](https://facebook.github.io/react/docs/refs-and-the-dom.html#adding-a-ref-to-a-dom-element) to assign the ref to a variable.

The [Radium Docs for `Radium.getState`](https://github.com/FormidableLabs/radium/tree/master/docs/api#getstate) method,  particularly the second parameter (`elementKey`) should be a string
>if you used multiple elements, pass the same `key=""` or `ref=""`. If you only have one element, you can leave it blank (`'main'` will be inferred)

Is there a solution for using `Radium.getState` with the updated callback styles of assigning `refs`? Or must we use the `key` prop in order to use `.getState`?

**Comment by stevenmusumeche** [comment]
@haxxxton you can use key (instead of ref) for this
