### ISSUE TITLE
[TRACKING] Update to use inline-style-prefixer v3

### ISSUE THREAD

**Issue by planttheidea** [FormidableLabs/radium#918]
Just as the title says... The newest major version of i-s-p is in use by most other libraries, and we've experienced breakages when used with radium wrapped components that use v2.

**Comment by omryr** [comment]
was this addressed? Im having a problem with Yandex problem which seems to be solved if we just update the inline-style-prefixer to the newest version

**Comment by ryan-roemer** [comment]
Can you submit a PR? Thanks!

/cc @alexlande

**Comment by alexlande** [comment]
Going to plan on upgrading to v3 and switching to the static prefixer if at all possible.

**Comment by cif** [comment]
Any update on this? We're resorting to using [yarn resolution support](https://github.com/yarnpkg/rfcs/pull/68 ) but have a moving target with versions of yarn on our build pipelines. Would be great to get this fixed at the root of the problem!

**Comment by ryan-roemer** [comment]
@exogen -- Can we close this or does it need to go back to Backlog?

**Comment by exogen** [comment]
@ryan-roemer The upstream changes we need in `inline-style-prefixer` were merged in rofrischmann/inline-style-prefixer#148, but there's hasn't been a release yet. We're waiting on that, unless we want to use a git revision dependency.
