### ISSUE TITLE
yandex browser issues

### ISSUE THREAD

**Issue by omryr** [FormidableLabs/radium#919]
Hi I found a problem with Yandex browser which is based on chromium when using flex.
for some reason any time i add flex attributes they are changed slightly and this makes the whole website not appear as it should.

example of styles on chrome vs yandex:
chrome:
    display: flex;
    justify-content: space-between;
    color: rgb(151, 151, 151);

yandex: 
    justify-content: space-between;
    -webkit-box-pack: justify;
    color: rgb(151, 151, 151);

chrome:
width: 100%;
    align-items: center;
    display: flex;
    color: rgb(151, 151, 151);
yandex: 
    align-items: center;
    -webkit-box-align: center;
    width: 100%;
    color: rgb(151, 151, 151);

**Comment by philpl** [comment]
Any reason you closed the issue? Did you resolve it on your own?

**Comment by omryr** [comment]
I figured it's radium not adding the new version in their package
