### ISSUE TITLE
Support React 0.13

### ISSUE THREAD

**Issue by jartek** [FormidableLabs/radium#92]
https://github.com/FormidableLabs/radium/blob/master/package.json#L24 and https://github.com/FormidableLabs/radium/blob/master/package.json#L33 have it hardcoded as 0.12

**Comment by gre** [comment]
+1

**Comment by alexlande** [comment]
Sorry for the wait, y'all. Resolved in 155fd07fe803ec9301cae336daf03ddeba676253.
