### ISSUE TITLE
Radium doesn't autoprefix by default ?

### ISSUE THREAD

**Issue by neovea** [FormidableLabs/radium#920]
Hi, I read in the doc that Radium added vendor prefix automatically.
But it seems that this isn't the case. I' created an app using create-react-app, which automatically add vendor prefix. But when using Radium, for instance in a media query, vendor prefixes are not applied.

example : 
```
const iconWrapper = {
  default: {
    textAlign: 'center',
    color: Colors.light,
    '@media only screen and (max-width: 660px)': {
      display: 'flex',
      flexFlow: 'column nowrap',
      justifyContent: 'baseline',
      alignItems: 'center'
    }
  }
}
``` 
the `flex`property is not prefixed at all. This is the screen capture : 
<img width="286" alt="capture d ecran 2017-08-21 a 09 49 02" src="https://user-images.githubusercontent.com/5021353/29508756-0b837c3e-8656-11e7-9d75-ad5bdf460ec0.png">

Question : did I miss something ? Is it compatible with create-react-app which automatically add vendor prefixes ?

Thanks

**Comment by TomiTakussaari** [comment]
AFAIK Radium uses inline-style-prefixer, which detects what browser you are using, and only does prefixes that are necessary for that browser.

So, to see it add prefixes, you have to use browser that does not support flex without prefix.

**Comment by alexlande** [comment]
That's right, Radium uses https://github.com/rofrischmann/inline-style-prefixer which only provides necessary prefixes at runtime. If your current browser doesn't need a prefix, it won't be applied.

If you see any issues with missing prefixes please let me know and I can reopen this.

**Comment by d-adamkiewicz** [comment]
Do vendor prefixed keyword values for 'width' supported?  '-moz-max-content' for FF? https://developer.mozilla.org/en-US/docs/Web/CSS/width

**Comment by alexlande** [comment]
No, afraid not. You can see the list of properties supported by inline-style-prefixer here: https://inline-style-prefixer.js.org/docs/data/SupportedProperties.html

The `sizing` plugin (https://inline-style-prefixer.js.org/docs/data/SpecialPlugins.html) adds support for `max-content`, but Radium doesn't support inline-style-prefixer plugins at this time. There's a ticket open to track that issue: https://github.com/FormidableLabs/radium/issues/901
