### ISSUE TITLE
Not maintained warning

### ISSUE THREAD

**Issue by sassanh** [FormidableLabs/radium#923]
Hey,

If Radium is not actively maintained anymore (https://github.com/FormidableLabs/radium/graphs) I think it'd be helpful for people building their stack if you put a "not actively maintained" warning in main page.

**Comment by ryan-roemer** [comment]
Thanks for checking in @sassanh -- Radium is indeed maintained and we're in the process of spending a good amount of effort triaging and curating the backlog of issues (some of which no longer apply) to get a smaller, more focused list of things to bang out.

**Comment by sassanh** [comment]
That's good news. Looking forward to see updates on this repo.
