### ISSUE TITLE
Question: Can I use the <Style> component to set the @font-face around my app?

### ISSUE THREAD

**Issue by fourcolors** [FormidableLabs/radium#925]
I have a custom font I'd like to use for my app and specifically Storybook.js Any good solutions out there for this?

**Comment by alexlande** [comment]
Yep, you can use `@font-face` in the `Style` component. Here's an example with PT Serif dropped in from Google fonts:

```js
<Style
  rules={{
    '@font-face': {
      fontFamily: 'PT Serif',
      fontStyle: 'normal',
      fontWeight: '400',
      src: 'url(https://fonts.gstatic.com/s/ptserif/v8/I-OtoJZa3TeyH6D9oli3iXYhjbSpvc47ee6xR_80Hnw.woff2) format("woff2")'
    },
    body: {
      fontFamily: 'PT Serif'
    }
  }}
/>
```

That said, it might be simpler to use normal CSS for `@font-face`. I like to keep that stuff separate from my application logic and use some of the techniques outlined here for better loading performance: https://www.zachleat.com/web/comprehensive-webfonts.

But, if you want to stick to JS-only, or if you're using a component in a context where you don't have
access to CSS, this will do the trick 🤘
