### ISSUE TITLE
Position: sticky not getting added in inline-styles

### ISSUE THREAD

**Issue by IanCStewart** [FormidableLabs/radium#929]
When i try to add position sticky to an element it doesn't get added.

For example this styling: 
```
tabContainer: {
      marginTop: '32px',
      backgroundColor: theme.colors.background,
      position: 'sticky',
      top: 0
    },
```
=>
```
    margin-top: 32px;
    background-color: rgb(254, 254, 254);
    top: 0px;
```

**Comment by davidsonsns** [comment]
I implemented in a div and it worked, which tag does not work correctly?

**Comment by IanCStewart** [comment]
I think i tried to add it on a section. I'm not sure since its a while back

**Comment by kylecesmat** [comment]
Closing this as it sounds like it may no longer be relevant. Please feel free to reopen if this is not the case!
