### ISSUE TITLE
borderRadius: cant use split notation

### ISSUE THREAD

**Issue by IanCStewart** [FormidableLabs/radium#935]
It would be nice if `borderRadius: '25%/50%'` would get accepted.

**Comment by davidsonsns** [comment]
I did the test with the examples and it worked. Which tag are you having problems with?

**Comment by IanCStewart** [comment]
I tried to add it on a `span` tag. It's not that it didn't have `borderRadius`. It just didn't add the `borderRadius` as expected. What You would expect is to see on the render `border-radius: 25% 5% / 50%;` vs. what you get `border-radius: 25% 5% 50%;`

**Comment by davidsonsns** [comment]
I did test implementing the [two raddi](https://developer.mozilla.org/en-US/docs/Web/CSS/border-radius) in pure react, and it seems to me that the problem is in the react.
Does not behave as expected

**Comment by davidsonsns** [comment]
at first I thought it was wrong the way the react applied this style.
but checked and this is as expected. check in codesandbox
[border radius radii](https://codesandbox.io/s/2v4m01pz7j)

this image shows that it has been applied correctly
![border](https://user-images.githubusercontent.com/9276511/32690739-91a773c0-c6e2-11e7-9007-e6939f9f95b9.png)

**Comment by kylecesmat** [comment]
It looks like this has been resolved, feel free to re-open if that is not the case!
