### ISSUE TITLE
Enable plugins to be called manually on an object of styles

### ISSUE THREAD

**Issue by dspacejs** [FormidableLabs/radium#942]
This is useful for certain cases, such as for [an issue I'm facing writing a unit test for a React component](https://stackoverflow.com/questions/47109817/how-to-test-if-styles-are-dynamically-applied-on-a-react-component). The link has all the code and details for context.

From trying to figure out a solution, I figured that I could perhaps use Radium's `resolveInteractionStyles` and `mergeStyleArray` plugins to process `styles.dark`, which would strip out the interaction styles. I'm also assuming that Radium's processing would evaluate the `Color()` functions, returning their `rgb()` value as a string. If both of these things occurred, then I could compare `styles.dark` with `componentStyles`.

I wrote the following code to try this:

```javascript
describe("when `dark` is `true`", () => {
  beforeEach(() => {
    props.dark = true
  })

  it("applies the component's `dark` styles", () => {
    const componentStyles = getComponent().props().style
    let darkStyles = Radium.Plugins.resolveInteractionStyles({style: styles.dark})
        darkStyles = Radium.Plugins.mergeStyleArray({style: darkStyles})
    expect(componentStyles).toEqual(expect.objectContaining(darkStyles))
  })
})
```

After trying that, I realised it doesn't work as the plugins exposed in the API obviously aren't intended to be used that way:

```
 FAIL  src/js/components/__tests__/Button.test.jsx
  ● <Button> › when `dark` is `true` › applies the component's `dark` styles

    TypeError: Cannot read property 'onMouseEnter' of undefined
      
      at Object.resolveInteractionStyles (node_modules/radium/lib/plugins/resolve-interaction-styles-plugin.js:35:37)
      at Object.<anonymous> (src/js/components/__tests__/Button.test.jsx:77:49)
```

If Radium's plugins were able to be called manually with an object containing styles as an argument, I'd be able to do this. Or perhaps there could be a function in the API that enables you to pass in a styles object without a React component, returning the processed styles object (which I'd be able to use for comparison in the unit test).

**Comment by mightyspaj** [comment]
**Update:** I figured out a workaround for the issue I was having. This still might be a useful feature, though.
