### ISSUE TITLE
State change does not work with @Radium decorator

### ISSUE THREAD

**Issue by gitsupersmecher** [FormidableLabs/radium#943]
The class is quite simple. It is in TypeScript. If I remove @Radium decorator then everything works fine, but with @Radium the state change does not happen, and also I see the Warning about setState cannot be updated on an unmounted component -> this is quite wrong since the component is mounted, but I suppose that the decorator introduced some issues here.

This is the code:

`var style = {
    color : "green"
  };
  
@Radium export class TestComponent extends React.Component < any, any > {

    constructor(){
        super();
        this.state = {
          shown : true
        };
      }
      render() {    

        if (this.state.shown) {
            style["color"] = "green";
        } else {
            style["color"] = "red";
        }
        return(  
          <div>
            <button key={1} onClick={ this.test}>
              Show
            </button>    
          </div>
        );
      }  
      
      private test = () => {
        // tried with !this.state.shown // I did not add the setTimeout as I think that would be a hack..
        this.setState({shown:(() => !this.state.shown)()});
      }
}
`
I have not used Radium before, now I am looking at it for a new project. I do not know if this issue was discussed before, I cannot really find it, but I could related with Hover bug from last May... IDK 

Thanks!

**Comment by benjy** [comment]
Yeah i'm having the exact same issue, unable to figure out what's causing it yet

**Comment by benjy** [comment]
I got to the bottom of this, it was how Radium interacts when connected wrong with react-redux. This is how I fixed it.

    -export default connect(mapStateToProps)(Radium(NewQuestionForm));
    +export default Radium(connect(mapStateToProps)(NewQuestionForm));

**Comment by acondiff** [comment]
I am having this problem as well... as soon as I take @Radium off it starts working. I also cannot access refs when @Radium is present...

**Comment by ryan-roemer** [comment]
Closing, as the decorator is now deprecated. If you're having issues with the supported approach of `Radium(MyComponent)` please open a new issue. Thanks!
