### ISSUE TITLE
Using Radium with NextJS creates different styles on server + client

### ISSUE THREAD

**Issue by valnub** [FormidableLabs/radium#951]
I'm using [NextJS](http://www.github.com/zeit/next.js) for both, server-side and client rendering with Radium.

First thing I noticed was that this code...

```jsx
const buttonRowStyle = {
  display: 'flex',
  justifyContent: 'space-between',
  marginTop: '20px',
};

const firstMetaDropdownStyle = {
  flex: 1,
  marginRight: '4%',
};

class ProductPage extends Component {
  render() {
    return (
      <StyleRoot>
        <div style={[buttonRowStyle]} />
        <Dropdown style={firstMetaDropdownStyle} />
      </StyleRoot>
    );
  }
}

export default Radium(ProductPage);
```

..would lead to this warning when used with Radium:

> Warning: Prop `style` did not match.
>
> Server: "-webkit-justify-content:space-between;-ms-flex-pack:justify;-webkit-box-pack:justify;display:-webkit-box,-moz-box,-ms-flexbox,-webkit-flex,flex;justify-content:space-between;margin-top:20px"
>
> Client: "display:flex;justify-content:space-between;margin-top:20px"

Looks like:

- Radium is only run on server-side (Don't know why)
- Radium adds vendor prefixes
- NextJS doesn't like server- and client styles to be different
- Chrome doesn't like the vendor fixes by Radium:

**_Screenshot from Chrome Devtools style inspector:_**
![radium](https://user-images.githubusercontent.com/3787662/33940650-16e8b7b0-e010-11e7-8db5-2ad18a10f074.jpg)

So, I tried to disable vendor prefixing by removing `Radium.Plugins.prefix`:

```jsx
  function ConfiguredRadium(component) {
    return Radium({
      plugins: [
        Radium.Plugins.mergeStyleArray,
        Radium.Plugins.checkProps,
        Radium.Plugins.resolveMediaQueries,
        Radium.Plugins.resolveInteractionStyles,
        Radium.Plugins.keyframes,
        Radium.Plugins.visited,
        Radium.Plugins.removeNestedStyles,
        // Radium.Plugins.prefix,
        Radium.Plugins.checkProps,
      ],
    })(component);
  }
```

And also changed this:

`export default Radium(ProductPage);`

to this:

`export default ConfiguredRadium(ProductPage);`

But now I get this warning:

> Warning: Prop `style` did not match.
>
> Server: "-webkit-flex:1;-ms-flex:1;flex:1;margin-right:4%"
>
> Client: "flex:1;margin-right:4%"

So, now it looks like Radium decided to not add vendor prefixes to `display: flex` and `justify-content:space-between` but now it adds vendor prefixes to `flex: 1`.

## Questions

1. Why is Radium still adding vendor prefixes to `display:flex` after disabling the plugin?
2. Why is Radium not run client-side when used with NextJS?
3. Is there some kind of best practice guide of using Radium with NextJS? I only found some instructions for React SSR but those did not apply for NextJS.

**Comment by ryan-roemer** [comment]
@valnub -- Can you see if some of the suggestions in https://github.com/FormidableLabs/radium/issues/487 help you? SSR I believe _requires_ that you pass in a user agent to get a match on client vs. server side rendering. Not sure if Next.js allows that...

If you can't figure it out, can you create a minimum reproduction repository + install/repro steps for us to dive in and see for ourselves? Thanks!

**Comment by valnub** [comment]
@ryan-roemer Hi, thanks for your reply. I finally found the solution to the issue after almost going crazy for the past two days.

I had been using a media query directly within my root app which was wrapped in `<StyleRoot>`. An error message told me that I would have to to wrap my app in `<StyleRoot>` which confused me a lot since that's what I did, so I wrapped one of the child components into `<StyleRoot>` as well. This made the error go away but lead to the problem I described in my initial post.

Today I saw [this post](https://stackoverflow.com/a/45203324/286149) on Stackoverflow which solved the issue. I moved the media query to a child component and removed `<StyleRoot>` from all components except for the root page component. Everything works perfectly now with `Radium.Plugins.prefix` disabled in Radium config.

However, I find it a bit cumbersome that you cannot use media queries directly within `<StyleRoot>` and I'd have to create a new component even if I only wanted to add a simple `<hr />` and make it responsive using media query, for example.

**Comment by ryan-roemer** [comment]
In retrospect, this looks like it may be the same issue as in https://github.com/FormidableLabs/radium/issues/958 (`,` instead of `;`)

**Comment by atropos0902** [comment]
HI @valnub 
How did you resolve the issue?
I am having the same problem.
Can you please let me know the details?
Thanks!

**Comment by valnub** [comment]
@atropos0902 Sorry, it‘s too long ago, so I don’t remember. What I do remember though is that we replaced Radium with styled-components eventually.

**Comment by atropos0902** [comment]
Hi @valnub 
Thanks for your reply.
That completely make sense.
