### ISSUE TITLE
Server/client classnames with NextJS do not match when using media queries and flex:1

### ISSUE THREAD

**Issue by valnub** [FormidableLabs/radium#952]
I'm using Radium with Next and ran into a very weird problem. Everything has been running smoothly so far but all out of sudden I get this warning:

`Warning: Prop className did not match. Server: "rmq-6e129611" Client: "rmq-57e49669"`

This started happening when I added `flex:1` to a media query:

```
const style = {
  '@media screen and (min-width: 768px)': {
    flex: 1,
    color: 'red',
  },
};
```

In the generated html, I can see that Radium has expanded `flex:1` to this:

```
<style>
@media screen and (min-width: 768px){
 .rmq-6e129611{
  -webkit-flex: 1 !important;
  -ms-flex: 1 !important;
  flex: 1 !important;
  color: red !important;}
}
</style>
```

## What I noticed:

- Server-rendered class `rmq-6e129611` exists in the generated markup, but `rmq-57e49669` does not.
- Radium has added vendor prefixes although I clearly turned it off:

```
  ConfiguredRadium(component) {
    return Radium({
      plugins: [
        Radium.Plugins.mergeStyleArray,
        Radium.Plugins.checkProps,
        Radium.Plugins.resolveMediaQueries,
        Radium.Plugins.resolveInteractionStyles,
        Radium.Plugins.keyframes,
        Radium.Plugins.visited,
        Radium.Plugins.removeNestedStyles,
        // Radium.Plugins.prefix,
        Radium.Plugins.checkProps,
      ],
    })(component);
  },
```

This does work flawlessly though up until the point when a media query is used. Without using media queries Radium correctly omits vendor prefixes as I configured using `ConfiguredRadium()`. I've had a similar [issue](https://github.com/FormidableLabs/radium/issues/951) before which I could solve by wrapping only the root element with `<StyleRoot>` but now I'm completely stuck.

## Source code download

[I uploaded the full source code to Github](https://github.com/valnub/radnext), so you can check it out there. The problematic media query is in [Dropdown.js](https://github.com/valnub/radnext/blob/master/src/components/dropdown.js).

**Comment by stefvhuynh** [comment]
Hi @valnub, it seems the issue may be that the `userAgent` is not being passed into the `StyleRoot` component on the server. The prefixer knows how to prefix the css if your code is already on the browser since it can read it from the browser. However, on the server side, you need to explicitly pass it in. If it is not passed in, the prefixer will use every prefix. Then on the browser side, it won't use every prefix. This results in a mismatched hash on the server vs browser. See this for an example: https://github.com/FormidableLabs/radium/tree/master/docs/api#configuseragent.
And this for a working example: https://github.com/FormidableLabs/radium/blob/master/examples/server.js#L33.

**Comment by stefvhuynh** [comment]
i don't know much about `next`, but if there is a way to access the `req` and pass in a value, that would be your best bet.

**Comment by valnub** [comment]
@stefvhuynh Indeed, that did the job, thanks!

**Comment by valnub** [comment]
@stefvhuynh One more thing, wrapping the root component of my pages into `<StyleRoot radiumConfig={userAgent}>` seems not to be enough in order for Radium to correctly handle media queries in child components. If I wrap all child components into `<StyleRoot radiumConfig={userAgent}>` it works but this seems a bit cumbersome. Is this the correct approach or am I doing something wrong?
