### ISSUE TITLE
radium is causing npm errors

### ISSUE THREAD

**Issue by PortableTomb** [FormidableLabs/radium#953]
radium is causing npm errors - react-scripts: command not found. npm start works again after uninstalling radium. 

sh: react-scripts: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! react-complete-guide@0.1.0 start: `react-scripts start`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the react-complete-guide@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

------------------------------------------------------------

**Comment by ryan-roemer** [comment]
Your error is this:

```
sh: react-scripts: command not found
```

Which means you have a command in your `package.json` that relies on `react-scripts` and the package isn't being installed. Radium's `dependencies` https://unpkg.com/radium@0.19.6/package.json do not provide nor should have any impact on installation of `react-scripts` and thus Radium has no relation to your issue.

If somehow radium is connected, feel free to re-open this issue with a minimal repository + install / error reproduction steps to recreate the error and we'll take a look. Thanks!
