### ISSUE TITLE
Guide for TypeScript?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [FormidableLabs/radium#954]
https://github.com/FormidableLabs/radium/issues/924
https://github.com/FormidableLabs/radium/pull/947

I'd like to use Radium in a TypeScript project. If you're going to be removing references to decorators, it would be nice if there were docs on the recommended way. If it's not decorators anymore, what is it?

For example, what's the recommended way to do directly `export` a class?

```typescript
@Radium
export class Button extends React.Component {
  // ...
}
```

_(http://formidable.com/open-source/radium/docs/guide/)_

**Comment by ryan-roemer** [comment]
You should be able to do this:

```js
import React from 'react';
import Radium from 'radium';


export default Radium(class Button extends React.Component {
  render() {/*stuff*/}
});
```

(It worked for me in the babel repl) Or you could break it up with:

```js
import React from 'react';
import Radium from 'radium';

class Button extends React.Component {
  render() {/*stuff*/}
}

export default Radium(Button);
```

which is probably the most common usage.

**Comment by JoshuaKGoldberg** [comment]
Seems reasonable. For the sake of SEO on not using `default` exports, 

```typescript
import React from 'react';
import Radium from 'radium';

export const Button = Radium(class extends React.Component {
  render() {/*stuff*/}
});
```
