### ISSUE TITLE
0.21.0: componentDidUpdate() is not called after changing property in Radium-decorated component

### ISSUE THREAD

**Issue by Q-Man** [FormidableLabs/radium#957]
Since Version 0.21.0 I observed the following wrong behaviour of a Radium-decorated React component:

Changing a property from outside of a Radium-decorated component correctly triggers a render() call of this component. But after the render() call there should be a call of componentDidUpdate(). Since 0.21.0 this call is not done. It's still working as expected in 0.19.6 and also without Radium-decoration.

React Version: 16.2.0
Radium Version: 0.21.0

Reproducable by this example (click on output to update data):

```import * as ReactDOM from "react-dom";
import * as React from "react";
import * as Radium from "radium";

class Main extends React.Component {

	constructor(props) {
		super(props);
		this.state = {data: 123};
	}

	render() {
		return <div onClick={() => this.setState({data: Math.random()})}>

			<Test data={this.state.data}/></div>
	}
}

@Radium
class Test extends React.Component {

	componentDidUpdate(prevProps, prevState) {
		//this should be called, but is not
		console.log("componentDidUpdate");
	}

	render() {
		return <div>{this.props.data}</div>
	}
}

ReactDOM.render(
	<Main/>,
	document.getElementById('app')
);
```

**Comment by ryan-roemer** [comment]
Thanks for the issue @Q-Man -- can you create a minimal repository with install + error reproduction steps so we can more easily jump in and see what you're seeing? 

And the Radium decorator is deprecated, so would you mind instead just wrapping your component like `WrappedComponent = Radium(MyComponent)`?

Thanks!

**Comment by minhduchua** [comment]
@ryan-roemer 
I confirm that just wrapping the component with `WrappedComponent = Radium(MyComponent)` is affected by the bug

**Comment by Q-Man** [comment]
@ryan-roemer I made a minimal example project demonstrating the problem.

What do you mean exactly with "create a minimal repository"? I never did this before, is there a description anywhere how to do it?

**Comment by ryan-roemer** [comment]
@Q-Man -- A minimal repository means a public github project that I can `git clone`, then follow your install steps and then follow your error reproduction steps to see the problem.

It's much faster for us to go from start to seeing the problem in a minute instead of figuring out what build you're using, seeing if there are any other dependencies issues, etc.

So `tl;dr`, create a simple GitHub project with the least demo code possible to show the issue in a browser that we can just download and build. Thanks!

**Comment by Q-Man** [comment]
Ok, here is the repository demonstrating the bug:

https://github.com/Q-Man/radium-bug

**Comment by or2008** [comment]
I have the same issue :)

**Comment by ryan-roemer** [comment]
Confirmed. Our implementation of `componentDidUpdate` in the Radium enhancer does not call the superclass' `componentDidUpdate`: https://github.com/FormidableLabs/radium/blob/master/src/enhancer.js#L204-L220

/cc @stefvhuynh
