### ISSUE TITLE
getBrowserStateEvents() overwrites native Events

### ISSUE THREAD

**Issue by dubert** [FormidableLabs/radium#97]
I have an input field that I want to style the focus, but I also want to capture the onFocus and onBlur events.

If I write:
```js
<input
  type='text'
  ref='input'
  value={this.state.input}
  onFocus={this.onFocus}
  onBlur={this.onBlur}
  onKeyDown={this.onKeyDown}
  onChange={this.onChange}
  placeholder={this.props.placeholder}
  {...this.getBrowserStateEvents()}
  style={this.buildStyles(style)}
/>
```
The component functions are not called, but the styling works. And if I rearrange it: 
```js
<input
  {...this.getBrowserStateEvents()}
  type='text'
  ref='input'
  value={this.state.input}
  onFocus={this.onFocus}
  onBlur={this.onBlur}
  onKeyDown={this.onKeyDown}
  onChange={this.onChange}
  placeholder={this.props.placeholder}
  style={this.buildStyles(style)}
/>
```
then my functions are called, but the styling does not work.

**Comment by dubert** [comment]
I looked through the BrowserStateMixin and found that getBrowserStateEvents() tries to call any props on the component, not any props that might be on the dom element.

I can work around it by making my input field it's own separate component. Though it's a little annoying.

**Comment by alexlande** [comment]
@dubert: Yeah, this is an unfortunate quirk. If you don't want the element to be it's own component, you can use your own listeners instead of `this.getBrowserStateEvents()` and call the Radium listeners manually. See the docs here: https://github.com/FormidableLabs/radium/tree/master/docs/api#getbrowserstateevents

**Comment by alexlande** [comment]
We should probably call this and any other quirks out better in the docs.
