### ISSUE TITLE
can't import Radium

### ISSUE THREAD

**Issue by tommybernaciak** [FormidableLabs/radium#978]
I wanted to try radium. Just installed:

```
yarn add radium
yarn add @types/radium
```

When I `import Radium from 'radium'` I have:
`Module (...)/node_modules/@types/radium/index"' has no default export.`

I use React with Typescript.

**Comment by ryan-roemer** [comment]
We don't maintain https://www.npmjs.com/package/@types/radium -- can you raise the issue with that project instead?
