### ISSUE TITLE
this.focus works in states array, but not in modifiers

### ISSUE THREAD

**Issue by mattborn** [FormidableLabs/radium#98]
If I create a hover state that uses the same styles as the focus state, I am able to do the following:

```
states: [
  {
    focus: { background: yellow }
  },
  {
    hover: this.focus
  }
]
```

which is awesome.

However, when I try to do this same thing in modifiers:

```
modifiers: [
  {
    type: {
      primary: {
        states: [
          {
            focus: { background: yellow }
          },
          {
            hover: this.focus
          }
        ]
      }
    }
  }
]
```

it loses the scope + returns undefined.

Is there a special method I am missing to access this? I tried inspecting the scope of this in the browser + trying different methods I see in the local scope but am getting errors for all of ’em.

Is this a bug?

**Comment by alexlande** [comment]
I think the fact that the first example is working is the bug. You shouldn't have access to the current object's scope when you initialize it. You would need to do something like this:

```js
states: function () {
  var hoverStyles = {
    background: 'yellow'
  };

  return [
    {
      hover: hoverStyles
    },
    {
      focus: hoverStyles
    }
  ];
}()
```

Or alternately declare the `hoverStyles` outside of the object and then assign `hover` and `focus` to it. (This is what I do usually.) Agree that a nice shorthand for this would be helpful though.

**Comment by mattborn** [comment]
@alexlande I’m good with this. Thanks for your quick reply!

**Comment by alexlande** [comment]
No problem!
