### ISSUE TITLE
What is best strategy for merging style objects with same breakpoint?

### ISSUE THREAD

**Issue by zeckdude** [FormidableLabs/radium#983]
I am trying to merge two objects that have a property for the same breakpoint. When it merges, I want the properties within the breakpoint from the second object to merge with the properties within the breakpoint from the first object. Unfortunately, it is currently just overriding the entire breakpoint object. How can I merge the two breakpoint objects when merging two objects that have the same breakpoint property?

```js
const styles = {
  footerGroup: {
    marginBottom: '21px',
    '@media (min-width: 992px)': {
      marginBottom: 0
    }
  },
  siteLinks: {
    marginBottom: '10px',
    '@media (min-width: 992px)': {
      flex: 1,
      textAlign: 'center'
    }
  },
};

const mergedSiteLinksGroupStyle = { ...styles.footerGroup, ...styles.siteLinks };
```

This is currently outputting:
```js
{
  marginBottom: '10px',
  '@media (min-width: 992px)': {
      flex: 1,
      textAlign: 'center'
    }
}
```

I want it to output this:
```js
{
  marginBottom: '10px',
  '@media (min-width: 992px)': {
      marginBottom: 0,
      flex: 1,
      textAlign: 'center'
    }
}
```

**Comment by ryan-roemer** [comment]
The JavaScript merge technique you're using is shallow. You need something that either deep merges like lodash merge.

```js
const mergedSiteLinksGroupStyle = _.merge({}, styles.footerGroup, styles.siteLinks);

// produces...
{
  "marginBottom": "10px",
  "@media (min-width: 992px)": {
    "marginBottom": 0,
    "flex": 1,
    "textAlign": "center"
  }
}
```

or you'll need to `Object.assign` in native js at both levels with a somewhat complicated ordering to insuring the right thing "wins".

```js
const mergedSiteLinksGroupStyle = Object.assign({}, styles.footerGroup, styles.siteLinks, {
  '@media (min-width: 992px)': Object.assign({},
    styles.footerGroup['@media (min-width: 992px)'],
    styles.siteLinks['@media (min-width: 992px)'])
});

// produces...
{
  "marginBottom": "10px",
  "@media (min-width: 992px)": {
    "marginBottom": 0,
    "flex": 1,
    "textAlign": "center"
  }
}
```

Closing this, as you have a pure JS issue, not a Radium one. Hope the tips help!

**Comment by zeckdude** [comment]
Those are awesome! Thanks @ryan-roemer!
