### ISSUE TITLE
Enhancer.js doesn't pass snapshot argument in componentDidUpdate

### ISSUE THREAD

**Issue by veob** [FormidableLabs/radium#985]
In last React version (16.3.0), which is supported in current package.json, `componentDidUpdate` takes `snapshot` as third argument ([docs](https://reactjs.org/docs/react-component.html#componentdidupdate)). The current implementation of enhancer.js [doesn't consider it](https://github.com/FormidableLabs/radium/blob/master/src/enhancer.js#L254):
```jsx
    componentDidUpdate(prevProps, prevState) {
      if (super.componentDidUpdate) {
        super.componentDidUpdate.call(this, prevProps, prevState);
      } 
```

A potential fix looks simple. Would you be intested in a PR?

**Comment by ryan-roemer** [comment]
@veob -- Yep! We'd be interested in a PR, and ideally with a failing regression test (our ssr tests are in `test` and our client tests are in `src/__tests__`

**Comment by stevenmusumeche** [comment]
ping @veob
