### ISSUE TITLE
You must install peer dependencies yourself

### ISSUE THREAD

**Issue by Dessare** [FormidableLabs/radium#986]
940 warn ajv-keywords@3.1.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
941 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
942 warn optional SKIPPING OPTIONAL DEPENDENCY: Error: EPERM: operation not permitted, rename 'C:\xampp\htdocs\react\myproject\node_modules\.staging\fsevents-0442c7b2\node_modules\asynckit' -> 'C:\xampp\htdocs\react\myproject\node_modules\.staging\asynckit-8d13c755'
943 verbose optional SKIPPING OPTIONAL DEPENDENCY:
943 verbose optional Please try running this command again as root/Administrator.
944 verbose stack Error: ENOENT: no such file or directory, rename 'C:\xampp\htdocs\react\myproject\node_modules\bowser' -> 'C:\xampp\htdocs\react\myproject\node_modules\.bowser.DELETE'
945 verbose cwd C:\xampp\htdocs\react\myproject
946 verbose Windows_NT 6.1.7601
947 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "radium"
948 verbose node v8.9.4
949 verbose npm  v5.6.0
950 error path C:\xampp\htdocs\react\myproject\node_modules\bowser
951 error code ENOENT
952 error errno -4058
953 error syscall rename
954 error enoent ENOENT: no such file or directory, rename 'C:\xampp\htdocs\react\myproject\node_modules\bowser' -> 'C:\xampp\htdocs\react\myproject\node_modules\.bowser.DELETE'
955 error enoent This is related to npm not being able to find a file.
956 verbose exit [ -4058, true ]

How to fix it?

**Comment by ryan-roemer** [comment]
@Dessare -- We'll need actual reproduction steps + OS information and likely a minimal repository that can reproduce the error so we can see it.

Simply

```sh
$ npm install radium
```

works on Mac, Linux, and Windows.

**Comment by Dessare** [comment]
It worked when npm wasn't running (before npm start). So I can't install modules when npm is running?
