### ISSUE TITLE
Radium not working with React-Final-Form

### ISSUE THREAD

**Issue by schingeldi** [FormidableLabs/radium#987]
This is a cross post from https://github.com/final-form/react-final-form/issues/239 as I don't know which library is causing the issue, but Radium doesn't work with react-final-form. 
The array syntax is just an example. Also mediaQueries are not working.

**What is the current behavior?**

When using Radium with React-Final-Form, Radium doesn't seem to work. In the provided example, I styled two div boxes identically with merged styles. (styles.one and styles.two)

**What is the expected behavior?**
Both div boxes should be red and 300x200 pixels. But only the one outside of a Form works

**Sandbox Link**
https://codesandbox.io/s/4jy1xlrwyx

**What's your environment?**
React Final Form 3.4.0
Final Form 4.6.1

**Other information**
Is this a bug or am I doing anything wrong here?

**Comment by rawrmonstar** [comment]
Right now, Radium can't traverse down into render prop rendered components. Since React-Final-Form uses render props you can wrap the component the render prop returns with Radium instead. In this scenario the parent doesn't need to be wrapped:

```js
const RadiumForm = Radium(({ handleSubmit }) => (
  <form onSubmit={handleSubmit}>
    <div style={[styles.one, styles.two]}>Within the form</div>
  </form>
))

const MyForm = () => {
  return (
    <Form
      onSubmit={async values => {
        console.log("submit", values);
      }}
      render={({ handleSubmit }) => <RadiumForm handleSubmit={handleSubmit} />}
    />
  );
};
```

Here is your code sandbox with the modification: https://codesandbox.io/s/pw9vl0478m
