### ISSUE TITLE
Testing components with MatchMedia

### ISSUE THREAD

**Issue by benoneal** [FormidableLabs/radium#99]
When attempting to unit test components which use mediaQueries, I'm getting the following error: 
```
matchers[key] = window.matchMedia(mediaQueryOpts[key]);
TypeError: Object #<Window> has no method 'matchMedia'
```
I could attempt to run MatchMediaBase.init() before running the tests, but without a top-level component to attach the mixin to, I'm not sure that would help? 

Has anyone successfully unit tested components that rely on radium media queries?

**Comment by ianobermiller** [comment]
I don't think this is an issue anymore; please reopen if it is.
