### ISSUE TITLE
style scope to include only component

### ISSUE THREAD

**Issue by omryr** [FormidableLabs/radium#992]
is there a way to use <Style > which will make it work only inside the component i use it in?

what i mean is that it wont run on any place that the scope selector class is the same (having multiple class input-range for example but only add the classes on the instance of my component).

thanks for the help

**Comment by mdekalka** [comment]
I think [scopeSelector] is what you are looking for:
https://github.com/FormidableLabs/radium/tree/master/docs/api#scopeselector

**Comment by mdekalka** [comment]
I think **scopeSelector** will still help you with this problem:
https://github.com/FormidableLabs/radium/tree/master/docs/api#scopeselector

> A good use case might be to generate a unique ID for a component to scope any styles to the particular component that owns the <Style> component instance.

**Comment by stevenmusumeche** [comment]
@omryr as @mdekalka, the `scopeSelector` prop is what you need.  You can generate a unique ID for each component in the constructor and use that as your scopeSelector.
