### ISSUE TITLE
Problems with React 16.4 and TypeScript

### ISSUE THREAD

**Issue by Willzyc** [FormidableLabs/radium#995]
When upgrading to React 16.4 TypeScript does not compile anymore.

The problem is that React 16.4 does not accept styles like the following examples:

`<div style={!isVisible && styles.show} />`

No boolean allowed

`<div style={[styles.style1, styles.style2]} />`

Arrays which should be combined by radium

And also it does not accept :hover or media queries

Maybe you could add a function to wrap those statements like:

`<div style={radium([styles.style1, styles.style2])} />`

**Comment by ayan2207** [comment]
Getting the same issue with React v16.2.0 with Typescript 2.7.0

` Type 'any[]' is not assignable to type 'CSSProperties | undefined'.`

**Comment by jiayihu** [comment]
I wrote the function myself as follows:

```ts
import { CSSProperties } from 'react';

interface StyleRules extends CSSProperties {
  ':hover'?: React.CSSProperties;
  ':focus'?: React.CSSProperties;
  ':active'?: React.CSSProperties;
}

export function asCSS(styles: StyleRules | StyleRules[]): CSSProperties {
  return styles as any;
}
```

**Comment by rawrmonstar** [comment]
Hi! We do not maintain the TypeScript typings for Radium, however I did look into updating them but I am not sure it's actually possible to solve with a typings update. I think the best solution is to use some function such as the one @jiayihu suggested. Thanks!
