### ISSUE TITLE
Warning: Prop `data-radium` did not match. Server: "null" Client: "true"

### ISSUE THREAD

**Issue by artozah** [FormidableLabs/radium#996]
Hi
I have this warning after upgrade to React 16.3.2.
I use server-side rendering.

Maybe it's somehow related to [#782](https://github.com/FormidableLabs/radium/pull/782)

"radium": "0.24.0",    
"react": "16.3.2",
"react-dom": "16.3.2",

**Comment by artozah** [comment]
Hi @ryan-roemer, I fixed this error by adding `radiumConfig` to `RouterContext` on the server side, like here [#487](https://github.com/FormidableLabs/radium/issues/487), but now I got new warning:

`Warning: Prop `style` did not match. Server: "transition-duration:0.5s;transition-timing-function:cubic-bezier(0.215, 0.610, 0.355, 1.000);transition-property:transform;will-change:transform;position:fixed;transform:translateY(0px);display:flex;left:16px;top:8px;z-index:11000" Client: "transition-duration:0.5s;transition-timing-function:cubic-bezier(0.215, 0.610, 0.355, 1.000);position:fixed;transform:translateY(0px);left:16px;top:8px;z-index:11000"`

**Comment by kylecesmat** [comment]
@artozah this is likely due to the userAgent not being set correctly. This PR has a great example of how you can resolve the mismatched style output:

https://github.com/FormidableLabs/radium-docs/pull/29/files

I'm going to close this, but feel free to re-open if the problem persists!
